docs/content/preview/migrate/release-notes.md

@netlify /preview/migrate/release-notes/

[docs] fixed rendering of characters on voyager release notes

---

docs/content/preview/yugabyte-platform/manage-deployments/delete-universe.md

Fix #15630
@netlify /preview/yugabyte-platform/manage-deployments/delete-universe/

[docs][platform] Fix for mention Pause / Resume #15630

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

resolves https://yugabyte.atlassian.net/browse/PLAT-7395
@netlify /preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises

[PLAT-7395] added extra kernel parameter for pre-provisioning nodes.

---

docs/content/preview/admin/yb-ctl.md
docs/content/preview/admin/yb-docker-ctl.md
docs/content/stable/admin/yb-ctl.md
docs/content/stable/admin/yb-docker-ctl.md

Add note on using macos monterey with yb-ctl and yb-ctl-docker.
@netlify /preview/admin/yb-docker-ctl/

[docs] Note on using monterey and ports

---

docs/content/preview/deploy/checklist.md
docs/content/stable/deploy/checklist.md
docs/content/v2.12/deploy/checklist.md
docs/content/v2.14/deploy/checklist.md
docs/content/v2.8/deploy/checklist.md

Fix for DOC-22
@netlify /preview/deploy/checklist/

[docs] Fix DOC-22

---

docs/content/preview/_index.md
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md
docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-replicated.md
docs/content/stable/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md
docs/content/stable/yugabyte-platform/upgrade/upgrade-yp-replicated.md

Fix links to Anywhere HA page
@netlify /preview/yugabyte-platform/upgrade/upgrade-yp-kubernetes/

[docs][platform] Fix HA Anywhere links

---

docs/content/preview/explore/fault-tolerance/macos-yba.md
docs/content/preview/explore/linear-scalability/scaling-transactions-cloud.md
docs/content/preview/explore/linear-scalability/scaling-transactions.md

Fix links to Workload app UI
@netlify /preview/explore/linear-scalability/scaling-transactions/

[docs][explore] Fix links to workload app UI

---

docs/content/preview/quick-start-yugabytedb-managed/_index.md
docs/content/preview/quick-start/_index.md
docs/content/preview/quick-start/docker.md
docs/content/preview/quick-start/kubernetes.md
docs/content/preview/quick-start/linux.md

1. https://deploy-preview-16435--infallible-bardeen-164bc9.netlify.app/preview/quick-start-yugabytedb-managed/
2. https://deploy-preview-16435--infallible-bardeen-164bc9.netlify.app/preview/quick-start/
3. https://deploy-preview-16435--infallible-bardeen-164bc9.netlify.app/preview/quick-start/linux/
4. https://deploy-preview-16435--infallible-bardeen-164bc9.netlify.app/preview/quick-start/docker/
5. https://deploy-preview-16435--infallible-bardeen-164bc9.netlify.app/preview/quick-start/kubernetes/

Suppress version picker on Quick start

---

docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md

[docs] Fix typo on max connections on sizing cluster

---

docs/content/preview/yugabyte-cloud/managed-freetrial.md
docs/content/preview/yugabyte-cloud/release-notes.md

Update what's new with database update 2.14.7

[docs] Managed What's New Mar 16

---

docs/content/preview/api/ycql/grammar_diagrams.md
docs/content/preview/api/ysql/syntax_resources/grammar_diagrams.md
docs/content/preview/architecture/docdb-replication/change-data-capture.md
docs/content/preview/architecture/transactions/transaction-priorities.md
docs/content/preview/benchmark/ycsb-jdbc.md
docs/content/preview/benchmark/ycsb-ycql.md
docs/content/preview/benchmark/ycsb-ysql.md
docs/content/preview/contribute/docs/docs-build.md
docs/content/preview/contribute/docs/include-markdown.md
docs/content/preview/drivers-orms/orms/nodejs/ysql-prisma.md
docs/content/preview/drivers-orms/orms/nodejs/ysql-sequelize.md
docs/content/preview/explore/indexes-constraints/_index.md
docs/content/preview/explore/indexes-constraints/covering-index-ysql.md
docs/content/preview/explore/indexes-constraints/expression-index-ysql.md
docs/content/preview/explore/indexes-constraints/foreign-key-ysql.md
docs/content/preview/explore/indexes-constraints/gin.md
docs/content/preview/explore/indexes-constraints/other-constraints.md
docs/content/preview/explore/indexes-constraints/partial-index-ycql.md
docs/content/preview/explore/indexes-constraints/partial-index-ysql.md
docs/content/preview/explore/indexes-constraints/primary-key-ycql.md
docs/content/preview/explore/indexes-constraints/primary-key-ysql.md
docs/content/preview/explore/indexes-constraints/secondary-indexes.md
docs/content/preview/explore/indexes-constraints/unique-index-ycql.md
docs/content/preview/explore/indexes-constraints/unique-index-ysql.md
docs/content/preview/explore/json-support/jsonb-ycql.md
docs/content/preview/explore/json-support/jsonb-ysql.md
docs/content/preview/faq/compatibility.md
docs/content/preview/faq/general.md

[docs] Remove duplicate meta info

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

The command options have been updated.

Update on-premises.md for node-agents

---

docs/content/preview/admin/ysqlsh-meta-commands.md
docs/content/preview/admin/ysqlsh-meta-examples.md
docs/content/preview/admin/ysqlsh-pset-options.md
docs/content/preview/admin/ysqlsh.md

Split pset options into separate file to shorten the page for indexing
@netlify /preview/admin/ysqlsh-meta-commands/

[docs] Break meta-commands

---

docs/content/preview/yugabyte-cloud/cloud-clusters/managed-read-replica.md

Remove limitation for read replicas.
@netlify /preview/yugabyte-cloud/cloud-clusters/managed-read-replica/

[docs][cloud] Read replicas now support public access

---

docs/content/preview/explore/ysql-language-features/postgresql-compatibility.md
docs/content/preview/explore/ysql-language-features/sql-feature-support.md

@netlify /preview/explore/ysql-language-features/sql-feature-support/

[docs] edits to compatibility matrix

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md

All KSM version below 2.0.0 are deprecated.
Related commit - https://github.com/yugabyte/charts/commit/bf10986cabb3f83ad289fcf3244a68b31ff92588

[PLAT-8046][yba][docs] Updated the kube-state-metrics version

---

docs/content/preview/migrate/known-issues/_index.md
docs/content/preview/migrate/reference/datatype-mapping-mysql.md
docs/content/preview/migrate/reference/datatype-mapping-oracle.md
docs/content/preview/migrate/reference/yb-voyager-cli.md

@netlify /preview/migrate/known-issues/#unsupported-features

[docs] typos and updates to voyager pages.

---

docs/content/preview/api/ysql/datatypes/type_serial.md
docs/content/preview/api/ysql/exprs/func_nextval.md
docs/content/preview/api/ysql/the-sql-language/statements/txn_begin.md
docs/content/preview/api/ysql/the-sql-language/statements/txn_set.md
docs/content/preview/api/ysql/the-sql-language/statements/txn_show.md
docs/content/preview/architecture/transactions/isolation-levels.md
docs/content/preview/architecture/transactions/read-committed.md
docs/content/preview/explore/transactions/isolation-levels.md
docs/content/preview/reference/configuration/yb-tserver.md

Document Server sequence cache method.
@netlify /preview/reference/configuration/yb-tserver/#ysql-sequence-cache-method

[docs] Fix DOC-28

---

docs/content/preview/faq/comparisons/amazon-dynamodb.md
docs/content/preview/troubleshoot/cluster/replace_failed_peers.md
docs/content/preview/troubleshoot/cluster/replace_tserver.md

Clarify paragraph on comparison page
@netlify /preview/faq/comparisons/amazon-dynamodb/

[docs] FAQ comparison edit

---

docs/content/preview/launch-and-manage/monitor-and-alert/metrics/cache-storage.md
docs/content/preview/launch-and-manage/monitor-and-alert/metrics/raft-dst.md
docs/content/preview/launch-and-manage/monitor-and-alert/metrics/throughput.md
docs/content/preview/launch-and-manage/monitor-and-alert/metrics/ybmaster.md
docs/content/preview/yugabyte-cloud/cloud-clusters/managed-read-replica.md
docs/content/preview/yugabyte-cloud/release-notes.md

Remove read replica YBM beta tag
@netlify /preview/yugabyte-cloud/cloud-clusters/managed-read-replica/

[docs] Format, remove beta tag

---

docs/content/preview/migrate/reference/yb-voyager-cli.md
docs/content/preview/migrate/release-notes.md

For v1.2 , added the enhancements for `import data file` command.
@netlify /preview/migrate/release-notes/

[docs] [voyager] added AWS S3 details and release notes for v1.2

---

docs/content/preview/yugabyte-cloud/release-notes.md

New features Mar 27

---

docs/content/preview/develop/learn/acid-transactions-ycql.md

- Fix isolation modes
- Cleanup ToC.

Clean up YCQL transactions page

---

docs/content/preview/admin/yb-admin.md
docs/content/preview/secure/encryption-at-rest.md
docs/content/stable/admin/yb-admin.md
docs/content/stable/secure/encryption-at-rest.md
docs/content/v2.12/admin/yb-admin.md
docs/content/v2.14/admin/yb-admin.md
docs/content/v2.14/secure/encryption-at-rest.md
docs/content/v2.8/admin/yb-admin.md

[docs] Fix typo `add_universe_keys_to_all_masters` -> `add_universe_key_to_all_masters`

---

docs/content/preview/releases/release-notes/v2.14.md
docs/data/currentVersions.json

Notes to self : RC build 17 at the moment. Change accordingly .
https://deploy-preview-16649--infallible-bardeen-164bc9.netlify.app/preview/releases/release-notes/v2.14/

[docs] release notes added for 2.14.8.0

---

docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md
docs/content/preview/yugabyte-cloud/release-notes.md

Update AWS instance type
@netlify /preview/yugabyte-cloud/cloud-basics/create-clusters-overview/

[docs][cloud] Update AWS instance type

---

docs/assets/scss/_code_block.scss
docs/content/preview/contribute/docs/docs-style.md

Highlight badcode or make wrong coding practices stand out  than regular code.

[Docs] Badcode highlight

---

docs/content/preview/integrations/apache-kafka.md

Fix the name of a file in Kafka example
@netlify /preview/integrations/apache-kafka/

[docs] Kafka Filename fix

---

docs/content/preview/api/ysql/the-sql-language/statements/ddl_create_sequence.md
docs/content/stable/api/ysql/the-sql-language/statements/ddl_create_sequence.md
docs/content/v2.12/api/ysql/the-sql-language/statements/ddl_create_sequence.md
docs/content/v2.14/api/ysql/the-sql-language/statements/ddl_create_sequence.md
docs/content/v2.8/api/ysql/the-sql-language/statements/ddl_create_sequence.md

resolves #16836 
@netlify /preview/api/ysql/the-sql-language/statements/ddl_create_sequence/#cache-cache

[docs] changed default value for cache size

---

.github/workflows/create-repository-dispatch.yml

The name of the repo has changed.

Update homebrew-yugabytedb to homebrew-tap

---

docs/content/preview/architecture/query-layer/overview.md
docs/content/preview/benchmark/sysbench-ysql.md
docs/content/preview/faq/yugabytedb-managed-faq.md
docs/content/preview/integrations/apache-spark/_index.md
docs/content/preview/integrations/wso2.md
docs/content/preview/reference/configuration/yugabyted.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/_index.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-vpc.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-vpc-intro.md
docs/content/stable/benchmark/sysbench-ysql.md
docs/content/stable/reference/configuration/yugabyted.md
docs/content/v2.12/benchmark/sysbench-ysql.md
docs/content/v2.12/explore/query-1-performance/pg-stat-activity.md
docs/content/v2.14/benchmark/sysbench-ysql.md
docs/content/v2.14/reference/configuration/yugabyted.md
docs/content/v2.8/benchmark/sysbench-ysql.md
docs/content/v2.8/explore/query-1-performance/pg-stat-activity.md

Fix duplicate tags and broken image
@netlify /preview/integrations/apache-spark/

[docs] Fix duplicate meta and broken image

---

docs/content/preview/admin/ysql-dump.md
docs/content/stable/admin/ysql-dump.md

Remove some extraneous backquotes that were messing up formatting.
@netlify /preview/admin/ysql-dump.md

[docs] Remove extraneous backquotes

---

docs/content/preview/admin/ysql-dump.md
docs/content/stable/admin/ysql-dump.md

Fix mangled link text
https://github.com/netlify /preview/admin/ysql-dump/

[docs] Fix broken link text

---

docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-overview.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/_index.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-cluster.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-network.md

Update commands to ybm CLI v0.1.6
@netlify /preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/

[docs][ybm] Update for ybm CLI

---

docs/content/preview/develop/learn/transactions/transactions-global-apps.md

-  Add info about the identity index in the Transactions section

add identity index

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md

@netlify /preview/yugabyte-platform/install-yugabyte-platform/install-software/airgapped/#set-the-tls-version-for-yugaware-frontend
https://deploy-preview-17051--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/install-yugabyte-platform/install-software/airgapped/#set-the-tls-version-for-yugaware-frontend

[docs] fixed image for yba install page

---

docs/content/preview/secure/vulnerability-disclosure-policy.md

- add "not in scope" section to the vulnerability disclosure

[docs] Update vulnerability disclosure policy

---

docs/content/preview/manage/backup-restore/snapshot-ysql.md
docs/content/stable/manage/backup-restore/snapshot-ysql.md
docs/content/v2.14/manage/backup-restore/snapshot-ysql.md

[docs] Fix ysql_dump,cp commands in snapshot-ysql.md

---

docs/content/preview/manage/data-migration/bulk-import-ycql.md
docs/content/stable/manage/data-migration/bulk-import-ycql.md
docs/content/v2.14/manage/data-migration/bulk-import-ycql.md

resolves #17086 
@netlify /preview/manage/data-migration/bulk-import-ycql/#install-cassandra-loader

[docs] correction with the file generator for sample data ycql

---

docs/content/preview/yugabyte-cloud/release-notes.md

EAR for CMK on AWS KMS
@netlify /preview/yugabyte-cloud/cloud-secure-clusters/managed-ear/

[docs][cloud] CMK on AWS KMS release note

---

docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software.md
docs/content/stable/yugabyte-platform/manage-deployments/upgrade-software.md

@netlify /preview/yugabyte-platform/manage-deployments/upgrade-software/
Note to self: Changes to go to stable as well.

[docs] Additional clean up for ybc workaround

---

docs/content/preview/develop/build-apps/python/cloud-ysql-python.md

[docs] Fix python code for `select_accounts` in "Build a Python application that uses YSQL" page

---

build-support/common-build-env.sh
src/yb/master/master-path-handlers.cc

This PR solves https://github.com/yugabyte/yugabyte-db/issues/15714

Deleted tablets will not be displayed on Underreplicated Tablets page

---

docs/content/preview/releases/versioning.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md

[docs] Mention that upgrading from preview to stable is not supported

---

docs/content/preview/secure/authorization/row-level-security.md
docs/content/stable/secure/authorization/row-level-security.md
docs/content/v2.14/secure/authorization/row-level-security.md

[docs] Fix RLS by using `BYPASSRLS` instead of `NOBYPASSRLS` to see all rows

---

docs/content/preview/admin/yb-admin.md
docs/content/stable/admin/yb-admin.md

[docs] Fix yb-admin add_transaction_tablet command arguments

---

docs/content/preview/yugabyte-platform/security/enable-encryption-in-transit.md
docs/content/stable/yugabyte-platform/security/enable-encryption-in-transit.md
docs/content/v2.14/yugabyte-platform/security/enable-encryption-in-transit.md

[docs] Fix sentence for when you "use an intermediate ca/issuer, but do not have the complete chain of certificates"

---

docs/content/preview/quick-start/linux.md

[docs] Mention that the ip may change when starting a local cluster

---

docs/content/stable/yugabyte-platform/back-up-restore-universes/back-up-universe-data/ysql.md

@netlify /preview/yugabyte-platform/back-up-restore-universes/back-up-universe-data/ysql/#create-incremental-backups

[docs] added ybc on k8s support for incremental backups

---

docs/assets/scss/_styles_project.scss
docs/assets/scss/_yb_badge.scss
docs/assets/scss/_yb_headings.scss
docs/layouts/_default/content.html
docs/layouts/indexpage/list.html
docs/layouts/partials/badges.html

Add `techPreview` or `earlyAccess` parameter similar to `beta` parameter.
```md
techPreview: /preview/faq/general/#what-is-the-definition-of-the-beta-feature-tag
```
```md
earlyAccess: /preview/faq/general/#what-is-the-definition-of-the-beta-feature-tag
```

[Docs] New badges (Tech Preview and Early Access) similar to Beta

---

docs/content/preview/manage/upgrade-deployment.md

Added guidance for handling upgrades when XCluster is enabled.

Update guidance for handling upgrades with xCluster

---

docs/content/preview/admin/yb-ts-cli.md

[docs] Explain --certs_dir_name flag to yb-ts-cli.md and in examples

---

docs/content/preview/deploy/multi-dc/async-replication.md

Added detailed steps for handling DDL changes with XCluster.

Docs update for Handling of DDL changes

---

docs/content/preview/yugabyte-platform/alerts-monitoring/_index.md
docs/content/preview/yugabyte-platform/alerts-monitoring/alert.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/alert-policy-templates.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-alerts-health-check.md

Update Alert configuration, including customizing templates and custom variables
@netlify /preview/yugabyte-platform/configure-yugabyte-platform/set-up-alerts-health-check/

[docs][yba] Update alert configuration

---

docs/content/preview/admin/ysqlsh-meta-commands.md
docs/content/preview/architecture/docdb-replication/async-replication.md
docs/content/preview/explore/ysql-language-features/_index.md
docs/content/preview/manage/backup-restore/point-in-time-recovery.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-alerts-health-check.md

Remove tablegroup references
@netlify /preview/manage/backup-restore/point-in-time-recovery/

[docs] Remove tablegroup references

---

docs/content/preview/drivers-orms/java/yugabyte-jdbc.md

[docs] Fix typo in jdbc smart driver url

---

docs/content/preview/admin/yb-admin.md
docs/content/stable/admin/yb-admin.md
docs/content/v2.12/admin/yb-admin.md
docs/content/v2.14/admin/yb-admin.md
docs/content/v2.8/admin/yb-admin.md

[docs] Fix list_tablets command for yb-admin.md

---

docs/content/preview/api/ysql/the-sql-language/statements/savepoint_release.md

[docs] Add note that releasing a savepoint will release all savepoints created after it.

---

docs/content/preview/explore/multi-region-deployments/read-replicas-ycql.md
docs/content/stable/explore/multi-region-deployments/read-replicas-ycql.md
docs/content/v2.12/explore/multi-region-deployments/read-replicas-ycql.md
docs/content/v2.14/explore/multi-region-deployments/read-replicas-ycql.md
docs/content/v2.8/explore/multi-region-deployments/read-replicas-ycql.md

[docs] Remove xCluster reference from read-replicas

---

docs/content/preview/api/ycql/dml_select.md
docs/content/stable/api/ycql/dml_select.md
docs/content/v2.12/api/ycql/dml_select.md
docs/content/v2.14/api/ycql/dml_select.md
docs/content/v2.8/api/ycql/dml_select.md

[docs] Explain `ALLOW FILTERING` on YCQL `SELECT` query

---

docs/content/preview/deploy/_index.md
docs/content/preview/deploy/checklist.md
docs/content/preview/deploy/manual-deployment/_index.md
docs/content/preview/deploy/manual-deployment/install-software.md
docs/content/preview/deploy/manual-deployment/start-masters.md
docs/content/preview/deploy/manual-deployment/start-tservers.md
docs/content/preview/deploy/manual-deployment/system-config.md
docs/content/preview/deploy/manual-deployment/verify-deployment.md
docs/content/preview/deploy/public-clouds/aws/manual-deployment.md
docs/content/preview/faq/general.md
docs/content/preview/launch-and-manage/_index.md

Fixes #14832
Please check all changes.

[docs] Fix metadata for some pages

---

docs/content/preview/admin/yb-admin.md
docs/content/preview/deploy/multi-dc/async-replication.md
docs/content/stable/admin/yb-admin.md
docs/content/stable/deploy/multi-dc/async-replication.md

Part of https://github.com/yugabyte/yugabyte-db/issues/15050

[docs] Add `<replication_stream_name>` to `setup_universe_replication` in xCluster deployment page

---

docs/content/preview/explore/cluster-management/point-in-time-recovery-ycql.md
docs/content/preview/explore/cluster-management/point-in-time-recovery-ysql.md
docs/content/preview/manage/backup-restore/snapshot-ysql.md
docs/content/preview/manage/backup-restore/snapshots-ycql.md
docs/content/stable/explore/cluster-management/point-in-time-recovery-ycql.md
docs/content/stable/explore/cluster-management/point-in-time-recovery-ysql.md
docs/content/stable/manage/backup-restore/snapshot-ysql.md
docs/content/stable/manage/backup-restore/snapshots-ycql.md

[docs] Add "Creation Time" column on `list_snapshots` output

---

docs/content/preview/troubleshoot/nodes/check-processes.md

[docs] Replace "selinux"->"firewall" on check-processes.md page

---

docs/content/preview/reference/configuration/yb-tserver.md

Fixes #14877
After this, I will start documenting options that we've added in this new section.

[docs] Postgresql options section in yb-tserver config

---

docs/content/preview/secure/vulnerability-disclosure-policy.md
docs/content/stable/secure/vulnerability-disclosure-policy.md
docs/content/v2.12/secure/vulnerability-disclosure-policy.md
docs/content/v2.14/secure/vulnerability-disclosure-policy.md

[docs] Remove ` and respond to your submission as soon as we can` from docs

---

docs/content/preview/admin/yb-admin.md
docs/content/stable/admin/yb-admin.md
docs/content/v2.12/admin/yb-admin.md
docs/content/v2.14/admin/yb-admin.md
docs/content/v2.8/admin/yb-admin.md

[docs] Explain `yb-admin -init_master_addrs` flag

---

docs/content/preview/migrate/migrate-steps.md
docs/content/preview/migrate/reference/yb-voyager-cli.md

@netlify /preview/migrate/migrate-steps/#import-data-file

[docs] added details about import data file with S3

---

docs/content/preview/api/ysql/the-sql-language/statements/_index.md
docs/content/stable/api/ysql/the-sql-language/statements/_index.md
docs/content/v2.12/api/ysql/the-sql-language/statements/_index.md
docs/content/v2.14/api/ysql/the-sql-language/statements/_index.md
docs/content/v2.16/api/ysql/the-sql-language/statements/_index.md
docs/content/v2.8/api/ysql/the-sql-language/statements/_index.md

Hide H4s in SQL statement pages #15408
@netlify /preview/api/ysql/the-sql-language/statements/

[docs] Hide H4s in SQL statement pages #15408

---

docs/content/preview/yugabyte-platform/_index.md
docs/content/stable/yugabyte-platform/_index.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/default.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites/default.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md

Port changes to install instructions to stable
@netlify /stable/yugabyte-platform/install-yugabyte-platform/prerequisites/default/

[docs][yba] Port changes to stable

---

docs/content/preview/yugabyte-cloud/cloud-secure-clusters/managed-ear.md

Edit to intro of EAR
@netlify /preview/yugabyte-cloud/cloud-secure-clusters/managed-ear/

[docs][ybm] Edit to EAR intro

---

docs/content/preview/releases/release-notes/v2.16.md
docs/content/preview/releases/release-notes/v2.17.md
docs/content/preview/releases/release-notes/v2.18.md
docs/content/preview/releases/yba-releases/v2.16.md
docs/content/preview/releases/yba-releases/v2.17.md

@netlify /preview/releases/release-notes/v2.18/

[docs] added third party licenses for missed release versions

---

docs/content/preview/drivers-orms/php/laravel.md
docs/content/stable/api/ysql/name-resolution-in-top-level-sql.md
docs/content/stable/api/ysql/user-defined-subprograms-and-anon-blocks/language-plpgsql-subprograms/plpgsql-execution-model.md
docs/content/stable/api/ysql/user-defined-subprograms-and-anon-blocks/pg-proc-catalog-table.md
docs/content/stable/api/ysql/user-defined-subprograms-and-anon-blocks/subprogram-attributes/alterable-function-only-attributes/immutable-function-examples.md
docs/content/stable/drivers-orms/orms/php/ysql-laravel.md
docs/content/stable/drivers-orms/php/laravel.md

Fix links in stable branch
@netlify /preview/drivers-orms/php/laravel/

[docs] Fix links in stable

---

docs/content/preview/secure/tls-encryption/server-to-server.md

[docs] Fix typo in sentence in server-to-server encryption

---

docs/content/preview/explore/_index.md
docs/content/preview/reference/configuration/yugabyted.md

Explain that nodes will need to be re-joined on vm/node restart.
Fixes #13745

[docs] Put inside Note that `yugabyted` is not production ready.

---

docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-endpoint.md
docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md

Remove Beta tags from Perf advisor and private service endpoints
@netlify /preview/yugabyte-cloud/cloud-monitor/cloud-advisor/

[docs][ybm] Remove Beta tags from Perf and PSE

---

docs/content/preview/architecture/core-functions/table-creation.md
docs/content/preview/architecture/core-functions/universe-creation.md
docs/content/stable/architecture/core-functions/table-creation.md
docs/content/stable/architecture/core-functions/universe-creation.md

[docs] Fix sentence "Suppose a table is created in a YugabyteDB universe with four nodes."

---

docs/content/preview/architecture/docdb-sharding/colocated-tables.md
docs/content/stable/architecture/docdb-sharding/colocated-tables.md

[docs] Fix query to create table (with colocation=false)

---

docs/content/preview/admin/yb-admin.md
docs/content/stable/admin/yb-admin.md

[docs] Add command `yb-admin compact_table_by_id`

---

docs/config/_default/menus.toml
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/_index.md
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/ldap-authentication.md
docs/content/preview/yugabyte-platform/alerts-monitoring/_index.md
docs/content/preview/yugabyte-platform/alerts-monitoring/live-queries-dashboard.md
docs/content/preview/yugabyte-platform/anywhere-automation/_index.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/_index.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/_index.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/aws.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
docs/content/preview/yugabyte-platform/create-deployments/_index.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/_index.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md
docs/content/preview/yugabyte-platform/manage-deployments/_index.md
docs/content/preview/yugabyte-platform/security/_index.md
docs/content/preview/yugabyte-platform/troubleshoot/_index.md
docs/content/preview/yugabyte-platform/upgrade/_index.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/_index.md
docs/content/stable/yugabyte-platform/anywhere-automation/_index.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md

Add Automation docs for YBA, including link to Terraform provider
@netlify /preview/yugabyte-platform/anywhere-automation/

[docs][yba] Add Automation docs for YBA

---

docs/content/preview/api/ysql/the-sql-language/statements/ddl_drop_table.md
docs/content/stable/api/ysql/the-sql-language/statements/ddl_drop_table.md
docs/content/v2.12/api/ysql/the-sql-language/statements/ddl_drop_table.md
docs/content/v2.14/api/ysql/the-sql-language/statements/ddl_drop_table.md
docs/content/v2.16/api/ysql/the-sql-language/statements/ddl_drop_table.md
docs/content/v2.8/api/ysql/the-sql-language/statements/ddl_drop_table.md

[docs] Fix typo on dropping table with RESTRICT/CASCADE

---

docs/content/preview/integrations/cdc/debezium.md
docs/content/stable/explore/change-data-capture/_index.md
docs/content/stable/explore/change-data-capture/cdc-get-started.md
docs/content/stable/explore/change-data-capture/cdc-monitor.md
docs/content/stable/explore/change-data-capture/cdc-overview.md
docs/content/stable/explore/change-data-capture/cdc-tutorials/_index.md
docs/content/stable/explore/change-data-capture/cdc-tutorials/cdc-aws-msk.md
docs/content/stable/explore/change-data-capture/cdc-tutorials/cdc-azure-event-hub.md
docs/content/stable/explore/change-data-capture/cdc-tutorials/cdc-confluent-cloud.md
docs/content/stable/explore/change-data-capture/cdc-tutorials/cdc-redpanda.md
docs/content/stable/explore/change-data-capture/debezium-connector-yugabytedb.md
docs/content/v2.14/explore/change-data-capture/_index.md
docs/content/v2.14/explore/change-data-capture/debezium-connector-yugabytedb.md
docs/content/v2.16/explore/change-data-capture/_index.md
docs/content/v2.16/explore/change-data-capture/debezium-connector-yugabytedb.md

EA for stable
TP for 2.14 and 2.16

[docs] added EA to stable CDC docs

---

docs/content/preview/architecture/docdb/persistence.md
docs/content/stable/architecture/docdb/persistence.md

@netlify /preview/architecture/docdb/persistence/#limitations
Slack request : https://yugabyte.slack.com/archives/CDQB8MEAU/p1685116341027539

[docs] removed a Github issue from limitations

---

docs/src/index.js

@netlify /preview/api/ysql/user-defined-subprograms-and-anon-blocks/subprogram-attributes/

[Docs] Change all page tabs when single tab is changed

---

docs/content/preview/explore/ysql-language-features/pg-extensions.md

Add the HypoPG pre-bundled PostgreSQL extension
JIRA DOC-38

[docs] Add HypoPG extension

---

docs/content/preview/architecture/docdb-replication/replication.md

minor correctness tweaks
should also be made to at least stable branch

Minor tweaks to replication.md

---

docs/content/preview/releases/release-notes/v2.14.md
docs/content/preview/releases/release-notes/v2.16.md

A release note needed to be moved from bugs to improvements.

[docs] fix for a release note 

---

docs/content/preview/releases/yba-releases/v2.16.md
docs/content/preview/yugabyte-cloud/cloud-clusters/_index.md
docs/content/preview/yugabyte-cloud/cloud-clusters/backup-clusters.md
docs/content/preview/yugabyte-cloud/cloud-clusters/cloud-maintenance.md
docs/content/preview/yugabyte-cloud/cloud-clusters/configure-clusters.md
docs/content/preview/yugabyte-cloud/cloud-clusters/managed-read-replica.md
docs/content/preview/yugabyte-cloud/cloud-monitor/_index.md
docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
docs/content/preview/yugabyte-platform/alerts-monitoring/performance-advisor.md
docs/content/preview/yugabyte-platform/create-deployments/async-replication-platform.md
docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-cloud.md
docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-zone.md

Clarify what happens if you try to perform an operation and a blocking operation running is already running.
@netlify /preview/yugabyte-cloud/cloud-clusters/managed-read-replica/#limitations

[docs][ybm] Clarify behavior on blocking operation

---

docs/content/preview/contribute/docs/docs-build.md

@netlify https://docs.yugabyte.com/preview/contribute/docs/docs-build/
slack thread: https://yugabyte.slack.com/archives/CDQB8MEAU/p1686070084305479

[docs] Update python instructions in contributor guide

---

docs/content/preview/releases/release-notes/v2.14.md
docs/data/currentVersions.json

[docs] RN for 2.14.10.1

---

docs/content/preview/yugabyte-cloud/cloud-admin/manage-access.md
docs/content/preview/yugabyte-cloud/cloud-admin/managed-roles.md
docs/content/preview/yugabyte-cloud/cloud-secure-clusters/add-users.md
docs/content/preview/yugabyte-cloud/cloud-secure-clusters/cloud-users.md

Clarify DB vs YBM users
@netlify /preview/yugabyte-cloud/cloud-admin/managed-roles/

[docs][ybm] Clarify DB vs YBM users

---

docs/content/preview/releases/release-notes/v2.14.md

[docs] RN 2.14 Fix typo

---

docs/content/preview/explore/query-1-performance/pg-stat-statements.md
docs/content/stable/explore/query-1-performance/pg-stat-statements.md

pg_stat_statements add yb_latency_histogram
2.18.1 (stable) and 2.19.1 (preview)
DOC-45
@netlify /preview/explore/query-1-performance/pg-stat-statements/

[docs] [DOC-45] pg_stat_statements add yb_latency_histogram

---

docs/content/preview/releases/release-notes/v2.14.md

Add note on using YBA 2.14.10.1

[docs] Note for PLAT-8833

---

docs/content/preview/integrations/apache-spark/python-ysql.md

[docs] Fix typo on PySpark integrations

---

docs/assets/scss/_tables.scss
docs/config/_default/config.toml
docs/content/preview/api/ycql/_index.md
docs/content/preview/api/ycql/cassandra-compatibility.md
docs/content/preview/faq/comparisons/cassandra.md
docs/layouts/shortcodes/icon/no.html
docs/layouts/shortcodes/icon/partial.html
docs/layouts/shortcodes/icon/yes.html
docs/layouts/shortcodes/issue.html

- Lists features that are missing or slightly different from Cassandra 3.4.2
@netlify /preview/api/ycql/cassandra-compatibility

YCQL - Cassandra 3.4.2 feature parity

---

docs/content/preview/launch-and-manage/monitor-and-alert/metrics/throughput.md

[docs] Update throughput.md

---

docs/content/preview/releases/release-notes/v2.14.md
docs/content/v2.14/reference/configuration/yb-master.md
docs/content/v2.16/reference/configuration/yb-master.md
docs/data/currentVersions.json

RN for 2.14.10.2 b1
@netlify /preview/releases/release-notes/v2.14/#v2.14.10.2

[docs] RN for 2.14.10.2 b1

---

docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-zone.md
docs/content/preview/yugabyte-platform/create-deployments/read-replicas.md
docs/content/preview/yugabyte-platform/manage-deployments/edit-config-flags.md
docs/content/stable/yugabyte-platform/create-deployments/create-universe-multi-zone.md
docs/content/stable/yugabyte-platform/create-deployments/read-replicas.md
docs/content/stable/yugabyte-platform/manage-deployments/edit-config-flags.md
docs/content/v2.14/yugabyte-platform/create-deployments/read-replicas.md
docs/content/v2.16/yugabyte-platform/create-deployments/read-replicas.md

Update instructions for changing RF of read replicas
DOC-47
@netlify /preview/yugabyte-platform/create-deployments/read-replicas/

[docs][yba][DOC-47][DOC-48] Changing replication factor of read replicas

---

docs/content/preview/releases/release-notes/v2.17.md
docs/content/preview/releases/release-notes/v2.18.md
docs/content/preview/releases/release-notes/v2.19.md
docs/content/preview/releases/yba-releases/v2.17.md
docs/content/preview/releases/yba-releases/v2.18.md
docs/content/preview/releases/yba-releases/v2.19.md

Remove item that is part of larger unfinished project
@netlify /preview/releases/release-notes/v2.19/

[docs] Update 2.19.0 RN

---

docs/content/stable/admin/yb-admin.md
docs/content/stable/manage/upgrade-deployment.md

Add promote_auto_flags command to the `yb-admin` doc.
Add AutoFlags promotion step to the `Upgrade a deployment` doc
Fixes #17248

[#17248] Doc: Update documentation for Upgrade and AutoFlag Promotion 

---

docs/content/preview/admin/yb-admin.md
docs/content/preview/manage/upgrade-deployment.md
docs/content/stable/admin/yb-admin.md
docs/content/stable/manage/upgrade-deployment.md

Port changes from #17248 to preview
@netlify /preview/admin/yb-admin/#upgrade

[docs] Port #17248 changes to preview

---

docs/content/preview/integrations/prisma.md
docs/netlify.toml

Fix links on legacy Prisma Integrations page
@netlify /preview/integrations/prisma/

[docs] Fix links on legacy Prisma

---

docs/content/preview/develop/build-apps/_index.md
docs/content/preview/drivers-orms/_index.md
docs/content/preview/integrations/_index.md

Fix aliases for drivers and sample apps
@netlify /preview/quick-start/build-apps/

[Docs] Fix aliases

---

src/postgres/src/backend/postmaster/pgstat.c
src/postgres/src/backend/utils/misc/pg_yb_utils.c
src/yb/yql/pggate/pg_doc_op.cc
src/yb/yql/pggate/pg_doc_op.h
src/yb/yql/pggate/pg_op.h
src/yb/yql/pggate/pg_perform_future.cc
src/yb/yql/pggate/pg_perform_future.h
src/yb/yql/pggate/pg_session.h
src/yb/yql/pggate/pggate.cc
src/yb/yql/pggate/util/CMakeLists.txt
src/yb/yql/pggate/util/ybc_stat.cpp
src/yb/yql/pggate/util/ybc_stat.h
src/yb/yql/pggate/ybc_pg_typedefs.h

Major work to be done:
* Add metadata for events
* Add support ofr YB PGGate events in pgstat.c so that it can print the right event names.

[WIP] Set PGGate AUH events in PGPROC 

---

docs/content/preview/migrate/known-issues/_index.md
docs/content/preview/migrate/migrate-steps.md
docs/content/preview/migrate/mysql.md
docs/content/preview/migrate/oracle.md
docs/content/preview/migrate/reference/yb-voyager-cli.md
docs/content/preview/migrate/release-notes.md

Update Voyager docs for v1.4
DOC-61
@netlify /preview/migrate/

[docs] Voyager Update for v1.4

---

docs/content/preview/migrate/release-notes.md

Minor edit to RN
@netlify /preview/migrate/release-notes/

[docs][ybv] Minor edit to RN

---

docs/content/preview/yugabyte-cloud/release-notes.md

[docs][ybm] Whats new Jun 30 2023

---

docs/content/preview/yugabyte-cloud/_index.md
docs/content/preview/yugabyte-cloud/cloud-basics/_index.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-vpc-intro.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-single-region.md
docs/content/preview/yugabyte-cloud/release-notes.md

Minor edits and add embedded Azure demo

[docs][ybm] Add supademo to RN

---

docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-free.md
docs/content/preview/yugabyte-cloud/cloud-troubleshoot.md

Add item on handling Copy in Sandbox
#17144
@netlify /preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-free/#limitations

[doc][ybm] Large Copy and Sandbox clusters

---

docs/content/stable/yugabyte-platform/create-deployments/read-replicas.md

Port RR intro change to stable
@netlify /stable/yugabyte-platform/create-deployments/read-replicas/

[docs][yba] Port RR intro change to stable

---

src/yb/client/async_rpc.cc
src/yb/common/common.proto
src/yb/rocksdb/db/db_impl.cc
src/yb/rocksdb/util/thread_posix.cc
src/yb/rpc/inbound_call.cc
src/yb/rpc/yb_rpc.cc
src/yb/tserver/pg_client_session.cc
src/yb/tserver/tablet_service.cc
src/yb/tserver/tserver.proto
src/yb/util/wait_state.cc
src/yb/util/wait_state.h
src/yb/yql/pggate/pg_client.cc
src/yb/yql/pggate/pg_session.cc
src/yb/yql/pggate/pg_session.h

Integrate with ASaha's AUHMetadataPB
trying to add more fields to AUHMetadata
populate client_node_id based on Connection::Endpoint/remote_address()
Include AUHMetadata in all the yb/async_rpc-s
use AUHMetadata in pg_session

Integrate with AUHMetadataPB from pg -> yb_client -> docdb

---

docs/content/preview/yugabyte-platform/_index.md
docs/content/stable/yugabyte-platform/_index.md

Update university links on YBA landing page to new YBA Operations course
@netlify /stable/yugabyte-platform/

[docs][yba] Update university links

---

docs/content/preview/admin/yb-admin.md
docs/content/preview/manage/backup-restore/point-in-time-recovery.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/pitr.md

Add notes about using PITR with YBA and changes made using yb-admin not being reflected in UI
@netlify /preview/manage/backup-restore/point-in-time-recovery/#yugabytedb-anywhere

[docs][yba][DOC-24] PITR and YBA note

---

docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-network.md

Minor corrections to endpoint CLI commands
@netlify /preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-network/

[docs][ybm] Fixes to cli command help

---

docs/content/preview/releases/yba-releases/_index.md

Fix a small typos in release notes

Fix 2.18 2.16 release note link

---

docs/content/preview/develop/learn/text-search/_index.md
docs/content/preview/develop/learn/text-search/pattern-matching.md

@netlify /preview/develop/learn/text-search/

[docs] Edits to full-text search

---

docs/content/preview/develop/_index.md
docs/content/preview/develop/common-patterns/_index.md
docs/content/preview/develop/common-patterns/keyvalue.md
docs/content/preview/develop/common-patterns/timeseries/_index.md
docs/content/preview/develop/common-patterns/timeseries/data-expiry.md
docs/content/preview/develop/common-patterns/timeseries/global-ordering.md
docs/content/preview/develop/common-patterns/timeseries/ordering-by-entity.md
docs/content/preview/develop/common-patterns/timeseries/partitioning-by-time.md
docs/content/preview/develop/learn/text-search/_index.md
docs/content/preview/develop/learn/text-search/full-text-search.md

-  Overview of different data models
- Details on the Timeseries

Common patterns

---

src/yb/util/wait_state.h

fix compilation errors on dev servers

fix compile errors

---

docs/content/preview/develop/build-global-apps/active-active-multi-master.md
docs/content/preview/develop/build-global-apps/active-active-single-master.md
docs/layouts/shortcodes/cluster-setup-tabs.html

- YBM does not support xcluster yet

Removing ybm support from xcluster patterns

---

docs/config/_default/menus.toml
docs/content/preview/yugabyte-cloud/release-notes.md

Move what's new, rename Change Log

[docs][ybm] Move what's new

---

docs/content/preview/releases/_index.md
docs/content/preview/releases/yba-releases/_index.md
docs/data/currentVersions.json

@netlify /preview/releases
https://deploy-preview-18221--infallible-bardeen-164bc9.netlify.app/preview/releases/#release-support-timelines

[DOC-58] changed STS/LTS timelines

---

docs/content/preview/releases/release-notes/v2.14.md
docs/data/currentVersions.json

[docs] RN for 2.14.11.0

---

docs/content/preview/reference/configuration/default-ports.md

Add yugabyted UI to default ports page
@netlify /preview/reference/configuration/default-ports/

[docs] Update ports for yugabyted UI

---

docs/content/preview/yugabyte-cloud/_index.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-peering.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/managed-endpoint-aws.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/managed-endpoint-azure.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-geopartition.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-multisync.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-single-region.md
docs/content/preview/yugabyte-cloud/cloud-clusters/backup-clusters.md
docs/content/preview/yugabyte-cloud/cloud-clusters/configure-clusters.md
docs/content/preview/yugabyte-cloud/cloud-clusters/managed-read-replica.md
docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-queries-slow.md
docs/content/preview/yugabyte-cloud/cloud-monitor/overview.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/_index.md

Update videos in ybm docs
@netlify /preview/yugabyte-cloud/

[docs][ybm] Update videos in ybm docs

---

docs/content/preview/releases/release-notes/v2.16.md

slack request : https://yugabyte.slack.com/archives/C6NHXQY6A/p1689705546546129
@netlify /preview/releases/release-notes/v2.16/#v2.16.5.0

[docs] added a 2.16.5 improvement release note

---

docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
docs/content/preview/yugabyte-platform/alerts-monitoring/performance-advisor.md
docs/content/stable/yugabyte-platform/alerts-monitoring/performance-advisor.md

@netlify /preview/yugabyte-platform/alerts-monitoring/performance-advisor/
slack request : https://yugabyte.slack.com/archives/C05AA8K0SRH/p1685542322993719

[docs] changed query to use hash sharding on perf advisor pages

---

docs/content/preview/explore/indexes-constraints/_index.md

- Explain how indexes are treated in YB
- Add the support level for different types of indexes in YSQL and YCQL
- resolves #11607
@netlify /preview/explore/indexes-constraints/

Small intro into Indexes

---

docs/content/preview/benchmark/key-value-workload-ycql.md
docs/content/preview/benchmark/scalability/scaling-queries-ysql.md
docs/content/preview/explore/linear-scalability/sharding-data.md
docs/content/preview/explore/observability/prometheus-integration/macos.md
docs/content/preview/explore/ysql-language-features/going-beyond-sql/follower-reads-ycql.md
docs/content/preview/reference/configuration/yugabyted.md
docs/content/stable/benchmark/key-value-workload-ycql.md
docs/content/stable/benchmark/scalability/scaling-queries-ysql.md
docs/content/stable/explore/linear-scalability/sharding-data.md
docs/content/stable/explore/observability/prometheus-integration/macos.md
docs/content/stable/explore/ysql-language-features/going-beyond-sql/follower-reads-ycql.md
docs/content/stable/reference/configuration/yugabyted.md
docs/layouts/shortcodes/yb-sample-apps-path.html

Slack request: https://yugabyte.slack.com/archives/CDQB8MEAU/p1690469262038669. Thanks @knicely87 . Updated in other places too.
@netlify /preview/benchmark/key-value-workload-ycql/#benchmark-tool

[docs] updated sample apps jar version

---

docs/content/preview/explore/multi-region-deployments/read-replicas-ycql.md
docs/content/preview/explore/multi-region-deployments/read-replicas-ysql.md
docs/layouts/shortcodes/api-tabs.html

- Also adds a shortcode for api tabs
@netlify /preview/explore/multi-region-deployments/read-replicas-ysql/

Add content for read replica in Explore

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md

Increase documented disk space requirement to match product checks

---

docs/content/preview/admin/yb-ts-cli.md
docs/content/preview/admin/ysql-dump.md
docs/content/preview/admin/ysqlsh.md
docs/content/preview/api/ycql/ddl_alter_role.md
docs/content/preview/api/ycql/ddl_alter_table.md
docs/content/preview/api/ycql/ddl_create_index.md
docs/content/preview/api/ycql/ddl_create_table.md
docs/content/preview/api/ycql/ddl_drop_keyspace.md
docs/content/preview/api/ycql/ddl_drop_role.md
docs/content/preview/api/ycql/dml_delete.md
docs/content/preview/api/ycql/dml_insert.md
docs/content/preview/api/ycql/dml_select.md
docs/content/preview/api/ycql/dml_transaction.md
docs/content/preview/api/ycql/dml_update.md
docs/content/preview/api/ycql/function_datetime.md
docs/content/preview/api/ycql/type_datetime.md
docs/content/preview/api/ycql/type_jsonb.md
docs/content/preview/develop/learn/aggregations-ycql.md
docs/content/preview/explore/json-support/jsonb-ycql.md
docs/content/preview/faq/comparisons/mongodb.md
docs/content/preview/quick-start/explore/binary/explore-ycql.md
docs/content/preview/quick-start/explore/docker/explore-ycql.md
docs/content/preview/sample-data/retail-analytics.md
docs/content/preview/secure/audit-logging/session-audit-logging-ysql.md
docs/content/preview/secure/authentication/_index.md
docs/content/preview/secure/authorization/column-level-security.md
docs/content/preview/secure/authorization/ysql-grant-permissions.md
docs/content/preview/yedis/api/echo.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md

Misc format, lint, typos
Address DOC-82
Address DOC-83
@netlify /preview/api/ycql/type_jsonb/

[docs] Misc format, lint, typos

---

docs/content/preview/explore/ycql-language/cassandra-feature-support.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-apikeys.md

@netlify /preview/yugabyte-cloud/cloud-admin/managed-roles/

[docs] fix typos in links 

---

docs/content/preview/releases/release-notes/v2.16.md
docs/content/preview/releases/yba-releases/v2.16.md
docs/data/currentVersions.json

RN for 2.16.6.1
@netlify /preview/releases/yba-releases/v2.16/

[docs] RN for 2.16.6.1

---

docs/content/preview/releases/release-notes/v2.14.md
docs/data/currentVersions.json

[docs] RN for 2.14.11.1

---

src/yb/client/batcher.cc
src/yb/client/session.cc
src/yb/consensus/raft_consensus.cc
src/yb/rocksdb/table/block_based_table_internal.h
src/yb/rocksdb/table/block_based_table_reader.cc
src/yb/rocksdb/util/thread_posix.cc
src/yb/rpc/inbound_call.cc
src/yb/rpc/service_pool.cc
src/yb/tserver/read_query.cc
src/yb/tserver/service_util.cc
src/yb/util/wait_state.h
src/yb/yql/pggate/util/ybc_stat.cpp

[tag internal rpc/compactions/flush as internal](https://github.com/yugabyte/yugabyte-db/pull/18574/commits/a25e7152fd63d54d899ee5f8c9061571e2403e9e)
[a25e715](https://github.com/yugabyte/yugabyte-db/pull/18574/commits/a25e7152fd63d54d899ee5f8c9061571e2403e9e)
@amitanandaiyer
[more wait-classes](https://github.com/yugabyte/yugabyte-db/pull/18574/commits/d6a8a7232e47ed83429b3c0dc4235daca6549333)
[d6a8a72](https://github.com/yugabyte/yugabyte-db/pull/18574/commits/d6a8a7232e47ed83429b3c0dc4235daca6549333)
@amitanandaiyer
[Set tablet aux in ConsensusServiceImpl](https://github.com/yugabyte/yugabyte-db/pull/18574/commits/96e84899c152cc5f3408c63b0428971dd716f2d4)
[96e8489](https://github.com/yugabyte/yugabyte-db/pull/18574/commits/96e84899c152cc5f3408c63b0428971dd716f2d4)
@amitanandaiyer
[Fix …

Metadata for internal flush/compactions (new)

---

docs/content/preview/explore/_index.md
docs/content/preview/releases/release-notes/v2.16.md
docs/content/preview/releases/yba-releases/v2.16.md
docs/content/stable/explore/_index.md

Format the 2.16.6.1 release notes for clarity
@netlify /preview/releases/release-notes/v2.16/#v2.16.6.1

[docs] Release notes 2.16 edit

---

docs/content/preview/api/ysql/the-sql-language/statements/ddl_create_table.md
docs/content/preview/architecture/docdb-sharding/colocated-tables.md

- Fixes syntax issue in colocated tables
- Fixes #[18563](https://github.com/yugabyte/yugabyte-db/issues/18563)

Fixed statements related to colocated tables

---

docs/content/preview/yugabyte-cloud/cloud-clusters/managed-read-replica.md
docs/content/preview/yugabyte-cloud/release-notes.md

Remove Read replica known issue

[docs][ybm] CLOUDGA-15680

---

docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/managed-endpoint-aws.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/managed-endpoint-azure.md

Fix wrong copy on AWS page
@netlify /preview/yugabyte-cloud/cloud-basics/cloud-vpcs/managed-endpoint-aws/

[docs][ybm] Minor fix for AWS PSE

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md
docs/content/v2.14/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md
docs/content/v2.16/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md

Fix python requirement and backport
@netlify /preview/yugabyte-platform/configure-yugabyte-platform/supported-os-and-arch/#requirements-for-all-oses

[docs][yba] DOC-80 python requirement

---

docs/content/preview/manage/data-migration/bulk-export-ycql.md
docs/content/preview/manage/data-migration/bulk-import-ycql.md

Bulk Import YCQL DB-6987
@netlify /preview/manage/data-migration/bulk-import-ycql/

[docs] Bulk Import YCQL DB-6987

---

docs/content/preview/deploy/manual-deployment/start-tservers.md
docs/content/preview/develop/common-patterns/_index.md
docs/content/preview/develop/common-patterns/keyvalue.md
docs/content/preview/develop/common-patterns/timeseries/_index.md
docs/content/preview/develop/common-patterns/timeseries/data-expiry.md
docs/content/preview/develop/common-patterns/timeseries/global-ordering.md
docs/content/preview/develop/common-patterns/timeseries/ordering-by-entity.md
docs/content/preview/develop/common-patterns/timeseries/partitioning-by-time.md
docs/content/stable/deploy/manual-deployment/start-tservers.md
docs/content/stable/develop/_index.md
docs/content/stable/develop/common-patterns/_index.md
docs/content/stable/develop/common-patterns/keyvalue.md
docs/content/stable/develop/common-patterns/timeseries/_index.md
docs/content/stable/develop/common-patterns/timeseries/data-expiry.md
docs/content/stable/develop/common-patterns/timeseries/global-ordering.md
docs/content/stable/develop/common-patterns/timeseries/ordering-by-entity.md
docs/content/stable/develop/common-patterns/timeseries/partitioning-by-time.md
docs/layouts/shortcodes/cluster-setup-tabs.html
docs/layouts/shortcodes/setup/anywhere.html
docs/layouts/shortcodes/setup/cloud.html

Edits and tidyups in Common patterns section
@netlify /preview/develop/common-patterns/

[docs] Common patterns section edits

---

docs/content/preview/develop/build-global-apps/_index.md
docs/content/preview/develop/build-global-apps/active-active-multi-master.md
docs/content/preview/develop/build-global-apps/active-active-single-master.md
docs/content/preview/develop/build-global-apps/duplicate-indexes.md
docs/content/preview/develop/build-global-apps/follower-reads.md
docs/content/preview/develop/build-global-apps/global-database.md
docs/content/preview/develop/build-global-apps/latency-optimized-geo-partition.md
docs/content/preview/develop/build-global-apps/locality-optimized-geo-partition.md
docs/content/preview/develop/build-global-apps/read-replicas.md
docs/content/preview/faq/general.md
docs/content/stable/develop/build-global-apps/_index.md
docs/content/stable/develop/build-global-apps/active-active-multi-master.md
docs/content/stable/develop/build-global-apps/active-active-single-master.md
docs/content/stable/develop/build-global-apps/duplicate-indexes.md
docs/content/stable/develop/build-global-apps/follower-reads.md
docs/content/stable/develop/build-global-apps/global-database.md
docs/content/stable/develop/build-global-apps/latency-optimized-geo-partition.md
docs/content/stable/develop/build-global-apps/locality-optimized-geo-partition.md
docs/content/stable/develop/build-global-apps/read-replicas.md

Edit the Global applications section in Develop and port the section to stable
@netlify /stable/develop/build-global-apps/

[docs] Edit global apps and port to stable

---

docs/content/preview/releases/_index.md
docs/content/preview/releases/yba-releases/_index.md

Slack request : https://yugabyte.slack.com/archives/CDQB8MEAU/p1692206947911599

[docs] Updated v2.20 to a LTS release

---

src/yb/consensus/raft_consensus.cc
src/yb/rocksdb/util/thread_posix.cc

This PR fixes compilation errors on the dev server.

Fix compile errors on dev server

---

docs/content/preview/releases/release-notes/v2.18.md

Slack thread : https://yugabyte.slack.com/archives/C03VBS9N0GG/p1692249347410019?thread_ts=1692221030.619729&cid=C03VBS9N0GG

[docs] fix issue numbers for RN 2.18.2.1

---

docs/content/preview/architecture/docdb-replication/async-replication.md
docs/content/stable/architecture/docdb-replication/async-replication.md

As title.  This is mostly based on a review by Hari Krishna.
I plan to backport this to the 2.18 branch.

[#17938] xCluster: minor fixes for xCluster architecture page

---

docs/content/preview/explore/observability/_index.md

Adds a small into observability and adds pointers to other sections.
@netlify /preview/explore/observability/

add a stub for observability

---

docs/content/preview/releases/release-notes/v2.18.md

Slack request : https://yugabyte.slack.com/archives/C03VBS9N0GG/p1692378195587649?thread_ts=1692221030.619729&cid=C03VBS9N0GG

[docs] added GitHub link to 2.18.2.1 bug fix

---

src/yb/rpc/service_pool.cc
src/yb/util/wait_state.cc
src/yb/util/wait_state.h

Add a log line in set_state_if
reduce spew. Use TRACE instead of VLOG

Support conditional setting of wait-state

---

docs/content/preview/yugabyte-cloud/release-notes.md

[docs][ybm] Update change log for Aug15

---

docs/content/preview/faq/operations-faq.md

@netlify /preview/faq/operations-faq/#gcp-universe-limitation

[docs] [PLAT-7496] Added GCP limitation to FAQ 

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites/kubernetes.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites/kubernetes.md

@netlify /preview/yugabyte-platform/install-yugabyte-platform/prerequisites/kubernetes/#prepare-the-cluster
To do (back port to stable)

[Doc-99] updated k8 requirements

---

docs/content/preview/secure/tls-encryption/server-certificates.md
docs/content/stable/secure/tls-encryption/server-certificates.md
docs/content/v2.16/secure/tls-encryption/server-certificates.md

@netlify /preview/secure/tls-encryption/server-certificates/
Applied the suggestion as mentioned : https://yugabyte.atlassian.net/browse/PLAT-8011?focusedCommentId=60958

[docs][PLAT-8011] Added days argument in the openssl command

---

docs/content/preview/develop/build-global-apps/read-replicas.md
docs/content/stable/develop/build-global-apps/read-replicas.md

- Adding an example topology for Read Replicas

Add example scenario for Read Replica

---

docs/content/preview/releases/release-notes/v2.14.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.14/#v2.14.12.0
To do(self) : change date, RC build is 19 (update if needed)

[docs] Added release notes for 2.14.12.0

---

docs/content/preview/admin/yb-ctl.md
docs/content/stable/admin/yb-ctl.md
docs/content/v2.12/admin/yb-ctl.md
docs/content/v2.14/admin/yb-ctl.md
docs/content/v2.16/admin/yb-ctl.md
docs/content/v2.8/admin/yb-ctl.md

fixed #18548 
@netlify /preview/admin/yb-ctl/#logs

[docs] fixed paths for server logs

---

docs/config/_default/menus.toml
docs/content/preview/explore/observability/_index.md
docs/content/preview/explore/observability/grafana-dashboard/grafana.md
docs/content/preview/releases/_index.md
docs/content/preview/releases/release-notes/end-of-life/v1.2.md
docs/content/preview/releases/release-notes/end-of-life/v1.3.md
docs/content/preview/releases/release-notes/end-of-life/v2.0.md
docs/content/preview/releases/release-notes/end-of-life/v2.1.md
docs/content/preview/releases/release-notes/end-of-life/v2.11.md
docs/content/preview/releases/release-notes/end-of-life/v2.12.md
docs/content/preview/releases/release-notes/end-of-life/v2.13.md
docs/content/preview/releases/release-notes/end-of-life/v2.2.md
docs/content/preview/releases/release-notes/end-of-life/v2.3.md
docs/content/preview/releases/release-notes/end-of-life/v2.4.md
docs/content/preview/releases/release-notes/end-of-life/v2.5.md
docs/content/preview/releases/release-notes/end-of-life/v2.6.md
docs/content/preview/releases/release-notes/end-of-life/v2.7.md
docs/content/preview/releases/release-notes/end-of-life/v2.8.md
docs/content/preview/releases/release-notes/end-of-life/v2.9.md
docs/content/preview/releases/yba-releases/_index.md
docs/content/preview/yugabyte-cloud/release-notes.md
docs/content/v2.12/yugabyte-platform/install-yugabyte-platform/prerequisites.md
docs/content/v2.14/yugabyte-platform/install-yugabyte-platform/prerequisites.md
docs/content/v2.8/yugabyte-platform/install-yugabyte-platform/prerequisites.md

Move older releases into subdirectory in left nav

[docs] Put older releases under End of life

---

docs/content/preview/benchmark/_index.md
docs/content/preview/benchmark/key-value-workload-ycql.md
docs/content/preview/benchmark/key-value-workload-ysql.md
docs/content/preview/benchmark/large-datasets-ycql.md
docs/content/preview/benchmark/large-datasets-ysql.md
docs/content/preview/benchmark/sysbench-ysql.md
docs/content/preview/benchmark/tpcc-ysql.md
docs/content/preview/benchmark/tpcc-ysql/_index.md
docs/content/preview/benchmark/ycsb-jdbc.md
docs/content/preview/benchmark/ycsb-ycql.md
docs/content/preview/benchmark/ycsb-ysql.md
docs/content/preview/explore/linear-scalability/_index.md

- Updating Benchmark data & stubs
@netlify /preview/benchmark/

Update Benchmark data with latest numbers

---

docs/content/preview/admin/yb-ctl.md
docs/content/preview/architecture/docdb-replication/_index.md
docs/content/preview/deploy/multi-dc/read-replica-clusters.md
docs/content/preview/develop/build-global-apps/duplicate-indexes.md
docs/content/preview/develop/build-global-apps/read-replicas.md
docs/content/stable/admin/yb-ctl.md

Combine macos instructions in a single section for clarity. Format
@netlify /preview/admin/yb-ctl/

[docs] Macos instructions for yb-ctl

---

docs/content/preview/benchmark/sysbench-ysql.md
docs/content/preview/benchmark/tpcc-ysql.md
docs/content/stable/benchmark/_index.md
docs/content/stable/benchmark/key-value-workload-ycql.md
docs/content/stable/benchmark/key-value-workload-ysql.md
docs/content/stable/benchmark/large-datasets-ycql.md
docs/content/stable/benchmark/large-datasets-ysql.md
docs/content/stable/benchmark/sysbench-ysql.md
docs/content/stable/benchmark/tpcc-ysql.md
docs/content/stable/benchmark/ycsb-jdbc.md
docs/content/stable/benchmark/ycsb-ycql.md
docs/content/stable/benchmark/ycsb-ysql.md

Port benchmark update and fixes to stable branch.
@netlify /stable/benchmark/

[docs] Port benchmark update to stable

---

src/yb/util/wait_state.h
src/yb/yql/pggate/util/ybc_stat.cpp

Merge components for ybclient/ycql/perform-api
Create a separate wait-class for pg-perform.

Merge components for ybclient/ycql/perform-api

---

src/yb/yql/pggate/util/ybc_stat.cpp

This reverts commit 11f979e01b017e8a9a1b59586fbf1b237978c4b9.

Revert a commit

---

docs/content/preview/yugabyte-cloud/release-notes.md

[docs][ybm] Change log Sep 6 2023

---

docs/content/preview/develop/best-practices-ycql.md
docs/content/preview/develop/best-practices-ysql.md

- Added YSQL Best practices page 
- Updated YCQL page
@netlify /preview/develop/best-practices-ycql

Best Practices YSQL

---

docs/content/preview/architecture/docdb-sharding/colocated-tables.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/azure.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/azure.md
docs/content/stable/architecture/docdb-sharding/colocated-tables.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/azure.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-environment/azure.md
docs/content/v2.12/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/azure.md
docs/content/v2.12/yugabyte-platform/install-yugabyte-platform/prepare-environment/azure.md
docs/content/v2.14/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/azure.md
docs/content/v2.14/yugabyte-platform/install-yugabyte-platform/prepare-environment/azure.md
docs/content/v2.16/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/azure.md
docs/content/v2.16/yugabyte-platform/install-yugabyte-platform/prepare-environment/azure.md
docs/content/v2.8/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/azure.md
docs/content/v2.8/yugabyte-platform/install-yugabyte-platform/prepare-environment/azure.md

Slack threads on #docs - 
https://yugabyte.slack.com/archives/CDQB8MEAU/p1693958894226129
https://yugabyte.slack.com/archives/CDQB8MEAU/p1693972891862949

[docs] Azure tenant ID link change and colocation text change.

---

docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-peering.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-vpc-intro.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-geopartition.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-multisync.md
docs/content/preview/yugabyte-cloud/cloud-clusters/managed-read-replica.md

Update for Azure support for multi-region clusters and read replicas
@netlify /preview/yugabyte-cloud/

[docs][ybm] Azure support for multi-region and RR

---

docs/content/preview/yugabyte-cloud/release-notes.md

Azure support for multi-region and read replicas in YBM

YBM change log for Sep 12

---

docs/content/preview/secure/vulnerability-disclosure-policy.md
docs/content/stable/secure/vulnerability-disclosure-policy.md

@netlify /preview/secure/vulnerability-disclosure-policy/

[DOC-112] Updates to vulnerability security policy

---

docs/content/preview/faq/comparisons/vitess.md

More correctly representative of current-day Vitess capabilities. The changes made were to be as least invasive as possible while updating the wording to be factually correct.
More background: as of the last few years, Vitess presents a single logical view of the database to clients and has a SQL query planner which distributes queries according to where data is placed across shards. While Vitess does not currently support distributed transactions, it will route reads and writes properly to their shards without client involvement. It supports JOINs, aggregates, etc even in sharded mode.
While these queries will be executed properly, if developers are not aware of how queries will be routed according to data placement in the cluster, they may be performed as a "scatter" and thus will not …

Updated Vitess comparison

---

src/yb/consensus/log.cc
src/yb/docdb/conflict_resolution.cc
src/yb/docdb/lock_batch.cc
src/yb/docdb/wait_queue.cc
src/yb/rocksdb/db/db_impl.cc
src/yb/rocksdb/table/block_based_table_reader.cc
src/yb/rpc/inbound_call.cc
src/yb/rpc/service_pool.cc
src/yb/rpc/yb_rpc.cc
src/yb/tablet/operations/operation_driver.cc
src/yb/tablet/tablet.cc
src/yb/tablet/tablet_peer.cc
src/yb/tablet/write_query.cc
src/yb/tserver/pg_client_service.cc
src/yb/tserver/pg_client_session.cc
src/yb/tserver/read_query.cc
src/yb/tserver/tablet_service.cc
src/yb/util/trace.cc
src/yb/util/trace.h
src/yb/util/wait_state.cc
src/yb/util/wait_state.h
src/yb/yql/cql/ql/exec/executor.cc
src/yb/yql/pgwrapper/pg_mini-test.cc

Use PGWaitingOnDocdb while waiting on docdb. Adopt the wait state in the callback
Comment out some ActiveOnCPU states and control using a gflag to print stack traces
Adopt/WaitStateInfo to set WaitOnTxn correctly

Fix tserver wait on conflict

---

docs/content/preview/architecture/docdb-replication/read-replicas.md
docs/content/preview/develop/build-global-apps/_index.md
docs/content/preview/yugabyte-voyager/release-notes.md
docs/content/stable/architecture/docdb-replication/read-replicas.md
docs/content/stable/develop/build-global-apps/_index.md

Slack requests- 
https://yugabyte.slack.com/archives/CDQB8MEAU/p1694699889712929
https://yugabyte.slack.com/archives/CDQB8MEAU/p1694698784926989

[docs] Voyager RN edit and other minor edits to read replicas 

---

docs/content/preview/releases/release-notes/v2.16.md
docs/content/preview/releases/yba-releases/v2.16.md
docs/data/currentVersions.json

RC-build59
@netlify /preview/releases/release-notes/v2.16/#v2.16.7.0

[docs] Release notes for 2.16.7.0

---

docs/content/preview/yugabyte-cloud/cloud-monitor/monitor-activity.md
docs/content/preview/yugabyte-cloud/cloud-secure-clusters/cloud-activity.md

Remove activity lists as they are redundant
@netlify /preview/yugabyte-cloud/cloud-monitor/monitor-activity/

[doc][ybm] Remove activity lists

---

docs/content/preview/reference/configuration/default-ports.md
docs/content/stable/reference/configuration/default-ports.md

@netlify /preview/reference/configuration/default-ports/#internode-rpc-communication
To do: port to stable if applicable

[DOC-120] Added node agent port to the default ports list.

---

docs/content/preview/yugabyte-cloud/release-notes.md

[docs][ybm] Remove known issue that is fixed

---

docs/content/preview/quick-start/include-connect.md

Fix link problem on included page
@netlify /preview/quick-start/

[docs] Fix links in include page

---

yugabyted-ui/ui/src/assets/yb-logo.svg
yugabyted-ui/ui/src/features/Sidebar.tsx
yugabyted-ui/ui/src/features/clusters/details/nodes/NodesTab.tsx

Backport PR https://github.com/yugabyte/yugabyte-db/pull/17235

[BACKPORT 2.18] yugabyted: Update YugabyteDB new logo in yugabyted UI

---

docs/content/preview/releases/release-notes/v2.14.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.14/#v2.14.13.0
Updated till b13

[docs] release notes for 2.14.13.0

---

docs/content/preview/quick-start/include-connect.md
docs/content/preview/quick-start/include-prerequisites-linux.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/network-access.md

set include files to private
@netlify /preview/

[docs] Set include files to private

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/restore-universe-data.md

[docs] Update restore-universe-data.md

---

docs/content/preview/deploy/manual-deployment/system-config.md
docs/static/code-samples/yb-master.service
docs/static/code-samples/yb-tserver.service

[docs] Add systemd service configuration examples

---

docs/content/preview/launch-and-manage/monitor-and-alert/metrics/cache-storage.md
docs/content/preview/launch-and-manage/monitor-and-alert/metrics/connections.md
docs/content/preview/launch-and-manage/monitor-and-alert/metrics/raft-dst.md
docs/content/preview/launch-and-manage/monitor-and-alert/metrics/replication.md
docs/content/preview/launch-and-manage/monitor-and-alert/metrics/throughput.md
docs/content/preview/launch-and-manage/monitor-and-alert/metrics/ybmaster.md
docs/content/stable/launch-and-manage/monitor-and-alert/metrics/cache-storage.md
docs/content/stable/launch-and-manage/monitor-and-alert/metrics/connections.md
docs/content/stable/launch-and-manage/monitor-and-alert/metrics/raft-dst.md
docs/content/stable/launch-and-manage/monitor-and-alert/metrics/replication.md
docs/content/stable/launch-and-manage/monitor-and-alert/metrics/throughput.md
docs/content/stable/launch-and-manage/monitor-and-alert/metrics/ybmaster.md

Format metric tables
@netlify /preview/launch-and-manage/monitor-and-alert/metrics/throughput/

[docs] Format metric tables

---

docs/content/preview/admin/ysql-dump.md
docs/content/preview/manage/backup-restore/export-import-data.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/_index.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/back-up-universe-data.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/restore-universe-data.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/restore-ysql-single-table.md
docs/content/stable/admin/ysql-dump.md
docs/content/stable/manage/backup-restore/export-import-data.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/_index.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/back-up-universe-data.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/restore-universe-data.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/restore-ysql-single-table.md

Add details to the advanced restore procedure
PLAT-3714
PLAT-10127
@netlify /preview/yugabyte-platform/back-up-restore-universes/restore-universe-data/

[docs][yba] Advanced restore procedure

---

docs/content/stable/architecture/transactions/read-committed.md

[docs] added TP tag for read committed isolation level

---

docs/content/preview/releases/release-notes/v2.14.md

2.14.10.3 Release notes
@netlify /preview/releases/release-notes/v2.14/#v2.14.10.3

[docs] 2.14.10.3 Release notes

---

docs/content/preview/yugabyte-cloud/release-notes.md

[docs][ybm] YBM changes

---

docs/content/preview/yugabyte-cloud/cloud-monitor/_index.md
docs/content/preview/yugabyte-cloud/cloud-monitor/metrics-export.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-metrics-exporter.md

Add Grafana to Metrics Export
@netlify /preview/yugabyte-cloud/cloud-monitor/metrics-export/

[docs][ybm] Add Grafana to Metrics Export

---

docs/content/preview/manage/backup-restore/point-in-time-recovery.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/pitr.md

Clarify features of YBA PITR
DOC-135
@netlify /preview/yugabyte-platform/back-up-restore-universes/pitr/

[docs][yba] PITR clarifications

---

docs/content/preview/yugabyte-cloud/managed-automation/managed-apikeys.md
docs/content/preview/yugabyte-cloud/managed-security/manage-access.md
docs/content/preview/yugabyte-cloud/managed-security/managed-roles.md

Admin page -> Security page
@netlify /preview/yugabyte-cloud/managed-security/manage-access/

[docs][ybm] Admin page -> Security page

---

docs/content/preview/yugabyte-platform/create-deployments/async-replication-platform.md
docs/content/stable/yugabyte-platform/create-deployments/async-replication-platform.md
docs/content/v2.16/yugabyte-platform/create-deployments/async-replication-platform.md

Slack request: https://yugabyte.slack.com/archives/C050VQ5S6TV/p1696255120270879
@netlify v2.16/yugabyte-platform/create-deployments/async-replication-platform/

[docs] [2.16] Updates to YBA xCluster replication 

---

docs/content/preview/architecture/docdb/persistence.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/architecture/docdb/persistence.md
docs/content/stable/architecture/transactions/read-committed.md
docs/content/stable/reference/configuration/yb-tserver.md

Build preview: https://deploy-preview-19395--infallible-bardeen-164bc9.netlify.app/preview/architecture/docdb/persistence/#packed-row-format

[DOC-137] updates to packed row from beta to Early access.

---

docs/content/preview/deploy/manual-deployment/system-config.md

Add clarification that IPC and shared memory do not need to be configured, unlike regular postgres
DOC-116
@netlify /preview/deploy/manual-deployment/system-config/

[docs] Configuration and note on IPC

---

docs/content/preview/deploy/_index.md
docs/content/preview/explore/observability/_index.md
docs/content/preview/quick-start/docker.md
docs/content/preview/quick-start/explore/binary/explore-ycql.md
docs/content/preview/quick-start/explore/binary/explore-ysql.md
docs/content/preview/quick-start/explore/docker/explore-ycql.md
docs/content/preview/quick-start/explore/docker/explore-ysql.md
docs/content/preview/quick-start/explore/kubernetes/explore-ycql.md
docs/content/preview/quick-start/explore/kubernetes/explore-ysql.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-applications.md

Update docker Quick Start shell connect command
see also #14384 #18581 #18572 
DOC-2 
@netlify /preview/quick-start/docker/

[docs] Update docker Quick Start shell connect command

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md

Fix version displayed in stable
DOC-143
@netlify /stable/yugabyte-platform/install-yugabyte-platform/install-software/installer/

[docs][yba] Fix version number in stable

---

yugabyted-ui/ui/src/components/YBTextBadge/YBTextBadge.tsx
yugabyted-ui/ui/src/features/Header.tsx
yugabyted-ui/ui/src/features/clusters/details/nodes/NodesTab.tsx
yugabyted-ui/ui/src/features/clusters/details/overview/ClusterInfoWidget.tsx

[yugabyted][UI] Improve encryption status label (#19336)

---

docs/content/preview/drivers-orms/c/ysql.md
docs/content/preview/drivers-orms/csharp/_index.md
docs/content/preview/drivers-orms/go/_index.md
docs/content/preview/drivers-orms/include-drivers-orms-list.md
docs/content/preview/drivers-orms/java/_index.md
docs/content/preview/drivers-orms/java/ysql-vertx-pg-client.md
docs/content/preview/drivers-orms/nodejs/_index.md
docs/content/preview/drivers-orms/python/_index.md
docs/content/preview/integrations/_index.md
docs/content/preview/reference/drivers/_index.md
docs/content/preview/reference/drivers/csharp/postgres-npgsql-reference.md
docs/content/preview/reference/drivers/go/pgx-reference.md
docs/content/preview/reference/drivers/go/pq-reference.md
docs/content/preview/reference/drivers/java/postgres-jdbc-reference.md
docs/content/preview/reference/drivers/nodejs/postgres-pg-reference.md
docs/content/preview/reference/drivers/python/postgres-psycopg2-reference.md
docs/content/preview/reference/drivers/ysql-client-drivers.md

Add version info to Integrations
@netlify /preview/integrations/

[docs] Add version info to Integrations

---

docs/content/preview/yugabyte-voyager/overview.md

@netlify https://docs.yugabyte.com/preview/yugabyte-voyager/overview/#features

[docs] removed version statement from voyager feature list

---

docs/content/preview/releases/release-notes/v2.14.md
docs/data/currentVersions.json

[docs] Release notes for 2.14.14.0

---

docs/content/preview/reference/configuration/yb-tserver.md

fix the mispronounced characters `truncate`

[docs] Update yb-tserver.md

---

docs/content/preview/drivers-orms/include-drivers-orms-list.md
docs/content/preview/explore/change-data-capture/cdc-tutorials/cdc-azure-event-hub.md
docs/content/preview/integrations/_index.md

Add version numbers for integrations
@netlify /preview/integrations/

[docs] Integrations versions

---

docs/content/preview/drivers-orms/include-drivers-orms-list.md
docs/content/preview/integrations/_index.md

Updated ORM version numbers for Integrations page
@netlify /preview/integrations/

[docs] Updated ORM version numbers

---

docs/data/currentVersions.json

Fix version number
@netlify /preview/quick-start/linux/

[docs] Fix version number

---

src/yb/rpc/yb_rpc.cc
src/yb/tserver/pg_client_service.cc
src/yb/util/wait_state.cc
src/yb/util/wait_state.h

Track which wait-state/code is pulled.
Support to export wait-state-code as a string based on a gflag

Some more instrumentation for YB_AUH

---

docs/content/preview/admin/yb-admin.md
docs/content/preview/deploy/multi-dc/read-replica-clusters.md
docs/content/preview/explore/change-data-capture/cdc-get-started.md
docs/content/preview/reference/configuration/yugabyted.md
docs/content/stable/admin/yb-admin.md
docs/content/stable/deploy/multi-dc/read-replica-clusters.md
docs/content/stable/explore/change-data-capture/cdc-get-started.md
docs/content/stable/reference/configuration/yugabyted.md

Clarify usage of for add_read_replica_placement_info
DOC-148
@netlify /preview/admin/yb-admin/#read-replica-deployment-commands

[docs] Fix for add_read_replica_placement_info

---

docs/src/algolia-search.js

Open https://deploy-preview-19704--infallible-bardeen-164bc9.netlify.app/search/?query=column-inserts and click on the first result. It should take you to the respective section which is currently not working on the live site.

[Docs] Alphanumeric characters in Header links (Search)

---

docs/content/preview/launch-and-manage/monitor-and-alert/metrics/connections.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yb-tserver.md

Clarify YSQL Max connections
@netlify /preview/reference/configuration/yb-tserver/#ysql-max-connections

[docs] YSQL max connections clarification

---

docs/content/preview/quick-start/_index.md
docs/content/preview/reference/configuration/yugabyted.md
docs/content/preview/releases/release-notes/v2.18.md
docs/content/stable/reference/configuration/yugabyted.md

Note that yugabyted is now GA
@netlify /preview/reference/configuration/yugabyted/

[docs] yugabyted GA

---

README.md

- Fixed instance of "isssues" to "issues"
- Removed redundant "an" in "an an"

Corrected spelling and grammatical errors in Readme.md

---

docs/content/preview/reference/configuration/yb-tserver.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md

YBA Installer doc enhancements
ysql_max_connections clarification
@netlify /preview/yugabyte-platform/install-yugabyte-platform/install-software/installer/

[docs][yba] YBA Installer doc enhancements

---

docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yb-master.md
docs/content/stable/reference/configuration/yb-tserver.md

documenting a newly added Google flag  added for https://github.com/yugabyte/yugabyte-db/issues/19176
once I have approval, I will backport this to stable and 2.18
@netlify /preview/reference/configuration/

[#19176] add documentation for flag export_help_and_type_in_prometheus_metrics

---

docs/content/preview/api/ycql/ddl_create_index.md
docs/content/preview/develop/learn/ttl-data-expiration-ycql.md

Add info on user_enforced consistency and index ttl

---

docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md
docs/content/preview/yugabyte-cloud/release-notes.md

Some regions formerly only available for single-region can now be used for multi-region
@netlify /preview/yugabyte-cloud/cloud-basics/create-clusters-overview/#cloud-provider-regions

[docs][ybm] Azure regions for multi-region

---

docs/content/preview/api/ysql/the-sql-language/statements/ddl_create_table.md
docs/content/preview/develop/best-practices-ysql.md

#13004
@netlify /preview/api/ysql/the-sql-language/statements/ddl_create_table/#primary-key

[Docs] Best practices around partition keys #13004

---

docs/content/preview/yugabyte-cloud/release-notes.md

Known issue of max number of 8 regions for a single cluster and its RRs

[docs][ybm] Max number of regions per cluster

---

docs/content/preview/releases/release-notes/v2.18.md
docs/content/preview/releases/yba-releases/v2.19.md

[docs] Fix license links

---

docs/content/preview/secure/vulnerability-disclosure-policy.md
docs/content/stable/api/ysql/exprs/aggregate_functions/invocation-syntax-semantics.md
docs/content/stable/api/ysql/exprs/window_functions/invocation-syntax-semantics.md
docs/content/stable/api/ysql/user-defined-subprograms-and-anon-blocks/language-plpgsql-subprograms/plpgsql-syntax-and-semantics.md
docs/content/stable/api/ysql/user-defined-subprograms-and-anon-blocks/subprogram-attributes/_index.md
docs/content/stable/api/ysql/user-defined-subprograms-and-anon-blocks/subprogram-overloading.md

@netlify /preview/secure/vulnerability-disclosure-policy/

[docs] vulnerability disclosure and multiple grammar diagrams updated

---

docs/content/preview/faq/yugabytedb-managed-faq.md
docs/content/preview/yugabyte-cloud/cloud-clusters/cloud-maintenance.md

Clarification of priority updates
CLOUDGA-13087
@netlify /preview/yugabyte-cloud/cloud-clusters/cloud-maintenance/

[doc][ybm] Clarification of priority updates

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/restore-universe-data.md

@netlify /preview/yugabyte-platform/back-up-restore-universes/restore-universe-data/

[DOC-129] View restore history

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/alert-policy-templates.md

Build preview : https://deploy-preview-19821--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/configure-yugabyte-platform/alert-policy-templates
Summary:
1. Added the following two alerts instead of DB node disk usage:
- DB node data disk usage
- DB node system disk usage
2. Added other new alerts. 
To do - Update existing ones (another follow-up PR)

[DOC-133] Updated node disk usage and added other new alerts

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/back-up-universe-data.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/restore-universe-data.md

Restore tablespaces in YBA
DOC-132
@netlify /preview/yugabyte-platform/back-up-restore-universes/restore-universe-data/

[doc][yba] Restore tablespaces

---

docs/assets/scss/_search.scss
docs/src/algolia-search.js

If there is a subhead, display it beneath the title like this (but without the highlight)

[Docs] Search Enhancement: Display subhead beneath the title

---

src/yb/cdc/cdc_service.cc
src/yb/cdc/cdc_service_context.h
src/yb/cdc/cdc_state_table.h
src/yb/client/async_initializer.cc
src/yb/client/async_initializer.h
src/yb/client/client-test.cc
src/yb/client/client_fwd.h
src/yb/master/master.cc
src/yb/master/master.h
src/yb/tserver/db_server_base.cc
src/yb/tserver/db_server_base.h
src/yb/tserver/metrics_snapshotter.cc
src/yb/tserver/pg_client_service.cc
src/yb/tserver/tablet_server.cc
src/yb/tserver/tablet_server.h

issue: https://github.com/yugabyte/yugabyte-db/issues/19920

[#19920] style: rename AsyncClientInitialiser to AsyncClientInitializer

---

docs/content/preview/releases/release-notes/v2.20.md
docs/content/preview/releases/versioning.md
docs/layouts/shortcodes/badge/beta.html
docs/layouts/shortcodes/badge/ea.html
docs/layouts/shortcodes/badge/ga.html
docs/layouts/shortcodes/badge/tp.html

- Adding a feature highlight for GA

[Docs] adding alter column type - on disk changes

---

docs/content/v2.12/reference/configuration/yugabyted.md
docs/content/v2.14/reference/configuration/yugabyted.md

Remove some flags that are not available in 2.14
@netlify /v2.14/reference/configuration/yugabyted/

[docs] Remove wrong flags from 2.14

---

docs/content/preview/explore/ycql-language/cassandra-feature-support.md
docs/content/stable/explore/ycql-language/cassandra-feature-support.md
docs/content/v2.18/explore/ycql-language/cassandra-feature-support.md

@netlify /v2.18/explore/ycql-language/cassandra-feature-support/

[docs] Backport delete table in Cassandra feature support 

---

docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-alerts.md
docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-queries-live.md
docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-queries-slow.md
docs/content/preview/yugabyte-cloud/cloud-monitor/metrics-export.md
docs/content/preview/yugabyte-cloud/cloud-monitor/monitor-activity.md
docs/content/preview/yugabyte-cloud/cloud-monitor/overview.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/_index.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-examples/managed-cli-example-create.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-api-key.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-auth.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-backup.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-cluster.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-metrics-exporter.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-network-allow-list.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-network.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-peering.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-permission.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-read-replica.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-region.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-role.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-user.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-vpc.md
docs/content/preview/yugabyte-cloud/release-notes.md

Metrics export to sumo logic
@netlify /preview/yugabyte-cloud/cloud-monitor/metrics-export/

[docs][ybm] Metrics export to sumo logic

---

docs/content/preview/yugabyte-platform/manage-deployments/edit-universe.md
docs/content/stable/yugabyte-platform/manage-deployments/edit-universe.md
docs/content/v2.14/yugabyte-platform/manage-deployments/edit-universe.md
docs/content/v2.16/yugabyte-platform/manage-deployments/edit-universe.md
docs/content/v2.18/yugabyte-platform/manage-deployments/edit-universe.md

Build preview : https://deploy-preview-19956--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/manage-deployments/edit-universe/#smart-resize

[DOC-142] YBA smart resize

---

docs/content/preview/contribute/docs/docs-build.md
docs/content/preview/contribute/docs/docs-edit.md

@netlify /preview/contribute/docs/docs-build/#live-reload

[DOC-141] Update GitHub instructions in the contributor guide.

---

docs/content/preview/releases/release-notes/v2.14.md

@netlify /preview/releases/release-notes/v2.14/#v2.14.10.4

[docs] Release notes for 2.14.10.4

---

docs/content/preview/yugabyte-cloud/cloud-monitor/metrics-export.md

Sumo logic metric export and dashboards
@netlify /preview/yugabyte-cloud/cloud-monitor/metrics-export/

[docs][ybm] Sumo logic caveats

---

docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/preview/yugabyte-platform/security/enable-encryption-in-transit.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/stable/yugabyte-platform/security/enable-encryption-in-transit.md

Build preview: https://deploy-preview-19940--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/administer-yugabyte-platform/high-availability/

[DOC-162] Update YBA HA steps

---

docs/content/preview/admin/yb-admin.md
docs/content/stable/admin/yb-admin.md
docs/content/v2.16/admin/yb-admin.md
docs/content/v2.18/admin/yb-admin.md

Add replication_name to get_replication_status
@netlify /stable/admin/yb-admin/#get-replication-status

[docs] Update get_replication_status

---

docs/content/preview/admin/yb-admin.md
docs/content/stable/admin/yb-admin.md

Add documentation for the `get_auto_flags_config` yb-admin command

[Docs] Add get_auto_flags_config

---

docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-cluster.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-metrics-exporter.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-usage.md

Update for ybm cli v0.1.17
@netlify /preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/

[docs][ybm] Update for ybm cli v0.1.17

---

docs/content/preview/yugabyte-platform/manage-deployments/remove-nodes.md
docs/content/stable/yugabyte-platform/manage-deployments/remove-nodes.md
docs/content/v2.14/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

Removing unresponsive on-prem nodes requires additional step
#14322
@netlify /preview/yugabyte-platform/manage-deployments/remove-nodes/

[docs][yba] Clarify removal of nodes for on-prem

---

docs/content/preview/yugabyte-cloud/managed-labs.md

Add video to product labs page
@netlify /preview/yugabyte-cloud/managed-labs/

[docs][ybm] Add video to labs page

---

docs/content/preview/explore/query-1-performance/pg-stat-statements.md
docs/content/stable/explore/query-1-performance/pg-stat-statements.md
docs/content/v2.18/explore/query-1-performance/pg-stat-statements.md

@netlify /preview/explore/query-1-performance/pg-stat-statements/

[DOC-167] Update description for `yb_hdr_bucket_factor`

---

docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/high-availability.md

Explain the steps for CA setup in more detail

[docs] [YBA] Update high-availability in administer section.

---

docs/content/preview/yugabyte-cloud/managed-labs.md
docs/content/preview/yugabyte-cloud/release-notes.md

[docs][ybm] Change log for Dec 4

---

yugabyted-ui/ui/src/features/clusters/details/overview/VCpuUsageSankey.tsx
yugabyted-ui/ui/src/features/clusters/details/performance/metrics/index.tsx
yugabyted-ui/ui/src/features/clusters/details/settings/RegionOverview.tsx

Backport https://github.com/yugabyte/yugabyte-db/pull/19967

[BACKPORT 2.20][#19991][yugabyted][UI] Sankey CPU core count and node filter fixes

---

docs/content/preview/explore/transactions/isolation-levels.md
docs/content/stable/explore/transactions/isolation-levels.md

Explore section isolation levels intro
#12491
@netlify /preview/explore/transactions/isolation-levels/

[docs] Isolation level intro

---

docs/content/preview/reference/configuration/yugabyted.md
docs/content/preview/secure/audit-logging/audit-logging-ysql.md
docs/content/preview/secure/audit-logging/trace-statements-ysql.md
docs/content/preview/troubleshoot/nodes/check-logs.md
docs/content/stable/reference/configuration/yugabyted.md
docs/content/stable/secure/audit-logging/audit-logging-ysql.md
docs/content/stable/secure/audit-logging/trace-statements-ysql.md
docs/data/currentVersions.json

pgaudit - Remove parameter_max_size
@netlify /preview/secure/audit-logging/audit-logging-ysql/

[docs] Remove parameter_max_size

---

docs/content/_index.md
docs/content/preview/explore/_index.md
docs/content/preview/explore/ycql-language/_index.md
docs/content/preview/explore/ysql-language-features/_index.md
docs/content/stable/explore/_index.md
docs/content/stable/explore/ycql-language/_index.md

Give more prominence to YCQL

---

docs/content/preview/api/ysql/syntax_resources/ysql_grammar.ebnf
docs/content/preview/api/ysql/the-sql-language/statements/ddl_alter_table.md
docs/content/stable/api/ysql/syntax_resources/ysql_grammar.ebnf
docs/content/stable/api/ysql/the-sql-language/statements/ddl_alter_table.md

[docs] Syntax for ADD COLUMN [ IF NOT EXISTS ], DROP COLUMN [ IF EXISTS ]

---

docs/content/preview/deploy/multi-dc/async-replication/async-replication-transactional.md
docs/content/preview/explore/change-data-capture/cdc-tutorials/cdc-azure-event-hub.md
docs/content/preview/integrations/spring-framework/sd-jpa.md
docs/content/preview/quick-start/_index.md
docs/content/preview/releases/_index.md
docs/content/preview/releases/release-notes/_index.md
docs/content/preview/releases/release-notes/end-of-life/v2.2.md
docs/content/preview/releases/release-notes/v2.18.md
docs/content/preview/tools/sql-workbench.md
docs/content/preview/yugabyte-cloud/cloud-monitor/metrics-export.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/default.md
docs/content/preview/yugabyte-voyager/known-issues/oracle.md
docs/content/preview/yugabyte-voyager/migrate/live-fall-back.md
docs/netlify.toml

[doc] Fix misc SEO issues

---

docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/stable/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md

Preview: https://deploy-preview-20283--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes/#create-common-tserver-service-for-zones

[docs][PLAT-11684] Instructions for creating common TServer service

---

docs/content/preview/releases/release-notes/v2.20.md

@netlify /preview/releases/release-notes/v2.20/#v2.20.1.0

[docs] Release notes updates to 2.20.1.0

---

docs/content/preview/faq/yugabyte-platform.md
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/default.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites/default.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites/kubernetes.md
docs/content/preview/yugabyte-platform/upgrade/_index.md
docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-replicated.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/default.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites/default.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites/kubernetes.md
docs/content/stable/yugabyte-platform/upgrade/_index.md
docs/content/stable/yugabyte-platform/upgrade/upgrade-yp-replicated.md

Using YBA Installer to migrate installation from Replicated
PLAT-10754
@netlify /preview/yugabyte-platform/install-yugabyte-platform/

[docs][yba] Migrate YBA from Replicated

---

docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-multisync.md
docs/content/preview/yugabyte-cloud/cloud-clusters/configure-clusters.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/_index.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-backup-policy.md

CLI backup policy command
@netlify /preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/

[docs][ybm] CLI backup policy

---

docs/content/preview/faq/yugabyte-platform.md
docs/content/preview/yugabyte-cloud/release-notes.md

Change log - Enhanced fault tolerance

[doc][ybm] Change log - fault tolerance

---

docs/content/preview/releases/release-notes/v2.18.md

@netlify /preview/releases/release-notes/v2.18/#v2.18.5.0

[docs] Updates to RN 2.18.5.0

---

docs/data/currentVersions.json
docs/layouts/partials/earlier-version-warning.html

Turn off the "This is a stable version notice".

[Docs] Introduce parameter to turn off version warning

---

docs/content/preview/tools/superset.md
docs/content/stable/tools/superset.md

Have added some steps to use YugabyteDB psycopg2 smart driver with Apache Superset instead of the upstream driver.

Update Apache Superset doc to use smart driver

---

docs/content/preview/explore/ysql-language-features/pg-extensions/_index.md
docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgvector.md
docs/content/stable/explore/ysql-language-features/pg-extensions/_index.md
docs/content/stable/explore/ysql-language-features/pg-extensions/extension-pgvector.md
docs/content/v2.18/explore/ysql-language-features/pg-extensions/_index.md

[doc] Add pgvector page

---

docs/content/preview/architecture/docdb-sharding/colocated-tables.md
docs/content/stable/architecture/docdb-sharding/colocated-tables.md
docs/content/v2.14/architecture/docdb-sharding/colocated-tables.md
docs/content/v2.16/architecture/docdb-sharding/colocated-tables.md
docs/content/v2.18/architecture/docdb-sharding/colocated-tables.md

[docs] Update the size limit for colocated database

---

docs/content/preview/reference/drivers/rust/rust-postgres-reference.md
docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac.md
docs/content/stable/reference/drivers/rust/rust-postgres-reference.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac.md

Indicate RBAC is EA
DOC-198
@netlify /stable/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac/

[doc][yba] RBAC is EA

---

docs/content/preview/releases/_index.md

slack request - https://yugabyte.slack.com/archives/CDQB8MEAU/p1704746406624569

[docs] updated upcoming releases

---

docs/content/preview/releases/release-notes/v2.18.md
docs/content/preview/releases/release-notes/v2.20.md

Slack thread - https://yugabyte.slack.com/archives/CDQB8MEAU/p1704397232191689?thread_ts=1704389291.748909&cid=CDQB8MEAU

[docs] Release notes updates based on feedback

---

docs/content/preview/yugabyte-voyager/migrate/live-fall-back.md
docs/content/preview/yugabyte-voyager/migrate/live-fall-forward.md
docs/content/preview/yugabyte-voyager/migrate/live-migrate.md
docs/content/preview/yugabyte-voyager/migrate/migrate-steps.md

Remove some duplicated arguments for voyager

Removed duplicated args for voyager import command

---

docs/content/preview/releases/release-notes/v2.18.md
docs/content/preview/releases/yba-releases/v2.18.md
docs/data/currentVersions.json

https://deploy-preview-20542--infallible-bardeen-164bc9.netlify.app/preview/releases/release-notes/v2.18/#v2.18.5.1

[docs] release notes for 2.18.5.1

---

docs/content/preview/deploy/checklist.md
docs/content/stable/deploy/checklist.md

[docs] Explain we support x86 & ARM in deploy checklist

---

docs/content/preview/faq/smart-drivers-faq.md

[docs] Drivers Faq: How can I limit traffic to specific clouds, regions, or AZs with the Smart Driver?

---

docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/v2.18/reference/configuration/yb-tserver.md

[docs] Explain `db_block_cache_num_shard_bits` yb-tserver flag

---

docs/content/preview/releases/release-notes/v2.14.md
docs/data/currentVersions.json

Release notes for 2.14.15.0-b57

RN 2.14.15.0-b57

---

docs/content/preview/develop/quality-of-service/write-heavy-workloads.md
docs/content/stable/develop/quality-of-service/write-heavy-workloads.md

[docs] Remove duplicate `Memstores flushed too frequently` section

---

docs/content/preview/deploy/manual-deployment/install-software.md
docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-replicated.md
docs/content/stable/reference/configuration/yugabyted.md
docs/content/stable/tutorials/azure/azure-openai.md
docs/content/stable/tutorials/google/google-vertex-ai.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/back-up-restore-yp.md
docs/content/stable/yugabyte-platform/upgrade/upgrade-yp-installer.md
docs/content/v2.18/deploy/manual-deployment/install-software.md
docs/content/v2.18/reference/configuration/yugabyted.md
docs/content/v2.18/yugabyte-platform/administer-yugabyte-platform/back-up-restore-k8s.md
docs/content/v2.18/yugabyte-platform/administer-yugabyte-platform/back-up-restore-yp.md
docs/content/v2.18/yugabyte-platform/install-yugabyte-platform/install-software/default.md

Fix version number for stable
@netlify /stable/yugabyte-platform/upgrade/upgrade-yp-installer/

[doc][yba] Upgrade fix versions

---

docs/content/preview/releases/release-notes/v2.16.md
docs/content/preview/releases/yba-releases/v2.16.md
docs/data/currentVersions.json

Release 2.16.9.0-b67
@netlify /preview/releases/release-notes/v2.16/

RN 2.16.9.0

---

docs/content/preview/yugabyte-cloud/cloud-monitor/_index.md
docs/content/preview/yugabyte-cloud/cloud-monitor/metrics-export.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-metrics-exporter.md
docs/content/preview/yugabyte-cloud/release-notes.md

Clarify that Grafana support is for Cloud only
CLOUDGA-18132
@netlify /preview/yugabyte-cloud/cloud-monitor/metrics-export/

[doc][ybm] Grafana Cloud supported only

---

docs/content/preview/manage/backup-restore/point-in-time-recovery.md
docs/content/stable/manage/backup-restore/point-in-time-recovery.md
docs/content/v2.18/manage/backup-restore/point-in-time-recovery.md

PITR remove Stop workloads warning
@netlify /preview/manage/backup-restore/point-in-time-recovery/

[doc] PITR remove Stop workloads warning

---

docs/content/preview/releases/release-notes/v2.20.md
docs/content/preview/releases/yba-releases/v2.20.md

Slack request - https://yugabyte.slack.com/archives/C01D8JQNTH9/p1706291952964709?thread_ts=1706217590.019239&cid=C01D8JQNTH9
Build preview - https://deploy-preview-20800--infallible-bardeen-164bc9.netlify.app/preview/releases/release-notes/v2.20/

[docs] Added a note to recommend using release versions 2.20.1.3 or later. 

---

docs/content/preview/tutorials/AI/ai-langchain-openai.md
docs/content/stable/tutorials/AI/ai-langchain-openai.md

Edit to LangChain tutorial
@netlify /stable/tutorials/ai/ai-langchain-openai/

[doc] Edit to LangChain tutorial

---

docs/content/preview/admin/_index.md
docs/content/stable/admin/_index.md
docs/content/stable/explore/ysql-language-features/expressions-operators.md
docs/content/stable/explore/ysql-language-features/join-strategies.md

Copy some updates to stable
@netlify /stable/admin/

[doc] Copy updates to stable

---

docs/content/_index.md
docs/content/preview/faq/comparisons/_index.md
docs/content/preview/faq/compatibility.md
docs/content/preview/faq/general.md
docs/content/preview/faq/operations-faq.md
docs/content/preview/faq/smart-drivers-faq.md
docs/content/preview/faq/yugabyte-platform.md
docs/content/preview/faq/yugabytedb-managed-faq.md
docs/content/preview/integrations/_index.md

Unversion FAQ and Integrations sections
@netlify /preview/faq/general/

[doc] Unversion FAQ and Integrations sections

---

docs/content/preview/api/ycql/dml_delete.md
docs/content/preview/api/ycql/dml_insert.md
docs/content/preview/api/ycql/dml_select.md
docs/content/preview/api/ycql/dml_update.md

[docs] Explain DML semantics in YCQL

---

docs/content/preview/admin/yb-admin.md
docs/content/preview/explore/multi-region-deployments/asynchronous-replication-ysql.md
docs/content/stable/admin/yb-admin.md
docs/content/stable/explore/multi-region-deployments/asynchronous-replication-ysql.md
docs/content/v2.14/explore/multi-region-deployments/asynchronous-replication-ysql.md
docs/content/v2.16/admin/yb-admin.md
docs/content/v2.16/explore/multi-region-deployments/asynchronous-replication-ysql.md
docs/content/v2.18/admin/yb-admin.md
docs/content/v2.18/explore/multi-region-deployments/asynchronous-replication-ysql.md

Slack requests: https://yugabyte.slack.com/archives/CDQB8MEAU/p1706543868941079
https://yugabyte.slack.com/archives/CDQB8MEAU/p1706547131198529

[docs] formatting changes to yb-abmin commands

---

docs/assets/scss/_styles_project.scss

Changed `font-size`, `line-height` and `color` on paragraph. Also added CSS property to for smooth font rendering.

[Docs] Change CSS spec for better readability

---

docs/content/preview/api/ysql/syntax_resources/ysql_grammar.ebnf
docs/content/preview/api/ysql/the-sql-language/statements/_index.md
docs/content/preview/api/ysql/the-sql-language/statements/ddl_create_tablespace.md
docs/content/preview/api/ysql/the-sql-language/statements/ddl_drop_tablespace.md

[docs] CREATE/DROP TABLESPACE

---

docs/content/preview/yugabyte-cloud/cloud-monitor/metrics-export.md
docs/content/preview/yugabyte-cloud/managed-security/managed-authentication.md

Add PingOne to federated authentication
CLOUDGA-18867
@netlify /preview/yugabyte-cloud/managed-security/managed-authentication/#federated-authentication

[doc][ybm] Add PingOne fed auth

---

docs/content/preview/quick-start/_index.md
docs/content/preview/quick-start/linux.md

Update 2 in page links and add note on Rosetta for Apple silicon
@netlify /preview/quick-start/

[doc] Quick Start in page links

---

docs/content/preview/api/ysql/the-sql-language/statements/ddl_create_index.md
docs/content/preview/explore/indexes-constraints/expression-index-ysql.md

[docs] Explain expression indexes in YSQL

---

docs/config/_default/menus.toml
docs/content/preview/integrations/nutanix-ahv.md
docs/content/preview/integrations/spring-framework/nutanix-ahv.md

build preview - https://deploy-preview-20911--infallible-bardeen-164bc9.netlify.app/preview/integrations/spring-framework/nutanix-ahv/

[DOC-196] Nutanix AHV integration

---

docs/content/preview/yugabyte-cloud/release-notes.md

[doc][ybm] Jan YBM new features

---

docs/content/preview/yugabyte-cloud/managed-security/managed-authentication.md
docs/content/preview/yugabyte-cloud/release-notes.md

Enable PingOne fed auth
@netlify /preview/yugabyte-cloud/managed-security/managed-authentication/

[doc][ybm] Enable PingOne fed auth

---

docs/content/preview/develop/best-practices-ysql.md
docs/content/preview/develop/build-global-apps/follower-reads.md
docs/content/preview/develop/learn/transactions/transactions-global-apps.md
docs/content/preview/explore/ysql-language-features/going-beyond-sql/follower-reads-ysql.md
docs/content/stable/develop/best-practices-ysql.md
docs/content/stable/develop/build-global-apps/follower-reads.md
docs/content/stable/develop/learn/transactions/transactions-global-apps.md
docs/content/stable/explore/ysql-language-features/going-beyond-sql/follower-reads-ysql.md

From an internal thread https://yugabyte.slack.com/archives/C4K1838GL/p1706649329838259?thread_ts=1683835794.030269&cid=C4K1838GL

[docs] Explain low values for `yb_follower_read_staleness_ms`

---

docs/netlify.toml

Added follwing urls to  `script-src` section of the `Content-Security-Policy`/`CSP` header
- https://x.clearbitjs.com/
- https://tag.clearbitscripts.com/

Added few urls to script-src section of CSP header

---

docs/content/preview/contribute/docs/syntax-diagrams.md

- Updating the docs to reflect the new scheme.
- closes #17379

update the contibution page for adding syntax diagrams

---

docs/netlify.toml

-  Need for tracking accounts 
cc: @samiahmedsiddiqui

Add clearbit to connect-src of CSP

---

docs/content/preview/contribute/docs/syntax-diagrams.md
docs/content/preview/deploy/public-clouds/gcp/gcp-deployment-manager.md
docs/content/stable/deploy/public-clouds/gcp/gcp-deployment-manager.md
docs/content/v2.14/deploy/public-clouds/gcp/gcp-deployment-manager.md
docs/content/v2.16/deploy/public-clouds/gcp/gcp-deployment-manager.md
docs/content/v2.18/deploy/public-clouds/gcp/gcp-deployment-manager.md
docs/netlify.toml

Syntax diagram format and minor edit
@netlify /preview/contribute/docs/syntax-diagrams/

[doc] Syntax diagram format and minor edit

---

docs/content/preview/yugabyte-voyager/airgapped.md

similar to PR - https://github.com/yugabyte/yugabyte-db/pull/20790/files

[docs] update install instructions for airgapped

---

docs/content/preview/releases/yba-releases/v2.18.md
docs/content/preview/releases/yba-releases/v2.19.md
docs/content/preview/releases/yba-releases/v2.20.md

Add YBA installer download links to releases - 2.18-2.10
@netlify /preview/releases/yba-releases/

[doc][yba] Add YBA installer download links to releases

---

docs/content/preview/integrations/_index.md

Add Apache Hudi to Integrations
@netlify /preview/integrations/

[doc] Add Apache Hudi to Integrations

---

docs/content/preview/drivers-orms/csharp/postgres-npgsql.md
docs/content/preview/reference/drivers/csharp/postgres-npgsql-reference.md
docs/content/stable/drivers-orms/csharp/postgres-npgsql.md
docs/content/stable/reference/drivers/csharp/postgres-npgsql-reference.md
docs/content/v2.18/drivers-orms/csharp/postgres-npgsql.md
docs/content/v2.18/reference/drivers/csharp/postgres-npgsql-reference.md
docs/content/v2.18/reference/drivers/ysql-client-drivers.md

Rephrased text to emphasize the recommended connection behaviour to avoid loading types on open.  Added connection string for this recommendation.

[doc] Update postgres-npgsql.md

---

docs/content/preview/releases/versioning.md

Update text for EA features
DOC-239
@netlify /preview/releases/versioning/

[doc] Update EA text

---

docs/content/preview/explore/transactions/_index.md
docs/content/preview/explore/ysql-language-features/data-manipulation.md
docs/content/preview/explore/ysql-language-features/sql-feature-support.md
docs/content/stable/develop/build-apps/c/cloud-ysql-c.md
docs/content/stable/develop/build-apps/cloud-add-ip.md
docs/content/stable/develop/build-apps/cpp/cloud-ysql-cpp.md
docs/content/stable/develop/build-apps/csharp/cloud-ysql-csharp.md
docs/content/stable/develop/build-apps/go/cloud-ysql-go.md
docs/content/stable/develop/build-apps/java/cloud-ysql-yb-jdbc.md
docs/content/stable/develop/build-apps/nodejs/cloud-ysql-node.md
docs/content/stable/develop/build-apps/php/cloud-ysql-php.md
docs/content/stable/develop/build-apps/python/cloud-ysql-python.md
docs/content/stable/develop/build-apps/ruby/cloud-ysql-ruby.md
docs/content/stable/develop/build-apps/rust/cloud-ysql-rust.md
docs/content/stable/drivers-orms/nodejs/prisma.md
docs/content/stable/drivers-orms/nodejs/yugabyte-node-driver.md
docs/content/stable/drivers-orms/orms/nodejs/ysql-prisma.md
docs/content/stable/drivers-orms/smart-drivers.md
docs/content/stable/explore/_index.md
docs/content/stable/explore/change-data-capture/debezium-connector-yugabytedb.md
docs/content/stable/explore/transactions/_index.md
docs/content/stable/explore/ysql-language-features/data-manipulation.md
docs/content/stable/explore/ysql-language-features/sql-feature-support.md
docs/content/stable/reference/drivers/nodejs/postgres-pg-reference.md
docs/content/stable/tools/_index.md
docs/content/v2.14/explore/transactions/_index.md
docs/content/v2.16/explore/transactions/_index.md
docs/content/v2.18/explore/transactions/_index.md

Fix links
@netlify /stable/explore/ysql-language-features/

[doc] Fix links

---

docs/content/preview/explore/ysql-language-features/postgresql-compatibility.md
docs/content/stable/explore/ysql-language-features/postgresql-compatibility.md
docs/content/v2.16/explore/ysql-language-features/postgresql-compatibility.md
docs/content/v2.18/explore/ysql-language-features/postgresql-compatibility.md

Slack request - https://yugabyte.slack.com/archives/CDQB8MEAU/p1708482805359029

[docs] Updated PG compatibility list

---

docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yb-tserver.md

Update ysql_pg_conf_csv instructions and example in yb-tserver.md to improve clarity for complex configurations.

Update ysql_pg_conf_csv instructions and example in yb-tserver.md

---

docs/content/preview/explore/ysql-language-features/pg-extensions/extension-auto-explain.md
docs/content/preview/explore/ysql-language-features/pg-extensions/extension-passwordcheck.md
docs/content/preview/releases/release-notes/end-of-life/v2.11.md
docs/content/preview/releases/release-notes/end-of-life/v2.8.md
docs/content/preview/secure/audit-logging/audit-logging-ysql.md
docs/content/preview/secure/authentication/password-authentication.md
docs/content/preview/yugabyte-platform/security/enable-encryption-in-transit.md
docs/content/stable/secure/audit-logging/audit-logging-ysql.md
docs/content/v2.14/secure/audit-logging/audit-logging-ysql.md
docs/content/v2.16/secure/audit-logging/audit-logging-ysql.md
docs/content/v2.18/secure/audit-logging/audit-logging-ysql.md

Update ysql_pg_conf_csv example in audit-logging-ysql.md with instructions and example for complex configurations.

Update ysql_pg_conf_csv example in audit-logging-ysql.md

---

docs/content/preview/yugabyte-cloud/managed-security/managed-authentication.md
docs/content/preview/yugabyte-cloud/release-notes.md

Build previews-
https://deploy-preview-21174--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-cloud/release-notes/
https://deploy-preview-21174--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-cloud/managed-security/managed-authentication/#learn-more

[DOC-242] added blog links for YBM SSO access 

---

docs/content/preview/tutorials/_index.md

Tutorials landing page format
@netlify /preview/tutorials/

[doc] Tutorials landing page

---

docs/netlify.toml

- This script allows netlify to collect Real User Metrics

Allow netlify rum scripts

---

docs/content/preview/explore/fault-tolerance/_index.md
docs/content/preview/explore/fault-tolerance/macos-yba.md
docs/content/preview/explore/fault-tolerance/macos.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/preview/reference/configuration/yugabyted.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-provider.md
docs/content/stable/explore/fault-tolerance/_index.md
docs/content/stable/explore/fault-tolerance/macos-yba.md
docs/content/stable/explore/fault-tolerance/macos.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yugabyted.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-provider.md

- Add content to Continous Availability about Node/Zone/Region & Rack failures
- Added tips across yugabyted/yb-tserver/yba on-prem about racks.

Add content for rack awareness

---

docs/content/preview/manage/upgrade-deployment.md
docs/content/stable/manage/upgrade-deployment.md

Made edits and link fixes to this PR : https://github.com/yugabyte/yugabyte-db/pull/21334

[docs] minor edits to rollback upgrades

---

docs/content/preview/yugabyte-voyager/migrate/live-fall-back.md
docs/content/preview/yugabyte-voyager/migrate/live-fall-forward.md
docs/content/preview/yugabyte-voyager/migrate/live-migrate.md

@netliffy /preview/yugabyte-voyager/migrate/live-migrate/#create-the-target-database

[DOC-263] added note on setting gflags for live migration 

---

docs/content/preview/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/stable/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/v2.14/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/v2.16/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/v2.18/deploy/kubernetes/multi-zone/eks/helm-chart.md

Fix typo on K8s pages
@netlify /preview/deploy/kubernetes/multi-zone/eks/helm-chart/#5-connect-using-yugabytedb-shells

[doc] MZ K8s eks Fix typo

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites/default.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites/default.md

Disk requirements for replicated
@netlify /stable/yugabyte-platform/install-yugabyte-platform/prerequisites/default/

[doc][yba] Disk requirements for replicated

---

docs/config/_default/menus.toml
docs/content/preview/releases/_index.md
docs/content/preview/releases/versioning.md
docs/content/preview/releases/yba-releases/_index.md
docs/content/preview/releases/yba-releases/v2.16.md
docs/content/preview/releases/yba-releases/v2.17.md
docs/content/preview/releases/yba-releases/v2.18.md
docs/content/preview/releases/yba-releases/v2.19.md
docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/releases/ybdb-releases/_index.md
docs/content/preview/releases/ybdb-releases/end-of-life/v1.2.md
docs/content/preview/releases/ybdb-releases/v2.14.md
docs/content/preview/releases/ybdb-releases/v2.15.md
docs/content/preview/releases/ybdb-releases/v2.16.md
docs/content/preview/releases/ybdb-releases/v2.17.md
docs/content/preview/releases/ybdb-releases/v2.18.md
docs/content/preview/releases/ybdb-releases/v2.19.md
docs/content/preview/releases/ybdb-releases/v2.20.md
docs/content/preview/yugabyte-cloud/release-notes.md
docs/content/preview/yugabyte-voyager/known-issues/postgresql.md
docs/content/v2.16/yugabyte-platform/_index.md
docs/content/v2.18/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/aws.md
docs/netlify.toml

[doc] Fix links to RN page

---

docs/content/stable/yugabyte-platform/manage-deployments/upgrade-nodes.md

Copy node upgrade changes to stable
@netlify /stable/yugabyte-platform/manage-deployments/upgrade-nodes/

[doc][yba] Copy node upgrade changes to stable

---

docs/content/preview/yugabyte-voyager/migrate/bulk-data-load.md

@netlify /preview/yugabyte-voyager/migrate/bulk-data-load/

[DOC-269] added prepare the target database in bulk data load

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/v2.18/yugabyte-platform/install-yugabyte-platform/install-software/installer.md

Minor edit to clarify QS
@netlify /preview/yugabyte-platform/install-yugabyte-platform/install-software/installer/#quick-start

[doc][yba] Minor edit to clarify QS

---

docs/content/preview/troubleshoot/nodes/trouble-common.md

Add note in troubleshoot doc
DOC-237
@netlify /preview/troubleshoot/nodes/trouble-common/#poll-stopped-service-unavailable

[doc] Poll stopped error message for troubleshoot

---

docs/content/preview/yugabyte-platform/create-deployments/async-replication-platform.md
docs/content/stable/yugabyte-platform/create-deployments/async-replication-platform.md
docs/content/v2.18/yugabyte-platform/create-deployments/async-replication-platform.md

Note on dropping tables in xCluster
DOC-177
DOC-288
@netlify /preview/yugabyte-platform/create-deployments/async-replication-platform/

[doc][yba] Note on dropping tables in xCluster

---

docs/content/preview/quick-start-yugabytedb-managed/_index.md
docs/content/preview/quick-start/_index.md
docs/content/preview/quick-start/linux.md
docs/content/preview/yugabyte-voyager/overview.md

Added ‘Migrate from PostgreSQL’ in Quickstart with summary and linking to Voyager

Added ‘Migrate from PostgreSQL’ in Quickstart with summary and linking to Voyager

---

docs/content/preview/faq/yugabyte-platform.md
docs/content/preview/manage/upgrade-deployment.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md
docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software-prepare.md
docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software.md
docs/content/preview/yugabyte-platform/upgrade/_index.md
docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-installer.md
docs/content/stable/manage/upgrade-deployment.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md
docs/content/stable/yugabyte-platform/manage-deployments/upgrade-software-prepare.md
docs/content/stable/yugabyte-platform/manage-deployments/upgrade-software.md
docs/content/stable/yugabyte-platform/upgrade/_index.md
docs/content/stable/yugabyte-platform/upgrade/upgrade-yp-installer.md

Added caveats about upgrades on deprecated OSs
@netlify /preview/yugabyte-platform/manage-deployments/upgrade-software/

[doc] Updates and OS support

---

docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yb-tserver.md

[docs] Explain `default_transaction_isolation`

---

docs/content/preview/develop/best-practices-ysql.md
docs/content/stable/develop/best-practices-ysql.md

From an internal thread: https://yugabyte.slack.com/archives/C3SP5KNAC/p1709146596390089?thread_ts=1708545320.320249&cid=C3SP5KNAC

[docs] Better memory detail on tablet overhead

---

docs/content/stable/develop/best-practices-ysql.md

[docs] Backport YSQL Best Practices to stable

---

docs/content/preview/deploy/manual-deployment/system-config.md
docs/content/stable/deploy/manual-deployment/system-config.md

- Added details on `vm.swappiness` and `vm.max_map_count`.
- [Slack thread](https://yugabyte.slack.com/archives/C06PAMYT3JA/p1710435841726629?thread_ts=1710431355.470589&cid=C06PAMYT3JA)

Add mmap kernel tuning params

---

docs/content/preview/api/ycql/ddl_create_index.md
docs/content/stable/api/ycql/ddl_create_index.md

- Added a Caution for the user to be wary of issues.
- Made a note on backfilling

Add more information to user enforced consistency

---

docs/src/algolia-search.js

Fix XSS vulnerability with svg onload: 
Production: https://docs.yugabyte.com/search/?query=%3Csvg/onload%3Dalert(%22XSS-vulnerability-test%22)+/%3E
Preview: https://deploy-preview-21615--infallible-bardeen-164bc9.netlify.app/search/?query=%3Csvg/onload%3Dalert(%22XSS-vulnerability-test%22)+/%3E
@netlify /search/?query=%3Csvg/onload%3Dalert(%22XSS-vulnerability-test%22)+/%3E .

[Docs] Fix XSS vulnerability issue

---

docs/content/preview/deploy/multi-dc/async-replication/async-deployment.md
docs/content/preview/reference/configuration/default-ports.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-provider.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/supported-os-and-arch.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/on-premises.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md
docs/content/preview/yugabyte-platform/security/customize-ports.md
docs/content/stable/deploy/multi-dc/async-replication/async-deployment.md
docs/content/stable/reference/configuration/default-ports.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-provider.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/supported-os-and-arch.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-environment/on-premises.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md
docs/content/stable/yugabyte-platform/security/customize-ports.md

Clarify prerequisites
DOC-240
DOC-279
DOC-251
@netlify /preview/yugabyte-platform/install-yugabyte-platform/install-software/installer/

[doc][yba] YBA install prereqs

---

docs/data/currentVersions.json

fix stable version number
@netlify /preview/quick-start/#download

[doc] fix stable version number

---

docs/content/preview/admin/yb-ts-cli.md

Added new functionality to clear a tablet server or master server's metacache

Update yb-ts-cli.md to include clear_server_metacache command

---

docs/content/preview/admin/yb-ts-cli.md

Reverts yugabyte/yugabyte-db#21679

Revert "Update yb-ts-cli.md to include clear_server_metacache command"

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/_index.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/_index.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-failover.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-switchover.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-tables.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/_index.md

Copy DR to preview
@netlify /preview/yugabyte-platform/back-up-restore-universes/

[doc][yba] Copy DR to preview

---

docs/content/preview/faq/yugabyte-platform.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
docs/content/preview/yugabyte-platform/manage-deployments/upgrade-nodes.md
docs/content/stable/api/ycql/_index.md
docs/content/stable/drivers-orms/smart-drivers.md
docs/content/stable/explore/ycql-language/_index.md
docs/content/stable/explore/ycql-language/cassandra-feature-support.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-provider.md
docs/content/stable/yugabyte-platform/manage-deployments/upgrade-nodes.md
docs/content/stable/yugabyte-platform/manage-deployments/upgrade-software-prepare.md
docs/content/v2.18/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md

Adjustments to node patching
@netlify /preview/yugabyte-platform/manage-deployments/upgrade-nodes/

[doc][yba] Upgrade nodes fixes

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software-prepare.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
docs/content/stable/yugabyte-platform/manage-deployments/upgrade-software-prepare.md

Fix for typo
@netlfy /preview/yugabyte-platform/manage-deployments/upgrade-software-prepare/#upgrading-from-versions-earlier-than-v2-18-2

[doc][yba] Minor fix for page

---

docs/content/preview/architecture/docdb-replication/async-replication.md
docs/content/stable/architecture/docdb-replication/async-replication.md

Instead of active-passive we call it active-active multi-master

Docs: Change xCluster docs from active-passive to active-active

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/supported-os-and-arch.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/supported-os-and-arch.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md

systemd user for onprem
DOC-290
DOC-291
DOC-293
@netlify /preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual/#enable-yugabyte-user-processes-to-run-after-logout

[doc][yba] systemd user for onprem

---

docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-cluster.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-peering.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-region.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-vpc.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md

#21592 ybm CLI region resource
@netlify /preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-cluster/#create

#21592 ybm CLI region resource

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/preview/yugabyte-platform/troubleshoot/install-upgrade-issues/installer.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/stable/yugabyte-platform/troubleshoot/install-upgrade-issues/installer.md
docs/content/v2.18/yugabyte-platform/install-yugabyte-platform/install-software/installer.md

Deploy preview: https://deploy-preview-21712--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/troubleshoot/install-upgrade-issues/installer/#high-disk-utilization-issue
Slack request: https://yugabyte.slack.com/archives/C05F136FUC9/p1711560277883939

[docs] [yba] Added high disk utilization issue to troubleshoot section

---

docs/content/preview/api/ysql/syntax_resources/ysql_grammar.ebnf
docs/content/preview/api/ysql/the-sql-language/statements/ddl_create_sequence.md
docs/content/stable/api/ysql/syntax_resources/ysql_grammar.ebnf
docs/content/stable/api/ysql/the-sql-language/statements/ddl_create_sequence.md

[docs] `CREATE SEQUENCE AS seq_data_type` syntax

---

docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software-prepare.md
docs/content/stable/yugabyte-platform/manage-deployments/upgrade-software-prepare.md

Links
@netlify /stable/yugabyte-platform/manage-deployments/upgrade-software-prepare/

[doc][yba] Fix links

---

docs/content/preview/releases/yba-releases/v2.16.md
docs/content/preview/releases/yba-releases/v2.17.md
docs/content/preview/releases/yba-releases/v2.18.md
docs/content/preview/releases/yba-releases/v2.19.md
docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/releases/yba-releases/v2.21.md
docs/content/preview/releases/ybdb-releases/v2.14.md
docs/content/preview/releases/ybdb-releases/v2.15.md
docs/content/preview/releases/ybdb-releases/v2.16.md
docs/content/preview/releases/ybdb-releases/v2.17.md
docs/content/preview/releases/ybdb-releases/v2.18.md
docs/content/preview/releases/ybdb-releases/v2.19.md
docs/content/preview/releases/ybdb-releases/v2.20.md
docs/content/preview/releases/ybdb-releases/v2.21.md

Add links to Release announcements

[doc] Add links to Release announcements

---

docs/content/preview/admin/_index.md
docs/content/stable/admin/_index.md

Added a tip above the list of tools.
@netlify /preview/admin/

Add tip to specify arguments with hypen

---

docs/content/preview/architecture/transactions/read-committed.md
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md
docs/content/stable/architecture/transactions/read-committed.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md
docs/content/v2.18/architecture/transactions/read-committed.md

Add description of YBA OIDC metadata option
@netlify /preview/yugabyte-platform/administer-yugabyte-platform/oidc-authentication/

[doc][yba] OIDC metadata help

---

docs/content/preview/yugabyte-voyager/overview.md

Fix YT links
@netlify /preview/yugabyte-voyager/overview/

[doc][voy] Fix YT links

---

docs/content/preview/releases/techadvisories/ta-20648.md

- The ta was pushed out without proper details
- Doing a quick fix to remove the comments
- Will do a proper fix in a separate PR

comment out the comments in TA-20648

---

docs/content/preview/yugabyte-cloud/cloud-admin/cloud-billing-costs.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-vpc-intro.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-geopartition.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-multisync.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-single-region.md

Some link fixes in YBM
@netlify /preview/yugabyte-cloud/cloud-basics/create-clusters/

[doc][ybm] YBM links

---

docs/layouts/partials/hooks/head-end.html
docs/netlify.toml

- Simple masking via btoa/atob .

Mask Segment api key

---

docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-vpc-aws.md

Update route table peering instruction for clarity
DOC-314
@netlify /preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-vpc-aws/#accept-the-peering-request-in-aws

[doc][ybm] Update route table peering instruction

---

docs/content/preview/reference/configuration/yb-master.md
docs/content/stable/reference/configuration/yb-master.md
docs/content/v2.14/reference/configuration/yb-master.md
docs/content/v2.16/reference/configuration/yb-master.md
docs/content/v2.18/reference/configuration/yb-master.md

Updating default value for outstanding_tablet_split_limit gflag
https://github.com/yugabyte/yugabyte-db/issues/21195

[#21195] Update default value for several tablet splitting gflags

---

docs/content/preview/api/ysql/the-sql-language/statements/txn_begin.md
docs/content/stable/api/ysql/the-sql-language/statements/txn_begin.md

Fixes https://yugabyte.atlassian.net/browse/DOC-300

[docs] Include full YSQL syntax in `BEGIN` page

---

docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-single-region.md
docs/content/preview/yugabyte-cloud/cloud-clusters/_index.md
docs/content/preview/yugabyte-cloud/cloud-clusters/cloud-maintenance.md
docs/content/preview/yugabyte-cloud/cloud-clusters/configure-clusters.md
docs/content/preview/yugabyte-cloud/cloud-clusters/managed-read-replica.md
docs/content/preview/yugabyte-cloud/release-notes.md

Locking operations requiring restart
@netlify /preview/yugabyte-cloud/cloud-clusters/

[doc][ybm] Locking operations

---

docs/content/preview/reference/configuration/operating-systems.md
docs/content/preview/releases/ybdb-releases/v2.20.md
docs/content/stable/reference/configuration/operating-systems.md

https://yugabyte.atlassian.net/browse/IDEA-1349?atlOrigin=eyJpIjoiZmNjN2M1YzNiZDQ5NGRhZWJlZDU0Y2U4Y2VkNzRmNDgiLCJwIjoiamlyYS1zbGFjay1pbnQifQ

[DOC-318] Added OS support for RHEL 9.3 on x86

---

docs/content/preview/yugabyte-platform/manage-deployments/delete-universe.md
docs/content/stable/yugabyte-platform/manage-deployments/delete-universe.md
docs/content/v2.18/yugabyte-platform/manage-deployments/delete-universe.md

DOC-317
@netlify /preview/yugabyte-platform/manage-deployments/delete-universe/

[doc][yba] No pause for on-prem

---

docs/src/algolia-search.js

Close search dropdown quick results menu on clicking anywhere else on the page.

[Docs] Close search dropdown quick results menu

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/_index.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/_index.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-tables.md
docs/content/stable/yugabyte-platform/create-deployments/async-replication-platform.md

Copy changes for #21981 to stable
@netlify /stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/

[doc][yba] Copy 21981 changes to stable

---

docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/preview/yugabyte-platform/alerts-monitoring/anywhere-metrics.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/on-premises-script.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-manual.md
docs/content/preview/yugabyte-platform/security/enable-encryption-in-transit.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/stable/yugabyte-platform/alerts-monitoring/anywhere-metrics.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/create-admin-user.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
docs/content/stable/yugabyte-platform/security/enable-encryption-in-transit.md
docs/content/v2.16/yugabyte-platform/security/enable-encryption-in-transit.md
docs/content/v2.16/yugabyte-platform/troubleshoot/_index.md
docs/content/v2.18/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
docs/content/v2.18/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-script.md
docs/content/v2.18/yugabyte-platform/security/enable-encryption-in-transit.md
docs/content/v2.18/yugabyte-platform/troubleshoot/_index.md

Remove more references to port for node agent (see #22440)
@netlify /preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-manual/#reconfigure-a-node-agent

[doc][yba] Backport node agent remove port ref #22466

---

docs/content/preview/yugabyte-platform/administer-yugabyte-platform/ldap-authentication.md
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md

OIDC group mapping new PR
@netlify /preview/yugabyte-platform/administer-yugabyte-platform/oidc-authentication/

[doc][yba] 2024.1 OIDC group mapping #22201

---

docs/content/preview/yugabyte-platform/anywhere-automation/_index.md
docs/content/preview/yugabyte-platform/anywhere-automation/anywhere-cli.md

YBA CLI landing page
@netlify /preview/yugabyte-platform/anywhere-automation/

[doc][yba] 2024.1 YBA CLI landing page #22209

---

docs/content/preview/admin/_index.md
docs/content/preview/develop/learn/transactions/acid-transactions-ycql.md
docs/content/preview/manage/backup-restore/point-in-time-recovery.md
docs/content/preview/reference/configuration/yb-master.md
docs/content/stable/admin/_index.md
docs/content/stable/develop/learn/transactions/acid-transactions-ycql.md
docs/content/v2.14/develop/learn/acid-transactions-ycql.md
docs/content/v2.14/manage/backup-restore/point-in-time-recovery.md
docs/content/v2.16/develop/learn/acid-transactions-ycql.md
docs/content/v2.16/manage/backup-restore/point-in-time-recovery.md
docs/content/v2.18/develop/learn/transactions/acid-transactions-ycql.md
docs/content/v2.18/manage/backup-restore/point-in-time-recovery.md

Updated PR for doc-65
Backport some other misc changes
@netlify /preview/develop/learn/transactions/acid-transactions-ycql/

DOC-65-Transaction-prepare-bind-syntax-errors #22530

---

docs/content/preview/architecture/docdb-sharding/tablet-splitting.md
docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md

@netlify preview/architecture/docdb-sharding/tablet-splitting/#tablet-limits

[DOC-319] [2024.1] Docs for tablet limits

---

docs/content/preview/explore/query-1-performance/pg-hint-plan.md
docs/content/preview/manage/backup-restore/point-in-time-recovery.md
docs/content/preview/reference/configuration/yb-tserver.md

@netlify /preview/reference/configuration/yb-tserver/#ddl-atomicity-flags

[DOC-343] [DOC-286] [DOC-354] [DOC-313] DDL atomicity flags, Catalog flag, bitmaps scan, Truncate table support in PITR

---

docs/content/preview/yugabyte-platform/troubleshoot/universe-issues.md

@netlify /preview/yugabyte-platform/troubleshoot/universe-issues/

[DOC-311] [2024.1] Added pre-checks before edit/upgrade operations

---

docs/content/preview/yugabyte-platform/administer-yugabyte-platform/uninstall-software.md

@netlify /preview/yugabyte-platform/administer-yugabyte-platform/uninstall-software/

[DOC-312] [2024.1] Update YBA docs for replacing unreachable node

---

docs/content/preview/deploy/checklist.md
docs/content/stable/deploy/checklist.md
docs/content/v2.18/deploy/checklist.md

DOC-380
@netlify /preview/deploy/checklist/

[doc] Memory requirement YSQL

---

docs/content/preview/releases/ybdb-releases/v2024.1.md

https://yugabyte.slack.com/archives/CDQB8MEAU/p1717607206072749

[docs] Minor change to tablet limit description on release notes

---

docs/config/_default/params.toml
docs/content/preview/admin/yb-docker-ctl.md
docs/content/preview/api/ycql/_index.md
docs/content/preview/api/ysql/_index.md
docs/content/preview/benchmark/tpcc/high-scale-workloads.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/preview/reference/configuration/yugabyted.md
docs/content/preview/releases/yba-releases/v2024.1.md
docs/content/preview/releases/ybdb-releases/v2.21.md
docs/content/preview/releases/ybdb-releases/v2024.1.md
docs/content/preview/yugabyte-voyager/performance.md
docs/content/stable/admin/yb-docker-ctl.md
docs/content/stable/api/ycql/_index.md
docs/content/stable/api/ysql/_index.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yugabyted.md
docs/content/v2.16/admin/yb-docker-ctl.md
docs/content/v2.16/api/ysql/_index.md
docs/content/v2.18/admin/yb-docker-ctl.md
docs/content/v2.18/api/ycql/_index.md
docs/content/v2.18/api/ysql/_index.md
docs/content/v2.20/admin/yb-docker-ctl.md
docs/content/v2.20/api/ycql/_index.md
docs/content/v2.20/api/ysql/_index.md

@netlify /stable/reference/configuration/yb-tserver/#yb-enable-base-scans-cost-model

[DOC-388] updated CBO flags

---

docs/netlify.toml

Analytics domain evaluating a new tool called '6sense' which I have added via GTM but due to the CSP it is not working, please merge this PR so that Analytics team can start evaluating the tool.

[Docs] Allow 6sense domains in CSP

---

docs/netlify.toml

Found errors in browser console due to CSP header. This PR fixes all of errors currently appearing on the production site.

[Docs] Update CSP connect-src directive to fix console errors

---

docs/config/_default/menus.toml
docs/content/preview/yugabyte-cloud/cloud-clusters/cloud-maintenance.md

Clarify maintenance impact on clusters
DOC-384
@netlify /preview/yugabyte-cloud/cloud-clusters/cloud-maintenance/

[doc][ybm] What to expect during maintenance

---

docs/content/preview/secure/vulnerability-disclosure-policy.md
docs/layouts/shortcodes/cve.html

@netlify /preview/secure/vulnerability-disclosure-policy/#security-tracker-cve-list
Build preview: https://deploy-preview-22824--infallible-bardeen-164bc9.netlify.app/preview/secure/vulnerability-disclosure-policy/#security-tracker-cve-list

[docs] CVE list updates

---

docs/content/preview/secure/vulnerability-disclosure-policy.md
docs/layouts/shortcodes/cve.html

@netlify /preview/secure/vulnerability-disclosure-policy/

[docs] CVE revert and link fixes

---

docs/config/_default/menus.toml
docs/content/preview/explore/query-1-performance/pg-stat-statements.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/_index.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-tables.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-assist.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-auto.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-manual.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md
docs/content/stable/explore/query-1-performance/pg-stat-statements.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/_index.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-tables.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-on-prem-assist.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-on-prem-auto.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-on-prem-manual.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md
docs/content/v2.18/explore/query-1-performance/pg-stat-statements.md
docs/content/v2.20/explore/query-1-performance/pg-stat-statements.md
docs/content/v2.20/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-tables.md

Clarify alter with constraint steps
DOC-389
@netlify /preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-tables/

[doc][yba] DR Managing tables and indexes fixes

---

docs/content/preview/releases/ybdb-releases/v2024.1.md
docs/content/stable/reference/configuration/yb-tserver.md

https://deploy-preview-22888--infallible-bardeen-164bc9.netlify.app/preview/releases/ybdb-releases/v2024.1/#new-features

[docs] EA badge for DDL atomicity

---

docs/content/preview/benchmark/tpcc/high-scale-workloads.md
docs/content/preview/benchmark/tpcc/horizontal-scaling.md
docs/content/preview/benchmark/tpcc/running-tpcc.md
docs/content/preview/explore/linear-scalability/scaling-reads.md
docs/content/preview/explore/linear-scalability/scaling-transactions.md
docs/content/preview/explore/linear-scalability/scaling-writes.md
docs/layouts/shortcodes/inst.html
docs/layouts/shortcodes/nobreak.html

- Update the docs with latest tpcc results
- Introduce new `inst` shortcode

Update TPCC results

---

docs/netlify.toml

[doc] 404 fixes

---

docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/v2.20/yugabyte-platform/administer-yugabyte-platform/high-availability.md

HA - Metrics only availabile on standby from activation
DOC-394
DOC-395
@netlify /preview/yugabyte-platform/administer-yugabyte-platform/high-availability

[doc][yba] HA - Metrics availability on standby

---

docs/content/preview/reference/configuration/yb-tserver.md
docs/content/preview/releases/ybdb-releases/v2.21.md
docs/content/preview/releases/ybdb-releases/v2024.1.md
docs/content/stable/reference/configuration/yb-tserver.md

Verify the following:
- [DDL concurrency](https://yugabyte.atlassian.net/jira/polaris/projects/IDEA/ideas/view/3573079?selectedIssue=IDEA-573) should be TP in 2.21 and GA in 2024.1
- [DDL atomicity](https://yugabyte.atlassian.net/jira/polaris/projects/IDEA/ideas/view/3573079?selectedIssue=IDEA-574) should be TP in 2.21 and GA in 2024.1
Slack request - https://yugabyte.slack.com/archives/CDQB8MEAU/p1718746149644979
Note to self ( check catalog flags)

[docs] Change badges for DDL concurrency and DDL atomicity features.

---

docs/content/preview/drivers-orms/include-drivers-orms-list.md
docs/content/preview/drivers-orms/java/_index.md
docs/content/preview/drivers-orms/java/ebean.md
docs/content/preview/drivers-orms/java/yugabyte-jdbc.md
docs/content/preview/drivers-orms/orms/java/ysql-ebean.md
docs/content/preview/integrations/apache-spark/java-ysql.md
docs/content/preview/integrations/apache-spark/python-ysql.md
docs/content/preview/integrations/apache-spark/scala-ysql.md
docs/content/preview/integrations/apache-spark/spark-sql.md
docs/content/preview/integrations/camunda.md
docs/content/preview/integrations/flyway.md
docs/content/preview/integrations/spring-framework/sd-jpa.md
docs/content/preview/integrations/spring-framework/sdyb.md
docs/content/preview/quick-start/docker.md
docs/content/preview/quick-start/kubernetes.md
docs/content/preview/reference/drivers/java/yugabyte-jdbc-reference.md
docs/content/preview/tutorials/build-and-learn/chapter3-tolerating-outages.md
docs/content/stable/drivers-orms/include-drivers-orms-list.md
docs/content/stable/drivers-orms/java/_index.md
docs/content/stable/drivers-orms/java/ebean.md
docs/content/stable/drivers-orms/java/yugabyte-jdbc.md
docs/content/stable/drivers-orms/orms/java/ysql-ebean.md
docs/content/stable/reference/drivers/java/yugabyte-jdbc-reference.md

- Update Flyway integrations page with details on the plugin.
- Update JDBC Smart driver version on rest of the pages.

[Docs update] Update JDBC Smart Driver details

---

docs/content/preview/releases/yba-releases/v2.18.md
docs/content/preview/releases/ybdb-releases/v2.18.md
docs/data/currentVersions.json

https://deploy-preview-22968--infallible-bardeen-164bc9.netlify.app/preview/releases/ybdb-releases/v2.18/#v2.18.8.0

[docs] Release v2.18.8.0-b42

---

docs/content/preview/explore/observability/_index.md
docs/content/preview/explore/query-1-performance/ycql-stat-statements.md
docs/content/stable/explore/observability/_index.md
docs/content/stable/explore/observability/active-session-history.md
docs/content/stable/explore/observability/yb-local-tablets.md
docs/content/stable/explore/query-1-performance/_index.md
docs/content/stable/explore/query-1-performance/pg-stat-statements.md
docs/content/stable/explore/query-1-performance/ycql-stat-statements.md

@netlify /stable/explore/observability/yb-local-tablets/

[docs] added ycql-stat-statements and yb_local_tablets pages to stable

---

docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/releases/ybdb-releases/v2.20.md
docs/data/currentVersions.json

@netlify preview/releases/yba-releases/v2.20/#v2.20.4.1

[docs] release notes for 2.20.4.1

---

docs/content/preview/faq/yugabytedb-managed-faq.md
docs/content/preview/yugabyte-cloud/_index.md
docs/content/preview/yugabyte-cloud/release-notes.md

[doc][ybm] Change log for Jun 2024

---

docs/assets/scss/_tables.scss
docs/src/index.js

**Criteria for Sortable Tables:**
- **Table Class:** Table must possess a `sortable` class.
- **Table Header:** Table must possess a header row containing column labels. Empty headers will disable sorting for that specific column. For example: 
https://deploy-preview-22836--infallible-bardeen-164bc9.netlify.app/preview/explore/linear-scalability/horizontal-vs-vertical-scaling/#differences
- **Number of rows:** Table must contain at least two data rows (excluding the header row).
- **Non-Empty Columns:** Each column participating in the sorting process must contain data. Empty columns (all blank cells) will not be included in the sorting functionality. For example: 
https://deploy-preview-22836--infallible-bardeen-164bc9.netlify.app/preview/explore/observability/active-session-history/#ysql …

[Docs] Sort feature to tables (Where fulfills the criteria)

---

docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/releases/ybdb-releases/v2.20.md

https://deploy-preview-23042--infallible-bardeen-164bc9.netlify.app/preview/releases/ybdb-releases/v2.20/#v2.20.2.3

[docs] Added RN 2.20.2.3-b2

---

docs/content/preview/manage/upgrade-deployment.md
docs/content/stable/manage/upgrade-deployment.md

Based on https://yugabyte.slack.com/archives/CDQB8MEAU/p1718700259749979

Doc upgrade versions

---

docs/content/preview/reference/configuration/yugabyted.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-manual.md
docs/content/stable/reference/configuration/yugabyted.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-on-prem-manual.md
docs/content/v2.14/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
docs/content/v2.18/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
docs/content/v2.20/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md

yugabyted --join flag enforces dns syntax
typo fix in 2.14
DOC-413
DOC-204
stable/reference/configuration/yugabyted

[doc] join flag syntax

---

docs/src/algolia-search.js

- Fix XSS vulnerability with svg onload:
- Production: https://docs.yugabyte.com/search/?query=%3Csvg/onload%3Dalert(%22XSS-vulnerability-test%22)+/%3E
- Preview: https://deploy-preview-23167--infallible-bardeen-164bc9.netlify.app/search/?query=%3Csvg/onload%3Dalert(%22XSS-vulnerability-test%22)+/%3E
- An update to the “not found” message to include a link to the Kapa widget. Following message (No results found for "SEARCH TERM". Try this search in AI.) needs to be shown whereas currently it is showing 0 results found for "SEARCH TERM". 
@netlify /search/?query=%3Csvg/onload%3Dalert(%22XSS-vulnerability-test%22)+/%3E .

[Docs] Adding back search functionalities removed mistakenly

---

docs/content/preview/develop/learn/_index.md
docs/content/preview/drivers-orms/java/_index.md
docs/content/preview/explore/change-data-capture/debezium-connector-yugabytedb.md
docs/content/preview/reference/configuration/yugabyted.md
docs/content/preview/yugabyte-platform/alerts-monitoring/alert-policy-templates.md
docs/content/preview/yugabyte-platform/alerts-monitoring/alert.md
docs/content/preview/yugabyte-platform/alerts-monitoring/latency-histogram.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/back-up-universe-data.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-manual.md
docs/content/preview/yugabyte-platform/security/security-checklist-yp.md
docs/netlify.toml

[doc] Fixes for 404

---

docs/content/preview/faq/yugabytedb-managed-faq.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-free.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-examples/managed-guide-api.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-cluster.md
docs/content/preview/yugabyte-cloud/release-notes.md

Early Access track
CLOUDGA-21942
@netlify /preview/yugabyte-cloud/cloud-basics/create-clusters-overview/

[doc][ybm] Early Access track

---

docs/content/preview/explore/change-data-capture/_index.md
docs/content/preview/tutorials/cdc-tutorials/_index.md
docs/content/preview/yugabyte-cloud/release-notes.md

[doc][ybm] change log

---

docs/content/preview/explore/change-data-capture/_index.md
docs/content/preview/explore/change-data-capture/using-yugabytedb-grpc-replication/_index.md
docs/content/preview/explore/change-data-capture/using-yugabytedb-grpc-replication/cdc-get-started.md
docs/content/preview/explore/change-data-capture/using-yugabytedb-grpc-replication/debezium-connector-yugabytedb.md

CDC Docs changes

---

docs/content/preview/releases/yba-releases/v2.18.md
docs/content/preview/releases/ybdb-releases/v2.18.md
docs/data/currentVersions.json

[doc] 2.18.1.1 release notes

---

docs/content/preview/architecture/transactions/read-restart-error.md
docs/content/stable/architecture/transactions/read-restart-error.md

DOC-408
@netlify /preview/architecture/transactions/read-restart-error/

[docs] Add basic troubleshooting steps for read restart errors.

---

docs/content/preview/yugabyte-cloud/cloud-secure-clusters/managed-ear.md

Remove ea badge from EAR page
@netlify /preview/yugabyte-cloud/cloud-secure-clusters/managed-ear/

[doc][ybm] Remove ea badge

---

docs/content/preview/integrations/_index.md
docs/content/preview/integrations/delphix.md

Delphix note on script deprecation
DOC-430
@netflix /preview/integrations/delphix/

[doc] Delphix note on script

---

docs/content/preview/secure/vulnerability-disclosure-policy.md

Deploy previews: https://deploy-preview-23282--infallible-bardeen-164bc9.netlify.app/preview/secure/vulnerability-disclosure-policy/#security-tracker-cve-list

[DOC-429] Added CVE's to the security list 

---

docs/content/preview/faq/yugabytedb-managed-faq.md
docs/content/stable/admin/ycqlsh.md
docs/content/stable/admin/ysqlsh.md

ysqlsh and ycqlsh installation instructions
DOC-372
@netlify /stable/admin/ycqlsh/

[doc][2024.1.1] yb shell client download

---

docs/content/preview/releases/techadvisories/_index.md
docs/content/preview/releases/techadvisories/ta-22802.md

@netlify /preview/releases/techadvisories/ta-22802/

[docs] Added TA-22802: Inconsistencies between system catalog and DocDB schema during DDL operations

---

docs/content/preview/explore/ysql-language-features/join-strategies.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/explore/ysql-language-features/join-strategies.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/v2.18/explore/ysql-language-features/join-strategies.md
docs/content/v2.18/reference/configuration/yb-tserver.md
docs/content/v2.20/explore/ysql-language-features/join-strategies.md
docs/content/v2.20/reference/configuration/yb-tserver.md

Add ysql_yb_bnl_batch_size flag
DOC-416
@netlify /preview/reference/configuration/yb-tserver/#ysql-yb-bnl-batch-size

[doc] ysql_yb_bnl_batch_size flag

---

docs/content/preview/reference/configuration/yugabyted.md
docs/content/stable/reference/configuration/yugabyted.md

update use of configure flag
@netlify /preview/reference/configuration/yugabyted/

[doc] yugabyted configure flag

---

docs/content/preview/explore/sql-nosql.md
docs/content/preview/yugabyte-cloud/release-notes.md

Change log - latency histogram

[doc][ybm] Change log - latency histogram

---

docs/content/preview/releases/yba-releases/v2.18.md
docs/content/preview/releases/ybdb-releases/v2.18.md
docs/data/currentVersions.json

https://deploy-preview-23485--infallible-bardeen-164bc9.netlify.app/preview/releases/ybdb-releases/v2.18/#v2.18.9.0

[docs] Release notes for 2.18.9.0

---

docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-region.md
docs/content/preview/yugabyte-platform/manage-deployments/delete-universe.md
docs/content/preview/yugabyte-platform/manage-deployments/edit-config-flags.md
docs/content/preview/yugabyte-platform/manage-deployments/remove-nodes.md
docs/content/preview/yugabyte-platform/security/create-kms-config/aws-kms.md
docs/content/preview/yugabyte-platform/security/create-kms-config/azure-kms.md
docs/content/preview/yugabyte-platform/security/create-kms-config/google-kms.md
docs/content/preview/yugabyte-platform/security/create-kms-config/hashicorp-kms.md
docs/content/preview/yugabyte-platform/security/enable-encryption-at-rest.md
docs/content/stable/yugabyte-platform/create-deployments/create-universe-multi-region.md
docs/content/stable/yugabyte-platform/manage-deployments/delete-universe.md
docs/content/stable/yugabyte-platform/manage-deployments/edit-config-flags.md
docs/content/stable/yugabyte-platform/manage-deployments/remove-nodes.md
docs/content/stable/yugabyte-platform/security/create-kms-config/aws-kms.md
docs/content/stable/yugabyte-platform/security/create-kms-config/azure-kms.md
docs/content/stable/yugabyte-platform/security/create-kms-config/google-kms.md
docs/content/stable/yugabyte-platform/security/create-kms-config/hashicorp-kms.md
docs/content/stable/yugabyte-platform/security/enable-encryption-at-rest.md
docs/content/v2.14/yugabyte-platform/security/create-kms-config/hashicorp-kms.md
docs/content/v2.18/yugabyte-platform/security/create-kms-config/hashicorp-kms.md
docs/content/v2.20/yugabyte-platform/alerts-monitoring/anywhere-metrics.md
docs/content/v2.20/yugabyte-platform/manage-deployments/delete-universe.md
docs/content/v2.20/yugabyte-platform/manage-deployments/edit-config-flags.md
docs/content/v2.20/yugabyte-platform/manage-deployments/remove-nodes.md
docs/content/v2.20/yugabyte-platform/security/create-kms-config/aws-kms.md
docs/content/v2.20/yugabyte-platform/security/create-kms-config/azure-kms.md
docs/content/v2.20/yugabyte-platform/security/create-kms-config/google-kms.md
docs/content/v2.20/yugabyte-platform/security/create-kms-config/hashicorp-kms.md
docs/content/v2.20/yugabyte-platform/security/enable-encryption-at-rest.md

Note on deleting KMS config
DOC-448
@netlify /preview/yugabyte-platform/security/create-kms-config/aws-kms/

[doc][yba] Note on deleting KMS config

---

docs/content/preview/releases/techadvisories/_index.md
docs/content/preview/releases/techadvisories/ta-22935.md

@netlify /preview/releases/techadvisories/ta-22935/

[DOC-445] TA-22935: Potential Issues with Server-side Sequence Caching in Multi-Database Clusters

---

docs/config/_default/menus.toml
docs/config/_default/params.toml
docs/content/preview/deploy/manual-deployment/install-software.md
docs/content/preview/drivers-orms/csharp/_index.md
docs/content/preview/drivers-orms/include-drivers-orms-list.md
docs/content/preview/releases/ybdb-releases/end-of-life/v2.2.md
docs/content/stable/drivers-orms/csharp/_index.md
docs/content/stable/drivers-orms/include-drivers-orms-list.md
docs/content/v2.18/drivers-orms/csharp/_index.md
docs/content/v2.20/deploy/manual-deployment/install-software.md
docs/content/v2.20/drivers-orms/csharp/_index.md
docs/content/v2.20/drivers-orms/include-drivers-orms-list.md

Slack requests:
https://yugabyte.slack.com/archives/CDQB8MEAU/p1723811631997749
https://yugabyte.slack.com/archives/CDQB8MEAU/p1724149166279839
https://yugabyte.slack.com/archives/CDQB8MEAU/p1724160255099969

[doc] Set 2024.1 (stable) as the default in releases menu

---

docs/content/preview/deploy/manual-deployment/install-software.md
docs/content/preview/yugabyte-cloud/cloud-monitor/managed-integrations.md
docs/content/stable/deploy/manual-deployment/install-software.md
docs/content/v2.14/deploy/manual-deployment/install-software.md
docs/content/v2.18/deploy/manual-deployment/install-software.md
docs/content/v2.20/deploy/manual-deployment/install-software.md

Add note box to install
@netlify /v2.14/deploy/manual-deployment/install-software/

[doc] Add note box to install

---

docs/content/preview/architecture/docdb-replication/cdc-logical-replication.md
docs/content/preview/architecture/docdb-replication/change-data-capture.md
docs/content/preview/explore/change-data-capture/using-yugabytedb-grpc-replication/_index.md
docs/content/stable/architecture/docdb-replication/cdc-logical-replication.md
docs/content/stable/architecture/docdb-replication/change-data-capture.md
docs/content/stable/explore/change-data-capture/using-yugabytedb-grpc-replication/_index.md

Change page names to match Explore section
@netlify /preview/architecture/docdb-replication/change-data-capture/

[doc] CDC architecture page names

---

docs/content/preview/releases/yba-releases/_index.md

@netlify /preview/releases/yba-releases/

[docs] added Replicated EOL note on YBA releases page 

---

docs/content/preview/releases/techadvisories/_index.md
docs/content/preview/releases/techadvisories/ta-23476.md

@netlify /preview/releases/techadvisories/ta-23476/

[docs] [TA] Added TA-23476: YCQL currenttimestamp() precision

---

docs/assets/scss/_yb_kapa_ai.scss
docs/config/_default/params.toml
docs/layouts/partials/navbar.html

1. Remove the phrase “Use Experimenta AI” and use “Ask AI”
2. Remove the notification box that reminds people to use AI

[Docs] Changes for Experimental AI

---

docs/content/preview/drivers-orms/include-drivers-orms-list.md
docs/content/preview/drivers-orms/python/yugabyte-psycopg2.md
docs/content/stable/drivers-orms/python/yugabyte-psycopg2.md
docs/content/v2.20/drivers-orms/python/yugabyte-psycopg2.md

Add Python smart driver PyPI link
@netlify /preview/drivers-orms/python/yugabyte-psycopg2/

[doc] Add Python smart driver PyPI link

---

docs/content/preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-yp.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-replicated.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/back-up-restore-yp.md
docs/content/v2.18/yugabyte-platform/administer-yugabyte-platform/back-up-restore-yp.md
docs/content/v2.20/yugabyte-platform/administer-yugabyte-platform/back-up-restore-yp.md

Clarify YBA backup using Replicated
DOC-426
@netlify /preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-yp/

[doc][yba] Replicated YBA backup

---

.github/vale-styles/Yugabyte/spelling-exceptions.txt
docs/content/preview/yugabyte-voyager/known-issues/mysql.md
docs/content/preview/yugabyte-voyager/known-issues/postgresql.md
docs/content/preview/yugabyte-voyager/release-notes.md
docs/content/preview/yugabyte-voyager/ubuntu.md

https://deploy-preview-23634--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-voyager/known-issues/postgresql/

[DOC-457] Added known issues to Manual review guideline

---

docs/content/preview/admin/yb-ts-cli.md
docs/content/preview/explore/observability/_index.md
docs/content/preview/explore/query-1-performance/_index.md
docs/content/preview/explore/query-1-performance/query-tuning-intro.md
docs/content/preview/launch-and-manage/_index.md
docs/content/preview/secure/audit-logging/trace-statements-ysql.md
docs/content/preview/troubleshoot/_index.md
docs/content/preview/troubleshoot/ysql-issues.md
docs/content/stable/admin/yb-ts-cli.md
docs/content/stable/explore/observability/_index.md
docs/content/stable/explore/query-1-performance/_index.md
docs/content/stable/explore/query-1-performance/query-tuning-intro.md
docs/content/stable/launch-and-manage/_index.md
docs/content/stable/secure/audit-logging/trace-statements-ysql.md
docs/content/v2.14/admin/yb-ts-cli.md
docs/content/v2.14/explore/query-1-performance/query-tuning-intro.md
docs/content/v2.14/launch-and-manage/_index.md
docs/content/v2.14/secure/audit-logging/trace-statements-ysql.md
docs/content/v2.18/admin/yb-ts-cli.md
docs/content/v2.18/explore/query-1-performance/query-tuning-intro.md
docs/content/v2.18/launch-and-manage/_index.md
docs/content/v2.18/secure/audit-logging/trace-statements-ysql.md
docs/content/v2.20/admin/yb-ts-cli.md
docs/content/v2.20/launch-and-manage/_index.md
docs/content/v2.20/secure/audit-logging/trace-statements-ysql.md

[doc] Troubleshoot link fix

---

docs/content/preview/yugabyte-cloud/cloud-troubleshoot.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/_index.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/_index.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-integration.md
docs/content/preview/yugabyte-platform/anywhere-automation/anywhere-cli.md

DOC-462
netlify /preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-integration/

CLI integration edits

---

docs/data/currentVersions.json

[docs] Fix 2024.1.2 build number

---

docs/content/preview/deploy/multi-dc/async-replication/async-transactional-setup-dblevel.md
docs/content/stable/deploy/multi-dc/async-replication/async-transactional-setup-dblevel.md

[docs] [xcluster] Add min version for semi-automatic mode

---

docs/content/preview/explore/going-beyond-sql/connection-mgr-ysql.md
docs/content/stable/explore/going-beyond-sql/connection-mgr-ysql.md
docs/content/v2.20/explore/connection-manager/connection-mgr-ysql.md

Fixes #23631
Explained in https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1724529062989439?thread_ts=1724422576.682679&cid=CG0KQF0GG

[docs] Enclose `allowed_preview_flags_csv` CSV parameters in brackets

---

docs/content/preview/reference/configuration/operating-systems.md
docs/content/stable/reference/configuration/operating-systems.md
docs/content/v2.20/reference/configuration/operating-systems.md

Slack request - https://yugabyte.slack.com/archives/CDQB8MEAU/p1725462142985099

[docs] Update RHEL 9.3 OS support entry

---

docs/content/preview/releases/ybdb-releases/v2024.1.md

Adjust heading link for correct section when linking from Aeon

[doc] Adjust heading link

---

docs/layouts/partials/earlier-version-warning.html

Comments out the debug warn msg from the earlier version warning shortcode

Comment out the warning message

---

docs/content/preview/explore/ysql-language-features/postgresql-compatibility.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/explore/ysql-language-features/postgresql-compatibility.md
docs/content/stable/reference/configuration/yb-tserver.md

yb_enable_bitmapscan flag
@netlify /preview/reference/configuration/yb-tserver/#yb-enable-bitmapscan

[doc] yb_enable_bitmapscan flag

---

docs/content/preview/architecture/docdb-replication/async-replication.md
docs/content/preview/deploy/multi-dc/async-replication/_index.md
docs/content/preview/deploy/multi-dc/async-replication/async-replication-transactional.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/_index.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-tables.md
docs/content/preview/yugabyte-platform/manage-deployments/xcluster-replication/_index.md
docs/content/preview/yugabyte-platform/manage-deployments/xcluster-replication/xcluster-replication-ddl.md
docs/content/stable/architecture/docdb-replication/async-replication.md
docs/content/stable/deploy/multi-dc/async-replication/_index.md
docs/content/stable/deploy/multi-dc/async-replication/async-replication-transactional.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/_index.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-tables.md
docs/content/stable/yugabyte-platform/manage-deployments/xcluster-replication/_index.md
docs/content/stable/yugabyte-platform/manage-deployments/xcluster-replication/xcluster-replication-ddl.md
docs/content/v2.20/architecture/docdb-replication/async-replication.md

Clarify some limitations including truncate
DOC-460
@netlify /preview/yugabyte-platform/manage-deployments/xcluster-replication/#limitations

[doc][xcluster] Truncate limitation

---

docs/content/preview/releases/techadvisories/_index.md
docs/content/preview/releases/techadvisories/ta-23476.md

@netlify /preview/releases/techadvisories/ta-23476/

[docs] Changed date for TA-23476

---

docs/content/preview/explore/ysql-language-features/pg-extensions/extension-auto-explain.md
docs/content/stable/explore/ysql-language-features/pg-extensions/extension-auto-explain.md
docs/content/v2.20/explore/ysql-language-features/pg-extensions/extension-auto-explain.md

@netlify preview/explore/ysql-language-features/pg-extensions/extension-auto-explain/

[#23814] docs: Add log_dist option to auto_explain page.

---

docs/content/preview/deploy/manual-deployment/install-software.md
docs/content/preview/deploy/manual-deployment/start-masters.md
docs/content/preview/deploy/manual-deployment/start-tservers.md
docs/content/preview/manage/_index.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/_index.md
docs/content/preview/yugabyte-platform/security/enable-encryption-at-rest.md
docs/content/stable/deploy/manual-deployment/install-software.md
docs/content/stable/deploy/manual-deployment/start-masters.md
docs/content/stable/deploy/manual-deployment/start-tservers.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/_index.md

Warning for disk encryption agent
DOC-440
@netlify /preview/yugabyte-platform/security/enable-encryption-at-rest/#manage-universe-encryption-at-rest

[doc][yba] Warning for disk encryption agent

---

docs/content/preview/releases/yba-releases/v2.21.md
docs/content/preview/releases/yba-releases/v2.23.md
docs/content/preview/releases/yba-releases/v2024.1.md
docs/content/preview/releases/ybdb-releases/end-of-life/v2.11.md
docs/content/preview/releases/ybdb-releases/end-of-life/v2.12.md
docs/content/preview/releases/ybdb-releases/end-of-life/v2.13.md
docs/content/preview/releases/ybdb-releases/v2.21.md
docs/content/preview/releases/ybdb-releases/v2.23.md
docs/content/preview/releases/ybdb-releases/v2024.1.md
docs/data/currentVersions.json

Fix RSS link
@netlify /preview/releases/ybdb-releases/v2.23/

[doc] Fix RSS link

---

docs/content/preview/yugabyte-cloud/cloud-monitor/managed-integrations.md
docs/content/preview/yugabyte-cloud/cloud-monitor/metrics-export.md
docs/content/preview/yugabyte-cloud/cloud-monitor/monitor-activity.md
docs/content/preview/yugabyte-cloud/release-notes.md

VictoriaMetrics Integration
CLOUDGA-23073
@netlify /preview/yugabyte-cloud/cloud-monitor/managed-integrations/

[doc][ybm] VictoriaMetrics

---

docs/content/preview/yugabyte-voyager/migrate/live-fall-back.md
docs/content/preview/yugabyte-voyager/migrate/live-fall-forward.md
docs/content/preview/yugabyte-voyager/migrate/live-migrate.md

@netlify /preview/yugabyte-voyager/migrate/live-fall-back/#prepare-the-source-database

[DOC-470] Include SSL Connectivity within the source database tabs.

---

docs/assets/scss/_yb_badge.scss
docs/layouts/shortcodes/badge/ea.html
docs/layouts/shortcodes/badge/ga.html
docs/layouts/shortcodes/badge/tp.html

Update badge colors
@netlify /preview/releases/versioning/#feature-maturity

[doc] Update badge colors

---

docs/content/preview/api/ysql/the-sql-language/statements/cmd_analyze.md
docs/content/preview/explore/ysql-language-features/join-strategies.md
docs/content/preview/explore/ysql-language-features/postgresql-compatibility.md
docs/content/stable/api/ysql/the-sql-language/statements/cmd_analyze.md
docs/content/stable/explore/ysql-language-features/join-strategies.md
docs/content/stable/explore/ysql-language-features/postgresql-compatibility.md
docs/content/v2.18/explore/ysql-language-features/join-strategies.md
docs/content/v2.18/reference/configuration/yb-tserver.md
docs/content/v2.20/explore/ysql-language-features/join-strategies.md
docs/content/v2.20/reference/configuration/yb-tserver.md

Fix BNL flag defaults
DOC-471
@netlify /preview/explore/ysql-language-features/postgresql-compatibility

[doc] Fix BNL flag defaults

---

docs/content/preview/reference/configuration/default-ports.md
docs/content/stable/reference/configuration/default-ports.md

Add ports for CIS hardened
@netlify /reference/configuration/default-ports/

[doc] Update ports for CIS hardened

---

docs/content/preview/secure/vulnerability-disclosure-policy.md

@netlify /preview/secure/vulnerability-disclosure-policy/#supply-chain-vulnerabilities-in-yugabytedb-postgres-query-layer-ysql
Slack thread- https://yugabyte.slack.com/archives/C022EKPB3C2/p1726776126748739?thread_ts=1726763531.834879&cid=C022EKPB3C2

[docs] Added and updated CVEs

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/stable/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md

Update the link for the crd file to point to the raw text link
DOC-481
@netlify /preview/yugabyte-platform/upgrade/upgrade-yp-kubernetes/

[doc][yba] Update link for crd file

---

docs/config/_default/menus.toml
docs/content/preview/yugabyte-voyager/diagnostics-report.md
docs/content/preview/yugabyte-voyager/monitor/performance.md

@netlify /preview/yugabyte-voyager/

[docs] Voyager left nav changes 

---

docs/content/preview/explore/transactions/_index.md
docs/content/stable/explore/transactions/_index.md
docs/content/v2.20/explore/transactions/_index.md

https://docs.yugabyte.com/preview/explore/transactions/
Add 'Read Committed' isolation level for YSQL isolation levels

Add Read Committed transaction isolation level

---

docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/releases/ybdb-releases/v2.20.md
docs/data/currentVersions.json

@netlify /preview/releases/ybdb-releases/v2.20/#v2.20.7.0

[docs] Added Release notes for 2.20.7.0

---

docs/content/preview/drivers-orms/include-drivers-orms-list.md
docs/content/preview/drivers-orms/java/_index.md
docs/content/preview/drivers-orms/java/ebean.md
docs/content/preview/drivers-orms/java/yugabyte-jdbc-reference.md
docs/content/preview/drivers-orms/java/yugabyte-jdbc.md
docs/content/preview/drivers-orms/orms/java/ysql-ebean.md
docs/content/preview/integrations/apache-spark/java-ysql.md
docs/content/preview/integrations/apache-spark/python-ysql.md
docs/content/preview/integrations/apache-spark/scala-ysql.md
docs/content/preview/integrations/apache-spark/spark-sql.md
docs/content/preview/integrations/camunda.md
docs/content/preview/integrations/flyway.md
docs/content/preview/integrations/spring-framework/sd-jpa.md
docs/content/preview/integrations/spring-framework/sdyb.md
docs/content/preview/quick-start/docker.md
docs/content/preview/quick-start/kubernetes.md
docs/content/preview/tutorials/build-and-learn/chapter3-tolerating-outages.md
docs/content/stable/drivers-orms/include-drivers-orms-list.md
docs/content/stable/drivers-orms/java/_index.md
docs/content/stable/drivers-orms/java/ebean.md
docs/content/stable/drivers-orms/java/yugabyte-jdbc-reference.md
docs/content/stable/drivers-orms/java/yugabyte-jdbc.md
docs/content/stable/drivers-orms/orms/java/ysql-ebean.md
docs/content/v2.18/drivers-orms/java/_index.md
docs/content/v2.20/drivers-orms/include-drivers-orms-list.md
docs/content/v2.20/drivers-orms/java/_index.md
docs/content/v2.20/drivers-orms/java/yugabyte-jdbc.md

- JDBC Driver version update to `42.3.5-yb-8`

JDBC Driver version update

---

docs/layouts/shortcodes/icon/no.html
docs/layouts/shortcodes/icon/yes.html

In correct colors [View the issue](https://docs.yugabyte.com/stable/explore/ysql-language-features/indexes-constraints/#learn-more).
**YB colors**
- Green= #13A868
- Yellow = Correct color. No need for change
- Red =  #DA1515

[Docs] Correct icon colors

---

docs/content/preview/releases/techadvisories/_index.md
docs/content/preview/releases/techadvisories/ta-cl-23623.md

@netlify /preview/releases/techadvisories/ta-cl-23623/

[DOC-492] Added TA-CL-23623: Upgrade failure from v2.20 to v2024.1 series

---

docs/content/preview/yugabyte-cloud/release-notes.md

[doc][ybm] Format change log

---

docs/content/preview/releases/versioning.md

@netlify /preview/releases/versioning/#early-access-ea
Slack request - https://yugabyte.slack.com/archives/C07PH35K023/p1727810174328569

[docs] Added note to EA versioning similar to GA

---

docs/layouts/partials/hooks/body-end.html

Add [Anonymous user tracking with Fingerprint](https://docs.kapa.ai/integrations/website-widget/user-tracking#anonymous-user-tracking-with-fingerprint) offer by kapa widget.

[Docs] Enable User Tracking in kapa widget

---

docs/content/preview/secure/vulnerability-disclosure-policy.md

@netlify /preview/secure/vulnerability-disclosure-policy/#supply-chain-vulnerabilities-in-yugabytedb-postgres-query-layer-ysql

[docs] CVE updates

---

docs/content/preview/yugabyte-platform/security/authentication/oidc-authentication-aad.md
docs/content/stable/yugabyte-platform/security/authentication/oidc-authentication-aad.md
docs/content/v2.20/yugabyte-platform/security/authentication/oidc-authentication-aad.md

@netlify /stable/yugabyte-platform/security/authentication/oidc-authentication-aad/

[DOC-474] [2024.1.3] Added another parameter for the flag `ysql_hba_conf_csv`

---

docs/netlify.toml

- Added exceptions for Kapa metrics
- Madkudu
- Elastic search testing.
- Sorted the lines.

Add csp exceptions

---

docs/netlify.toml

- https://metrics.kapa.ai/ to `connect-src 'self'`

Adding csp exceptions

---

docs/content/preview/yugabyte-voyager/macos.md
docs/content/preview/yugabyte-voyager/release-notes.md

@netlify /preview/yugabyte-voyager/release-notes/

[docs] [voyager] added release notes for 1.8.3

---

docs/src/index.js

Clicking on the parent tab was hiding the inner tab content. This PR fixes that issue.
https://github.com/user-attachments/assets/9fadb0f2-cf79-4a43-8f14-6d55589eaf62

[Docs] Show inner tab content on changing parent tab

---

docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/releases/ybdb-releases/v2.20.md
docs/data/currentVersions.json

@netlify /preview/releases/ybdb-releases/v2.20/#v2.20.7.1

[docs] Release notes for 2.20.7.1

---

docs/content/preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/preview/yugabyte-platform/alerts-monitoring/prometheus-custom/_index.md
docs/content/preview/yugabyte-platform/alerts-monitoring/prometheus-custom/prometheus-scrape.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/stable/yugabyte-platform/alerts-monitoring/prometheus-custom/_index.md
docs/content/stable/yugabyte-platform/alerts-monitoring/prometheus-custom/prometheus-scrape.md
docs/content/v2.18/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
docs/content/v2.20/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md

HA certificate chain
DOC-424 - Grafana dashboard
@netlify /preview/yugabyte-platform/administer-yugabyte-platform/high-availability/

[doc][yba][DOC-466] HA certificate chain

---

docs/content/preview/architecture/transactions/read-restart-error.md
docs/content/preview/deploy/checklist.md
docs/content/preview/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/preview/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/preview/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/preview/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/preview/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/preview/deploy/manual-deployment/start-masters.md
docs/content/preview/deploy/manual-deployment/start-tservers.md
docs/content/preview/deploy/manual-deployment/system-config.md
docs/content/preview/explore/going-beyond-sql/connection-mgr-ysql.md
docs/content/preview/quick-start/linux.md
docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md
scripts/k8s_preflight.py

@netlify /preview/deploy/manual-deployment/system-config/

[#21963] YSQL: Configure clockbound agent

---

docs/content/preview/explore/observability/active-session-history.md

This PR updates the wait event type of the TServer wait event - Raft_ApplyingEdits

[DOC][ASH] Update wait event type of Raft_ApplyingEdits

---

docs/content/preview/yugabyte-cloud/cloud-admin/_index.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-client-shell.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-cloud-shell.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect/ycql.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect/ysql.md
docs/content/preview/yugabyte-cloud/cloud-monitor/_index.md
docs/content/preview/yugabyte-cloud/managed-automation/_index.md

Account status
DOC-278
@netlify /preview/yugabyte-cloud/cloud-monitor/

[doc][ybm] Account status

---

docs/content/preview/api/ysqlsh-meta-commands.md
docs/content/preview/api/ysqlsh-meta-examples.md
docs/content/preview/api/ysqlsh-pset-options.md

menu fix preview
@netlify /preview/api/ysqlsh/

[doc] menu fix preview

---

docs/content/preview/sample-data/_index.md
docs/content/preview/secure/_index.md
docs/content/preview/secure/audit-logging/_index.md
docs/content/preview/secure/authentication/_index.md
docs/content/preview/secure/authorization/_index.md
docs/content/preview/secure/enable-authentication/_index.md
docs/content/preview/secure/security-checklist.md
docs/content/preview/secure/tls-encryption/_index.md
docs/content/preview/secure/tls-encryption/client-to-server.md
docs/content/preview/secure/tls-encryption/connect-to-cluster.md
docs/content/preview/secure/tls-encryption/server-certificates.md
docs/content/preview/secure/tls-encryption/server-to-server.md
docs/content/preview/secure/tls-encryption/tls-authentication.md
docs/content/stable/sample-data/_index.md
docs/content/stable/secure/_index.md
docs/content/stable/secure/audit-logging/_index.md
docs/content/stable/secure/authentication/_index.md
docs/content/stable/secure/authorization/_index.md
docs/content/stable/secure/enable-authentication/_index.md
docs/content/stable/secure/security-checklist.md
docs/content/stable/secure/tls-encryption/_index.md
docs/content/stable/secure/tls-encryption/client-to-server.md
docs/content/stable/secure/tls-encryption/connect-to-cluster.md
docs/content/stable/secure/tls-encryption/server-certificates.md
docs/content/stable/secure/tls-encryption/server-to-server.md
docs/content/stable/secure/tls-encryption/tls-authentication.md

Format landing pages, icons
@netlify /preview/secure/

[doc] Format landing pages

---

docs/content/preview/faq/compatibility.md
docs/content/preview/faq/operations-faq.md
docs/content/preview/faq/smart-drivers-faq.md
docs/content/preview/faq/yugabyte-platform.md
docs/content/preview/faq/yugabytedb-managed-faq.md

@netlify /preview/faq/general/

[docs] Updates to FAQ pages with lead links

---

docs/content/preview/api/ysql/exprs/geo_partitioning_helper_functions/_index.md
docs/content/preview/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_is_local_table.md
docs/content/preview/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_cloud.md
docs/content/preview/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_region.md
docs/content/preview/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_zone.md
docs/content/stable/api/ysql/exprs/geo_partitioning_helper_functions/_index.md
docs/content/stable/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_is_local_table.md
docs/content/stable/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_cloud.md
docs/content/stable/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_region.md
docs/content/stable/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_zone.md
docs/content/v2.18/api/ysql/exprs/geo_partitioning_helper_functions/_index.md
docs/content/v2.18/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_is_local_table.md
docs/content/v2.18/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_cloud.md
docs/content/v2.18/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_region.md
docs/content/v2.18/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_zone.md
docs/content/v2.20/api/ysql/exprs/geo_partitioning_helper_functions/_index.md
docs/content/v2.20/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_is_local_table.md
docs/content/v2.20/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_cloud.md
docs/content/v2.20/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_region.md
docs/content/v2.20/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_zone.md

@netlify /preview/api/ysql/exprs/geo_partitioning_helper_functions/
will copy to stable after preview is reviewed.

[DOC-530] Removed note about some flag defaults

---

docs/assets/scss/_yb_topbar.scss
docs/layouts/partials/topbar.html

on safari the banner is causing some spacing issue.

[Docs] Fix banner spacing issue on safari

---

docs/netlify.toml

Temporarily re-enabling Clearbit integration.

[Docs] Add Clearbit in Content Security Policy header

---

docs/content/preview/yugabyte-platform/manage-deployments/edit-universe.md
docs/content/stable/yugabyte-platform/manage-deployments/edit-universe.md
docs/content/v2.20/yugabyte-platform/manage-deployments/edit-universe.md

Clarify smart resize
@netlify /preview/yugabyte-platform/manage-deployments/edit-universe/

[doc][yba] Clarify smart resize

---

docs/config/_default/menus.toml
docs/content/preview/api/_index.md
docs/content/preview/api/ycql/_index.md
docs/content/preview/api/ysql/_index.md
docs/content/preview/api/ysql/datatypes/_index.md
docs/content/preview/releases/_index.md
docs/content/preview/releases/yba-releases/_index.md
docs/content/preview/releases/ybdb-releases/_index.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-api.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-terraform.md
docs/content/preview/yugabyte-platform/anywhere-automation/anywhere-api.md
docs/content/preview/yugabyte-platform/anywhere-automation/anywhere-terraform.md
docs/content/stable/api/_index.md
docs/content/stable/api/ycql/_index.md
docs/content/stable/api/ysql/_index.md
docs/content/stable/api/ysql/datatypes/_index.md
docs/content/stable/yugabyte-platform/anywhere-automation/anywhere-api.md
docs/content/stable/yugabyte-platform/anywhere-automation/anywhere-terraform.md
docs/content/v2.14/api/_index.md
docs/content/v2.14/api/ycql/_index.md
docs/content/v2.14/api/ysql/_index.md
docs/content/v2.18/api/_index.md
docs/content/v2.18/api/ycql/_index.md
docs/content/v2.18/api/ysql/_index.md
docs/content/v2.20/api/_index.md
docs/content/v2.20/api/ycql/_index.md
docs/content/v2.20/api/ysql/_index.md
docs/content/v2.20/api/ysql/datatypes/_index.md

clarify jsonb
@netlify /preview/api/ysql/datatypes/

[DOC-540] clarify jsonb

---

docs/content/preview/reference/configuration/yugabyted.md
docs/content/stable/reference/configuration/yugabyted.md
docs/content/v2.14/reference/configuration/yugabyted.md
docs/content/v2.18/reference/configuration/yugabyted.md
docs/content/v2.20/reference/configuration/yugabyted.md

Context for yugabyted config flag
#18677
@netlify /preview/reference/configuration/yugabyted/

[doc][yugabyted] Context for config flag

---

docs/content/preview/yugabyte-platform/manage-deployments/edit-universe.md
docs/content/v2024.2/yugabyte-platform/manage-deployments/edit-universe.md

Description
--
List additional fields that can be modified in EDIT mode

[doc-523][yba] List additional fields that can be modified in EDIT mode

---

docs/content/preview/contribute/docs/docs-build.md

Update node version for building docs

[doc] Update node version

---

docs/content/preview/yugabyte-voyager/known-issues/postgresql.md

@netlify /preview/yugabyte-voyager/known-issues/postgresql/#unsupported-query-construct-xml-functions

[docs] Added PG known issues for voyager

---

docs/content/v2024.2/explore/ysql-language-features/pg-extensions/_index.md
docs/content/v2024.2/explore/ysql-language-features/pg-extensions/extension-pgcron.md
docs/content/v2024.2/explore/ysql-language-features/pg-extensions/extension-pgpartman.md

@netlify /v2024.2/explore/ysql-language-features/pg-extensions/extension-pgpartman/
To do - Add limitations

[DOC-543] [2024.2] [EA] pg_partman extension

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/azure.md
docs/content/v2024.2/yugabyte-platform/configure-yugabyte-platform/azure.md

Edit Azure provider regions
@netlify /v2024.2/yugabyte-platform/configure-yugabyte-platform/azure

[doc][yba][2024.2] DOC-509 Edit Azure provider regions

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/migrate-replicated.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/migrate-replicated.md
docs/content/v2.20/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/v2.20/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/v2024.2/yugabyte-platform/install-yugabyte-platform/migrate-replicated.md

[doc][yba] Small fixes

---

docs/content/preview/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/preview/releases/yba-releases/v2024.1.md
docs/content/preview/releases/ybdb-releases/v2024.1.md
docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/stable/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/stable/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/v2024.2/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/v2024.2/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/v2024.2/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md

k8s readiness probes
DOC_365
@netlify /v2024.2/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes/#configure-helm-overrides

[doc][yba][2024.2][DOC-365] k8s readiness probes

---

docs/content/preview/integrations/apache-spark/scala-ysql.md

fix typo
@netlify /preview/integrations/apache-spark/scala-ysql/

[doc][integration] fix typo

---

docs/content/preview/yugabyte-cloud/release-notes.md

[doc][ybm] Aeon changes nov 2024

---

architecture/design/vector-index.md

Doc: Update vector-index.md

---

docs/content/v2.20/reference/configuration/operating-systems.md

Slack request: https://yugabyte.slack.com/archives/C07RMJ25HAQ/p1731633531497649?thread_ts=1730841765.679559&cid=C07RMJ25HAQ
@netlify /v2.20/reference/configuration/operating-systems/

[docs] Updated 2.20 OS compatibility page

---

docs/content/preview/yugabyte-platform/manage-deployments/remove-nodes.md
docs/content/v2024.2/yugabyte-platform/manage-deployments/remove-nodes.md

Auto master failover
@netlify /v2024.2/yugabyte-platform/manage-deployments/remove-nodes/

[doc][yba][DOC-521][2024.2] Auto master failover

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/on-premises-script.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/on-premises-script.md
docs/content/v2.18/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-script.md
docs/content/v2.20/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-script.md

@netlify /preview/yugabyte-platform/configure-yugabyte-platform/on-premises-script/#manually-provision-nodes-using-the-script

[DOC-558] Remove port 9000 from the description of `--yba_url` 

---

docs/content/v2024.2/reference/configuration/yb-tserver.md

@netlify /v2024.2/reference/configuration/yb-tserver/#yb-skip-redundant-update-ops

[DOC-339] [2024.2] Added YSQL parameter - yb_skip_redundant_update_ops

---

docs/content/preview/drivers-orms/csharp/postgres-npgsql-reference.md
docs/content/preview/drivers-orms/csharp/postgres-npgsql.md
docs/content/preview/drivers-orms/csharp/yb-npgsql-reference.md
docs/content/preview/drivers-orms/java/ycql-ssl.md
docs/content/preview/drivers-orms/nodejs/postgres-node-driver.md
docs/content/preview/drivers-orms/nodejs/yugabyte-node-driver.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/managed-endpoint-aws.md
docs/content/preview/yugabyte-cloud/cloud-clusters/aeon-cdc.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-applications.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect/ycql.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect/ysql.md
docs/content/preview/yugabyte-cloud/cloud-troubleshoot.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-examples/managed-cli-example-create.md

Change ybdb.io to yugabyte.cloud hostnames
@netlify /preview/yugabyte-cloud/cloud-basics/cloud-vpcs/managed-endpoint-aws/

[doc][ybm] Change ybdb.io to yugabyte.cloud

---

docs/content/preview/yugabyte-platform/manage-deployments/xcluster-replication/bidirectional-replication.md
docs/content/v2024.2/yugabyte-platform/manage-deployments/xcluster-replication/bidirectional-replication.md

This diff adds minor updates to the bidirectional replication doc page to reflect latest code changes.

[DOC-510][yba][2024.2] Improve YBA support for bidirectional xcluster replication

---

docs/content/v2024.2/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md
docs/content/v2024.2/yugabyte-platform/anywhere-automation/_index.md
docs/content/v2024.2/yugabyte-platform/anywhere-automation/yb-kubernetes-operator.md
docs/content/v2024.2/yugabyte-platform/back-up-restore-universes/disaster-recovery/_index.md
docs/content/v2024.2/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/v2024.2/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/v2024.2/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md

IDEAS modified in this PR (EA tags removed):
- [IDEA-27](https://yugabyte.atlassian.net/jira/polaris/projects/IDEA/ideas/view/3573079?selectedIssue=IDEA-27) - Xcluster DR v1.0
- [IDEA-660](https://yugabyte.atlassian.net/jira/polaris/projects/IDEA/ideas/view/3573079?selectedIssue=IDEA-660) - K8S core count & memory config
- [IDEA-1015](https://yugabyte.atlassian.net/jira/polaris/projects/IDEA/ideas/view/3573079?selectedIssue=IDEA-1015) - Map OIDC groups to YBA built-in roles
GA already:
- [IDEA-1238](https://yugabyte.atlassian.net/jira/polaris/projects/IDEA/ideas/view/3573079?selectedIssue=IDEA-1238) - Backup sets copyable
The remaining IDEAS don't have docs (they either didn’t require docs or never got documented), so no changes needed:
- …

[DOC-519][2024.2][YBA] Removed EA tags for features transitioning to GA

---

docs/content/preview/contribute/docs/widgets-and-shortcodes.md
docs/layouts/shortcodes/table.html

- Fixes table shortcut to correctly replace pipe symbol

Fix table shortcut

---

docs/content/v2024.2/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md

ARM architecture for k8s
@netlify /v2024.2/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes/

[DOC-549][yba][2024.2] ARM architecture for k8s

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/v2024.2/yugabyte-platform/install-yugabyte-platform/install-software/installer.md

YBA Installer no root
@netlify /v2024.2/yugabyte-platform/install-yugabyte-platform/install-software/installer/

[DOC-511][yba][2024.2] YBA Installer no root

---

docs/content/v2024.2/explore/colocation.md

@netlify /v2024.2/explore/colocation/#colocated-tables-with-tablespaces
Note to self - Move the backup section to back up and restore after confirmation.

[DOC-539] [2024.2] [EA] Added colocated tables with tablespaces

---

docs/content/v2024.2/yugabyte-platform/configure-yugabyte-platform/on-premises-nodes.md
docs/content/v2024.2/yugabyte-platform/configure-yugabyte-platform/on-premises.md
docs/content/v2024.2/yugabyte-platform/prepare/server-nodes-hardware.md
docs/content/v2024.2/yugabyte-platform/prepare/server-nodes-software/software-on-prem-assist.md
docs/content/v2024.2/yugabyte-platform/prepare/server-nodes-software/software-on-prem-auto.md
docs/content/v2024.2/yugabyte-platform/prepare/server-nodes-software/software-on-prem-manual.md
docs/content/v2024.2/yugabyte-platform/prepare/server-nodes-software/software-on-prem-na.md
docs/content/v2024.2/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md

Node agent provisioning
@netlify /v2024.2/yugabyte-platform/prepare/server-nodes-software/software-on-prem/

[DOC-504][yba][2024.2] Node agent provisioning

---

docs/content/preview/yugabyte-platform/alerts-monitoring/alert-policy-templates.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/_index.md
docs/content/v2024.2/yugabyte-platform/alerts-monitoring/alert-policy-templates.md
docs/content/v2024.2/yugabyte-platform/prepare/server-nodes-software/_index.md

Time sync support
@netlify /v2024.2/yugabyte-platform/prepare/server-nodes-software/

[DOC-520][yba][2024.2] Time sync support

---

docs/content/v2024.2/explore/going-beyond-sql/connection-mgr-ysql.md

YSQL Connection Manager update
@netlify /v2024.2/explore/going-beyond-sql/connection-mgr-ysql/#configuration

[DOC-565][2024.2] YSQL Connection Manager update

---

docs/content/preview/yugabyte-cloud/cloud-monitor/managed-integrations.md
docs/content/preview/yugabyte-cloud/release-notes.md

Change log for Victoriametrics GA

[doc][ybm] Change log for Victoriametrics ga

---

docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/releases/ybdb-releases/v2.20.md
docs/data/currentVersions.json

Deploy preview - https://deploy-preview-25079--infallible-bardeen-164bc9.netlify.app/preview/releases/ybdb-releases/v2.20/#v2.20.8.0

[docs] Release notes for 2.20.8.0-b53

---

docs/content/preview/contribute/docs/docs-build.md
docs/content/preview/contribute/docs/macos.md
docs/content/preview/contribute/docs/ubuntu.md

[DOC-562] Update build the docs page with instructions for Ubuntu and a specific hugo version.

---

docs/content/preview/yugabyte-cloud/_index.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-topology.md
docs/content/preview/yugabyte-cloud/cloud-clusters/_index.md
docs/content/preview/yugabyte-cloud/cloud-monitor/_index.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-integration.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-metrics-exporter.md

Add deprecation notices to CLI Metrics Export commands
CLOUDGA-24948
@netlify /preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-metrics-exporter/

[doc][ybm][cli] Metrics export deprecation

---

docs/data/currentVersions.json

Update 2024.2 release date
@netlify /preview/releases/ybdb-releases/

[doc] Update 2024.2 release date

---

docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-assist.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-auto.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-legacy.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-manual.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-on-prem-assist.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-on-prem-auto.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-on-prem-legacy.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-on-prem-manual.md
docs/content/v2.14/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/software-on-prem-assist.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/software-on-prem-auto.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/software-on-prem-legacy.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/software-on-prem-manual.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md

Backport on-prem provisioning structure
@netlify /v2024.1/yugabyte-platform/prepare/server-nodes-software/software-on-prem/

[doc][yba] Backport on-prem structure

---

docs/content/preview/yugabyte-voyager/github.md
docs/content/preview/yugabyte-voyager/migrate/assess-migration.md
docs/content/preview/yugabyte-voyager/migrate/live-fall-back.md
docs/content/preview/yugabyte-voyager/migrate/live-fall-forward.md
docs/content/preview/yugabyte-voyager/migrate/live-migrate.md
docs/content/preview/yugabyte-voyager/migrate/postgresql.md
docs/content/preview/yugabyte-voyager/release-notes.md

@netlify /preview/yugabyte-voyager/release-notes/

[DOC-579] Docs for voyager v1.8.7

---

docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/releases/ybdb-releases/v2.20.md

v2.20 release notes - remove invalid items
@netlify /preview/releases/ybdb-releases/v2.20/#bug-fixes

[doc] v2.20 rn - remove invalid items

---

docs/content/stable/api/ysql/syntax_resources/ysql_grammar.ebnf
docs/content/stable/api/ysql/the-sql-language/statements/ddl_alter_sequence.md
docs/content/stable/api/ysql/the-sql-language/statements/ddl_alter_table.md
docs/content/stable/api/ysql/the-sql-language/statements/ddl_create_sequence.md
docs/content/stable/api/ysql/the-sql-language/statements/ddl_create_table.md

Changes for the `/stable` folder.
See **preview** PR for details: https://github.com/yugabyte/yugabyte-db/pull/25117

[#DOC-528] YSQL, docs: Add documentation for ALTER new features

---

docs/content/preview/releases/techadvisories/_index.md
docs/content/preview/releases/techadvisories/ta-24992.md

@netlify  /preview/releases/techadvisories/ta-24992/
Preview Link: https://deploy-preview-25290--infallible-bardeen-164bc9.netlify.app/preview/releases/techadvisories/ta-24992/

 [DOC-581][TA] Add Tech advisory TA-24992 

---

docs/content/preview/deploy/kubernetes/clients.md
docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/releases/ybdb-releases/v2.20.md
docs/content/stable/deploy/kubernetes/clients.md
docs/content/v2.14/deploy/kubernetes/clients.md
docs/content/v2.18/deploy/kubernetes/clients.md
docs/content/v2.20/deploy/kubernetes/clients.md
docs/content/v2024.1/deploy/kubernetes/clients.md
docs/data/currentVersions.json

Release Notes v2.20.8.1-b2
@netlify /preview/releases/ybdb-releases/v2.20/

[doc] Release Notes v2.20.8.1-b2

---

docs/content/preview/reference/configuration/operating-systems.md
docs/content/stable/reference/configuration/operating-systems.md
docs/content/v2.20/reference/configuration/operating-systems.md
docs/content/v2024.1/reference/configuration/operating-systems.md

Rocky Linux support in v2.20.8
DOC-545
@netlify /v2.20/reference/configuration/operating-systems/

[doc] Rocky Linux support in v2.20.8

---

docs/content/preview/yugabyte-cloud/cloud-clusters/aeon-cdc.md

Add TP badge to Aeon CDC
@netlify /preview/yugabyte-cloud/cloud-clusters/aeon-cdc/

[doc][ybm] Add TP badge to CDC

---

docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/releases/ybdb-releases/v2.20.md

@netlify /preview/releases/ybdb-releases/v2.20/#v2.20.8.0

[docs] Update release notes for 2.20.8.0-b53

---

docs/config/_default/menus.toml
docs/config/_default/params.toml
docs/content/preview/api/ysql/user-defined-subprograms-and-anon-blocks/commit-in-user-defined-subprograms.md
docs/content/preview/get-started-guide.md
docs/content/preview/tutorials/build-and-learn/chapter5-going-cloud-native.md
docs/content/preview/yugabyte-cloud/_index.md
docs/content/preview/yugabyte-platform/_index.md
docs/content/stable/api/ysql/user-defined-subprograms-and-anon-blocks/commit-in-user-defined-subprograms.md
docs/content/stable/get-started-guide.md
docs/content/stable/yugabyte-platform/_index.md
docs/content/v2.18/api/ysql/user-defined-subprograms-and-anon-blocks/commit-in-user-defined-subprograms.md
docs/content/v2.18/yugabyte-platform/_index.md
docs/content/v2.20/api/ysql/user-defined-subprograms-and-anon-blocks/commit-in-user-defined-subprograms.md
docs/content/v2.20/yugabyte-platform/_index.md
docs/content/v2024.1/api/ysql/user-defined-subprograms-and-anon-blocks/commit-in-user-defined-subprograms.md
docs/content/v2024.1/get-started-guide.md
docs/content/v2024.1/yugabyte-platform/_index.md

https://communityinviter.com/apps/yugabyte-db/register is replaced with [this](https://inviter.co/yugabytedb) new one.
DOC-589

[Docs] Update Community Inviter link

---

docs/content/preview/benchmark/sysbench-ysql.md
docs/content/stable/benchmark/sysbench-ysql.md
docs/content/v2.14/benchmark/sysbench-ysql.md
docs/content/v2.18/benchmark/sysbench-ysql.md
docs/content/v2.20/benchmark/sysbench-ysql.md
docs/content/v2024.1/benchmark/sysbench-ysql.md

@netlify /preview/benchmark/sysbench-ysql/

 [DOC-594][ysql] add note to sysbench doc

---

docs/content/preview/develop/change-data-capture/using-logical-replication/_index.md
docs/content/preview/develop/change-data-capture/using-logical-replication/monitor.md
docs/content/preview/develop/change-data-capture/using-logical-replication/yugabytedb-connector.md
docs/content/preview/develop/change-data-capture/using-yugabytedb-grpc-replication/_index.md
docs/content/preview/develop/change-data-capture/using-yugabytedb-grpc-replication/cdc-get-started.md
docs/content/preview/develop/change-data-capture/using-yugabytedb-grpc-replication/cdc-monitor.md
docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/develop/change-data-capture/using-logical-replication/_index.md
docs/content/stable/develop/change-data-capture/using-logical-replication/monitor.md
docs/content/stable/develop/change-data-capture/using-logical-replication/yugabytedb-connector.md
docs/content/stable/develop/change-data-capture/using-yugabytedb-grpc-replication/_index.md
docs/content/stable/develop/change-data-capture/using-yugabytedb-grpc-replication/cdc-get-started.md
docs/content/stable/develop/change-data-capture/using-yugabytedb-grpc-replication/cdc-monitor.md
docs/content/stable/reference/configuration/yb-master.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/v2024.1/develop/change-data-capture/using-logical-replication/_index.md

CDC docs updates from #25372
@netlify /preview/develop/change-data-capture/

[doc] CDC docs updates

---

docs/content/preview/faq/yugabyte-platform.md

Update YBA node agent FAQ
DOC-573
@netlify /preview/faq/yugabyte-platform/

[doc][yba] Update YBA node agent FAQ

---

docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yb-master.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/v2024.1/reference/configuration/yb-master.md
docs/content/v2024.1/reference/configuration/yb-tserver.md

It was missing. I copied the text from yb-master page.

Add `allowed_preview_flags_csv` to yb-tserver configuration docs.

---

docs/content/preview/secure/vulnerability-disclosure-policy.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/preview/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-storage.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/stable/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-storage.md
docs/content/v2.20/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/v2.20/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-storage.md
docs/content/v2024.1/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/v2024.1/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-storage.md

Add details for S3-compatible storage
DOC-587
@netlify /preview/yugabyte-platform/back-up-restore-universes/configure-backup-storage/#amazon-s3

[doc][yba] S3-compatible storage

---

docs/content/preview/admin/yb-admin.md
docs/content/stable/admin/yb-admin.md
docs/content/v2.14/admin/yb-admin.md
docs/content/v2.18/admin/yb-admin.md
docs/content/v2.20/admin/yb-admin.md
docs/content/v2024.1/admin/yb-admin.md

Read replica delete and modify placement command fix
@netlify /preview/admin/yb-admin/#modify-read-replica-placement-info

[doc] Read replica placement command fix

---

docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-integration.md

Reverts yugabyte/yugabyte-db#25508

Revert "[DOC-598][doc][ybm][cli] Docs for GOOGLECLOUD integration"

---

docs/content/preview/releases/yba-releases/v2024.1.md
docs/content/preview/releases/ybdb-releases/v2024.1.md
docs/content/v2.20/yugabyte-platform/prepare/server-nodes-software/software-on-prem-auto.md
docs/content/v2024.1/yugabyte-platform/_index.md
docs/content/v2024.1/yugabyte-platform/administer-yugabyte-platform/back-up-restore-k8s.md
docs/content/v2024.1/yugabyte-platform/administer-yugabyte-platform/back-up-restore-yp.md
docs/content/v2024.1/yugabyte-platform/configure-yugabyte-platform/_index.md
docs/content/v2024.1/yugabyte-platform/configure-yugabyte-platform/on-premises-nodes.md
docs/content/v2024.1/yugabyte-platform/configure-yugabyte-platform/on-premises-provider.md
docs/content/v2024.1/yugabyte-platform/configure-yugabyte-platform/on-premises-script.md
docs/content/v2024.1/yugabyte-platform/configure-yugabyte-platform/on-premises.md
docs/content/v2024.1/yugabyte-platform/create-deployments/create-universe-multi-cloud.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/software-on-prem-assist.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/software-on-prem-auto.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/software-on-prem-legacy.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/software-on-prem-manual.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md
docs/data/currentVersions.json

@netlify /preview/releases/ybdb-releases/v2024.1/#v2024.1.4.0
DOC-572

[docs] Release notes for 2024.1.4.0-b108

---

docs/content/preview/releases/techadvisories/_index.md
docs/content/preview/releases/techadvisories/ta-25193.md

@netlify /preview/releases/techadvisories/ta-25193/

[DOC-599][TA] Add Tech advisory TA-25193

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/v2.20/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/v2024.1/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md

Also want to add this image into docs to show where container URL can be found.

Improving Azure backup config docs

---

docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/_index.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-db-query-logging.md

@netlify /preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-db-query-logging/
Preview URL : https://deploy-preview-25213--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-db-query-logging/

[DOC-580][CLOUDGA-24950][ybm][cli] DB Query logging cli commands

---

docs/content/preview/releases/ybdb-releases/v2024.1.md

@netlify /preview/releases/ybdb-releases/v2024.1/#v2024.1.4.0

update v2024.1.4.0 release notes

---

docs/content/preview/yugabyte-platform/alerts-monitoring/alert-policy-templates.md
docs/content/preview/yugabyte-platform/alerts-monitoring/anywhere-metrics.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/_index.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-tables.md
docs/content/preview/yugabyte-platform/manage-deployments/xcluster-replication/xcluster-replication-setup.md
docs/content/preview/yugabyte-platform/troubleshoot/universe-issues.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md

Copy YBA changes to preview
@netlify /preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup/

[doc][yba][2.25] Copy YBA changes to preview

---

docs/content/stable/manage/backup-restore/instant-db-cloning.md

YCQL keyspace cloning is TP in 2024.2
@netlify /stable/manage/backup-restore/instant-db-cloning/#clone-a-ycql-keyspace

[doc] YCQL cloning TP

---

docs/content/preview/yugabyte-voyager/known-issues/postgresql.md
docs/content/preview/yugabyte-voyager/migrate/live-fall-back.md
docs/content/preview/yugabyte-voyager/migrate/live-fall-forward.md

@netlify /preview/yugabyte-voyager/known-issues/postgresql/

[DOC-608][Doc] update schema review workaround PG section

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/on-premises-nodes.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/on-premises-provider.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/on-premises-script.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/on-premises.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-assist.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-auto.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-legacy.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem-manual.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/on-premises-script.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/on-premises.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md
docs/content/v2.20/yugabyte-platform/configure-yugabyte-platform/on-premises-script.md
docs/content/v2.20/yugabyte-platform/configure-yugabyte-platform/on-premises.md
docs/content/v2024.1/yugabyte-platform/configure-yugabyte-platform/on-premises-script.md
docs/content/v2024.1/yugabyte-platform/configure-yugabyte-platform/on-premises.md

Add auto provisioning for v2.25
@netlify /preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem/

[doc][yba][2.25] Add auto provisioning

---

docs/content/preview/develop/learn/transactions/transactions-global-apps.md
docs/content/preview/explore/going-beyond-sql/follower-reads-ysql.md
docs/content/preview/explore/ysql-language-features/pg-extensions/_index.md
docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgpartman.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/explore/going-beyond-sql/follower-reads-ysql.md

Copy LRT 2024.2 changes to preview
@netlify /preview/explore/going-beyond-sql/follower-reads-ysql/

[doc][2.25] Copy LRT 2024.2 changes to preview

---

docs/content/preview/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac.md
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/ldap-authentication.md
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md
docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/preview/yugabyte-platform/manage-deployments/edit-config-flags.md
docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software-install.md
docs/content/stable/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md

[doc][yba][2.25] Copy more changes to preview

---

docs/content/preview/architecture/docdb/packed-rows.md
docs/content/stable/architecture/docdb/packed-rows.md
docs/content/v2024.1/architecture/docdb/packed-rows.md

Remove the limitations in packed-rows.md

Remove the limitations in packed-rows.md

---

docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/explore/ysql-language-features/pg-extensions/extension-pgcron.md
docs/content/stable/reference/configuration/yb-master.md
docs/content/stable/reference/configuration/yb-tserver.md

Add pg_cron flags
@netlify /stable/explore/ysql-language-features/pg-extensions/extension-pgcron/#set-up-pg-cron

[doc][2.25] Add pg_cron flags

---

docs/config/_default/menus.toml
docs/config/_default/params.toml
docs/content/preview/releases/yba-releases/_index.md
docs/content/preview/releases/yba-releases/v2.23.md
docs/content/preview/releases/yba-releases/v2.25.md
docs/content/preview/releases/ybdb-releases/_index.md
docs/content/preview/releases/ybdb-releases/v2.23.md
docs/content/preview/releases/ybdb-releases/v2.25.md
docs/data/currentVersions.json

https://github.com/netlify /preview/releases/yba-releases/v2.25/

[docs] Release notes for 2.25.0.0-b489

---

docs/content/preview/releases/yugabyte-clients.md

YB Client download
@netlify /preview/releases/yugabyte-clients/

[doc] Bump client download version

---

docs/content/preview/api/ysql/the-sql-language/statements/perf_explain.md
docs/content/preview/explore/observability/active-session-history.md
docs/content/stable/api/ysql/syntax_resources/ysql_grammar.ebnf
docs/content/stable/api/ysql/the-sql-language/statements/perf_explain.md
docs/content/stable/explore/observability/active-session-history.md
docs/content/v2.20/api/ysql/syntax_resources/ysql_grammar.ebnf
docs/content/v2.20/api/ysql/the-sql-language/statements/perf_explain.md
docs/content/v2024.1/api/ysql/syntax_resources/ysql_grammar.ebnf
docs/content/v2024.1/api/ysql/the-sql-language/statements/perf_explain.md

ASH corrections from review
@netlify /preview/explore/observability/active-session-history

[doc] ASH corrections

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md
docs/content/v2.20/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md
docs/content/v2024.1/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md

DR example correction
@netlify /preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup/#metrics

[doc] DR example correction

---

docs/content/preview/reference/configuration/yb-master.md
docs/content/stable/reference/configuration/yb-master.md
docs/content/v2.14/reference/configuration/yb-master.md
docs/content/v2.18/reference/configuration/yb-master.md
docs/content/v2.20/reference/configuration/yb-master.md
docs/content/v2024.1/reference/configuration/yb-master.md

Add caveat for cdc flag
DOC-616
@netlify /preview/reference/configuration/yb-master/#enable-tablet-split-of-cdcsdk-streamed-tables

[doc][cdc] Add caveat for cdc flag

---

docs/content/preview/deploy/multi-dc/async-replication/_index.md
docs/content/preview/deploy/multi-dc/async-replication/async-deployment.md
docs/content/preview/deploy/multi-dc/async-replication/async-replication-transactional.md
docs/content/stable/deploy/multi-dc/async-replication/_index.md
docs/content/stable/deploy/multi-dc/async-replication/async-deployment.md
docs/content/stable/deploy/multi-dc/async-replication/async-replication-transactional.md
docs/content/v2.20/deploy/multi-dc/async-replication/_index.md
docs/content/v2.20/deploy/multi-dc/async-replication/async-deployment.md
docs/content/v2.20/deploy/multi-dc/async-replication/async-replication-transactional.md
docs/content/v2024.1/deploy/multi-dc/async-replication/_index.md
docs/content/v2024.1/deploy/multi-dc/async-replication/async-deployment.md
docs/content/v2024.1/deploy/multi-dc/async-replication/async-replication-transactional.md

Feature implemented as part of https://github.com/yugabyte/yugabyte-db/issues/22244

Doc: Update doc about xCluster bidirectional index

---

docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/v2024.1/reference/configuration/yb-tserver.md

DDL atomicity flags remove TP tag
DOC-617
@netlify /preview/reference/configuration/yb-tserver/#ddl-atomicity-flags

[doc] DDL atomicity flags remove TP tag

---

docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/preview/releases/ybdb-releases/v2024.2.md
docs/content/stable/reference/configuration/yb-master.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/v2024.1/reference/configuration/yb-master.md

@netlify /preview/releases/ybdb-releases/v2024.2/#highlights

[DOC-622] 2024.2.0 Release Highlights & Docs updates

---

docs/content/preview/faq/operations-faq.md

- Calculate YSQL db size function from https://yugabytedb.tips/display-ysql-database-size/

[doc][faq] db size

---

docs/content/preview/yugabyte-cloud/managed-security/managed-authentication/_index.md
docs/content/preview/yugabyte-cloud/managed-security/managed-authentication/federated-custom.md
docs/content/preview/yugabyte-cloud/managed-security/managed-authentication/federated-entra.md
docs/content/preview/yugabyte-cloud/managed-security/managed-authentication/federated-jump.md
docs/content/preview/yugabyte-cloud/managed-security/managed-authentication/federated-okta.md
docs/content/preview/yugabyte-cloud/managed-security/managed-authentication/federated-ping.md

Custom IdP
CLOUDGA-25421
@netlify /preview/yugabyte-cloud/managed-security/managed-authentication/federated-custom/

[doc][ybm] Custom IdP

---

docs/assets/scss/_footer.scss
docs/netlify.toml

Content Security Policy for Intercom: https://www.intercom.com/help/en/articles/3894-using-intercom-with-content-security-policy

[Docs] Add CSP for intercom messenger

---

docs/content/preview/yugabyte-voyager/known-issues/postgresql.md
docs/content/preview/yugabyte-voyager/release-notes.md

@netlify /preview/yugabyte-voyager/release-notes/#v1-8-10-january-28-2025

[DOC-626] Voyager 1.8.10 docs changes

---

docs/content/preview/secure/authentication/host-based-authentication.md
docs/content/stable/secure/authentication/host-based-authentication.md
docs/content/v2.14/secure/authentication/host-based-authentication.md
docs/content/v2.18/secure/authentication/host-based-authentication.md
docs/content/v2.20/secure/authentication/host-based-authentication.md
docs/content/v2024.1/secure/authentication/host-based-authentication.md

Fix host auth example
DOC-548
@netlify /preview/secure/authentication/host-based-authentication/#single-host-entry

[doc] Fix host auth example

---

docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/releases/ybdb-releases/v2.20.md

[doc] 2.20.9.0-b47 release notes

---

docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md
docs/content/stable/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md
docs/content/v2.14/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md
docs/content/v2.18/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md
docs/content/v2.20/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md
docs/content/v2024.1/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md

@netlify /preview/yugabyte-platform/upgrade/upgrade-yp-kubernetes/#upgrade-using-helm
DOC-620

[DOC-620]Update command on upgrade using helm page

---

docs/content/preview/integrations/flyway.md

@netlify /preview/integrations/flyway/

[DOC-621] Fix broken link on Flyway integration page

---

docs/content/preview/develop/best-practices-ycql.md
docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/develop/best-practices-ycql.md
docs/content/stable/reference/configuration/yb-master.md
docs/content/stable/reference/configuration/yb-tserver.md

Details on memory default flag
@netlify /preview/develop/best-practices-ycql/#memory-and-tablet-limits

[doc] Memory default details

---

docs/content/preview/manage/upgrade-deployment.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/manage/upgrade-deployment.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/v2024.1/manage/upgrade-deployment.md

Fix maturity tags for rollback

[doc] Fix tags for rollback

---

docs/content/preview/explore/colocation.md
docs/content/stable/explore/colocation.md

Remove colocated tables and tablespace limitation that no longer applies
@netlify /stable/explore/colocation/#limitations-and-considerations

[doc] Remove colocated tables and tablespace limitation

---

docs/content/preview/develop/pg15-features.md

DOC-630
@netlify /preview/develop/pg15-features/

[doc] Update PG15 page

---

docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-api-key.md

@netlify /preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-api-key/

[DOC-625][docs][cli][ybm] CLI documentation for additional functionality in API keys

---

docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-api-key.md

Reverts yugabyte/yugabyte-db#25779

Revert "[DOC-625][docs][cli][ybm] CLI documentation for additional functionality in API keys"

---

docs/config/_default/menus.toml
docs/content/preview/tutorials/quick-start-yugabytedb-managed/_index.md
docs/content/preview/tutorials/quick-start/_index.md
docs/content/preview/tutorials/quick-start/docker.md
docs/content/preview/tutorials/quick-start/kubernetes.md
docs/content/preview/tutorials/quick-start/linux.md
docs/content/preview/tutorials/quick-start/macos.md
docs/content/preview/yugabyte-cloud/cloud-monitor/_index.md
docs/content/preview/yugabyte-cloud/cloud-quickstart/_index.md
docs/content/preview/yugabyte-cloud/release-notes.md
docs/content/preview/yugabyte-platform/alerts-monitoring/_index.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/_index.md
docs/content/stable/yugabyte-platform/alerts-monitoring/_index.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/_index.md
docs/content/v2.20/yugabyte-platform/alerts-monitoring/_index.md
docs/content/v2.20/yugabyte-platform/configure-yugabyte-platform/_index.md
docs/content/v2024.1/yugabyte-platform/alerts-monitoring/_index.md
docs/content/v2024.1/yugabyte-platform/configure-yugabyte-platform/_index.md

Left nav menu separator changes

[doc] menu separator changes

---

docs/content/preview/api/ysql/the-sql-language/statements/ddl_create_index.md
docs/content/v2.20/api/ysql/the-sql-language/statements/ddl_create_index.md
docs/content/v2024.1/api/ysql/the-sql-language/statements/ddl_create_index.md

https://github.com/netlify /preview/api/ysql/the-sql-language/statements/ddl_create_index/#split-at-values

[doc] fix ddl statements

---

docs/content/preview/manage/upgrade-deployment.md
docs/content/preview/reference/configuration/yugabyted.md
docs/content/preview/releases/techadvisories/ta-reol-24.md
docs/content/preview/yugabyte-voyager/reference/schema-migration/import-schema.md
docs/content/preview/yugabyte-voyager/release-notes.md
docs/content/v2.20/explore/ysql-language-features/going-beyond-sql/follower-reads-ysql.md
docs/content/v2.20/reference/drivers/go/yb-pgx-reference.md
docs/content/v2.20/reference/drivers/java/yugabyte-jdbc-reference.md
docs/content/v2.20/reference/drivers/rust/rust-postgres-reference.md
docs/content/v2.20/secure/enable-authentication/yedis.md

[doc] Link fixes

---

docs/content/preview/admin/ysql-dump.md
docs/content/preview/api/ycql/ddl_grant_permission.md
docs/content/preview/api/ycql/ddl_grant_role.md
docs/content/preview/api/ycql/ddl_revoke_permission.md
docs/content/preview/api/ycql/ddl_revoke_role.md
docs/content/preview/api/ycql/expr_fcall.md
docs/content/preview/api/ycql/expr_ocall.md
docs/content/preview/api/ycql/expr_simple.md
docs/content/preview/api/ycql/expr_subscript.md
docs/content/preview/architecture/system-catalog.md
docs/content/stable/admin/ysql-dump.md
docs/content/stable/api/ycql/expr_fcall.md
docs/content/stable/api/ycql/expr_subscript.md
docs/content/stable/architecture/system-catalog.md
docs/content/v2.14/api/ycql/expr_fcall.md
docs/content/v2.14/api/ycql/expr_subscript.md
docs/content/v2.18/api/ycql/expr_fcall.md
docs/content/v2.18/api/ycql/expr_subscript.md
docs/content/v2.20/api/ycql/expr_fcall.md
docs/content/v2.20/api/ycql/expr_subscript.md
docs/content/v2024.1/api/ycql/expr_fcall.md
docs/content/v2024.1/api/ycql/expr_subscript.md
docs/content/v2024.1/architecture/system-catalog.md
docs/netlify.toml

[doc] Adjust some redirects

---

docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-examples/managed-cli-example-create.md
docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-cluster.md

@netlify /preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-examples/managed-cli-example-create/#create-a-single-region-cluster
DOC-632

[CLOUDGA-25784][doc][ybm][cli]update YBM CLI docs examples to remove root node info

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/back-up-universe-data.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/restore-universe-data.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/schedule-data-backups.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/back-up-universe-data.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/restore-universe-data.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/schedule-data-backups.md

Scheduled backups new wizard with support for PITR
DOC-561
@netlify /preview/yugabyte-platform/back-up-restore-universes/schedule-data-backups/

[doc][yba] Scheduled backups new UI/PITR

---

docs/content/preview/yugabyte-voyager/airgapped.md
docs/content/preview/yugabyte-voyager/release-notes.md

@netlify /preview/yugabyte-voyager/install-yb-voyager/#airgapped

[DOC-639] Voyager 1.8.11 changes for Feb 11

---

docs/content/preview/yugabyte-voyager/release-notes.md

@netlify /preview/yugabyte-voyager/release-notes/

[doc]Voyager 1.8.11 release notes changes.

---

docs/content/preview/tutorials/build-apps/_index.md
docs/content/v2.14/drivers-orms/nodejs/prisma.md
docs/content/v2.14/quick-start/build-apps/nodejs/ysql-prisma.md
docs/content/v2.14/reference/drivers/ysql-client-drivers.md

Fix links/alias
@netlify /preview/yugabyte-cloud/cloud-quickstart/cloud-build-apps/

[doc][ybm] Fix links/alias

---

docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md
docs/content/v2.20/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md

Fix to flag
@netlify /preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem/

[doc][yba] Fix to flag

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/preview/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-storage.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/stable/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-storage.md
docs/content/v2.20/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/v2.20/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-storage.md
docs/content/v2024.1/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/v2024.1/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-storage.md

IAM S3 permissions for backup storage on AWS
DOC-567
@netlify /preview/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-storage/

[doc][yba] IAM S3 permissions

---

docs/content/preview/deploy/manual-deployment/start-masters.md
docs/content/preview/deploy/manual-deployment/start-tservers.md
docs/content/preview/deploy/manual-deployment/system-config.md
docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/preview/releases/ybdb-releases/v2024.2.md
docs/content/preview/yugabyte-voyager/install-yb-voyager.md
docs/content/preview/yugabyte-voyager/macos.md
docs/content/stable/deploy/manual-deployment/start-masters.md
docs/content/stable/deploy/manual-deployment/start-tservers.md
docs/content/stable/deploy/manual-deployment/system-config.md
docs/content/stable/reference/configuration/yb-master.md
docs/content/stable/reference/configuration/yb-tserver.md

PTP and Clockbound (TP)
Note on MacOS support in Voyager
@netlify /preview/releases/ybdb-releases/v2024.2/#new-features-1

[doc] Add missing items to RN

---

docs/content/preview/reference/configuration/yugabyted.md
docs/content/stable/reference/configuration/yugabyted.md
docs/content/v2024.1/reference/configuration/yugabyted.md

Remove trailing comma from config file example

[doc][yugabyted] Remove rogue comma

---

docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md
docs/content/v2.20/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/software-on-prem.md

[doc] Fix flag in command

---

docs/content/preview/releases/yba-releases/v2024.1.md
docs/content/preview/releases/ybdb-releases/v2024.1.md
docs/content/v2.20/reference/drivers/rust/rust-postgres-reference.md
docs/content/v2024.1/deploy/manual-deployment/install-software.md
docs/content/v2024.1/reference/configuration/yugabyted.md
docs/data/currentVersions.json

@netlify /preview/releases/ybdb-releases/v2024.1/#v2024.1.5.0

[docs] Release notes for 2024.1.5.0-b26

---

docs/content/preview/yugabyte-voyager/airgapped.md
docs/content/preview/yugabyte-voyager/rhel.md
docs/content/preview/yugabyte-voyager/ubuntu.md

Fix download URLs to correct format
@netlify /preview/yugabyte-voyager/install-yb-voyager/

[doc][voy] Fix download URLs

---

docs/content/preview/releases/ybdb-releases/v2024.1.md

RN 2024.1.5.0 - yugabyted support for ipv6
@netlify /preview/releases/ybdb-releases/v2024.1/#v2024.1.5.0

[doc] RN - yugabyted support for ipv6

---

docs/content/preview/drivers-orms/ruby/ruby-pg.md

Fix ruby pg alias
@netlify /preview/drivers-orms/ruby/ysql-pg/

[doc] Fix ruby pg alias

---

docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md

Wording of Raft flag intro
@netlify /preview/reference/configuration/yb-tserver/#raft-flags

[doc] Wording of Raft flag intro

---

docs/content/preview/develop/best-practices-ycql.md
docs/content/preview/develop/best-practices-ysql.md
docs/content/preview/drivers-orms/smart-drivers.md
docs/content/stable/develop/best-practices-ysql.md
docs/content/stable/drivers-orms/smart-drivers.md
docs/content/v2.18/drivers-orms/smart-drivers.md
docs/content/v2.20/develop/best-practices-ysql.md
docs/content/v2.20/drivers-orms/smart-drivers.md
docs/content/v2024.1/develop/best-practices-ysql.md
docs/content/v2024.1/drivers-orms/smart-drivers.md

Best practice - note about using new nodes
CLOUDGA-8581
@netlify /preview/develop/best-practices-ysql/

[doc] Best practice - note about using new nodes

---

docs/content/preview/explore/observability/active-session-history.md
docs/content/stable/explore/observability/active-session-history.md

@netlify /preview/explore/observability/active-session-history/#ysql

[DOC-645][doc][ysql] YSQL wait event

---

docs/content/preview/yugabyte-cloud/cloud-clusters/aeon-cdc.md

Aeon CDC TP -> EA
CLOUDGA-26272
@netlify /preview/yugabyte-cloud/cloud-clusters/aeon-cdc/

[doc][ybm] Aeon CDC TP -> EA

---

docs/content/preview/yugabyte-platform/prepare/server-nodes-software/_index.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/_index.md
docs/content/v2.20/yugabyte-platform/prepare/server-nodes-software/_index.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/_index.md

Red Hat Enterprise Linux 8-based systems DefaultLimitNOFILE=1048576
DOC-488
@netlify /preview/yugabyte-platform/prepare/server-nodes-software/

[doc][yba] RH8 node ulimits

---

docs/content/preview/deploy/checklist.md
docs/content/stable/deploy/checklist.md
docs/content/v2024.1/deploy/checklist.md

Change max storage per node

---

docs/content/preview/releases/yba-releases/v2024.1.md
docs/content/preview/yugabyte-platform/anywhere-automation/anywhere-cli.md
docs/content/stable/yugabyte-platform/anywhere-automation/anywhere-cli.md

yba CLI environment variable
DOC-642
@netlify /preview/yugabyte-platform/anywhere-automation/anywhere-cli/

[doc][yba][2024.2.2] yba CLI environment variable

---

docs/content/preview/releases/yba-releases/v2.18.md
docs/content/preview/releases/yba-releases/v2.19.md
docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/releases/yba-releases/v2.21.md
docs/content/preview/releases/yba-releases/v2.23.md
docs/content/preview/releases/yba-releases/v2.25.md
docs/content/preview/releases/yba-releases/v2024.1.md
docs/content/preview/releases/yba-releases/v2024.2.md

Fix download links
@netlify /preview/releases/yba-releases/

[doc][yba] Fix download links

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/v2024.1/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md

@netlify /v2024.1/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes/#use-yugabyte-kubernetes-operator-to-automate-yba-deployments

[DOC-652] Update Use Yugabyte Kubernetes Operator to automate YBA deployments section

---

docs/content/preview/yugabyte-platform/alerts-monitoring/anywhere-metrics.md
docs/content/stable/yugabyte-platform/alerts-monitoring/anywhere-metrics.md

Metrics timezone menu
DOC-640
@netlify /stable/yugabyte-platform/alerts-monitoring/anywhere-metrics/

[doc][yba][2024.2.2] Metrics timezone menu

---

docs/content/preview/develop/pg15-features.md

@netlify /preview/develop/pg15-features/#coming-soon

[doc] Note for extended stats

---

docs/content/preview/reference/configuration/operating-systems.md
docs/content/stable/reference/configuration/operating-systems.md
docs/content/v2.20/reference/configuration/operating-systems.md
docs/content/v2024.1/reference/configuration/operating-systems.md

@netlify /preview/reference/configuration/operating-systems/

[doc] Remove os recommendations

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/preview/yugabyte-platform/prepare/server-yba.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/stable/yugabyte-platform/prepare/server-yba.md
docs/content/v2.18/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/v2.20/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/v2.20/yugabyte-platform/prepare/server-yba.md
docs/content/v2024.1/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/v2024.1/yugabyte-platform/prepare/server-yba.md

DOC-662
@netlify /preview/yugabyte-platform/install-yugabyte-platform/install-software/installer/

[doc][yba] License link

---

docs/content/preview/reference/configuration/yugabyted.md
docs/content/stable/reference/configuration/yugabyted.md
docs/content/v2024.1/reference/configuration/yugabyted.md

@netlify /stable/reference/configuration/yugabyted/#xcluster

Fix yugabyted xcluster command examples

---

docs/content/preview/deploy/manual-deployment/install-software.md
docs/content/preview/manage/backup-restore/instant-db-cloning.md
docs/content/preview/releases/yba-releases/v2024.2.md
docs/content/preview/tutorials/quick-start/linux.md
docs/content/stable/deploy/manual-deployment/install-software.md
docs/content/v2.20/deploy/manual-deployment/install-software.md
docs/content/v2024.1/deploy/manual-deployment/install-software.md
docs/data/currentVersions.json

Add tabs for Linux DL
@netlify /preview/tutorials/quick-start/linux/#download

[doc] Add tabs for Linux DL

---

docs/content/preview/deploy/public-clouds/aws/manual-deployment.md
docs/content/preview/develop/gitdev/codespaces.md
docs/content/preview/develop/gitdev/gitpod.md
docs/content/preview/manage/upgrade-deployment.md
docs/content/stable/deploy/public-clouds/aws/manual-deployment.md
docs/content/stable/develop/gitdev/codespaces.md
docs/content/stable/develop/gitdev/gitpod.md
docs/content/stable/manage/upgrade-deployment.md
docs/content/v2.14/deploy/public-clouds/aws/manual-deployment.md
docs/content/v2.14/develop/gitdev/codespaces.md
docs/content/v2.14/develop/gitdev/gitpod.md
docs/content/v2.14/manage/upgrade-deployment.md
docs/content/v2.18/deploy/public-clouds/aws/manual-deployment.md
docs/content/v2.18/develop/gitdev/codespaces.md
docs/content/v2.18/develop/gitdev/gitpod.md
docs/content/v2.18/manage/upgrade-deployment.md
docs/content/v2.20/deploy/public-clouds/aws/manual-deployment.md
docs/content/v2.20/develop/gitdev/codespaces.md
docs/content/v2.20/develop/gitdev/gitpod.md
docs/content/v2.20/manage/upgrade-deployment.md
docs/content/v2024.1/deploy/public-clouds/aws/manual-deployment.md
docs/content/v2024.1/develop/gitdev/codespaces.md
docs/content/v2024.1/develop/gitdev/gitpod.md
docs/content/v2024.1/manage/upgrade-deployment.md

Fix download links
@netlify /preview/deploy/public-clouds/aws/manual-deployment/#2-install-yugabytedb

[doc] Fix download links

---

docs/content/preview/yugabyte-cloud/cloud-monitor/managed-integrations.md

@netlify /preview/yugabyte-cloud/cloud-monitor/managed-integrations/#prometheus

[doc][ybm][DOC-655] Prometheus export - out of order ingestion

---

docs/content/preview/integrations/nutanix-ahv.md

Add Nutanix partner link
#26280
@netlify /preview/integrations/nutanix-ahv/

[doc] Integrations - Nutanix link

---

docs/content/preview/releases/yba-releases/v2024.2.md
docs/content/preview/releases/ybdb-releases/v2024.2.md

@netlify /preview/releases/ybdb-releases/v2024.2/#v2024.2.2.1

[doc] Release Notes 2024.2.2.1-b6

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/azure.md
docs/content/preview/yugabyte-platform/create-deployments/connect-to-universe.md
docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-zone.md
docs/content/preview/yugabyte-platform/security/authorization-platform.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/azure.md
docs/content/stable/yugabyte-platform/create-deployments/connect-to-universe.md
docs/content/stable/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/stable/yugabyte-platform/create-deployments/create-universe-multi-zone.md
docs/content/stable/yugabyte-platform/security/authorization-platform.md
docs/content/v2.20/yugabyte-platform/create-deployments/connect-to-universe.md
docs/content/v2.20/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/v2.20/yugabyte-platform/create-deployments/create-universe-multi-zone.md
docs/content/v2.20/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes-azure.md
docs/content/v2.20/yugabyte-platform/security/authorization-platform.md
docs/content/v2024.1/yugabyte-platform/configure-yugabyte-platform/azure.md
docs/content/v2024.1/yugabyte-platform/create-deployments/connect-to-universe.md
docs/content/v2024.1/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/v2024.1/yugabyte-platform/create-deployments/create-universe-multi-zone.md
docs/content/v2024.1/yugabyte-platform/security/authorization-platform.md

Clarify db admin password in YBA
@netlify /preview/yugabyte-platform/create-deployments/create-universe-multi-zone/#authentication-settings

[doc][yba] Clarify db admin password in YBA

---

docs/content/preview/contribute/docs/macos.md

Update Homebrew formula link for Hugo installation instructions for macOS

---

docs/content/preview/architecture/docdb/_index.md

@netlify /preview/architecture/docdb/#performance

[docdb] YugabyteDB runs exclusively in Linux,

---

docs/content/preview/yugabyte-platform/security/create-kms-config/azure-kms.md
docs/content/stable/yugabyte-platform/security/create-kms-config/azure-kms.md
docs/content/v2024.1/yugabyte-platform/security/create-kms-config/azure-kms.md

Azure managed ID for EAR
DOC-637
@netlify /preview/yugabyte-platform/security/create-kms-config/azure-kms/

[doc][yba] Azure managed id for EAR

---

docs/content/preview/deploy/kubernetes/single-zone/oss/yugabyte-operator.md
docs/content/preview/releases/yba-releases/v2.21.md
docs/content/preview/releases/yba-releases/v2024.1.md
docs/content/preview/releases/yba-releases/v2024.2.md
docs/content/preview/releases/ybdb-releases/v2.21.md
docs/content/preview/releases/ybdb-releases/v2024.2.md
docs/content/preview/tutorials/quick-start/kubernetes.md
docs/content/preview/yugabyte-platform/anywhere-automation/_index.md
docs/content/preview/yugabyte-platform/anywhere-automation/yb-kubernetes-operator.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md
docs/content/stable/deploy/kubernetes/single-zone/oss/yugabyte-operator.md
docs/content/stable/yugabyte-platform/anywhere-automation/_index.md
docs/content/stable/yugabyte-platform/anywhere-automation/yb-kubernetes-operator.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/stable/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md
docs/content/v2024.1/deploy/kubernetes/single-zone/oss/yugabyte-operator.md
docs/content/v2024.1/yugabyte-platform/anywhere-automation/_index.md
docs/content/v2024.1/yugabyte-platform/anywhere-automation/yb-kubernetes-operator.md
docs/content/v2024.1/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/v2024.1/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md

TP 2024.1, EA 2024.2/2.25
@netlify /preview/yugabyte-platform/anywhere-automation/yb-kubernetes-operator/

[doc] Update K8s Operator maturity tags

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/kubernetes.md
docs/content/preview/yugabyte-platform/security/enable-encryption-in-transit/add-certificate-kubernetes.md
docs/content/stable/yugabyte-platform/security/enable-encryption-in-transit/add-certificate-kubernetes.md

K8s cert-manager details
PLAT-16629
@netlify /preview/yugabyte-platform/security/administer-yugabyte-platform/manage-runtime-config/

[doc][yba] k8s cert-mgr update

---

docs/content/preview/architecture/docdb-sharding/tablet-splitting.md
docs/content/preview/architecture/transactions/read-restart-error.md
docs/content/preview/explore/_index.md
docs/content/preview/manage/backup-restore/_index.md
docs/content/preview/manage/backup-restore/point-in-time-query.md
docs/content/preview/manage/backup-restore/time-travel-query.md
docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md

Point in time query
DOC-644
@netlify /preview/manage/backup-restore/point-in-time-query/

[doc][v2.25.1] Point in time query

---

.github/vale-styles/Yugabyte/spelling-exceptions.txt
docs/content/preview/explore/ysql-language-features/pg-extensions/_index.md
docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pganon.md
docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md

[DOC-672][2.25.1] Anonymizer extension

---

docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgvector.md

@netlify /preview/explore/ysql-language-features/pg-extensions/extension-pgvector/#indexing-in-yugabytedb

[DOC-666][v2.25.1] pgvector with indexing

---

docs/content/preview/explore/ysql-language-features/advanced-features/_index.md
docs/content/preview/explore/ysql-language-features/advanced-features/snapshot-synchronization.md
docs/content/stable/explore/ysql-language-features/advanced-features/_index.md
docs/content/stable/explore/ysql-language-features/advanced-features/snapshot-synchronization.md

[#26073][2.25.1] Doc: pg_export_snapshot document changes

---

docs/content/preview/architecture/docdb-replication/async-replication.md
docs/content/preview/deploy/multi-dc/async-replication/async-transactional-failover.md
docs/content/preview/deploy/multi-dc/async-replication/async-transactional-setup-manual.md
docs/content/preview/deploy/multi-dc/async-replication/async-transactional-switchover.md
docs/content/preview/deploy/multi-dc/async-replication/includes/automatic-setup.md
docs/content/preview/deploy/multi-dc/async-replication/includes/semi-automatic-setup.md
docs/content/preview/deploy/multi-dc/async-replication/includes/transactional-add-db.md
docs/content/preview/deploy/multi-dc/async-replication/includes/transactional-drop.md
docs/content/preview/deploy/multi-dc/async-replication/includes/transactional-remove-db.md

Update limitations, and set up instructions

[Docs][v2.25.1] Update xCluster docs for DDL replication part2

---

docs/content/preview/releases/yba-releases/v2024.2.md
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md
docs/content/v2.20/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md
docs/content/v2024.1/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md

OIDC default scope
DOC-678
@netlify /preview/yugabyte-platform/administer-yugabyte-platform/oidc-authentication/

[doc][yba] OIDC default scope

---

docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pganon.md

Add an example for how to check if a role is masked and update the backup and list all backup and restore feature which might cause issues with masked security label for users

[DOC-681] Update pg anonymizer documentation about how to check if a role is masked

---

docs/content/preview/tutorials/AI/ai-ollama.md

Reported in https://github.com/yugabyte/yugabyte-db/issues/26551

Fix typo on `ollama pull nomic-embed-text:latest`

---

docs/content/preview/releases/yba-releases/v2.20.md
docs/content/preview/releases/ybdb-releases/v2.20.md
docs/data/currentVersions.json

@netlify /preview/releases/ybdb-releases/v2.20/#v2.20.10.0

 [docs] Release notes for 2.20.10.0-b29

---

docs/content/preview/admin/yb-admin.md

Fix formatting consistency in yb-admin reference
DOC-689
@netlify /

[doc] yb-admin format issues

---

docs/content/preview/manage/backup-restore/instant-db-cloning.md
docs/content/stable/manage/backup-restore/instant-db-cloning.md

Remove preview flag for db cloning feature
#26622
@netlify /preview/manage/backup-restore/instant-db-cloning

[doc] Remove preview flag for db cloning feature

---

docs/content/preview/yugabyte-cloud/cloud-clusters/aeon-cdc.md

CDC functions to create replication role
@netlify /preview/yugabyte-cloud/cloud-clusters/aeon-cdc/

[doc][ybm] CDC role

---

docs/content/preview/api/ysql/the-sql-language/statements/dcl_create_user.md
docs/content/preview/faq/operations-faq.md

@netlify /preview/api/ysql/the-sql-language/statements/dcl_create_user/#examples

[DOC-627][doc] Password with expiration

---

docs/content/preview/admin/yb-admin.md
docs/content/preview/api/ysql/the-sql-language/statements/dml_values.md
docs/content/preview/architecture/docdb-sharding/sharding.md
docs/content/preview/explore/going-beyond-sql/data-sharding.md
docs/content/stable/api/ysql/the-sql-language/statements/dml_values.md
docs/content/stable/api/ysql/the-sql-language/statements/txn_show.md
docs/content/stable/architecture/docdb-sharding/sharding.md
docs/content/stable/architecture/query-layer/planner-optimizer.md
docs/content/stable/architecture/transactions/read-restart-error.md
docs/content/stable/explore/colocation.md
docs/content/stable/explore/going-beyond-sql/data-sharding.md
docs/content/stable/manage/upgrade-deployment.md
docs/content/stable/reference/configuration/operating-systems.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yugabyted.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac.md
docs/content/stable/yugabyte-platform/alerts-monitoring/anywhere-export-configuration.md
docs/content/stable/yugabyte-platform/alerts-monitoring/universe-logging.md
docs/content/stable/yugabyte-platform/anywhere-automation/anywhere-cli.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/_index.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/restore-universe-data.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/stable/yugabyte-platform/manage-deployments/edit-config-flags.md
docs/content/stable/yugabyte-platform/manage-deployments/remove-nodes.md
docs/content/stable/yugabyte-platform/prepare/networking-kubernetes.md
docs/content/v2.20/api/ysql/the-sql-language/statements/dml_values.md
docs/content/v2.20/architecture/docdb-sharding/sharding.md
docs/content/v2024.1/api/ysql/the-sql-language/statements/dml_values.md
docs/content/v2024.1/architecture/docdb-sharding/sharding.md
docs/content/v2024.1/explore/going-beyond-sql/data-sharding.md

Update Idea numbers for features

[doc] Idea numbers

---

docs/content/preview/develop/learn/transactions/transactions-retries-ysql.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/on-premises-nodes.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/on-premises-script.md
docs/content/stable/develop/learn/transactions/transactions-retries-ysql.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/on-premises-nodes.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/on-premises-script.md
docs/content/v2.20/yugabyte-platform/configure-yugabyte-platform/on-premises-nodes.md
docs/content/v2.20/yugabyte-platform/configure-yugabyte-platform/on-premises-script.md
docs/content/v2024.1/yugabyte-platform/configure-yugabyte-platform/on-premises-nodes.md
docs/content/v2024.1/yugabyte-platform/configure-yugabyte-platform/on-premises-script.md

Clarify legacy assisted provisioning
@netlify /preview/yugabyte-platform/configure-yugabyte-platform/on-premises-script/

[doc][yba] Clarify legacy assisted provisioning

---

docs/content/preview/admin/yb-admin.md
docs/content/stable/admin/yb-admin.md
docs/content/v2.20/admin/yb-admin.md
docs/content/v2024.1/admin/yb-admin.md

YB-Admin remove_table ignore-errors option
DOC-680
@netlify /preview/admin/yb-admin/#alter-universe-replication

[doc] remove_table ignore-errors option

---

.github/vale-styles/Yugabyte/spelling-exceptions.txt
docs/content/preview/tutorials/AI/ai-ollama.md

I tested the app locally and reflected missing steps in this pull request.

[docs] Added missing steps in ai-ollama.md

---

docs/content/preview/tutorials/AI/ai-llamaindex-openai.md
docs/content/preview/tutorials/AI/ai-ollama.md

Updates to llamaindex tutorial
@netlify /preview/tutorials/ai/ai-llamaindex-openai/

[doc] Updates to llamaindex tutorial

---

docs/content/preview/develop/change-data-capture/using-yugabytedb-grpc-replication/cdc-get-started.md
docs/content/preview/manage/diagnostics-reporting.md
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/_index.md
docs/content/preview/yugabyte-platform/alerts-monitoring/set-up-alerts-health-check.md
docs/content/stable/develop/change-data-capture/using-yugabytedb-grpc-replication/cdc-get-started.md
docs/content/stable/manage/diagnostics-reporting.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/_index.md
docs/content/stable/yugabyte-platform/alerts-monitoring/set-up-alerts-health-check.md
docs/content/v2.20/explore/change-data-capture/cdc-get-started.md
docs/content/v2.20/manage/diagnostics-reporting.md
docs/content/v2.20/yugabyte-platform/administer-yugabyte-platform/_index.md
docs/content/v2.20/yugabyte-platform/alerts-monitoring/set-up-alerts-health-check.md
docs/content/v2024.1/develop/change-data-capture/using-yugabytedb-grpc-replication/cdc-get-started.md
docs/content/v2024.1/manage/diagnostics-reporting.md
docs/content/v2024.1/yugabyte-platform/administer-yugabyte-platform/_index.md
docs/content/v2024.1/yugabyte-platform/alerts-monitoring/set-up-alerts-health-check.md

YBA callhome details + CDC note
DOC-707
DOC-705
@netlify /preview/yugabyte-platform/alerts-monitoring/set-up-alerts-health-check/#configure-health-check

[DOC-707][yba] YBA callhome details

---

docs/content/preview/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac.md
docs/content/v2.20/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac.md
docs/content/v2024.1/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac.md

Backup admin can restore
@netlify /preview/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac/#built-in-roles

[doc][yba] Backup admin can restore

---

docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/v2.20/yugabyte-platform/administer-yugabyte-platform/high-availability.md
docs/content/v2024.1/yugabyte-platform/administer-yugabyte-platform/high-availability.md

Note about ingress and large requests
@netlify /preview/yugabyte-platform/administer-yugabyte-platform/high-availability/#limitations

[DOC-728] Note about ingress and large requests

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/v2.20/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/v2024.1/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md

GCS permissions
@netlify /preview/yugabyte-platform/back-up-restore-universes/configure-backup-storage/

[DOC-725][yba] GCS permissions

---

docs/content/preview/develop/best-practices-ysql.md
docs/content/stable/develop/best-practices-ysql.md
docs/content/v2.20/develop/best-practices-ysql.md
docs/content/v2024.1/develop/best-practices-ysql.md

See https://github.com/yugabyte/yugabyte-db/issues/12449 for more information on the original context.

[#12449] Recommend using a single conn for DDL scripts & migrations

---

docs/content/preview/admin/yb-admin.md
docs/content/preview/reference/configuration/default-ports.md
docs/content/preview/yugabyte-platform/prepare/networking.md
docs/content/stable/admin/yb-admin.md
docs/content/stable/reference/configuration/default-ports.md
docs/content/stable/reference/configuration/yugabyted.md
docs/content/stable/yugabyte-platform/prepare/networking.md
docs/content/v2.20/admin/yb-admin.md
docs/content/v2.20/reference/configuration/default-ports.md
docs/content/v2.20/yugabyte-platform/prepare/networking.md
docs/content/v2024.1/admin/yb-admin.md
docs/content/v2024.1/reference/configuration/default-ports.md
docs/content/v2024.1/yugabyte-platform/prepare/networking.md

Note on port 7000
#11605
DOC-742
@netlify /preview/reference/configuration/default-ports/

[doc] Note on port 7000

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/v2.20/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/v2024.1/yugabyte-platform/install-yugabyte-platform/install-software/installer.md

YBA installer proxy settings
DOC-650
@netlify /preview/yugabyte-platform/install-yugabyte-platform/install-software/installer/#configure-yba

[doc][yba] YBA installer proxy settings

---

docs/content/preview/releases/yba-releases/v2024.1.md
docs/content/preview/releases/ybdb-releases/v2024.1.md
docs/data/currentVersions.json

@netlify /preview/releases/ybdb-releases/v2024.1/#v2024.1.6.0

 [docs] Release note for 2024.1.6.0-b53

---

docs/content/preview/explore/going-beyond-sql/follower-reads-ysql.md
docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/explore/going-beyond-sql/follower-reads-ysql.md
docs/content/stable/reference/configuration/yb-master.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/v2.20/explore/ysql-language-features/going-beyond-sql/follower-reads-ysql.md
docs/content/v2.20/reference/configuration/yb-master.md
docs/content/v2.20/reference/configuration/yb-tserver.md
docs/content/v2024.1/explore/going-beyond-sql/follower-reads-ysql.md
docs/content/v2024.1/reference/configuration/yb-master.md
docs/content/v2024.1/reference/configuration/yb-tserver.md

Add details of `ysql_follower_reads_avoid_waiting_for_safe_time`
Add details about the metric `consistent_prefix_failed_reads`

Update follower reads gflags

---

docs/content/preview/develop/change-data-capture/using-logical-replication/_index.md
docs/content/preview/develop/change-data-capture/using-logical-replication/advanced-topic.md
docs/content/preview/develop/change-data-capture/using-logical-replication/monitor.md
docs/content/preview/develop/change-data-capture/using-yugabytedb-grpc-replication/_index.md
docs/content/stable/develop/change-data-capture/using-logical-replication/_index.md
docs/content/stable/develop/change-data-capture/using-logical-replication/advanced-topic.md
docs/content/stable/develop/change-data-capture/using-yugabytedb-grpc-replication/_index.md

- Added description for all the fields in pg_stat_replication.
- Updated the description for field plugin in pg_replication_slots and added the field attnames in pg_publication_tables

[docs] CDC: Add documentation for pg_stat_replication view

---

docs/content/preview/yugabyte-voyager/known-issues/postgresql.md

@netlify /preview/yugabyte-voyager/known-issues/postgresql/#redundant-indexes

[DOC-746] add postgresql schema workaround in voyager docs

---

docs/content/preview/admin/yb-admin.md
docs/content/stable/admin/yb-admin.md

Format yb-admin stable page
@netlify /stable/admin/yb-admin/

[doc] Format yb-admin stable page

---

docs/content/_index.md
docs/content/preview/yugabyte-voyager/migrate/live-fall-back.md
docs/content/preview/yugabyte-voyager/migrate/live-fall-forward.md
docs/content/preview/yugabyte-voyager/migrate/live-migrate.md
docs/content/preview/yugabyte-voyager/migrate/migrate-steps.md

[DOC-753] Landing page text

---

docs/assets/scss/_yb_headings.scss
docs/src/index.js

Automatically copy the link if anyone click on the link icon.

[Docs] Copy to clipboard link on clicking heading icon

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/v2.20/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
docs/content/v2024.1/yugabyte-platform/install-yugabyte-platform/install-software/installer.md

Minor correction to Installer command
@netlify /preview/yugabyte-platform/install-yugabyte-platform/install-software/installer/

[doc][yba] Minor correction to Installer command

---

docs/content/preview/contribute/docs/macos.md
docs/content/preview/contribute/docs/ubuntu.md

[DOC-756][doc] Infrastructure - update Contribute instructions to latest updates

---

docs/content/preview/explore/ysql-language-features/pg-extensions/_index.md
docs/content/preview/yugabyte-cloud/_index.md
docs/content/stable/explore/ysql-language-features/pg-extensions/_index.md
docs/content/v2.20/explore/ysql-language-features/pg-extensions/_index.md
docs/content/v2024.1/explore/ysql-language-features/pg-extensions/_index.md

DOC-761
earthdistance and cube

[DOC-761] earthdistance and cube

---

docs/content/preview/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/stable/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/v2024.1/deploy/kubernetes/single-zone/oss/helm-chart.md

Finalize k8s upgrade
@netlify /preview/deploy/kubernetes/single-zone/oss/helm-chart/#upgrade-the-software-version-of-yugabytedb

[DOC-747] Finalize k8s upgrade

---

.github/vale-styles/Yugabyte/spelling-exceptions.txt
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/kubernetes.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-kubernetes.md
docs/content/preview/yugabyte-platform/security/enable-encryption-in-transit/add-certificate-kubernetes.md
docs/content/preview/yugabyte-voyager/known-issues/postgresql.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/kubernetes.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-kubernetes.md
docs/content/stable/yugabyte-platform/security/enable-encryption-in-transit/add-certificate-kubernetes.md

cert-manager clarifications
@netlify /preview/yugabyte-platform/security/enable-encryption-in-transit/add-certificate-kubernetes/#including-the-common-name

[doc][yba] cert-manager clarifications

---

docs/content/preview/reference/configuration/operating-systems.md
docs/content/preview/yugabyte-platform/manage-deployments/edit-config-flags.md
docs/content/preview/yugabyte-platform/manage-deployments/edit-universe.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/_index.md
docs/content/preview/yugabyte-platform/security/authorization-platform.md
docs/content/preview/yugabyte-platform/security/enable-encryption-at-rest.md
docs/content/preview/yugabyte-platform/security/enable-encryption-in-transit/_index.md
docs/content/stable/reference/configuration/operating-systems.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/_index.md
docs/content/stable/yugabyte-platform/prepare/server-yba.md

Python and AL2023 support
DOC-762
DOC-763
@netlify /preview/yugabyte-platform/prepare/server-nodes-software/#python

[DOC-763][yba] Python and AL2023 support

---

docs/content/preview/architecture/docdb-replication/async-replication.md
docs/content/stable/architecture/docdb-replication/async-replication.md
docs/content/stable/explore/observability/active-session-history.md

xCluster transactional writes to target
@netlify /preview/architecture/docdb-replication/async-replication/#transactional

[DOC-740][2024.2.3] xCluster transactional writes to target

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/gcp.md
docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/preview/yugabyte-platform/manage-deployments/edit-helm-overrides.md
docs/content/preview/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes-aws.md
docs/content/preview/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes-azure.md
docs/content/preview/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes-gcp.md
docs/content/preview/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes.md
docs/content/preview/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-storage.md
docs/content/preview/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-yba.md
docs/content/preview/yugabyte-platform/prepare/server-nodes-software/software-cloud-provider.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/gcp.md
docs/content/stable/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/stable/yugabyte-platform/manage-deployments/edit-helm-overrides.md
docs/content/stable/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes-aws.md
docs/content/stable/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes-azure.md
docs/content/stable/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes-gcp.md
docs/content/stable/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes.md
docs/content/stable/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-storage.md
docs/content/stable/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-yba.md
docs/content/stable/yugabyte-platform/prepare/server-nodes-software/software-cloud-provider.md

GCP IAM
DOC-713
@netlify /preview/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-yba/

[DOC-713][2024.2.3][yba] GCP IAM

---

docs/content/preview/tutorials/quick-start/docker.md

Clarify base_dir
@netlify /preview/tutorials/quick-start/docker/#run-docker-in-a-persistent-volume

[doc] Clarify base_dir

---

docs/content/_index.md

adjust spacing of landing page

[doc] format landing page

---

docs/content/preview/releases/yba-releases/v2024.2.md
docs/content/preview/releases/ybdb-releases/v2024.2.md

@netlify /preview/releases/yba-releases/v2024.2/#v2024.2.2.4

[docs] Release notes for 2024.2.2.4-b2

---

docs/assets/scss/_sidebar-toc.scss
docs/src/index.js

@netlify /preview/reference/configuration/yb-tserver/

[Docs] Autoscroll right nav where the right nav is a very long one

---

docs/content/preview/yugabyte-voyager/migrate/live-fall-back.md
docs/content/preview/yugabyte-voyager/migrate/live-fall-forward.md
docs/content/preview/yugabyte-voyager/migrate/live-migrate.md
docs/content/preview/yugabyte-voyager/migrate/migrate-steps.md
docs/content/preview/yugabyte-voyager/release-notes.md

@netlify /preview/yugabyte-voyager/release-notes/#v2025-5-2-may-20-2025

[DOC-774] Yugabyte Voyager Release v2025.5.2

---

docs/content/preview/releases/yba-releases/v2.25.md
docs/content/preview/releases/ybdb-releases/v2.25.md
docs/data/currentVersions.json

@netlify /preview/releases/ybdb-releases/v2.25/#v2.25.2.0

 [docs] Release note for 2.25.2.0-b359

---

docs/content/preview/releases/yba-releases/v2024.2.md
docs/content/preview/releases/ybdb-releases/v2024.2.md

[doc] Fix release build number

---

docs/content/preview/develop/best-practices-develop/administration.md
docs/content/preview/develop/best-practices-develop/data-modeling-perf.md
docs/content/stable/develop/best-practices-develop/administration.md
docs/content/stable/develop/best-practices-develop/data-modeling-perf.md

Fix link in best practices
@netlify /preview/develop/best-practices-develop/data-modeling-perf/#minimize-the-number-of-tablets-you-need

[doc] Fix link in best practices

---

docs/content/stable/drivers-orms/smart-drivers.md
docs/content/v2024.1/drivers-orms/smart-drivers.md

Copy new wording to previous versions

[doc] Backport smart driver change

---

docs/content/preview/admin/yb-admin.md
docs/content/preview/api/ysql/the-sql-language/statements/streaming_create_repl_slot.md
docs/content/preview/explore/going-beyond-sql/connection-mgr-ysql.md
docs/content/preview/explore/query-1-performance/pg-hint-plan.md
docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/preview/secure/audit-logging/audit-logging-ysql.md
docs/content/preview/secure/audit-logging/trace-statements-ysql.md

Tserver page comments
@netlify /preview/reference/configuration/yb-tserver/

[doc] Tserver page comments

---

docs/content/preview/tutorials/AI/_index.md
docs/content/preview/tutorials/AI/hello-rag.md

Hello rag tutorial
@netlify /preview/tutorials/ai/hello-rag/

[DOC-776] Hello rag tutorial

---

docs/content/v2.20/yugabyte-platform/prepare/server-nodes-software/_index.md
docs/content/v2024.1/yugabyte-platform/prepare/server-nodes-software/_index.md

Copy THP setup to 2024.1 and 2.20
@netlify /v2024.1/yugabyte-platform/prepare/server-nodes-software/#transparent-hugepages

[doc][yba] Copy THP setup to 2024.1 and 2.20

---

docs/content/preview/yugabyte-cloud/cloud-admin/cloud-billing-costs-classic.md
docs/content/preview/yugabyte-cloud/cloud-admin/cloud-billing-costs.md

Make price decimals consistent
#27504
@netlify /preview/yugabyte-cloud/cloud-admin/cloud-billing-costs/

[doc] Inaccurate pricing in rate card

---

docs/content/preview/architecture/docdb-sharding/tablet-splitting.md
docs/content/preview/reference/configuration/smart-defaults.md
docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md

TServer reference - Move some memory division details
@netlify /preview/reference/configuration/yb-tserver/#memory-division-flags

[doc] Move some memory division details

---

docs/content/preview/releases/ybdb-releases/end-of-life/v2.19.md
docs/content/preview/releases/ybdb-releases/end-of-life/v2.21-anywhere.md
docs/content/preview/releases/ybdb-releases/end-of-life/v2.21.md
docs/content/preview/releases/ybdb-releases/end-of-life/v2.23-anywhere.md
docs/content/preview/releases/ybdb-releases/v2.25.md
docs/content/preview/releases/ybdb-releases/v2024.1.md

@netlify /preview/releases/ybdb-releases/v2024.1/

[DOC-833] link fixes and added blogs to release pages

---

docs/content/v2025.1/explore/ysql-language-features/pg-extensions/extension-pganon.md

@netlify /v2025.1/explore/ysql-language-features/pg-extensions/extension-pganon/

[DOC-826] [2025.1] Removed EA from PostgreSQL Anonymizer extension

---

docs/content/v2025.1/deploy/kubernetes/single-zone/oss/yugabyte-operator.md
docs/content/v2025.1/yugabyte-platform/anywhere-automation/_index.md
docs/content/v2025.1/yugabyte-platform/anywhere-automation/yb-kubernetes-operator.md
docs/content/v2025.1/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/v2025.1/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md

@netlify /v2025.1/yugabyte-platform/anywhere-automation/yb-kubernetes-operator/

[DOC-811] [EA->GA] Kubernetes operator

---

docs/content/preview/yugabyte-cloud/cloud-clusters/aeon-cdc.md

Add cdcsdk_flush_lag metric
@netlify /preview/yugabyte-cloud/cloud-clusters/aeon-cdc/#charts

[DOC-831][ybm] Add cdcsdk_flush_lag metric

---

docs/content/preview/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac.md
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/ldap-authentication.md
docs/content/preview/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/ldap-authentication.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md
docs/content/v2025.1/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac.md
docs/content/v2025.1/yugabyte-platform/administer-yugabyte-platform/ldap-authentication.md
docs/content/v2025.1/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md

Fine-grain RBAC GA; removed classic RBAC
@netlify /v2025.1/yugabyte-platform/administer-yugabyte-platform/anywhere-rbac/

[DOC-818][yba][2025.1] Fine-grain RBAC GA

---

docs/content/preview/api/ysql/the-sql-language/statements/dml_insert.md
docs/content/preview/manage/data-migration/bulk-import-ysql.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/manage/data-migration/bulk-import-ysql.md
docs/content/v2.20/manage/data-migration/bulk-import-ysql.md
docs/content/v2024.1/manage/data-migration/bulk-import-ysql.md
docs/content/v2025.1/api/ysql/the-sql-language/statements/dml_insert.md
docs/content/v2025.1/manage/data-migration/bulk-import-ysql.md
docs/content/v2025.1/reference/configuration/yb-tserver.md

@netlify /v2025.1/reference/configuration/yb-tserver/

[DOC-847] [2025.1]  InsertOnConflict Batching config parameters

---

docs/content/preview/reference/configuration/yb-master.md
docs/content/stable/reference/configuration/yb-master.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/v2.20/best-practices-operations/_index.md
docs/content/v2.20/best-practices-operations/administration.md
docs/content/v2.20/best-practices-operations/ysql-catalog-cache-tuning-guide.md
docs/content/v2.20/deploy/_index.md
docs/content/v2.20/develop/best-practices-ysql.md
docs/content/v2.20/launch-and-manage/monitor-and-alert/_index.md
docs/content/v2.20/manage/_index.md
docs/content/v2.20/reference/configuration/yb-master.md
docs/content/v2.20/reference/configuration/yb-tserver.md
docs/content/v2024.1/reference/configuration/yb-master.md
docs/content/v2025.1/reference/configuration/yb-master.md

Copy catalog flags to 2.20
@netlify /preview/best-practices-operations/ysql-catalog-cache-tuning-guide/

[DOC-832] Copy catalog flags to 2.20

---

docs/content/preview/architecture/query-layer/planner-optimizer.md
docs/content/preview/best-practices-operations/_index.md
docs/content/preview/best-practices-operations/ysql-catalog-cache-tuning-guide.md
docs/content/preview/best-practices-operations/ysql-yb-enable-cbo.md
docs/content/preview/develop/postgresql-compatibility.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/architecture/query-layer/planner-optimizer.md
docs/content/stable/best-practices-operations/_index.md
docs/content/stable/best-practices-operations/ysql-yb-enable-cbo.md
docs/content/stable/develop/postgresql-compatibility.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/v2025.1/architecture/query-layer/planner-optimizer.md
docs/content/v2025.1/best-practices-operations/_index.md
docs/content/v2025.1/best-practices-operations/ysql-catalog-cache-tuning-guide.md
docs/content/v2025.1/best-practices-operations/ysql-yb-enable-cbo.md
docs/content/v2025.1/develop/postgresql-compatibility.md
docs/content/v2025.1/reference/configuration/yb-tserver.md

Add yb_enable_cbo parameter
DOC-827 - CBO EA->GA
@netlify /v2025.1/best-practices-operations/ysql-yb-enable-cbo/

[DOC-778][2025.1] yb_enable_cbo parameter

---

docs/content/preview/api/ysql/exprs/_index.md
docs/content/preview/api/ysql/exprs/func_yb_index_check.md
docs/content/preview/explore/ysql-language-features/indexes-constraints/_index.md
docs/content/stable/api/ysql/exprs/_index.md
docs/content/stable/api/ysql/exprs/func_yb_index_check.md
docs/content/stable/explore/ysql-language-features/indexes-constraints/_index.md
docs/content/v2.20/api/ysql/exprs/_index.md
docs/content/v2.20/api/ysql/exprs/func_yb_index_check.md
docs/content/v2024.1/api/ysql/exprs/_index.md
docs/content/v2024.1/api/ysql/exprs/func_yb_index_check.md
docs/content/v2024.1/explore/ysql-language-features/indexes-constraints/_index.md
docs/content/v2025.1/api/ysql/exprs/_index.md
docs/content/v2025.1/api/ysql/exprs/func_yb_index_check.md
docs/content/v2025.1/explore/ysql-language-features/indexes-constraints/_index.md

@netlify /preview/api/ysql/exprs/func_yb_index_check
@netlify /stable/api/ysql/exprs/func_yb_index_check
@netlify /v2.20/api/ysql/exprs/func_yb_index_check
@netlify /v2024.1/api/ysql/exprs/func_yb_index_check
@netlify /v2025.1/api/ysql/exprs/func_yb_index_check

[DOC-862] [2025.1] Documentation for yb_index_check

---

docs/content/preview/deploy/checklist.md
docs/content/stable/deploy/checklist.md
docs/content/v2025.1/deploy/checklist.md

This is GA for 2024.2.4 and 2025.1. I have also added it preview (commented it out for 2.27)
@netlify /stable/deploy/checklist/#disks

[DOC-777] [2024.2.4] [2025.1] Added GCP hyperdisk support

---

docs/content/preview/api/ysql/the-sql-language/statements/cmd_copy.md
docs/content/v2025.1/api/ysql/the-sql-language/statements/cmd_copy.md

Add a section in cmd_copy.md for fast-path copy on colocated table.

[DOC-816] [2025.1] add doc for fast-path COPY

---

docs/content/preview/reference/configuration/yb-tserver.md
docs/content/v2025.1/reference/configuration/yb-tserver.md

@netlify /preview/reference/configuration/yb-tserver/#ysql-configuration-parameters
https://deploy-preview-27873--infallible-bardeen-164bc9.netlify.app/v2025.1/reference/configuration/yb-tserver/#yb-sampling-algorithm

[DOC-817] [2025.1] Added yb_sampling_algorithm config parameter

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/_index.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-switchover.md
docs/content/preview/yugabyte-platform/manage-deployments/xcluster-replication/xcluster-replication-setup.md
docs/content/v2025.1/yugabyte-platform/back-up-restore-universes/disaster-recovery/_index.md
docs/content/v2025.1/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md
docs/content/v2025.1/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-switchover.md
docs/content/v2025.1/yugabyte-platform/manage-deployments/xcluster-replication/xcluster-replication-setup.md

xCluster DR changes
@netlify /v2025.1/yugabyte-platform/back-up-restore-universes/disaster-recovery/

[DOC-738][2025.1][yba] xCluster DR changes

---

docs/content/v2025.1/develop/postgresql-compatibility.md
docs/content/v2025.1/explore/transactions/_index.md
docs/content/v2025.1/explore/transactions/transactional-ddl.md

@netlify /v2025.1/explore/transactions/transactional-ddl/

[DOC-859] [2025.1] Added Transactional DDL

---

docs/content/stable/reference/configuration/yb-tserver.md

Add enable CBO flag in stable
@netlify /stable/reference/configuration/yb-tserver/#cost-based-optimizer-flag

[doc] Add enable CBO flag in stable

---

docs/content/preview/yugabyte-voyager/known-issues/postgresql.md
docs/content/preview/yugabyte-voyager/reference/bulk-data-load/import-data-file.md
docs/content/preview/yugabyte-voyager/reference/data-migration/import-data.md
docs/content/preview/yugabyte-voyager/release-notes.md
src/yb/yql/pgwrapper/pg_get_lock_status-test.cc

@netlify /preview/yugabyte-voyager/reference/data-migration/import-data/#arguments

[DOC-875] Docs for Voyager 2025.7.2

---

docs/content/preview/explore/ysql-language-features/advanced-features/inheritance.md
docs/content/v2025.1/explore/ysql-language-features/advanced-features/inheritance.md

Update the github issue that tracks future inheritance issues.

Minor docs fix to inheritance page

---

docs/content/preview/manage/upgrade-deployment.md
docs/content/preview/manage/ysql-major-upgrade-local.md
docs/content/preview/manage/ysql-major-upgrade-yugabyted.md
docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software-install.md
docs/content/stable/manage/upgrade-deployment.md
docs/content/stable/yugabyte-platform/manage-deployments/upgrade-software-install.md
docs/content/v2.20/manage/upgrade-deployment.md
docs/content/v2.20/yugabyte-platform/manage-deployments/upgrade-software-install.md
docs/content/v2024.1/manage/upgrade-deployment.md
docs/content/v2024.1/yugabyte-platform/manage-deployments/upgrade-software-install.md
docs/content/v2025.1/manage/upgrade-deployment.md
docs/content/v2025.1/manage/ysql-major-upgrade-local.md
docs/content/v2025.1/manage/ysql-major-upgrade-yugabyted.md
docs/content/v2025.1/yugabyte-platform/manage-deployments/upgrade-software-install.md

Upgrades: Add limit for monitor phase of 2 days
@netlify /preview/yugabyte-platform/manage-deployments/upgrade-software-install/#monitor-the-universe

[DOC-858] Add limit for monitor phase of 2 days

---

docs/content/preview/faq/compatibility.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-single-region.md
docs/content/preview/yugabyte-cloud/cloud-clusters/configure-clusters.md
docs/content/preview/yugabyte-cloud/release-notes.md

[DOC-880] Update YBM change log

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/kubernetes.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/kubernetes.md
docs/content/v2.20/yugabyte-platform/configure-yugabyte-platform/kubernetes.md
docs/content/v2024.1/yugabyte-platform/configure-yugabyte-platform/kubernetes.md
docs/content/v2025.1/yugabyte-platform/configure-yugabyte-platform/kubernetes.md

Note on Istio change requiring YBA pod restart
@netlify /preview/yugabyte-platform/configure-yugabyte-platform/kubernetes/#prepare-kubernetes-clusters-for-istio-multicluster

[DOC-872][yba] Note on Istio change requiring YBA pod restart

---

docs/content/preview/tutorials/AI/ai-localai.md
docs/content/preview/tutorials/AI/azure-openai.md

Summary: Added vector indexing as part of the LocalAI tutorial app. Made some more minor changes.

[#GROWENG-79] Updating LocalAI tutorial docs page to add vector indexing

---

docs/content/preview/tutorials/AI/google-vertex-ai.md

Summary: Added vector indexing as part of the Google VertexAI tutorial app. Made some more minor changes.

[GROWENG-80] Updating Google VertexAI tutorial docs page to add vector indexing

---

docs/config/_default/menus.toml
docs/content/preview/releases/ybdb-releases/v2025.1.md

@netlify /preview/releases/ybdb-releases/v2025.1/

[doc] Changed path for DB and YBA releases

---

docs/content/preview/tutorials/AI/hello-rag.md

From https://forum.yugabyte.com/t/a-git-error-occurred-on-the-hello-rag-page/4573/6

[docs] Add note to psycopg2 installation instructions in "Hello RAG"

---

docs/content/preview/yugabyte-cloud/release-notes.md

[doc][ybm] Aeon change log

---

docs/content/preview/api/ysql/the-sql-language/statements/cmd_analyze.md
docs/content/preview/architecture/query-layer/planner-optimizer.md
docs/content/preview/explore/query-1-performance/_index.md
docs/content/preview/explore/query-1-performance/auto-analyze.md
docs/content/preview/reference/configuration/yb-master.md
docs/content/preview/reference/configuration/yb-tserver.md

Copy auto analyze to preview
from #25188
@neltlify /preview/explore/query-1-performance/

[doc] Copy auto analyze to preview

---

docs/content/preview/contribute/docs/macos.md
docs/content/preview/releases/yba-releases/v2024.2.md
docs/content/preview/releases/ybdb-releases/v2024.2.md

@netlify /preview/releases/ybdb-releases/v2024.2/#v2024.2.3.3

[DOC-909] Added Release notes for 2024.2.3.3-b4 and updated Hugo version 

---

docs/content/preview/releases/yugabyte-clients.md

@netlify /preview/releases/yugabyte-clients/#installation

[DOC-902] Changed version for yugabyte-clients to the GA version 2025.1

---

docs/content/preview/releases/yba-releases/v2024.2.md
docs/content/preview/releases/ybdb-releases/v2024.2.md
docs/data/currentVersions.json

@netlify /preview/releases/ybdb-releases/v2024.2/#v2024.2.4.1

[docs] fix build number for 2024.2.4.1

---

docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software-prepare.md
docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software.md
docs/content/preview/yugabyte-platform/manage-deployments/ybdb-releases.md
docs/content/stable/yugabyte-platform/manage-deployments/upgrade-software-prepare.md
docs/content/stable/yugabyte-platform/manage-deployments/upgrade-software.md
docs/content/stable/yugabyte-platform/manage-deployments/ybdb-releases.md
docs/content/v2024.1/yugabyte-platform/manage-deployments/upgrade-software-prepare.md
docs/content/v2024.1/yugabyte-platform/manage-deployments/upgrade-software.md
docs/content/v2024.1/yugabyte-platform/manage-deployments/ybdb-releases.md
docs/content/v2024.2/yugabyte-platform/manage-deployments/upgrade-software-prepare.md
docs/content/v2024.2/yugabyte-platform/manage-deployments/upgrade-software.md
docs/content/v2024.2/yugabyte-platform/manage-deployments/ybdb-releases.md

Clarify the import releases page
@netlify /preview/yugabyte-platform/manage-deployments/ybdb-releases/

[DOC-923] Clarify the import releases page

---

docs/content/stable/yugabyte-platform/prepare/server-yba.md

[doc][yba] Python for YBA in v2025.1

---

docs/content/preview/deploy/checklist.md
docs/content/preview/releases/techadvisories/_index.md
docs/content/preview/releases/techadvisories/ta-28222.md
docs/content/stable/deploy/checklist.md
docs/content/v2024.1/reference/configuration/yb-master.md
docs/content/v2024.1/reference/configuration/yb-tserver.md
docs/content/v2024.2/deploy/checklist.md

@netlify /preview/releases/techadvisories/ta-28222/

[DOC-927] [TA] Regression for Queries with BNL Plans

---

docs/content/preview/secure/vulnerability-disclosure-policy.md

@netlify /preview/secure/vulnerability-disclosure-policy/#supply-chain-vulnerabilities-in-yugabytedb-postgres-query-layer-ysql

[DOC-935] Added CVE-2023-39418

---

docs/content/preview/manage/backup-restore/_index.md
docs/content/preview/yugabyte-cloud/managed-security/managed-authentication/_index.md
docs/content/preview/yugabyte-cloud/managed-security/managed-authentication/federated-custom.md
docs/content/preview/yugabyte-cloud/managed-security/managed-authentication/federated-entra.md
docs/content/preview/yugabyte-cloud/managed-security/managed-authentication/federated-jump.md
docs/content/preview/yugabyte-cloud/managed-security/managed-authentication/federated-okta.md
docs/content/preview/yugabyte-cloud/managed-security/managed-authentication/federated-ping.md
docs/content/preview/yugabyte-platform/alerts-monitoring/prometheus-custom/_index.md
docs/content/preview/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes-k8s.md
docs/content/stable/manage/backup-restore/_index.md
docs/content/stable/yugabyte-platform/alerts-monitoring/prometheus-custom/_index.md
docs/content/stable/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes-k8s.md
docs/content/v2.20/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes-k8s.md
docs/content/v2024.1/yugabyte-platform/alerts-monitoring/prometheus-custom/_index.md
docs/content/v2024.1/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes-k8s.md
docs/content/v2024.2/yugabyte-platform/alerts-monitoring/prometheus-custom/_index.md
docs/content/v2024.2/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes-k8s.md

Fix namespaced RBAC in k8s
References to password Auth in Aeon
Format
@netlify /preview/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-nodes-k8s/

[DOC-932] Fix namespaced RBAC in k8s

---

docs/content/v2024.2/yugabyte-platform/security/enable-encryption-in-transit/add-certificate-kubernetes.md

@netlify /v2024.2/yugabyte-platform/security/enable-encryption-in-transit/add-certificate-kubernetes/#configurable-common-name

[DOC-921] [2024.2.5]Added a custom common name override

---

docs/content/preview/develop/learn/transactions/acid-transactions-ycql.md
docs/content/preview/develop/learn/transactions/transactions-global-apps.md
docs/content/preview/drivers-orms/c/ysql.md
docs/content/preview/drivers-orms/csharp/postgres-npgsql.md
docs/content/preview/drivers-orms/nodejs/prisma.md
docs/content/preview/drivers-orms/smart-drivers-ycql.md
docs/content/preview/drivers-orms/smart-drivers.md

[doc] Minor fixes

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/azure.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/azure.md
docs/content/v2.20/yugabyte-platform/configure-yugabyte-platform/azure.md
docs/content/v2024.1/yugabyte-platform/configure-yugabyte-platform/azure.md
docs/content/v2024.2/yugabyte-platform/configure-yugabyte-platform/azure.md

Note on runtime config for Azure images
@netlify /preview/yugabyte-platform/configure-yugabyte-platform/azure/#use-a-shared-image-gallery

[DOC-274] Note on runtime config for Azure images

---

docs/content/preview/yugabyte-platform/upgrade/prepare-to-upgrade.md
docs/content/stable/yugabyte-platform/upgrade/prepare-to-upgrade.md
docs/content/v2024.2/yugabyte-platform/upgrade/prepare-to-upgrade.md

Clarify python req applies only to YBA node
@netlify /preview/yugabyte-platform/upgrade/prepare-to-upgrade

[doc][yba] Clarify python req

---

docs/content/preview/admin/yb-admin.md
docs/content/stable/admin/yb-admin.md
docs/content/v2.20/admin/yb-admin.md
docs/content/v2024.1/admin/yb-admin.md
docs/content/v2024.2/admin/yb-admin.md

Add note on using yb-admin
@netlify /preview/admin/yb-admin/

[doc][yba] Add note on using yb-admin

---

docs/content/preview/develop/tutorials/AI/_index.md
docs/content/preview/develop/tutorials/AI/mcp-server.md

MCP tutorial
@netlify /preview/develop/tutorials/ai/mcp-server/

[DOC-879] MCP tutorial

---

docs/content/preview/explore/observability/pg-locks.md
docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/explore/observability/pg-locks.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/v2.20/explore/observability/pg-locks.md
docs/content/v2.20/reference/configuration/yb-tserver.md
docs/content/v2024.1/explore/observability/pg-locks.md
docs/content/v2024.1/reference/configuration/yb-tserver.md
docs/content/v2024.2/explore/observability/pg-locks.md
docs/content/v2024.2/reference/configuration/yb-tserver.md
docs/netlify.toml

Reformat pg_locks page
@netlify /preview/explore/observability/pg-locks/

[DOC-993] Reformat pg_locks page

---

docs/content/preview/releases/yba-releases/v2024.2.md
docs/content/preview/releases/yba-releases/v2025.1.md

[doc] Fix to highlight wording

---

docs/content/preview/manage/upgrade-deployment.md
docs/content/preview/yugabyte-cloud/cloud-clusters/_index.md
docs/content/preview/yugabyte-cloud/cloud-clusters/cloud-maintenance.md
docs/content/preview/yugabyte-cloud/cloud-clusters/database-upgrade.md
docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software.md

DOC-896
@netlify /preview/yugabyte-cloud/cloud-clusters/cloud-maintenance/#what-to-expect-during-maintenance

[DOC-702][ybm] DB upgrades on Aeon

---

docs/content/preview/yugabyte-cloud/release-notes.md

Deploy preview - https://deploy-preview-28825--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-cloud/release-notes/

[DOC-1000] Added release notes for Aeon
