yugabyte/yugabyte-db

docs/README.md

Docs directory for design docs, discussions, etc. Also added a basic README.

Created a docs directory

---

cloud/kubernetes/helm/yugabyte-rbac.yaml
cloud/kubernetes/helm/yugabyte/.helmignore
cloud/kubernetes/helm/yugabyte/Chart.yaml
cloud/kubernetes/helm/yugabyte/templates/NOTES.txt
cloud/kubernetes/helm/yugabyte/templates/_helpers.tpl
cloud/kubernetes/helm/yugabyte/templates/service.yaml
cloud/kubernetes/helm/yugabyte/values.yaml

Add YugaByte helm chart and rbac yaml

---

cloud/kubernetes/helm/README.md

Create README.md for helm

---

cloud/kubernetes/helm/yugabyte/Chart.yaml
cloud/kubernetes/helm/yugabyte/values.yaml

Tested by running
`helm package`
and 
`helm install yugabyte-1.0.4.tgz --name demo --wait`

Bump helm chart version and add storageClassName

---

cloud/kubernetes/helm/README.md
cloud/kubernetes/helm/yugabyte/templates/NOTES.txt
cloud/kubernetes/helm/yugabyte/templates/service.yaml

- Remove Release Name from the labels
- Use namespaces for helm install

Remove release name

---

README.md

Add GA Tracking

---

README.md

Put useReferer in proper url

---

cloud/kubernetes/helm/yugabyte/values.yaml

Change the version tag to latest

---

cloud/kubernetes/helm/README.md
cloud/kubernetes/helm/expose-all-shared.yaml
cloud/kubernetes/helm/expose-all.yaml
cloud/kubernetes/helm/yugabyte/templates/NOTES.txt
cloud/kubernetes/helm/yugabyte/templates/service.yaml
cloud/kubernetes/helm/yugabyte/values.yaml

Validated by running
Expose master ui alone using loadbalancer (Default).
`helm install yugabyte --name demo --debug --dry-run`
Expose all the service (YQL, YEDIS) endpoints using one shared loadbalancer
`helm install yugabyte -f expose-all-shared.yaml --name demo --debug --dry-run`
Expose all the service (YQL, YEDIS) endpoints using one individual loadbalancers
`helm install yugabyte -f expose-all.yaml --name demo --debug --dry-run`

Add loadbalancer option

---

cloud/kubernetes/helm/yugabyte/Chart.yaml

Tested via helm install command and validated.
`helm install yugabyte`

Change Helm chart version label to be latest

---

cloud/kubernetes/helm/yugabyte/templates/service.yaml

This fixes master/tserver pod failure cases.

Added broadcast address for stable pod IDs in K8s.

---

cloud/kubernetes/helm/README.md

Fix helm charts docs bug

---

cloud/kubernetes/helm/yugabyte/templates/service.yaml
cloud/kubernetes/helm/yugabyte/values.yaml

Previous commit didn't function as expected (https://github.com/YugaByte/yugabyte-db/pull/751).
This PR fixes the issue.

Fixed service.yaml for disabling loadbalancers

---

cloud/kubernetes/helm/yugabyte/templates/service.yaml

Add gflag input for num_cpus, ignoring any related undefined gflag errors.

Add num_cpus gflag input

---

bin/yb-docker-ctl

Moving yb-docker-ctl to CE from devops.

Added yb-docker-ctl to CE

---

cloud/kubernetes/helm/generate_kubeconfig.py

Tested by running
`./cloud/kubernetes/helm/generate_kubeconfig.py -s yugabyte-helm`
fixes: #1334

Fix a bug with generate kubeconfig script

---

docs/content/latest/quick-start/build-apps/python/ycql.md
docs/content/latest/quick-start/build-apps/python/ysql-psycopg2.md

Fix Python code in build-apps page to handle Python 3 and remove side effects

---

docs/layouts/partials/footer_js.html

Relates to #1757 
The page will not scroll on newer browsers; however, on older browsers you will still see the page jump to the section.

Fix anchor link not updating the URL and preventing the page from scrolling

---

docs/content/latest/quick-start/build-apps/python/ysql-psycopg2.md

Fixes #1718 
Implemented Bryn's suggestions for Python sample code.
-Add drop table at beginning
-Remove semi-colons

Add drop table prior to create, remove semi-colons

---

docs/content/latest/develop/learn/ysql_date_and_times

I closed the previous Pull request as the changes were too significant. I fixed some errors I missed and added a bit more relevant content.

Revised YSQL Date and Time doco

---

docs/content/latest/deploy/public-clouds/gcp.md
docs/content/latest/deploy/public-clouds/gcp/terraform.md

Added document for the deployment of Yugabyte cluster in GCP cloud using terraform module.

Added document for GCP terraform deployment

---

docs/content/latest/deploy/public-clouds/azure.md
docs/content/latest/deploy/public-clouds/azure/terraform.md

Added document for the deployment of Yugabyte cluster in Azure cloud using terraform module.

Added document for azure terraform module

---

README.md

Update links in the ReadMe

---

docs/content/v1.2/develop/learn/working_with_strings

New file for Develop/Learn YSQL

---

docs/content/latest/deploy/manual-deployment/system-config.md

Described what steps need to be taken to persist the recommended ulimit configuration across restarts and provided the configuration lines.

Added notes on persistent ulimit configuration

---

docs/README.md

Some minor edits to [the docs README](docs/README.md).  Mainly updating
outdated references.

[docs] README fixes

---

docs/content/latest/_index.html
docs/content/v1.0/_index.html
docs/content/v1.1/_index.html
docs/content/v1.2/_index.html
docs/layouts/_default/list.html
docs/layouts/_default/single.html

- Changed "older" to "earlier"
- Changed "v1.2 — recommend upgrading to latest (v1.3)", and others.

Update wording for latest and earlier versions.

---

docs/content/latest/_index.html
docs/content/latest/deploy/_index.md
docs/content/latest/deploy/kubernetes/_index.html
docs/content/latest/deploy/kubernetes/helm-chart.md
docs/content/latest/deploy/kubernetes/helm-configuration.md
docs/content/latest/deploy/kubernetes/rook-operator.md
docs/content/v1.0/_index.html
docs/content/v1.1/_index.html
docs/content/v1.2/_index.html
docs/layouts/_default/list.html
docs/layouts/_default/single.html

Added to Deploy > Kubernetes section.

Add Rook operator page

---

docs/content/latest/releases/v2.0.0.md
docs/content/latest/secure/tls-encryption/_index.md
docs/content/latest/secure/tls-encryption/client-to-server.md

- Found two more client-server TLS notes to update.
- Review and edit 2.0 release notes, including deleting duplicate issue.

Two more client-server TLS note fixes and edits

---

docs/content/latest/architecture/docdb/performance.md
docs/content/v1.2/architecture/docdb/performance.md
docs/content/v1.3/architecture/docdb/performance.md

Fix typo in performace.md

---

docs/content/latest/architecture/_index.html

Fix bad icon link

---

docs/content/latest/manage/backup-restore/_index.md
docs/content/latest/manage/backup-restore/snapshots.md

fixes links,menu,overview,inside-menu and makes page nicer

Doc snapshot fix

---

docs/content/latest/quick-start/build-apps/go/ycql.md
docs/content/latest/quick-start/build-apps/go/ysql-pq.md
docs/content/latest/quick-start/build-apps/nodejs/ycql.md
docs/content/latest/quick-start/build-apps/nodejs/ysql-pg.md
docs/content/latest/quick-start/build-apps/python/ycql.md
docs/content/latest/quick-start/build-apps/python/ysql-psycopg2.md
docs/content/latest/quick-start/build-apps/ruby/ycql.md
docs/content/latest/quick-start/build-apps/ruby/ysql-pg.md

A few simple link fixes for the quick start guide :)

[Docs] fix quick start app guide broken links

---

docs/content/latest/deploy/cdc/cdc-to-stdout.md
docs/content/latest/deploy/replicate-2dc.md
docs/content/latest/explore/binary/auto-sharding.md
docs/content/latest/explore/binary/fault-tolerance.md
docs/content/latest/explore/binary/global-distribution.md
docs/content/latest/explore/binary/linear-scalability.md
docs/content/latest/explore/binary/observability.md
docs/content/latest/explore/binary/tunable-reads.md
docs/content/latest/explore/docker/fault-tolerance.md
docs/content/latest/explore/docker/linear-scalability.md
docs/content/latest/explore/docker/observability.md
docs/content/latest/explore/docker/tunable-reads.md
docs/content/latest/explore/fault-tolerance.md
docs/content/latest/explore/kubernetes/fault-tolerance.md
docs/content/latest/explore/kubernetes/linear-scalability.md
docs/content/latest/explore/kubernetes/tunable-reads.md
docs/content/latest/explore/linear-scalability.md

Based on changes made in the name of the repo tool by Sid, this updates the name used in the Explore Core examples. Also, made updates on some of the steps in the examples.

Rename yb-sample-apps.jar in examples and update content.

---

docs/content/latest/admin/ysqlsh.md
docs/content/latest/deploy/manual-deployment/start-masters.md
docs/content/latest/deploy/manual-deployment/start-tservers.md
docs/content/latest/secure/authentication/ycql-authentication.md

Adds enabling YSQL in YB-Master and removed initdb step in YB-TServer.
Closes https://github.com/yugabyte/yugabyte-db/issues/2641.

YSQL deploy fix

---

docs/content/latest/admin/_index.html
docs/content/latest/admin/yb-admin.md

Adds yb-admin page to CLIs section.

yb-admin page

---

CONTRIBUTORS.md

Adding myself to contributors per https://github.com/yugabyte/yugastore/pull/3#issuecomment-544001480. Excited to be here!

contributors: add hasheddan

---

docs/content/latest/quick-start/binary/create-local-cluster.md
docs/content/latest/quick-start/binary/macos-install.md
docs/content/latest/quick-start/build-apps/java/ycql.md
docs/content/latest/quick-start/build-apps/java/ysql-jdbc.md
docs/content/latest/quick-start/build-apps/java/ysql-spring-data.md
docs/content/latest/secure/authentication/_index.md
docs/content/latest/secure/authentication/client-authentication.md
docs/content/latest/secure/authentication/ycql-authentication.md
docs/content/latest/secure/authentication/yedis-authentication.md
docs/content/latest/secure/authentication/ysql-authentication.md
docs/content/latest/secure/authorization/_index.md
docs/content/latest/secure/encryption-at-rest.md
docs/content/latest/secure/tls-encryption/_index.md

- Changed authentication to multi-tab page.
- Improved quick-start based on feedback from user.
- Fixed navigation issue, some items missing parent in front-matter.

YSQL fixes

---

docs/content/latest/admin/yb-admin.md
docs/styles/_yuga_overrides.scss

- Add styles for headings used in yb-admin
- Format and tweaks to yb-admin syntax.

Add CSS for h5 and h6 and format changes

---

docs/content/_index.html
docs/content/latest/_index.html
docs/content/latest/admin/_index.html
docs/content/latest/admin/yb-admin.md

- Fixes to navigation and sections.
- Added note to `set_preferred_zones`.
- Other tweaks.

Yb admin update 3

---

docs/styles/_yuga_overrides.scss

Change font size for h6

---

docs/styles/_yuga_overrides.scss

Makes breadcrumbs more visible.

Change breadcrumb size and weight

---

docs/content/latest/admin/yb-admin.md
docs/content/latest/secure/encryption-at-rest.md
docs/content/latest/secure/security-checklist.md

- Add note that YSQL is not supported.
- Add links to new `yb-admin` content related to encryption at rest.

Encryption at rest update

---

docs/content/latest/admin/yb-master.md
docs/content/latest/admin/yb-tserver.md
docs/content/latest/architecture/concepts/universe.md
docs/content/latest/deploy/kubernetes/helm-chart.md
docs/content/latest/deploy/manual-deployment/start-masters.md
docs/content/latest/deploy/public-clouds/aws/manual-deployment.md

- Update content about enabling YSQL.
- Fix wrong link.
- Update naming.

Update enable YSQL

---

docs/content/latest/deploy/_index.md
docs/content/latest/deploy/cdc/cdc-to-kafka.md
docs/content/latest/deploy/cdc/cdc-to-stdout.md
docs/content/latest/quick-start/explore-ysql.md

Also, removed syntax-highlighting from a couple of result displays in Explore YSQL.

Add wget downloads for JAR file

---

docs/content/latest/releases/v2.0.1.md
docs/content/latest/releases/v2.0.3.md

Remove "Release highlights" from 2.0.1 and 2.0.3 release notes.

Remove highlights

---

docs/content/latest/admin/yb-master.md
docs/content/latest/admin/yb-tserver.md
docs/content/latest/secure/tls-encryption/client-to-server.md
docs/content/latest/secure/tls-encryption/connect-to-cluster.md
docs/content/latest/secure/tls-encryption/server-to-server.md
docs/content/latest/troubleshoot/nodes/check-logs.md

- Fixes #2803 (Add log options to yb-master and yb-tserver pages)
- Adds security and CDC options

Config updates

---

docs/content/latest/admin/yb-ctl.md
docs/content/latest/explore/binary/linear-scalability.md
docs/content/latest/explore/linear-scalability.md
docs/content/latest/quick-start/binary/macos-install.md

Adds steps to verify loopback addresses and note in Linear scalability for macOS.

[docs] Add loopback steps and note

---

docs/content/latest/admin/yb-admin.md
docs/content/latest/admin/yb-ctl.md
docs/content/latest/admin/yb-master.md
docs/content/latest/admin/yb-tserver.md
docs/content/latest/sample-data/_index.html

- Add syntax and examples for yb-admin master_addresses.
- Tweak syntax and help options for CLIs.

[docs] Update "yb-admin" syntax and examples

---

docs/content/latest/deploy/public-clouds/_index.html
docs/content/latest/deploy/public-clouds/azure.md
docs/content/latest/deploy/public-clouds/azure/azure-arm.md
docs/content/latest/deploy/public-clouds/gcp.md
docs/content/latest/deploy/public-clouds/gcp/gcp-deployment-manager.md

I have updated the docs for Azure arm template and GCP deployment manager.

Docs updated for various deployment method.

---

docs/content/latest/explore/_index.md
docs/content/latest/explore/binary/two-data-centers.md
docs/content/latest/explore/two-data-centers.md

- Fix numbering
- Add links to design documents.
- Shorten navtitle.
- Fix code example.

Update "Two data center deployment" example

---

docs/content/latest/admin/cqlsh.md
docs/content/latest/admin/yb-admin.md
docs/content/latest/deploy/kubernetes/yugabyte-operator.md
docs/content/latest/deploy/manual-deployment/_index.html
docs/content/latest/deploy/manual-deployment/start-masters.md
docs/content/latest/deploy/manual-deployment/start-tservers.md
docs/content/latest/deploy/public-clouds/aws/manual-deployment.md
docs/content/latest/explore/binary/auto-sharding.md
docs/content/latest/explore/binary/two-data-centers.md
docs/content/latest/quick-start/docker/create-local-cluster.md
docs/content/latest/quick-start/kubernetes/create-local-cluster.md
docs/content/latest/reference/configuration/_index.md
docs/content/latest/reference/configuration/yb-master.md
docs/content/latest/reference/configuration/yb-tserver.md
docs/content/latest/secure/security-checklist.md
docs/content/latest/secure/tls-encryption/server-to-server.md

- Reordered YB-TServer before YB-Master.
- Changed YB-Master node to YB-Master service.
- Changed YB-TServer node to YB-TServer service.

Services fix

---

docs/content/latest/api/ycql/ddl_create_index.md
docs/content/latest/api/ycql/ddl_create_table.md
docs/content/latest/api/ysql/commands/ddl_create_table.md

- For YCQL and YSQL.
- Mentioned adding to CREATE INDEX, but doc'ing after updates to syntax and syntax diagrams.

Add "WITH tablets" to CREATE TABLE

---

docs/content/latest/secure/tls-encryption/_index.md

- Remove "(Yugabyte Platform only)"
- Add YSQL to server-server encryption."

Update encryption support

---

architecture/design/multi-region-2DC-deployment.md

Add log retention by op id policy documentation

Add log retention by op id policy documentation

---

docs/content/latest/secure/encryption-at-rest.md

Fix step number in encryption at rest doc.

[docs] Fix step number

---

docs/content/latest/api/ysql/commands/_index.md

Fix two broken links on statements listing page.

[docs] Fix two broken links

---

docs/content/latest/deploy/public-clouds/aws/cloudformation.md
docs/content/latest/deploy/public-clouds/azure/azure-arm.md
docs/content/latest/deploy/public-clouds/gcp/gcp-deployment-manager.md
docs/content/latest/deploy/public-clouds/gcp/terraform.md

Fix some of the documentation around Google and Azure deployments.

Azure/Google Deployment docs updates

---

docs/styles/_yuga_overrides.scss

Also format CSS code to be nested in scss (more idiomatically correct).

[Docs] Remove italics on all article h4 and change code font size in headers

---

architecture/design/ysql-tablet-colocation.md

* Fix lots of typos and grammar errors
* Fix some minor, incorrect information
* Make formatting more consistent
* Reduce several characters to ASCII

[docs][YSQL] Clean up colocation doc

---

architecture/design/ysql-colocated-tables.md

Add a section for the `CREATE INDEX` grammar.  Also, perform other minor edits.

[docs][YSQL] Colocation add CREATE INDEX design

---

docs/content/latest/develop/explore-sample-apps.md
docs/content/latest/quick-start/create-local-cluster.md
docs/content/latest/quick-start/install.md
docs/content/latest/quick-start/kubernetes/create-local-cluster.md
docs/content/latest/quick-start/kubernetes/install.md

Based on conflict between file and text description noted by @kmuthukk.

[docs] Update Kubernetes install page in Quick Start

---

docs/content/latest/deploy/kubernetes/helm-chart.md

- Remove section "Install YugabyteDB with YSQL"
- Remove `--set "disableYSQL=false"` in examples
- Edit and update content for clarity and usability

[docs] Update Helm content and remove install with YSQL section

---

docs/content/latest/deploy/kubernetes/helm-chart.md

- Add `--set "disableYsql=false"` flag to install examples
- Add note about needing this flag in the current version and link to track update
- Change "`yb-demo` chart" to "`yb-demo` deployment after discussing with @Arnav15.

[docs] Add enable YSQL option back and note

---

docs/content/latest/deploy/kubernetes/helm-chart.md

Update Helm chart page based on https://github.com/yugabyte/charts/pull/44:
- Remove `--set "disableYsql=false" and note about enabling YSQL.

[docs] Remove '--set disableYsql=false' and note

---

docs/content/_index.html
docs/content/latest/_index.html
docs/content/latest/admin/yb-admin.md
docs/content/latest/faq/_index.md
docs/content/latest/faq/architecture.md
docs/content/latest/faq/compatibility.md
docs/content/latest/faq/enterprise-edition.md
docs/content/latest/faq/operations-faq.md
docs/content/latest/faq/product.md
docs/content/latest/reference/configuration/yb-master.md
docs/content/latest/reference/configuration/yb-tserver.md
docs/content/latest/reference/drivers/yugabytedb-jdbc-driver.md
docs/content/latest/secure/encryption-at-rest.md

- Add new FAQ page: "Operations FAQ"
- Add FAQ topics.
- Add notes to API and configuration commands and options
- Fix heading style in yb-tserver and yb-master.
Fixes #3258, #3260, #3261, #3263, 3264.

[docs] Update FAQ content and add operations FAQ

---

docs/content/latest/deploy/enterprise-edition/install-admin-console/kubernetes.md
docs/content/latest/deploy/kubernetes/helm-chart.md

Minor edits for Yugabyte Platform Install Admin Console page for Kubernetes
https://docs.yugabyte.com/latest/deploy/enterprise-edition/install-admin-console/#kubernetes
- Update link for RBAC file
- Minor edits to steps.

[docs] Update download link and edit steps

---

docs/content/latest/faq/compatibility.md
docs/content/latest/reference/configuration/yb-tserver.md

- Based on Stack Overflow comment.
- Added link to Presto blog.

[docs] Add question on compatibility between YSQL and YCQL

---

docs/content/latest/deploy/manual-deployment/start-masters.md
docs/content/latest/deploy/manual-deployment/start-tservers.md
docs/content/latest/deploy/multi-dc/3dc-deployment.md
docs/content/latest/reference/configuration/yb-master.md
docs/content/latest/reference/configuration/yb-tserver.md

@iSignal Check the reference pages based on our discussion.
- Added hyperlinks from deployment doc pages to relevant flags/options in the configuration reference.

[docs] Update "rpc-bind-addresses" and "server-broadcast-addresses".

---

docs/content/latest/benchmark/_index.html
docs/content/latest/benchmark/tpcc.md
docs/content/latest/benchmark/ycsb.md
docs/content/latest/benchmark/ycsb/yugabytecql.md
docs/content/latest/benchmark/ycsb/yugabytesql.md

This pull request has 2 commits, one for changing the documentation for running YCSB and the other for adding the documentation for running TPCC.

Benchmark doc

---

docs/content/latest/quick-start/explore-ysql.md

[docs] Correct query results in Quick Start

---

docs/content/latest/admin/_index.html
docs/content/latest/admin/yb-ctl.md
docs/content/latest/admin/yb-ts-cli.md
docs/content/latest/admin/ysql-dump.md
docs/content/latest/admin/ysql-dumpall.md

This PR adds a new page for the `yb-ts-cli` to the CLIs reference.

[docs] Add yb-ts-cli to CLIs reference

---

docs/content/latest/deploy/docker/docker-compose.md

The current docker-compose file does not support volume mounts, so data is not persisted across restarts. Moreover, when a volume mount is added, the cluster cannot be restarted succesfully because both master and tserver are missing the `rpc_bind_addresses` parameter.

Update docker-compose file to add volume mounts

---

CONTRIBUTORS.md
LICENSE.md
bin/yb-docker-ctl
build-support/yb_release.py
cloud/README.md
cloud/kubernetes/README.md
cloud/kubernetes/design/operator_design.md
docs/content/latest/comparisons/postgresql.md
docs/content/latest/releases/v2.0.1.md
managed/ui/src/components/common/footer/Footer.js
managed/ui/src/pages/AuthenticatedComponent.js
python/yb/build_postgres.py
python/yb/postprocess_test_result.py
python/yb/yb_dist_tests.py
src/postgres/src/backend/access/index/indexam.c
src/postgres/src/backend/access/transam/varsup.c
src/postgres/src/backend/commands/indexcmds.c
src/postgres/src/backend/executor/execIndexing.c
src/postgres/src/backend/executor/ybc_fdw.c
src/postgres/src/backend/parser/gram.y
src/postgres/src/bin/initdb/initdb.c
src/yb/master/master-path-handlers.cc
src/yb/server/server_base.cc
src/yb/server/webserver.cc
src/yb/tablet/tablet_metadata.cc

made the change in files where the name was present in text files or comments/output of source files.

changed YugaByte DB to YugabyteDB

---

docs/content/latest/explore/auto-sharding-docker.md
docs/content/latest/explore/auto-sharding-kubernetes.md
docs/content/latest/explore/auto-sharding-linux.md
docs/content/latest/explore/auto-sharding-macos.md
docs/content/latest/explore/fault-tolerance-docker.md
docs/content/latest/explore/fault-tolerance-kubernetes.md
docs/content/latest/explore/fault-tolerance-linux.md
docs/content/latest/explore/fault-tolerance-macos.md
docs/content/latest/explore/linear-scalability-docker.md
docs/content/latest/explore/linear-scalability-kubernetes.md
docs/content/latest/explore/linear-scalability-linux.md
docs/content/latest/explore/linear-scalability-macos.md
docs/content/latest/explore/observability-docker.md
docs/content/latest/explore/observability-kubernetes.md
docs/content/latest/explore/observability-linux.md
docs/content/latest/explore/observability-macos.md

Fixes changes in names of images between tabs and buttons.

[docs] Fix image references

---

architecture/design/ysql-table-level-partitioning.md

Update design document for table level partitioning with additional details

Update design document for table level partitioning

---

docs/content/latest/reference/configuration/yb-tserver.md

Based on: 
https://github.com/yugabyte/yugabyte-db/commit/1040e720ec2bb8b7cd8b4937c98a7712fb6d5cc2#diff-6b50faabb7dc9a2816f5a0582b885ebcR27

[DOCS] explain --cql_table_is_transactional_by_default

---

docs/content/latest/secure/tls-encryption/_index.html
docs/content/latest/secure/tls-encryption/client-certificates.md
docs/content/latest/secure/tls-encryption/client-to-server.md
docs/content/latest/secure/tls-encryption/connect-to-cluster.md
docs/content/latest/secure/tls-encryption/server-certificates.md
docs/content/latest/secure/tls-encryption/server-to-server.md

- Use server-to-server and client-to-server instead of server-server and client-server.
- Correct titles in section page and navigation bar.

[docs] Update titles and naming

---

docs/content/latest/contribute/core-database/build-from-src-centos.md
docs/content/latest/contribute/core-database/build-from-src-macos.md
docs/content/latest/contribute/core-database/build-from-src-ubuntu.md
docs/content/latest/contribute/core-database/checklist.md

Fixes files not showing -- showed in VS Code but source control didn't recognize them.
Fixes #3706

[doc] Force add files to source control

---

docs/content/_index.html
docs/content/latest/_index.html
docs/content/latest/benchmark/ycsb-ycql.md
docs/content/latest/benchmark/ycsb-ysql.md
docs/content/latest/sample-data/_index.html
docs/content/latest/sample-data/chinook.md
docs/content/latest/sample-data/northwind.md

- Fix number of tables in Chinook sample dataset. Closes #3711
- Change title of sample data to sample datasets.
- Fix navigation link to YCSB in Benchmark.
- Make minor edits.

[docs] Fix link and edit content.

---

docs/content/latest/develop/learn/acid-transactions-ycql.md
docs/content/latest/develop/learn/acid-transactions-ysql.md
docs/content/latest/develop/learn/aggregations-ycql.md
docs/content/latest/develop/learn/aggregations-ysql.md
docs/content/latest/develop/learn/batch-operations-ycql.md
docs/content/latest/develop/learn/batch-operations-ysql.md
docs/content/latest/develop/learn/data-modeling-ycql.md
docs/content/latest/develop/learn/data-modeling-ysql.md
docs/content/latest/develop/learn/data-types-ycql.md
docs/content/latest/develop/learn/data-types-ysql.md
docs/content/latest/develop/learn/date-and-time-ycql.md
docs/content/latest/develop/learn/date-and-time-ysql.md
docs/content/latest/develop/learn/strings-and-text-ycql.md
docs/content/latest/develop/learn/strings-and-text-ysql.md

In Develop > Learn app developerment, change identifiers to properly display YSQL or YCQL based on content available.

[docs] Fix identifiers to display proper links

---

CONTRIBUTORS.md

Adding contributors https://github.com/yugabyte/yugabyte-operator/pull/6

adding contributors to the operator

---

docs/content/latest/develop/ecosystem-integrations/metabase.md
docs/content/latest/develop/learn/date-and-time-ysql.md
docs/content/latest/develop/learn/strings-and-text-ysql.md
docs/content/latest/develop/realworld-apps/retail-analytics.md
docs/content/latest/quick-start/build-apps/ysql/csharp.md
docs/content/latest/quick-start/explore-ysql/_index.md
docs/content/latest/quick-start/explore-ysql/binary/explore-ysql.md
docs/content/latest/quick-start/explore-ysql/docker/explore-ysql.md
docs/content/latest/quick-start/explore-ysql/kubernetes/explore-ysql.md

- Simplify quick start by updating to use the sample dataset files available in the `share` directory.
- Correct a value in the quick start query output.
- Change Kubernetes database name `yb_demo` to `yb-demo` to be consistent with others and in learn application development examples.

[docs] Update quick start to use .sql files in share directory

---

CONTRIBUTORS.md

Adding myself as requested: https://github.com/yugabyte/charts/pull/53

[CONTRIBUTORS] Add 'ghaskins'

---

docs/content/latest/develop/graphql/hasura.md

- Replace environment variable with new flag: `--ysql_suppress_unsupported_error`
- Edit and correct steps based on testing, including add step on making script file executable.
- Update Hasura GraphQL Engine version.
Fixes #3662

[docs] Update Hasura steps to include new ysql_suppress_unsupported_error flag

---

CONTRIBUTORS.md

For helping fix the driver examples, you can reference this [PR](https://github.com/yugabyte/yugabyte-db/pull/3800) for more info.

CONTRIBUTORS: Add `junwei0117`

---

docs/content/latest/deploy/manual-deployment/_index.html
docs/content/latest/develop/explore-sample-apps.md

[docs] Fix aliases for Michelle

---

docs/content/latest/deploy/multi-dc/read-replica-clusters.md

A quick republish adding just one word to see if we can get Netlify to publish updates.

[docs] Expand "zone" to "availability zone"

---

docs/content/google1a29d8f2fc04a31e.html

Verifies to Google that I have access.

[docs] Add Google verification file

---

docs/content/latest/secure/tls-encryption/connect-to-cluster.md
docs/content/latest/secure/tls-encryption/server-certificates.md

- Fix links to client certificate files
- Edit and correct prerequisites
- Correct cqlsh connection command
Fixes #3840

[docs] Correct prerequisites and cqlsh connection command

---

docs/content/latest/api/ysql/datatypes/type_json/_index.md
docs/content/latest/api/ysql/datatypes/type_json/create-indexes-check-constraints.md
docs/content/latest/api/ysql/datatypes/type_json/functions-operators/code-example-conventions.md
docs/content/latest/api/ysql/datatypes/type_json/functions-operators/containment-operators.md
docs/content/latest/api/ysql/datatypes/type_json/functions-operators/equality-operator.md
docs/content/latest/api/ysql/datatypes/type_json/functions-operators/json-subvalue-operators.md
docs/content/latest/api/ysql/datatypes/type_json/functions-operators/jsonb-array-elements-text.md
docs/content/latest/api/ysql/datatypes/type_json/functions-operators/jsonb-array-elements.md
docs/content/latest/api/ysql/datatypes/type_json/functions-operators/jsonb-array-length.md
docs/content/latest/api/ysql/datatypes/type_json/functions-operators/jsonb-build-array.md
docs/content/latest/api/ysql/datatypes/type_json/functions-operators/jsonb-each-text.md
docs/content/latest/api/ysql/datatypes/type_json/functions-operators/jsonb-each.md
docs/content/latest/api/ysql/datatypes/type_json/functions-operators/jsonb-to-recordset.md
docs/content/latest/manage/enterprise-edition/create-universe-multi-zone.md
docs/content/latest/secure/encryption-at-rest.md

Thanks to @jj-kim, we found another conflict and fixed, and i learned a few more of his tricks.

[docs] Resolve merge conflicts

---

docs/content/latest/api/ysql/datatypes/_index.md
docs/content/latest/api/ysql/datatypes/type_json/_index.md
docs/content/latest/api/ysql/datatypes/type_json/functions-operators/_index.md

- Fix data types table, mentioned by Kannan.
- Fix link to concatenation operators.
- Minor edits to content.

[docs] Fix display issues for data types and JSON subsections

---

docs/content/latest/api/ycql/ddl_create_table.md
docs/content/latest/api/ysql/commands/ddl_create_table.md
docs/content/latest/reference/configuration/yb-master.md
docs/content/latest/reference/configuration/yb-tserver.md

- Add `--ysql_num_shards_per_tserver` to `yb-master` configuration options
- Add notes to --ysql_num_shards_per_tserver` and `ysql` `CREATE TABLE` on behavior.

[docs] Add ysql_num_shards_per_tserver and update yb_num_shards_per_tserver

---

docs/content/latest/api/_index.html
docs/content/latest/reference/configuration/_index.html
docs/content/latest/reference/configuration/default-ports.md
docs/content/latest/reference/configuration/yb-master.md
docs/content/latest/reference/configuration/yb-tserver.md

- Change yb-tserver and yb-master config section from "Cluster options" to "Sharding options" 
- recommended by @ndeodhar 
- Add and update front matter content for SEO improvement

[docs] Update configuration section title and front matter

---

docs/content/latest/architecture/docdb/colocated-tables.md

- Adds beta flag to [Colocated tables](https://docs.yugabyte.com/latest/architecture/docdb/colocated-tables/) topic in the Architecture section.

[docs] Add beta flag to colocated table topic

---

docs/content/latest/api/ysql/commands/ddl_create_database.md
docs/content/latest/api/ysql/commands/ddl_create_table.md

Missed adding beta status note to CREATE TABLE. 
- Note about status in CREATE DATABASE.
- "Colocated tables" topic has BETA flag.

Add beta note to CREATE TABLE

---

docs/content/latest/develop/learn/batch-operations-ycql.md

[docs] fix missing ul breaking code fragment

---

docs/content/latest/admin/ysql-dump.md

Change header from "Connection options" to "Database connection options".

[docs] Fix broken internal link

---

docs/styles/_yuga_overrides.scss

[#4059][Docs] Add margin to code block if it is inside an anchor tag

---

.github/workflows/build.yml
python/yb/download_and_extract_archive.py

Adding a basic build of non-test code (what's needed by the release package) in a CentOS Docker image on GitHub Actions.

Add a GitHub Actions build

---

docs/content/latest/secure/authentication/ysql-authentication.md

Fix minor typo with ysql_enable_auth

---

docs/content/latest/develop/best-practices-ycql.md

Please only exact fixes, or remove sections, or graphic fixes.
docdb:
ysql:
ycql:

[docs] best practices ycql v1

---

docs/layouts/partials/head.html

Use page level description if it exists, otherwise fallback to existing hard coded string. Add additional OG tags and link page to Yugabyte FB page.

[#4166][Docs] Add OG description to html head and include some additional tags

---

docs/content/latest/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/oss/operator-hub.md
docs/content/latest/deploy/kubernetes/single-zone/oss/rook-operator.md
docs/content/latest/deploy/kubernetes/single-zone/oss/yugabyte-operator.md
docs/content/latest/manage/enterprise-edition/node-actions.md
docs/content/latest/manage/enterprise-edition/read-replicas.md
docs/content/latest/yedis/api/flushall.md
docs/content/latest/yedis/api/flushdb.md

- Change gflag to flag when not explicitly hard-coded.
- Add headerTitle to front matter and edit content.

[doc] Change gflag to flag

---

docs/content/latest/deploy/checklist.md

[docs] zfs is not supported

---

docs/content/latest/architecture/_index.md

[docs] fix architecture page layout+images

---

docs/content/latest/reference/configuration/default-ports.md

Correct port numbers for Prometheus monitoring.

[docs] Correct port numbers for monitoring

---

src/yb/tserver/tablet_server.cc

#4107: Minor fix to http://yb-tserver:9000/utilz page

---

docs/content/latest/deploy/kubernetes/clients.md

This is a rough draft of documentation that describes how clients should connect to Kubernetes clusters.
https://github.com/yugabyte/yugabyte-db/issues/2925 
My plan is not to merge this as it is, because I am pretty sure this doesn't seem like a professional docs page. It is meant to list all the commands involved and provide an outline for @stevebang or someone else to start with.
CC: @Arnav15 @ramkumarvs  for feedback.

Client connections to Kubernetes

---

sample/airflowybrepo.sql

Redo because of formatting issue from Slack file

Open and save SQL script

---

docs/content/latest/yedis/develop/client-drivers/yedis/nodejs.md

[docs] fix link to yedis quickstart

---

docs/content/latest/architecture/transactions/_index.md
docs/content/latest/architecture/transactions/distributed-txns.md
docs/content/latest/architecture/transactions/explicit-locking.md
docs/content/latest/architecture/transactions/isolation-levels.md
docs/content/latest/architecture/transactions/single-row-transactions.md
docs/content/latest/architecture/transactions/transactional-io-path.md
docs/content/latest/architecture/transactions/transactions-overview.md

Added information about the following topics:
* Overview of transactions
* Hybrid logical clocks
* Concurrency control topics
* Explicit row-locking

Updated transactions architecture section in docs

---

docs/content/latest/benchmark/_index.md
docs/content/latest/benchmark/sysbench-ysql.md
docs/content/latest/benchmark/sysbench.md

Add steps for running sysbench against YSQL.

---

.github/workflows/create-repository-dispatch.yml

Signed-off-by: Sameer Kulkarni <samkulkarni20@gmail.com>
Create repository_dispatch event to trigger github actions of below listed repositories:
- yugabyte/terraform-gcp-yugabyte
- yugabyte/terraform-aws-yugabyte
- yugabyte/terraform-azure-yugabyte
- yugabyte/azure-resource-manager
- yugabyte/gcp-deployment-manager
- yugabyte/aws-cloudformation
- yugabyte/homebrew-yugabytedb
- yugabyte/utilities

Create Repository_dispatch event

---

docs/content/latest/sample-data/pgexercises.md

Two examples that didn't work before are now working. Removed these from the page.

[docs] Remove two exceptions that now work

---

docs/content/latest/api/ysql/extensions.md

[docs] Document postgresql-hll extension

---

docs/content/latest/benchmark/sysbench-ysql.md

Sysbench Docs: Add expected results for the run.

---

docs/content/latest/benchmark/ycsb-jdbc.md
docs/content/latest/benchmark/ycsb-ycql.md

Adding expected results to the YCSB docs.

---

docs/content/latest/architecture/docdb-replication/_index.md
docs/content/latest/architecture/docdb-sharding/_index.md
docs/content/latest/benchmark/ycsb-jdbc.md
docs/content/latest/benchmark/ycsb-ysql.md
docs/content/latest/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/gke/statefulset-yaml-local-ssd.md
docs/content/latest/deploy/kubernetes/single-zone/gke/statefulset-yaml.md
docs/content/latest/explore/global-distribution/macos.md

Fixed duplicate meta descriptions based on April 30 report.

[docs] Fix duplicate meta descriptions based on generated report

---

docs/content/latest/benchmark/ycsb-jdbc.md
docs/content/latest/benchmark/ycsb-ycql.md
docs/content/latest/benchmark/ycsb-ysql.md

YCSB doc improvements.

---

docs/content/latest/benchmark/sysbench-ysql.md

Changes to sysbench documentation to align with YCSB documentation.

---

docs/content/latest/deploy/checklist.md

[docs] fixed missing newline & added nfs-issue roadmap

---

docs/content/latest/secure/authentication/ysql-authentication.md
docs/content/v2.0/secure/authentication/ysql-authentication.md

docs: fix ysql create role with password 'pass'

---

.github/workflows/create-repository-dispatch.yml

1. Added repository dispatch event URL for the "yugabyte/charts" repo.
2. Modified repository dispatch event URL for the "yugabyte/homebrew-yugabytedb" as per the [update-formula-version.yaml](https://github.com/yugabyte/homebrew-yugabytedb/blob/master/.github/workflows/update-formula-version.yaml).

Added repository dispatch event url for yugabyte/charts repo

---

docs/content/latest/deploy/public-clouds/azure/terraform.md

- Modifies the document according to the updated instructions from
README.md of terraform-azure-yugabyte repository. https://github.com/yugabyte/terraform-azure-yugabyte
- Created a stack by following the instructions

[docs] update the instructions according to terraform-azure-yugabyte

---

docs/content/latest/explore/global-distribution/linux.md
docs/content/latest/explore/global-distribution/macos.md

Fixing the broken link to the yb-sample-apps.jar

[docs] fix link to yb-sample-apps jar

---

CONTRIBUTORS.md

- Added [baba230896 ](https://github.com/baba230896)as a contributor

Added baba230896 as contributor

---

docs/content/latest/develop/graphql/hasura.md

Removes step about using the yb-tserver flag `--ysql_suppress_unsupported_error`.

[docs] Update Hasura page to remove unnecessary flag

---

docs/content/latest/develop/graphql/hasura.md

Reverts yugabyte/yugabyte-db#4497
Broke Netlify build

Revert "[docs] Update Hasura page to remove unnecessary flag"

---

docs/content/latest/contribute/core-database/run-unit-tests.md

From https://yugabyte-db.slack.com/archives/G014789RAQ4/p1590124011026800

[DOCS] explain ysql java tests

---

docs/content/latest/architecture/docdb-replication/read-replicas.md
docs/content/latest/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/v1.2/deploy/kubernetes/helm-configuration.md
docs/content/v1.3/deploy/kubernetes/helm-configuration.md
docs/content/v2.0/deploy/kubernetes/oss/helm-chart.md

fixed doc bug reported in https://github.com/yugabyte/yugabyte-db/issues/4631

fixed doc bug in storageClass config

---

docs/content/latest/manage/data-migration/ycql/bulk-import.md

[docs] Fix formatting issue

---

java/yb-cql/src/test/java/org/yb/cql/BaseAuthenticationCQLTest.java
java/yb-cql/src/test/java/org/yb/cql/TestAuthentication.java
java/yb-cql/src/test/java/org/yb/cql/TestAuthenticationCached.java
src/yb/yql/cql/cqlserver/cql_processor.cc
src/yb/yql/cql/cqlserver/cql_service.cc
src/yb/yql/cql/cqlserver/cql_service.h

Implements a password cache to allow connections to be created more quickly from recently used accounts. Closes or ameliorates #4596 .

Password cache

---

docs/content/latest/deploy/enterprise-edition/install-admin-console/kubernetes.md
docs/content/latest/deploy/public-clouds/aws/manual-deployment.md
docs/content/latest/manage/enterprise-edition/_index.md
docs/content/latest/manage/enterprise-edition/migrate-to-helm3.md
docs/content/latest/quick-start/install/linux.md
docs/content/latest/quick-start/install/macos.md
docs/content/latest/releases/whats-new/_index.md

Before merging, change `b??` to release build and update release date.

[docs] Update docs for 2.1.8.2

---

docs/content/latest/admin/yb-ctl.md
docs/content/latest/quick-start/create-local-cluster/linux.md
docs/content/latest/quick-start/create-local-cluster/macos.md
docs/content/v2.0/quick-start/create-local-cluster/linux.md

- Updates to the Linux and Mac sections of "Create a local cluster" based on feedback from @robertsami, @iSignal,  and @bmatican.

[docs] Update quick start

---

java/yb-pgsql/src/test/java/org/yb/pgsql/TestPgRegressWindow.java
src/postgres/src/test/regress/expected/yb_pg_window.out
src/postgres/src/test/regress/sql/yb_pg_window.sql
src/postgres/src/test/regress/yb_pg_window_schedule

I created TestPgRegressWindow.java using yb_pg_window.{sql, out} based on the PostgreSQL regress test framework window.out file. 
All the queries that were not working have been commented out in yb_pg_window.out(And all reported as an issue). For most of the queries, I added ORDER BY to ensure the same output. (outlined in issue-4832)
EDIT: Issue-4832, which addresses the queries that have not been working in the test, has been resolved and the updated code in yb_pg_window.sql has no queries commented out and all the tests are passing as expected.

Window Function Unit Tests

---

docs/content/latest/benchmark/tpcc-ysql.md

[docs] TPCC doc changes to reflect the new changes made in the code.

---

docs/content/latest/architecture/transactions/distributed-txns.md

- Reflected the change which makes provisional records storage a separate RocksDB instance
- Fixed typos and formatting

Updated distributed-txns.md and fixed some typos

---

docs/content/latest/benchmark/tpcc-ysql/10-wh/tpcc-ysql.md
docs/content/latest/benchmark/tpcc-ysql/100-wh/tpcc-ysql.md
docs/content/latest/benchmark/tpcc-ysql/1000-wh/tpcc-ysql.md
docs/content/latest/benchmark/tpcc-ysql/_index.md

[docs] Add Results on the top of the TPC-C page.

---

docs/content/latest/api/ycql/ddl_create_index.md
docs/content/latest/api/ysql/commands/ddl_create_index.md

Add note on index backfill to YCQL and YSQL `CREATE INDEX` reference pages.

Add note on index backfill

---

architecture/design/docdb-automatic-tablet-splitting.md

Preview before merge: https://github.com/ttyusupov/yugabyte-db/blob/update-tablet-splitting-docs/architecture/design/docdb-automatic-tablet-splitting.md

Updated tablet splitting architecture design doc

---

docs/content/latest/deploy/checklist.md

Closes #5167 -- thanks, @jiaolongxue!

[docs] Fix network port for ysql

---

docs/content/latest/benchmark/tpcc-ysql/10-wh/tpcc-ysql.md
docs/content/latest/benchmark/tpcc-ysql/100-wh/tpcc-ysql.md
docs/content/latest/benchmark/tpcc-ysql/1000-wh/tpcc-ysql.md
docs/content/latest/benchmark/tpcc-ysql/10000-wh/tpcc-ysql.md
docs/content/latest/benchmark/tpcc-ysql/_index.md

Added instructions to run 10k warehouses.

---

docs/content/latest/benchmark/ycsb-jdbc.md
docs/content/latest/benchmark/ycsb-ycql.md
docs/content/latest/benchmark/ycsb-ysql.md

Change the YCSB instructions to use 32 threads for loading.

---

docs/content/latest/deploy/kubernetes/single-zone/aks/helm-chart.md

[docs] Update node-vm-size and helm install

---

docs/content/latest/deploy/checklist.md

[docs] add security checklist to deploy-checklist

---

docs/content/latest/comparisons/cassandra.md

fixes https://github.com/yugabyte/yugabyte-db/issues/3671

[DOCS] disk space relief when adding new nodes compared to cassandra

---

docs/content/latest/api/ysql/extensions.md

fixes https://github.com/yugabyte/yugabyte-db/issues/4730

docs: explain pg_stat_statements in YSQL extensions.md

---

docs/content/latest/develop/best-practices-ycql.md

fixes:https://github.com/yugabyte/yugabyte-db/issues/5056

docs: big collections in YCQL Best Practices

---

docs/content/latest/reference/drivers/_index.md
docs/content/latest/reference/drivers/ycql-client-drivers.md
docs/content/latest/reference/drivers/ysql-client-drivers.md
docs/content/latest/yugabyte-platform/deploy/configure-cloud-providers/kubernetes.md
docs/content/latest/yugabyte-platform/deploy/install-admin-console/kubernetes.md

- Fix broken link to Create a cluster.
- Add Kubernetes secret to prerequisites.
- Change titles for YCQL and YSQL drivers pages.

[docs] Updates based on feedback

---

java/yb-cql/src/test/java/org/yb/cql/BaseCQLTest.java
src/yb/yql/cql/cqlserver/CMakeLists.txt
src/yb/yql/cql/cqlserver/cql_processor.cc
src/yb/yql/cql/cqlserver/cql_processor.h
src/yb/yql/cql/cqlserver/cql_service.cc
src/yb/yql/cql/cqlserver/cql_service.h
src/yb/yql/cql/cqlserver/system_query_cache.cc
src/yb/yql/cql/cqlserver/system_query_cache.h

Draft of system query cache; not currently fetching from master.

#5306 Create system cache.

---

docs/content/latest/manage/data-migration/ycql/bulk-import.md

remove unmaintained database importer
change small-medium-large --> small-large

[docs] remove unmaintained database importer

---

docs/content/latest/benchmark/tpcc-ysql/_index.md

[docs] Point to our fork of oltpbench in the TPC-C docs page.

---

docs/config.yaml

Switching from internal scraping to Algolia. 
- Update index name and app key.
- @ramkumarvs disabled internal scraping today.

[docs Update DocSearch settings

---

docs/content/latest/api/ysql/commands/cmd_copy.md

[docs] Added examples for COPY in YSQL

---

docs/content/latest/reference/configuration/yugabyted.md

[docs] yugabyted collect_logs, connect commands

---

docs/content/latest/deploy/manual-deployment/system-config.md

[docs] systemd config example for ulimits

---

docs/content/latest/quick-start/build-apps/java/ysql-jdbc.md

Replace Java code example.
Replace Maven dependency description not used in the example.

[docs] Fix java ysql jdbc example

---

docs/content/latest/secure/tls-encryption/server-to-server.md

From: https://yugabyte.slack.com/archives/C0133L58J92/p1598069240047700?thread_ts=1598068204.028200&cid=C0133L58J92

[docs] Allow insecure connections is available in yb-tserver

---

docs/content/latest/yugabyte-cloud/_index.md
docs/content/latest/yugabyte-cloud/connect-to-clusters.md

Add steps to Yugabyte Cloud topic on "Connect to clusters"
- Steps for YSQL cloud shell
- Steps for YCQL cloud shell

[docs] Add steps to access cloud shells

---

docs/content/latest/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/aks/statefulset-yaml.md

- Modified `clusterrolebinding` name for the Kubernetes dashboard in helm.md.
- Modified the kubectl command for `statefulset` to change the `storageClassName` at runtime in statefulset-yaml.md.

Modified clusterolebinding name and storageClassName name for AKS

---

docs/content/latest/manage/backup-restore/_index.md
docs/content/latest/manage/backup-restore/snapshot-ysql.md
docs/content/latest/manage/backup-restore/snapshots-ycql.md

Fixed YCQL snapshots with transactional support.
Small fixes on YSQL.

[DOCS] YCQL/YSQL snapshots fixes

---

docs/content/latest/troubleshoot/cluster/replace_tserver.md

fixes https://github.com/yugabyte/yugabyte-db/issues/4675
Screenshot:

[DOCS] replace failed tserver process/node/vm etc

---

docs/content/latest/releases/releases-overview.md
docs/content/latest/releases/whats-new/stable-releases.md

Fix links broken when content was moved to new section.

[docs] Fix links on moved content

---

docs/content/latest/releases/versioning.md
docs/content/latest/releases/whats-new/latest-releases.md

Add a missing backtick and added use of REVISION and PATCH.

[docs] Fix formatting and wording

---

docs/content/latest/releases/whats-new/latest-releases.md
docs/content/latest/releases/whats-new/stable-releases.md

Update from "recommended v2.2 stable release series" to "current v2.2 stable release series, recommended for production deployments."

[docs] Update text for current stable release series

---

docs/content/latest/quick-start/build-apps/java/ysql-jdbc.md

Please test before commititng. fixes #5512 
For ycql test, I'm getting output:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Created keyspace ybdemo
Created table employee
Inserted data: INSERT INTO ybdemo.employee (id, name, age, language) VALUES (1, 'John', 35, 'Java');
Query returned 1 row: name=John, age=35, language: Java
```
I'm assuming the SLF4J is harmless and just says you need to add logging.

[docs] small fixes to java-jdbc example

---

docs/content/latest/deploy/public-clouds/aws/manual-deployment.md
docs/content/latest/quick-start/install/linux.md
docs/content/latest/quick-start/install/macos.md
docs/content/latest/reference/configuration/yugabyted.md
docs/content/latest/releases/whats-new/_index.md
docs/content/latest/releases/whats-new/latest-releases.md
docs/content/latest/releases/whats-new/stable-releases.md
docs/content/latest/secure/authentication/password-authentication.md
docs/content/latest/yugabyte-platform/deploy/install-admin-console/kubernetes.md

Adds the latest updates to the release notes.

[docs] Add 2.3.2 release notes

---

docs/content/latest/api/ysql/extensions.md

This relates to the change https://github.com/yugabyte/yugabyte-db/commit/32b08f559be9cca9d76f9fb5bdf14da25d127e42  and issues #5529 and #3269.
I'm sure the doc change can be improved, but this is the gist of what needs to change.

[docs] Add info on post_install.sh -e

---

docs/content/_index.html
docs/content/latest/yugabyte-platform/back-up-restore-universes/back-up-universe-data.md
docs/content/latest/yugabyte-platform/configure-yugabyte-platform/backup-target.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/back-up-universe-data.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/backup-target.md

Updates to the Yugabyte Platform sections:
- Configure the backup target"
- "Back up data" pages
- New screenshots

[docs] Update Yugabyte Platform backup-related pages and images

---

docs/content/latest/benchmark/tpcc-ysql/100-wh/tpcc-ysql.md
docs/content/latest/benchmark/tpcc-ysql/1000-wh/tpcc-ysql.md
docs/content/latest/benchmark/tpcc-ysql/10000-wh/tpcc-ysql.md

[Docs] Add a note for the proper estimation of loaderthreads during the load phase.

---

docs/content/latest/api/ycql/ddl_create_table.md

[DOCS] explain COMPACT STORAGE syntax

---

docs/content/latest/manage/upgrade-deployment.md

[DOCS] mention PostgreSQL extensions when upgrading

---

docs/content/latest/api/ysql/commands/ddl_create_sequence.md
docs/content/latest/yugabyte-platform/_index.md
docs/content/latest/yugabyte-platform/administer-yugabyte-platform/_index.md
docs/content/latest/yugabyte-platform/administer-yugabyte-platform/back-up-restore-yp.md

Rename the folders to be consistent with others.

[docs] Fix broken yp link on home page

---

docs/content/latest/troubleshoot/nodes/trouble-common.md

[docs] troubleshooting common error messages 

---

.github/workflows/create-repository-dispatch.yml

This dispatch is required for https://github.com/yugabyte/yugabyte-operator/pull/18.
Ref: https://github.com/yugabyte/yugabyte-db/issues/5987

Add repository dispatch for yugabyte/yugabyte-operator

---

docs/content/latest/yugabyte-platform/alerts-monitoring/live-queries-dashboard.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md

This PR updates the Kubernetes content in the Install Yugabyte Platform section.

[docs] Update Kubernetes content on installing Yugabyte Platform

---

docs/content/latest/contribute/core-database/build-from-src-centos.md
docs/content/latest/contribute/core-database/build-from-src-macos.md
docs/content/latest/contribute/core-database/build-from-src-ubuntu.md

[docs] add steps to build a release package

---

docs/content/latest/releases/whats-new/stable-releases.md

Content accessible at `/latest/releases/whats-new/stable-releases/#v2-2-4-october-30-2020`

[Docs] Release notes for v2.2.4

---

docs/content/latest/api/ysql/extensions.md

Add note for multiple postgresql versions.
Simple installation on ubuntu 18.04.
fixes #3269 
closes #2543
fixes #3444

[docs] Better Postgis docs

---

docs/content/latest/api/ysql/exprs/aggregate_functions/covid-data-case-study/_index.md

Fixed tiny critical typo in `.../covid-data-case-study/_index.md`

Aggregate functions covid stats study fix

---

docs/content/latest/api/ysql/the-sql-language/statements/ddl_alter_table.md

[docs] rename table in YSQL is only metadata change

---

scripts/installation/bin/yb-ctl

add force option for destroy, stop, stop_node and restart in yb-ctl.
Fixing #6308

[yb-ctl] Add force option for destroy, stop, stop_node and restart

---

docs/content/latest/benchmark/tpcc-ysql/_index.md

[Docs] Change the download link for TPCC binary.

---

docs/content/latest/api/ysql/exprs/aggregate_functions/covid-data-case-study/_index.md
docs/content/latest/api/ysql/exprs/aggregate_functions/covid-data-case-study/analyze-the-covidcast-data/_index.md
docs/content/latest/api/ysql/exprs/aggregate_functions/covid-data-case-study/analyze-the-covidcast-data/analysis-scripts/_index.md
docs/content/latest/api/ysql/exprs/aggregate_functions/covid-data-case-study/analyze-the-covidcast-data/daily-regression-analysis.md
docs/content/latest/api/ysql/exprs/aggregate_functions/covid-data-case-study/analyze-the-covidcast-data/scatter-plot-for-2020-10-21.md
docs/content/latest/api/ysql/exprs/aggregate_functions/covid-data-case-study/analyze-the-covidcast-data/symptoms-vs-mask-wearing-by-state.md
docs/content/latest/api/ysql/exprs/aggregate_functions/covid-data-case-study/ingest-the-covidcast-data/_index.md
docs/content/latest/api/ysql/exprs/aggregate_functions/covid-data-case-study/ingest-the-covidcast-data/ingest-scripts/ingest-the-data-sql.md
docs/content/latest/api/ysql/exprs/aggregate_functions/covid-data-case-study/ingest-the-covidcast-data/stage-the-csv-files.md
docs/content/latest/explore/json-support/jsonb-ysql.md

Added x-refs to JSON doc in 'docs/content/latest/explore/json-support/jsonb-ysql.md'

Small typo fixes to 'covid-data-case-study'

---

architecture/design/online-index-backfill.md

Detail that YSQL needs to do a tserver to postgres connection for
backfilling a tablet.

arch: detail tserver-postgres connection for backfill

---

docs/content/latest/secure/authentication/host-based-authentication.md

- style: s/similar/similarly/
- style: make comma-separated list items uniform
- style: fix alignment of `SHOW hba_file` output

docs: fix host-based-authentication.md style

---

docs/README.md

Suggest running npm ci in the docs directory.

[docs] Run npm ci in docs directory

---

docs/content/latest/releases/whats-new/latest-releases.md

[Docs] Add v2.5.1 to latest release page

---

docs/content/latest/manage/change-cluster-config.md
docs/content/latest/manage/grow-cluster.md

[docs] grow cluster

---

managed/ui/src/components/config/Security/KeyManagementConfiguration.js

[#6861] Platform: Added a cancel button in the Create New-enc.-at-rest

---

managed/ui/src/components/config/Security/KeyManagementConfiguration.js

PTAL at the tooltip content and lemme know if we need to change that(I'm sure we've to).

[#6230] Platform: Add tooltips to KMS Configuration UI.

---

docs/content/latest/releases/earlier-releases/v2.2.0.md
docs/content/latest/releases/whats-new/stable-releases.md

Doc2.4 rel notes

---

managed/devops/bin/yb_backup.py
managed/src/main/java/com/yugabyte/yw/common/TableManager.java
managed/src/test/java/com/yugabyte/yw/common/TableManagerTest.java

**Heading:** 
[#6858]Platform: Preflight checks for NFS backup storage configuration
When user initiates a manual backup -or- a scheduled backup, check whether
NFS path is a valid path on each of the database nodes before starting the backup task .
Fail the task right away before creating the snapshots for the backup.
**Testing:**
Configured the NFS backup storage PATH and created a AWS cloud provider
Then using cloud provider, created a multinode/single node universe
Ran sample Apps, which created table for backup.
Then after tried to create backup.
It will fail immediately if the storage path is not mounted on anyone of
the node.
Added unit Tests as well. It's working fine.
**Test Results:**
[info] Test run started
[info] Test …

[#6858]Platform: Preflight checks for NFS backup storage configuration

---

docs/content/latest/architecture/docdb-sharding/tablet-splitting.md
docs/content/latest/reference/configuration/yb-master.md

https://github.com/yugabyte/yugabyte-db/issues/6977

Tablet splitting architecture design doc update

---

docs/content/latest/explore/ysql-language-features/data-manipulation.md

#6842  Document data manipulation support in YSQL

Document data manipulation support in YSQL - Doc6842

---

docs/content/latest/explore/ysql-language-features/_index.md
docs/content/latest/explore/ysql-language-features/data-manipulation.md

Update index file for data manipulation support in YSQL doc #6842

---

docs/content/latest/faq/general.md
docs/content/latest/faq/yugabyte-platform.md
docs/content/latest/legal/vulnerability-disclosure-policy.md
docs/content/latest/secure/vulnerability-disclosure-policy.md

~~Edited with Cyrus and Liza. Note that this PR isn't ready to merge yet, but please review the content, formatting, and suggested location (/latest/legal).~~
~~Next steps: adding links to this page from the appropriate places.~~
**Update**: ready for review. FAQ links added in general and platform, and final (for now) home is under `/latest/secure`.

docs: add vulnerability disclosure policy

---

docs/content/stable/architecture/docdb-replication/read-replicas.md
docs/content/v2.1/architecture/docdb-replication/read-replicas.md
docs/content/v2.2/architecture/docdb-replication/read-replicas.md

Same as #7072, but for older docs. :)

Finish missing sentence under schema change in read replica doc (part 2)

---

managed/ui/src/components/universes/UniverseForm/ClusterFields.js

On select, the onPrem provider while creating the Universe UI alignment was getting disturbed. Minor fix.

[#6583] Platform: Fixed the UI alignment.

---

docs/content/latest/architecture/docdb-sharding/tablet-splitting.md
docs/content/stable/architecture/docdb-sharding/tablet-splitting.md
docs/content/v2.2/architecture/docdb-sharding/tablet-splitting.md

docs: update tablet splitting limitations

---

docs/content/stable/quick-start/install/linux.md
docs/content/stable/quick-start/install/macos.md

Quick fix to correct version numbers on download links for the stable release.

correct links to download stable packages

---

managed/src/main/java/com/yugabyte/yw/controllers/UniverseController.java
managed/src/test/java/com/yugabyte/yw/controllers/UniverseControllerTest.java

This change is applicable to the providers which have AZs with
KUBENAMESPACE set in the config.
Currently, we don't support multiple clusters for these type of
providers. This change makes sure that such universe / cluster
creation fails immediately.
Fixes https://github.com/yugabyte/yugabyte-db/issues/6931
- Created a provider with namespace set for one of the AZs.
- Created universe with that provider.
- Tried creating another universe with same provider, it returned 400.
- Tried adding a read replica to the universe using same provider,
it failed as expected.
- Created a provider without namespace, tried creating two single zone
universe with it. Those work as expected.

[Platform] Allow only one cluster per K8s provider with namespace

---

docs/content/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/on-premises.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/prerequisites.md

Updated YB Platform prerequisites document

Update YB Platform installation and prereq docs (Doc #7253)

---

docs/content/latest/explore/ysql-language-features/_index.md
docs/content/latest/explore/ysql-language-features/triggers.md

PR for "Document Triggers in Explorer Section #7177"

PR for "Document Triggers in Explorer Section Doc7177"

---

docs/content/latest/yugabyte-platform/back-up-restore-universes/back-up-universe-data/ysql.md

update backup tip for authenticated connection

---

docs/netlify.toml

Redirect all comparisons sections to latest

---

docs/content/latest/releases/earlier-releases/_index.md
docs/content/latest/releases/earlier-releases/v2.2.0.md

Don't merge this until 2.2.7 actually ships, of course...

2.2.7 release notes

---

managed/ui/src/components/universes/UniverseForm/AZSelectorTable.js
managed/ui/src/components/universes/UniverseForm/ClusterFields.js

Reverts yugabyte/yugabyte-db#7029

Revert "[#7024] Platform: Fixed edit number of nodes in AZ section"

---

docs/content/latest/quick-start/install/kubernetes.md
docs/content/latest/quick-start/install/linux.md
docs/content/latest/quick-start/install/macos.md
docs/content/latest/releases/whats-new/latest-releases.md
docs/layouts/partials/footer.html
docs/layouts/partials/footer_content.html

Update release notes and install instructions for 2.5.2 release

[Docs] 2.5.2 release notes

---

managed/src/main/java/com/yugabyte/yw/commissioner/HealthCheckerReport.java

**Summary:**
Currently, health check alert emails include the Universe Name and Universe Version
Have added the Yugaware Hostname and IP in the health check alert email for debugging purposes.
**Testing:**
1. Configure email and cutom SMTP details in profile section.
2. Enable the heath check
3. Try to startup the yugaware application
We would get email alert with yugaware hostname and IP along with other details
**O/p of sbt test:**
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1107) has been closed.
at …

[#6718][Platform]: Health check emails should include Yugaware Hostname and IP

---

docs/content/latest/api/ysql/datatypes/_index.md

Updated '.../datatypes/_index.md' to add entries to the table for the range data types.'

Added '.../ysql/datatypes/type_range.md'

---

managed/src/main/java/com/yugabyte/yw/controllers/CustomerController.java
managed/src/test/java/com/yugabyte/yw/controllers/CustomerControllerTest.java

When there is a namespace configured in the AZ configuration, the
metrics tab fails to show the metrics as it assumes that the namespace
is always going to be in `<nodePrefix>-[AZ]` form, which is not true
now.
This change filters the metrics based on explicit values of all the
namespaces.
We depend on the fact that a provider with namespace in the AZ allows
to create only one universe with it. That way, even if a namespace
does not have any pods, we won't have wrong metrics. These are the
scenarios like:
You have a provider with myns-1 for az1, myns-2 for az2. But you
create a universe with only az1. There won't be any pods in
myns-2 (i.e. az2) from now on, because the provider does not allow
that. The resulting filter string will be: `myns-1|myns-2`, which will
still produce correct …

[#6611][Platform][Kubernetes] Consider AZ level namespace for the metrics

---

docs/content/latest/explore/ysql-language-features/query-1-performance/_index.md
docs/content/latest/explore/ysql-language-features/query-1-performance/pg-hint-plan.md

[#7009][docs]Updated docs for pg_hint_plan in the web portal

---

managed/ui/src/components/config/Security/KeyManagementConfigurationContainer.js

Description: Error toaster appears even when the Provider is added successfully.

[#7554] Platform:Fixed KMS Error toaster when it is added successfully

---

docs/content/latest/deploy/multi-dc/2dc-deployment.md
docs/content/latest/deploy/multi-dc/_index.md

Adding steps from Daniel to let Platform know about a 2DC deployment.
Also did some cleaning up on the 2DC page.
Deploy [preview is here](https://6050069484860700085e902b--infallible-bardeen-164bc9.netlify.app/latest/deploy/multi-dc/2dc-deployment/).

add 2DC steps for platform

---

managed/src/main/java/com/yugabyte/yw/cloud/CloudAPI.java
managed/src/main/java/com/yugabyte/yw/cloud/aws/AWSCloudImpl.java
managed/src/main/java/com/yugabyte/yw/controllers/CloudProviderController.java
managed/src/test/java/com/yugabyte/yw/controllers/CloudProviderControllerTest.java
managed/ui/src/actions/cloud.js
managed/ui/src/components/config/PublicCloud/ProviderConfigurationContainer.js

Description: Created a branch with all the reverted changes for 6460.

Resolved merge conflicts and merged all reverted branch

---

docs/content/latest/architecture/design-goals.md

Fix issue #7503: [Docs] yugabyte db transaction isolation level default value 

---

docs/content/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md

update k8s cloud provider prerequisites

---

docs/content/latest/yugabyte-platform/administer-yugabyte-platform/back-up-restore-k8s.md
docs/content/latest/yugabyte-platform/administer-yugabyte-platform/back-up-restore-yp.md

Resolves #7784
* Adds a k8s link to the default [backup/restore page](https://deploy-preview-7785--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/administer-yugabyte-platform/back-up-restore-yp.md)
* Adds a [new k8s page](https://deploy-preview-7785--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/administer-yugabyte-platform/back-up-restore-k8s.md)

add k8s to platform backup/restore

---

docs/content/latest/api/ysql/extensions.md
docs/content/latest/explore/_index.md
docs/content/latest/explore/extensions/_index.md

Resolves #7697
PR PREVIEW pages:
* [new extensions page](https://deploy-preview-7777--infallible-bardeen-164bc9.netlify.app/latest/explore/extensions) in explore
* cleaned-up [api/extensions page](https://deploy-preview-7777--infallible-bardeen-164bc9.netlify.app/latest/api/ysql/extensions)
* added a link to extensions on the [explore front page](https://deploy-preview-7777--infallible-bardeen-164bc9.netlify.app/latest/explore)

add explore/extensions and clean up api/extensions

---

docs/content/latest/explore/ysql-language-features/_index.md

Deleted table row containing an obsolete link

PR 2 for PR [Docs] fix broken link to query performance #7818

---

docs/content/latest/deploy/kubernetes/single-zone/oss/helm-chart.md

Since this doc was originally created, the helm chart values have
slightly changed. Update the "example" helm chart values to reflect the
current state.

[Docs] Update example helm chart values

---

src/yb/server/default-path-handlers.cc

Added a max_depth param.
Fixes #7758 
Signed-off-by: Yash Sharma <yashrsharma44@gmail.com>

added a max_depth param to the mem-trackers view

---

docs/content/latest/explore/ysql-language-features/partitions.md

The changes were made based on a slack exchange between Jon Roberts and Deepthi Srinivasan on March 24, 2021

[doc] PR Modified examples and descriptons in partitions.md

---

docs/content/latest/secure/audit-logging/audit-logging-ycql.md
docs/content/stable/secure/audit-logging/audit-logging-ycql.md
src/yb/yql/cql/ql/audit/audit_logger.cc

Also slightly clarified gflag tooltips.

YCQL, docs: Changed audit docs for clarity, added example to show how to exclude SELECTs/DMLs

---

docs/content/latest/manage/backup-restore/_index.md
docs/content/latest/manage/backup-restore/point-in-time-restore-ycql.md
docs/content/latest/manage/backup-restore/point-in-time-restore-ysql.md

Fixes #7122
Deploy preview: https://deploy-preview-7912--infallible-bardeen-164bc9.netlify.app/latest/manage/backup-restore/point-in-time-restore-ysql/

[docs] point in time restore

---

docs/content/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md

- Removed the `yugabyte-helm` SA creation from YW installation steps & added in K8s Provider setup steps.
- Explained the way to enable the internal load balancer using annotations.
- Added usage to get the YW LB IP after helm installation.
- Described the related RBACs.
- Described the way to change the CPU & Memory resources for YW.
- Explained the overrides to provide the custom resource configuration for the YB universe.
fixes: https://github.com/yugabyte/yugabyte-db/issues/7326

[YW] Updated the docs for K8s provider

---

docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md

Also cleans up some of the whitespaces from the code snippets.

[Platform][docs] add clarification about StorageClass to OpenShift

---

src/yb/common/wire_protocol.proto
src/yb/master/master-path-handlers.cc
src/yb/server/server_base.cc

New pr for issue-7543

---

docs/content/latest/yugabyte-platform/security/enable-encryption-in-transit.md

Changed tlsv12 to tls12.
This PR relates to https://github.com/yugabyte/yugabyte-db/pull/7306

[doc] Minor fix requested under PR 7306 (DocTypoInPR7306Commit)

---

docs/content/latest/benchmark/tpcc-ysql/10-wh/tpcc-ysql.md
docs/content/latest/benchmark/tpcc-ysql/100-wh/tpcc-ysql.md
docs/content/latest/benchmark/tpcc-ysql/1000-wh/tpcc-ysql.md

In the interest of simplicity, we'd like to direct folks to run each step independently, rather than running all in one shot. This PR modifies the docs with TPCC instructions accordingly.

[docs] Update documented instructions on running TPCC

---

docs/content/latest/api/ysql/the-sql-language/statements/ddl_create_table.md

[Docs] remove beta tag from "split at values"

---

docs/content/latest/explore/ysql-language-features/_index.md

Added a row to the table in YSQL vs Postgresql section index file

[doc] PR for Add link to DDL statements API doc to the Explore section (Doc7578)

---

docs/content/latest/benchmark/ycsb-jdbc.md

Modified content for clarity; Added link to the table splitting example

[doc] PR for Update YCSB benchmark docs to include Automatic Tablet splitting (Doc7064)

---

docs/content/latest/explore/query-1-performance/_index.md

[docs] change query optimization overview wording

---

managed/src/main/java/com/yugabyte/yw/controllers/InstanceTypeController.java
managed/src/main/java/com/yugabyte/yw/models/InstanceType.java
managed/src/main/java/com/yugabyte/yw/models/Provider.java
managed/src/test/java/com/yugabyte/yw/controllers/InstanceTypeControllerTest.java

Use the new global exception handling in the Instance Type controller.
Test Plan:

[#WIP] [Platform] [API] Instance Type controller error handling.

---

docs/content/latest/explore/multi-region-deployments/row-level-geo-partitioning.md

Preview [is here](https://deploy-preview-7795--infallible-bardeen-164bc9.netlify.app/latest/explore/multi-region-deployments/row-level-geo-partitioning)

[Docs] add language to geopartitioning code blocks

---

docs/content/latest/releases/whats-new/stable-releases.md

Just look at the **2.4.2.0 section**. The rest is markdown housekeeping :)
Preview build: https://deploy-preview-8171--infallible-bardeen-164bc9.netlify.app/latest/releases/whats-new/stable-releases

[Docs] 2.4.2.0 release notes

---

managed/src/main/java/com/yugabyte/yw/controllers/BackupsController.java
managed/src/main/java/com/yugabyte/yw/models/CustomerConfig.java
managed/src/test/java/com/yugabyte/yw/controllers/BackupsControllerTest.java

Use the new global exception handling in the Backups controller.
**Test Plan:**
**TODO:** Will work on followup change to get rid of raw json used in this controller 
#8315

[#8316] [Platform] [API] Backups controller error handling.

---

docs/content/latest/_index.html
docs/layouts/_default/list.html
docs/layouts/_default/single.html
docs/layouts/partials/detect_version.html
docs/layouts/partials/version_switcher.html

Forgot to update the version switcher in the 2.7 release note PR

[docs] update the version switcher

---

docs/content/latest/yugabyte-platform/security/enable-encryption-at-rest.md

@VijiYB I didn't have a screenshot showing "enable encryption at rest" on the platform (and I can't currently access the platform itself), so I couldn't verify the steps. Could you, please, let me know if the changes I made to the doc are correct?

[Docs] PR for Managing Encryption moved to Edit Security under Actions (Doc8143)

---

docs/content/latest/admin/yb-ts-cli.md

Sonal reported a few misnamed commands. Fixed, and made Markdown and other improvements while I was in there.
Preview build is here: https://deploy-preview-8309--infallible-bardeen-164bc9.netlify.app/latest/admin/yb-ts-cli/

[docs] fix and improve yb-ts-cli

---

docs/content/latest/explore/_index.md
docs/content/latest/explore/query-1-performance/_index.md
docs/content/latest/explore/query-1-performance/explain-analyze.md
docs/content/latest/explore/query-1-performance/pg-hint-plan.md

Long overdue... Renaming Query Optimization to Query Tuning.
Need to check carefully for link breakage, but not much actually links to this...
Preview build: https://deploy-preview-8344--infallible-bardeen-164bc9.netlify.app/latest/explore/query-1-performance/

[docs] Query Tuning name change

---

docs/content/latest/yugabyte-platform/security/enable-encryption-in-transit.md

[docs] Update enable-encryption-in-transit.md

---

docs/content/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

make option --ask_password easier to find

[docs] Update on-premises.md

---

managed/src/main/java/com/yugabyte/yw/controllers/AlertController.java
managed/src/main/java/com/yugabyte/yw/models/AlertDefinition.java
managed/src/test/java/com/yugabyte/yw/controllers/AlertControllerTest.java

Use the new global exception handling in the alert controller.
**Test Plan:**
1.  Its mostly refactor. Unit tests are updated.
2.  Run server and test basic operations.
3. Gone through the steps of creating an alert edited and saved the new alerts without any error.
SBT TEST: 
```[info] Passed: Total 1303, Failed 0, Errors 0, Passed 1299, Skipped 4
[success] Total time: 1284 s (21:24), completed 12 May, 2021 12:13:27 PM```

[#8303] [Platform][API] Alert controller error handling.

---

docs/content/latest/quick-start/build-apps/java/ysql-jdbc.md

Fixes #8351
Build preview is here: https://deploy-preview-8353--infallible-bardeen-164bc9.netlify.app/latest/quick-start/build-apps/java/ysql-jdbc/

[docs] update java quickstart

---

docs/content/latest/releases/whats-new/stable-release.md

build preview: https://deploy-preview-8420--infallible-bardeen-164bc9.netlify.app/latest/releases/whats-new/stable-release/

[docs] 2.4.3.0 release notes

---

docs/README.md

[Docs] Minor edit

---

docs/content/latest/admin/yb-admin.md
docs/content/latest/manage/backup-restore/_index.md
docs/content/latest/manage/backup-restore/point-in-time-restore-ycql.md
docs/content/latest/manage/backup-restore/point-in-time-restore-ysql.md
docs/content/latest/manage/backup-restore/snapshot-ysql.md
docs/content/latest/manage/backup-restore/snapshots-ycql.md

(Or at least some of phase 2!)
Fixes #8230
Preview build: https://deploy-preview-8233--infallible-bardeen-164bc9.netlify.app/latest/admin/yb-admin/#backup-and-snapshot-commands

[docs] PITR docs, phase 2

---

src/yb/master/master_service.cc
src/yb/master/ts_descriptor.cc
src/yb/master/ts_descriptor.h

Fixes #7571. Existing tests suffice.

[#7571][docdb] Grouping and cleaning up setters to eliminate locking overhead

---

managed/src/main/java/com/yugabyte/yw/controllers/CloudProviderController.java
managed/src/test/java/com/yugabyte/yw/controllers/CloudProviderControllerTest.java

Use the new global exception handling in the Cloud Provider controller.
**Test Plan:**
**Summary**
Use exceptions for error handling. This allows for restructuring the code and also cleans up API.  
**sbt test results:**
2021-05-15 16:25:56.237 [warn] TaskGarbageCollector.java:56 [pool-1-thread-1] Failed to build prometheus Counter for name: yw_task_gc_error_count: java.lang.IllegalArgumentException
[info] Test com.yugabyte.yw.commissioner.TaskGarbageCollectorTest.testPurge_invalidData started
[info] Test run finished: 0 failed, 0 ignored, 7 total, 0.234s
[info] Passed: Total 1312, Failed 0, Errors 0, Passed 1308, Skipped 4
[success] Total time: 1101 s (18:21), completed 15 May, 2021 …

[#8368] [Platform] [API] Cloud Provider controller error handling.

---

managed/src/main/java/com/yugabyte/yw/controllers/UsersController.java
managed/src/main/java/com/yugabyte/yw/models/Users.java
managed/src/test/java/com/yugabyte/yw/controllers/UsersControllerTest.java

Use the new global exception handling in the Userscontroller.
**Test Plan:**
**sbt test result:**
[info] Test com.yugabyte.yw.commissioner.TaskGarbageCollectorTest.testDefaultProm started
[info] Test com.yugabyte.yw.commissioner.TaskGarbageCollectorTest.testStart_disabled started
[info] Test com.yugabyte.yw.commissioner.TaskGarbageCollectorTest.testPurge_noneStale started
[info] Test com.yugabyte.yw.commissioner.TaskGarbageCollectorTest.testIgnorePromError started
[info] Test com.yugabyte.yw.commissioner.TaskGarbageCollectorTest.testPurge_invalidData started
[info] Test run finished: 0 failed, 0 ignored, 7 total, 0.227s
[info] Passed: Total 1312, Failed 0, Errors 0, Passed 1308, Skipped 4 …

[#8394] [Platform] [API] Users controller error handling.

---

docs/content/latest/quick-start/build-apps/java/ycql-4.6.md
docs/content/latest/quick-start/build-apps/java/ysql-jdbc.md
docs/content/latest/quick-start/build-apps/java/ysql-spring-data.md

Fixed minor doc issues in quick start java section

issue-8497: fix minor doc issues in quick start java section

---

docs/content/latest/explore/security/security.md

[Docs] fix links

---

managed/src/main/java/com/yugabyte/yw/controllers/CustomerConfigController.java
managed/src/main/java/com/yugabyte/yw/models/helpers/CommonUtils.java
managed/src/main/resources/v1.routes
managed/src/test/java/com/yugabyte/yw/controllers/CustomerConfigControllerTest.java
managed/src/test/java/com/yugabyte/yw/models/helpers/CommonUtilsTest.java
managed/ui/src/actions/customers.js
managed/ui/src/components/config/ConfigProvider/providerConfig.scss
managed/ui/src/components/config/Storage/AwsStorageConfiguration.js
managed/ui/src/components/config/Storage/StorageConfiguration.js
managed/ui/src/components/config/Storage/StorageConfigurationContainer.js
managed/ui/src/reducers/reducer_customer.js

Backup config security credentials can change over time. The platform should support editing the security credentials even if there are existing backups associated with a Backup Config. When security credentials expire, the Platform will fail to take new backups and also fail to delete old backups.
This change should be implemented for all three storage configs:
AWS: Allow editing Access Key/Secret, also toggling between IAM and AccessKey
GCP: Allow editing GCS Credentials [Do not allow editing bucket name]
Azure: Allow editing Azure SAS token [Do not allow editing Container URL]
**Test Plan:**
1. Hit the config button from the SideNav.
2. Click on Backup Tab and then hit the amazon s3 tab.
3. Create a backup config for s3.
4. Once it got created then you'll see the Edit …

[#7706] [Platform] [Backport-2.4] Edit backup config credentials. 

---

docs/content/latest/releases/whats-new/stable-release.md
docs/content/stable/quick-start/install/kubernetes.md
docs/content/stable/quick-start/install/linux.md
docs/content/stable/quick-start/install/macos.md

Preview build is here: https://deploy-preview-8549--infallible-bardeen-164bc9.netlify.app/latest/releases/whats-new/stable-release

[docs] 2.4.4.0 release notes

---

managed/src/main/java/com/yugabyte/yw/common/kms/util/EncryptionAtRestUtil.java
managed/src/main/java/com/yugabyte/yw/controllers/EncryptionAtRestController.java
managed/src/main/java/com/yugabyte/yw/controllers/NodeInstanceController.java
managed/src/main/java/com/yugabyte/yw/models/NodeInstance.java
managed/src/test/java/com/yugabyte/yw/controllers/EncryptionAtRestControllerTest.java
managed/src/test/java/com/yugabyte/yw/controllers/NodeInstanceControllerTest.java

Use the new global exception handling in the NodeInstanceController.
**Also included the change for Auto formatting change which was introduced by** https://github.com/yugabyte/yugabyte-db/pull/8474.
**Test Plan:**
Run server and tested basic operations.
**O/p of sbt test run:**
[info] Test com.yugabyte.yw.controllers.ScheduleControllerTest.testDeleteInvalidCustomerUUID started
[info] Test com.yugabyte.yw.controllers.ScheduleControllerTest.testDeleteInvalidScheduleUUID started
[info] Test com.yugabyte.yw.controllers.ScheduleControllerTest.testListWithValidCustomer started
[info] Test com.yugabyte.yw.controllers.ScheduleControllerTest.testListWithInvalidCustomer started
[info] Test run finished: 0 failed, 0 ignored, 5 total, …

[#8573] [Platform] [API] NodeInstanceController error handling.

---

managed/build.sbt
managed/src/main/java/AppInit.java
managed/src/main/java/com/yugabyte/yw/common/ConfigHelper.java
managed/src/main/java/com/yugabyte/yw/models/helpers/CustomerConfigValidator.java
managed/src/test/java/com/yugabyte/yw/common/ConfigHelperTest.java
managed/src/test/java/com/yugabyte/yw/models/helpers/CustomerConfigValidatorTest.java
managed/ui/src/components/config/Storage/StorageConfigurationContainer.js

Reverts yugabyte/yugabyte-db#8518
Some i-test are failing due to this change. Hence reverting.

Revert "[#6857]Platform: Preflight checks for S3 backup storage configuration"

---

managed/src/main/java/com/yugabyte/yw/controllers/RuntimeConfController.java
managed/src/main/java/com/yugabyte/yw/models/RuntimeConfigEntry.java
managed/src/test/java/com/yugabyte/yw/controllers/RuntimeConfControllerTest.java

Use the new global exception handling in the RuntimeConf controller.
**Test Plan:**

[#8706] [Platform] [API] RuntimeConfController error handling.

---

managed/src/main/java/com/yugabyte/yw/controllers/TablesController.java
managed/src/test/java/com/yugabyte/yw/controllers/TablesControllerTest.java

Use the new global exception handling in the TablesController.
**Test Plan:**

[#8668] [Platform] [API] Tables controller error handling. 

---

.github/workflows/yugabyted-test.yml
scripts/yugabyted/test/yugabyted-test-runner.sh
scripts/yugabyted/test/yugabyted-test.sh

Recent YugabyteDB releases are not posted on github.

github action tests: fix YB download path

---

docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md

[docs] Update airgapped install

---

docs/content/latest/develop/ecosystem-integrations/apache-spark/java.md

Build preview:  https://deploy-preview-8720--infallible-bardeen-164bc9.netlify.app/latest/develop/ecosystem-integrations/apache-spark/java/
(disregard the left menu structure; it'll be fixed before the PR is merged)

[doc] PR for Document Apache Spark 3 with YCQL (Doc8716)

---

managed/ui/src/components/config/Storage/BackupList.test.js

Added the unit test file for the multiple backup configurations.

[#8063] [Platform] Added unit test file for the multiple backup config.

---

docs/content/latest/architecture/docdb-replication/async-replication.md

[docs] Update async-replication.md

---

docs/content/latest/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md

[docs] Update prepare-on-prem-nodes.md

---

docs/content/latest/explore/linear-scalability/_index.md

[docs] Update linear-scalability

---

docs/content/latest/quick-start/build-apps/java/ycql-4.6.md
docs/content/latest/quick-start/build-apps/java/ycql.md
docs/content/latest/quick-start/build-apps/java/ysql-jdbc-ssl.md
docs/content/latest/quick-start/build-apps/java/ysql-jdbc.md
docs/content/latest/quick-start/build-apps/java/ysql-spring-data.md

Building a Java app with SSL #8436
https://deploy-preview-8910--infallible-bardeen-164bc9.netlify.app/latest/quick-start/build-apps/java/ysql-jdbc-ssl/

[docs] build java with ssl

---

docs/content/latest/admin/yb-admin.md
docs/content/latest/explore/backup-restore/point-in-time-recovery-ycql.md
docs/content/latest/explore/backup-restore/point-in-time-recovery-ysql.md
docs/content/latest/manage/backup-restore/point-in-time-recovery.md

I missed actually pushing the changes in this commit before i merged #8727. This corrects that omission.
@netlify /latest/explore/backup-restore/point-in-time-recovery-ycql

[docs] apply missed PITR changes

---

architecture/design/ysql-gin-indexes.md

Add design doc for YSQL GIN indexes.

arch: add ysql gin design doc

---

docs/content/latest/releases/whats-new/stable-release.md

Preview build: https://deploy-preview-8981--infallible-bardeen-164bc9.netlify.app/latest/releases/whats-new/stable-release/

[docs] 2.4.5 release notes

---

managed/src/main/java/com/yugabyte/yw/controllers/UniverseController.java
managed/src/main/java/com/yugabyte/yw/models/HealthCheck.java
managed/src/test/java/com/yugabyte/yw/models/HealthCheckTest.java

Reverts yugabyte/yugabyte-db#8840

[Platform][API] Revert Health check  API json cleanups

---

docs/content/latest/releases/whats-new/stable-release.md

Add bug 8503 that I missed in the first round

[docs] add missing bugfix to 2.4.5 release notes

---

docs/content/latest/develop/graphql/hasura.md

Add note about hasura cloud #8880
PREVIEW: https://deploy-preview-8934--infallible-bardeen-164bc9.netlify.app/latest/develop/graphql/hasura/

[docs] add hasura cloud

---

managed/ui/src/routes.js

Description: Platform power user feedback: "When I click on a platform URL, but I have to sign in first, I’m then redirected to the home page, rather than to the URL I initially clicked. Any cheap way we can fix that with some referral magic?"
Fix uses search param to pass the redirect page URL.
Test Plan:
Navigate to a valid URL other than / and clear the browser cookies and local storage details, so it expires the session, now try to navigate to some other URL, you will be redirected to the login page and once the valid credential is entered you will land on the original URL instead of the default landing page.

[Backport 2.6][#8461][Platform] Added fix for redirecting user to intended url.

---

docs/content/latest/explore/multi-region-deployments/_index.md

Changed consistency to "Timeline" for read replicas and (in the next commit) xCluster

[Docs] PR for Read Replica Consistency Level Inconsistency (Doc8833)

---

docs/content/latest/secure/tls-encryption/_index.md
docs/content/latest/secure/tls-encryption/tls-authentication.md

From comment https://github.com/yugabyte/yugabyte-db/issues/7153#issuecomment-780368608
Examples of using TLS with authentication
If this location in the tree is suitable, need to add link to index page.

[docs] TLS used with authentication

---

docs/content/latest/integrations/_index.html
docs/content/latest/integrations/apache-spark/scala.md
docs/content/latest/integrations/janusgraph.md
docs/content/latest/integrations/kairosdb.md
docs/content/latest/integrations/metabase.md
docs/content/latest/integrations/prisma.md

See https://github.com/yugabyte/yugabyte-db/pull/9105

[docs] Minor changes based on review comments in the now-closed PR 9105

---

docs/content/latest/architecture/docdb-replication/replication.md
docs/content/latest/architecture/docdb-sharding/sharding.md
docs/content/latest/architecture/docdb-sharding/tablet-splitting.md
docs/content/latest/explore/transactions/explicit-locking.md

Various minor edits and corrections to 3 files (#9010)
Added fix for #9150

[docs] cosmetic edits sharding etc

---

docs/content/latest/admin/yb-ctl.md
docs/content/latest/secure/enable-authentication/_index.md
docs/content/latest/secure/enable-authentication/ysql.md
docs/content/latest/secure/enable-authentication/ysql_hba_conf-configuration.md

Fix command for creating a regular user in YSQL (#7849) and other fixes/edits

[docs] fix create regular user ysql

---

docs/content/latest/yugabyte-platform/back-up-restore-universes/back-up-universe-data/ycql.md
docs/content/latest/yugabyte-platform/back-up-restore-universes/back-up-universe-data/ysql.md
docs/content/latest/yugabyte-platform/back-up-restore-universes/restore-universe-data/ycql.md
docs/content/latest/yugabyte-platform/back-up-restore-universes/restore-universe-data/ysql.md
docs/content/latest/yugabyte-platform/back-up-restore-universes/schedule-data-backups/ycql.md
docs/content/latest/yugabyte-platform/back-up-restore-universes/schedule-data-backups/ysql.md

Typos and misc formatting fixes (#9068)

[docs] backup restore fixes

---

docs/content/latest/admin/yb-admin.md

Add list_cdc_streams YB-Admin command with notes on use with setup and apply replication (#9089)
@RunningJon in Slack thread: "This looks good."

[docs] add list_cdc_streams

---

docs/content/latest/explore/follower-reads/fr-ycql.md
docs/content/latest/manage/backup-restore/restore-data-ycql.md
docs/content/latest/manage/backup-restore/restore-data.md
docs/content/latest/troubleshoot/nodes/_index.md
docs/content/latest/troubleshoot/nodes/check-logs.md
docs/content/latest/troubleshoot/nodes/check-processes.md
docs/content/latest/troubleshoot/nodes/check-stats.md
docs/content/latest/troubleshoot/nodes/recover-disk.md
docs/content/latest/troubleshoot/nodes/trouble-common.md
docs/content/latest/yugabyte-platform/manage-deployments/_index.md
docs/content/latest/yugabyte-platform/manage-deployments/add-nodes.md
docs/content/latest/yugabyte-platform/manage-deployments/delete-universe.md
docs/content/latest/yugabyte-platform/manage-deployments/edit-config-flags.md
docs/content/latest/yugabyte-platform/manage-deployments/edit-universe.md
docs/content/latest/yugabyte-platform/manage-deployments/high-availability.md
docs/content/latest/yugabyte-platform/manage-deployments/instance-tags.md
docs/content/latest/yugabyte-platform/manage-deployments/remove-nodes.md
docs/content/latest/yugabyte-platform/manage-deployments/upgrade-software.md

Minor changes to fix menu order and page tabs

[docs] fixes to menus

---

docs/content/latest/explore/backup-restore/point-in-time-recovery-ycql.md

Remove Beta tag from PITR page

[docs] pitr remove beta tag

---

docs/content/latest/manage/backup-restore/point-in-time-recovery.md
docs/content/stable/explore/backup-restore/point-in-time-recovery-ycql.md
docs/content/stable/manage/backup-restore/point-in-time-recovery.md

also adjust a couple of titles

[docs] remove beta tags from PITR for YCQL

---

docs/content/latest/admin/yb-admin.md
docs/content/latest/explore/multi-region-deployments/row-level-geo-partitioning.md
docs/content/latest/explore/ysql-language-features/partitions.md
docs/content/stable/admin/yb-admin.md
docs/content/stable/explore/multi-region-deployments/row-level-geo-partitioning.md
docs/content/stable/explore/ysql-language-features/partitions.md

Adds the changes from #9027 to /stable. Some tweaks to the files in /latest at the same time for consistency.

[docs] backport geopartitioning changes to stable

---

docs/content/latest/explore/ysql-language-features/tablespaces.md

multi-region transcends one country in this case

[docs] Update tablespaces.md

---

docs/content/latest/yugabyte-platform/security/create-kms-config.md/aws-kms.md

Match bullet points to GUI fields.

[docs] Update aws-kms.md

---

docs/content/latest/yugabyte-platform/security/customize-ports.md
docs/content/latest/yugabyte-platform/security/enable-encryption-in-transit.md

procedure clarifications and grammar fixes

[docs] security clarifications and grammar fixes

---

docs/content/latest/integrations/_index.html
docs/content/latest/integrations/smart-driver.md

Doc build preview: https://deploy-preview-9240--infallible-bardeen-164bc9.netlify.app/latest/integrations/smart-driver/

[docs] PR for Document the new cluster aware jdbc driver (Doc9156)

---

docs/content/latest/yugabyte-platform/create-deployments/create-universe-multi-zone.md

2 typos on multi zone universe page

[docs] fix 2 typos

---

docs/content/latest/explore/_index.md
docs/content/latest/explore/cluster-management/_index.md
docs/content/latest/explore/ysql-language-features/_index.md

Checking in list items 1, 2, and 6 of https://github.com/yugabyte/yugabyte-db/issues/9434
Reassigning the base issue to Alex to finish the rest.

[docs] 1st PR for Restructure Explore Part 2 (Doc9434)

---

docs/content/latest/deploy/docker/docker-compose.md
docs/content/latest/deploy/docker/docker-swarm.md

Changes on the Docker compose page: Added a prerequisite section.
Changes on the Docker swarm page: Updated with the right URL's under prerequisite section.

[#9305][Docs] Updates to Docker prerequisites section

---

docs/content/latest/architecture/docdb-sharding/tablet-splitting.md

[docs] remove #5854 from tablet-splitting known limitations

---

docs/content/latest/architecture/docdb-sharding/colocated-tables.md

Removed link to the content deleted from Explore

[Docs] PR for Link on Colocated tables doc leads to Page Not Found (Doc9481)

---

docs/content/latest/benchmark/tpcc-ysql/10-wh/tpcc-ysql.md
docs/content/latest/benchmark/tpcc-ysql/100-wh/tpcc-ysql.md
docs/content/latest/benchmark/tpcc-ysql/1000-wh/tpcc-ysql.md

Edited files for clarity and consistency

[docs] PR for Cosmetic changes to benchmark/tpcc-ysql files (Doc9487)

---

docs/content/latest/explore/multi-region-deployments/asynchronous-replication-ycql.md
docs/content/latest/explore/multi-region-deployments/asynchronous-replication-ysql.md
docs/content/latest/integrations/smart-driver.md
docs/content/latest/quick-start/install/kubernetes.md
docs/content/latest/quick-start/install/linux.md
docs/content/latest/quick-start/install/macos.md
docs/content/latest/releases/whats-new/latest-release.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md

[docs] release notes and other changes for 2.7.2.0

---

docs/content/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md

1. Added the istio compatibility info.
2. Edited the whole file to ensure clarity.

[Docs] PR for Need istioCompatability flag when creating k8s platform config (Doc9293)

---

docs/content/latest/yugabyte-platform/install-yugabyte-platform/uninstall-software.md
docs/content/latest/yugabyte-platform/manage-deployments/remove-nodes.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/uninstall-software.md
docs/content/stable/yugabyte-platform/manage-deployments/remove-nodes.md

Updating the k8s uninstall page to fix some bad formatting. Also updating the remove-nodes page to correct the name of the unresponsive node.
@netlify /latest/yugabyte-platform/install-yugabyte-platform/uninstall-software/

[docs] fix markdown in k8s uninstall doc

---

docs/content/latest/architecture/transactions/distributed-txns.md

[docs] acid transactions typo

---

docs/content/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md

[docs] fix typo in kubernetes.md

---

docs/content/latest/integrations/_index.html
docs/content/latest/integrations/liquibase.md

This PR is replacing 9640 that I closed because of extensive merge conflicts.
Preview: https://deploy-preview-9691--infallible-bardeen-164bc9.netlify.app/latest/integrations/liquibase/

PR for Document Liquibase under Ecosystem Integrations (Doc8964)

---

src/yb/master/catalog_manager.cc
src/yb/master/catalog_manager.h
src/yb/master/catalog_manager_bg_tasks.cc

[docdb] fix issue-4262

---

docs/content/latest/quick-start/build-apps/java/ycql-4.6.md
docs/content/latest/quick-start/build-apps/java/ycql.md
docs/content/latest/reference/drivers/ycql-client-drivers.md
docs/content/stable/quick-start/build-apps/java/ycql-4.6.md
docs/content/stable/quick-start/build-apps/java/ycql.md
docs/content/stable/reference/drivers/ycql-client-drivers.md

Fix xml code blocks
https://deploy-preview-9753--infallible-bardeen-164bc9.netlify.app/latest/quick-start/build-apps/java/ycql/
https://deploy-preview-9753--infallible-bardeen-164bc9.netlify.app/latest/quick-start/build-apps/java/ycql-4.6/
https://deploy-preview-9753--infallible-bardeen-164bc9.netlify.app/latest/reference/drivers/ycql-client-drivers/
and same in stable

[docs] Format xml code blocks

---

docs/content/latest/releases/releases-overview.md
docs/content/latest/releases/whats-new/latest-release.md

[docs] correct the 2.9.0.0 release date

---

docs/content/latest/architecture/design-goals.md
docs/content/latest/benchmark/tpcc-ysql/_index.md

@ameyb @polarweasel @hbhanawat 
Pull Request for TPCC Doc Page Enhancements:
Fixes #9745 
Modified _index.md in latest:
1. Added Microsoft Azure Test Results
2. Added Performance Team TPCC Best Practices
@netlify /latest/benchmark/tpcc-ysql/

[docs] updates for TPC-C page

---

docs/content/latest/releases/whats-new/stable-release.md

@netlify /latest/releases/whats-new/stable-release/

[docs] add release notes for 2.6.1.0

---

docs/content/latest/architecture/transactions/distributed-txns.md
docs/content/stable/architecture/transactions/distributed-txns.md
docs/content/v2.1/architecture/transactions/distributed-txns.md
docs/content/v2.2/architecture/transactions/distributed-txns.md

fixed typo in distributed-txns.md

[docs] fixed typo in distributed-txns.md

---

docs/content/latest/benchmark/tpcc-ysql/_index.md

Added link to the new TPCC release

[docs] Added link to the new TPCC release

---

docs/content/latest/explore/json-support/jsonb-ysql.md
docs/content/stable/api/ysql/datatypes/type_json/create-indexes-check-constraints.md

range queries on JSON int with index expressions

[docs] JSON index expressions

---

docs/content/latest/secure/authentication/_index.md
docs/content/latest/secure/authentication/ldap-authentication-ycql.md
docs/content/latest/secure/authentication/ldap-authentication-ysql.md

@netlify /latest/secure/authentication/ldap-authentication-ycql

[Docs] LDAP authentication for YCQL

---

docs/content/latest/releases/earlier-releases/v2.4.md

@netlify /latest/releases/earlier-releases/v2.4/

[docs] add 2.4.7.0 release notes

---

docs/content/latest/yugabyte-cloud/release-notes.md

[docs] cloud release notes for sep15

---

docs/content/latest/yugabyte-cloud/cloud-basics/create-databases-ycql.md
docs/content/latest/yugabyte-cloud/cloud-basics/create-databases.md

add a basic YCQL example
@netlify /latest/yugabyte-cloud/cloud-basics/create-databases/

[docs] add YCQL example

---

docs/content/latest/yugabyte-cloud/release-notes.md

Known issues for What's new page

[docs] more known issues

---

docs/content/latest/reference/drivers/ysql-client-drivers.md
docs/content/stable/reference/drivers/ysql-client-drivers.md
docs/content/v2.2/reference/drivers/ysql-client-drivers.md
docs/content/v2.4/reference/drivers/ysql-client-drivers.md

[docs] fix title to "Build a C# application"

---

docs/content/latest/yugabyte-cloud/cloud-network/vpc-peers.md

@netlify /latest/yugabyte-cloud/cloud-network/vpc-peers/

[docs] vpc peering info

---

docs/content/latest/yugabyte-cloud/cloud-basics/connect-to-clusters.md
docs/content/latest/yugabyte-cloud/cloud-basics/connect/ycql.md
docs/content/latest/yugabyte-cloud/cloud-basics/connect/ysql.md
docs/content/latest/yugabyte-cloud/cloud-faq.md
docs/content/latest/yugabyte-cloud/cloud-security/_index.md
docs/content/latest/yugabyte-cloud/release-notes.md

Added note on client shells and RN reorg
@juanman2

[docs] faq and RN notes

---

managed/ui/src/components/universes/UniverseForm/AZSelectorTable.js

Description
--
Fix reset config should also restore the number of nodes under  CLOUD CONFIGURATION
Please refer to the issue here for more detail here: https://github.com/yugabyte/yugabyte-db/issues/9743

[#9743][Platform] - Fix reset config should also restore the number of nodes

---

docs/content/latest/yugabyte-cloud/cloud-basics/connect-to-clusters.md
docs/content/latest/yugabyte-cloud/cloud-clusters/backup-clusters.md
docs/content/latest/yugabyte-cloud/cloud-faq.md
docs/content/latest/yugabyte-cloud/release-notes.md

@netlify /latest/yugabyte-cloud/release-notes/#known-issues-in-cloud-shell

[docs] update cloud shell limitations

---

docs/content/latest/yugabyte-cloud/release-notes.md

Add another known cloud shell issue: "If the cloud shell stops responding, close the browser tab and restart the cloud shell."

[docs] quick cloud release-note update

---

docs/content/latest/benchmark/ycsb-ycql.md

Preview: https://deploy-preview-10060--infallible-bardeen-164bc9.netlify.app/latest/benchmark/ycsb-ycql/#1-million-rows

 [Docs] PR for YCSB Results Written in Indian Notation (Doc10058) 

---

docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md

[docs] helm chart updates

---

docs/content/latest/quick-start/build-apps/nodejs/ycql.md
docs/content/latest/quick-start/build-apps/nodejs/ysql-pg.md
docs/content/latest/quick-start/build-apps/nodejs/ysql-sequelize.md

@netlify /latest/quick-start/build-apps/nodejs/

[docs] add SSL to nodejs quickstart

---

docs/content/latest/quick-start/build-apps/csharp/ycql.md
docs/content/latest/quick-start/build-apps/csharp/ysql.md
docs/content/latest/reference/drivers/ysql-client-drivers.md

Resolves #10073
@netlify /latest/quick-start/build-apps/csharp/ysql/

[docs] add SSL details for C# npgsql

---

docs/content/latest/yugabyte-platform/create-deployments/create-universe-multi-zone.md

Preview: https://deploy-preview-10165--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/create-deployments/create-universe-multi-zone/#examine-the-universe

 [Doc] PR for Platform "Connect to a database node" - some steps and screenshots are outdated (Doc9400) 

---

docs/content/latest/faq/yugabyte-platform.md

I added a note.
(however, since the document is clearly only applicable to Platform, I don't think this was necessary)

 [Doc] PR for Clarify OS requirements for Platform vs DB (Doc9847) 

---

docs/content/latest/releases/whats-new/stable-release.md
docs/content/stable/quick-start/install/docker.md
docs/content/stable/quick-start/install/linux.md
docs/content/stable/quick-start/install/macos.md

@netlify /latest/releases/whats-new/stable-release/

[docs] 2.6.5.0 release notes

---

docs/content/latest/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/latest/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/latest/quick-start/install/kubernetes.md
docs/content/latest/quick-start/install/linux.md
docs/content/latest/quick-start/install/macos.md
docs/content/latest/releases/whats-new/latest-release.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/default.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
docs/content/stable/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/v2.1/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/v2.2/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/v2.4/deploy/kubernetes/single-zone/aks/helm-chart.md

[docs] 2.9.1.0 release

---

docs/content/latest/yugabyte-cloud/cloud-security/_index.md

Minor update regarding encryption
https://yugabyte.atlassian.net/browse/CLOUDGA-3068
@netlify /latest/yugabyte-cloud/cloud-security/

[docs] cloud security page

---

docs/content/latest/faq/yugabyte-platform.md
docs/content/latest/releases/earlier-releases/v2.0.9.md
docs/content/latest/releases/earlier-releases/v2.3.0.md
docs/content/latest/releases/earlier-releases/v2.4.md
docs/content/latest/releases/earlier-releases/v2.5.md
docs/content/latest/releases/whats-new/stable-release.md

Link fixes, remove references to Yugaware
This also probably resolves #7267 
@netlify /latest/faq/yugabyte-platform/

[docs] Platform FAQ fixes

---

docs/content/latest/yugabyte-cloud/cloud-faq.md

Replacing 'paid' with standard, mainly
@netlify /latest/yugabyte-cloud/cloud-faq/

[docs] cloud faq edits

---

managed/ui/src/components/common/forms/fields/stylesheets/YBSelect.scss
managed/ui/src/components/universes/UniverseForm/ClusterFields.js
src/yb/common/partition.cc

[#8517, #6302, #5355][Platform] -   Auto populate provider dropdown, remove parenthesis around range partition and adjust DB version margin
What does this PR not cover: 
1. From 8517 issue, does not cover REGION AUTO POPULATE

[#8517, #6302, #5355][Platform] - Auto populate provider dropdown, remove parenthesis around range partition and adjust DB version margin

---

docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/prerequisites.md

PR for https://yugabyte.atlassian.net/browse/PLAT-2163
Preview: https://deploy-preview-10484--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/install-yugabyte-platform/prerequisites/#hardware-requirements
and
https://deploy-preview-10484--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes/

[doc] PR for Min CPU / mem requirements for Platform k8s (Doc-PLAT-2163)

---

docs/content/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

@netlify /latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises/

[docs] update on-prem for manual and no-sudo

---

docs/content/latest/yugabyte-platform/overview/_index.md

Preview: https://deploy-preview-10593--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/overview/

 [Docs] PR for browsers and versions (Doc10525) 

---

docs/content/latest/releases/whats-new/stable-release.md

@netlify /latest/releases/whats-new/stable-release/

[docs] add links to stable release notes

---

docs/content/latest/yugabyte-platform/create-deployments/create-universe-multi-zone.md

Preview: https://deploy-preview-10625--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/create-deployments/create-universe-multi-zone/#examine-the-universe

[docs] PR for Minor content addition to create-universe-multi-zone/#examine-the-universe (Doc10624)

---

docs/content/latest/yugabyte-platform/security/create-kms-config.md/aws-kms.md
docs/content/latest/yugabyte-platform/security/create-kms-config.md/equinix-smartkey.md
docs/content/latest/yugabyte-platform/security/enable-encryption-at-rest.md

Ticket: https://yugabyte.atlassian.net/browse/PLAT-2304
Preview: https://deploy-preview-10627--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/security/create-kms-config.md/aws-kms/

[docs] PR for Document PLAT-1962 feature (DocPLAT-2304)

---

docs/content/latest/yugabyte-cloud/release-notes.md

Add new features for Nov 18 release
https://deploy-preview-10640--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-cloud/release-notes/

[docs] Cloud Whats New

---

docs/content/latest/api/ysql/exprs/_index.md
docs/content/latest/api/ysql/exprs/func_currval.md
docs/content/latest/api/ysql/exprs/func_yb_hash_code.md
docs/content/stable/api/ysql/exprs/_index.md
docs/content/stable/api/ysql/exprs/func_yb_hash_code.md

[docs] yb_hash_code docs

---

docs/content/latest/_index.html
docs/content/latest/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/latest/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/latest/quick-start/install/kubernetes.md
docs/content/latest/quick-start/install/linux.md
docs/content/latest/quick-start/install/macos.md
docs/content/latest/releases/earlier-releases/v2.9.md
docs/content/latest/releases/releases-overview.md
docs/content/latest/releases/versioning.md
docs/content/latest/releases/whats-new/_index.md
docs/content/latest/releases/whats-new/latest-release.md
docs/content/latest/releases/whats-new/stable-release.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/layouts/partials/detect_version.html
docs/layouts/partials/version_switcher.html

[docs] 2.11.0.0 release

---

docs/content/latest/reference/configuration/yb-master.md
docs/content/latest/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yb-master.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/v2.6/reference/configuration/yb-master.md
docs/content/v2.6/reference/configuration/yb-tserver.md

cipher_list and ciphersuites g flags - add to tserver and master flag reference
@netlify /latest/reference/configuration/yb-tserver/#security-flags

[docs] cipher g flags

---

docs/content/latest/yugabyte-cloud/cloud-develop/_index.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/_index.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/qs-add.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/qs-connect.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/qs-data.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/qs-explore.md

Split quickstart into multiple pages to be consistent with Core quickstart
@netlify /latest/yugabyte-cloud/cloud-quickstart/

[docs] Cloud multi-page quickstart

---

docs/content/latest/releases/earlier-releases/v2.4.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/content/v2.4/quick-start/install/linux.md
docs/content/v2.4/quick-start/install/macos.md
docs/content/v2.4/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md

@netlify /latest/releases/earlier-releases/v2.4/

[docs] 2.4.8.0 release notes

---

docs/layouts/_default/list.html
docs/layouts/_default/single.html

@netlify /stable/api/ysql/datatypes/type_datetime/

[docs] [infra] update version notice to 2.11

---

docs/content/latest/releases/earlier-releases/v2.6.md
docs/content/v2.6/quick-start/install/docker.md
docs/content/v2.6/quick-start/install/linux.md
docs/content/v2.6/quick-start/install/macos.md

[docs] update 2.6 to 2.6.7.0

---

docs/content/latest/quick-start/build-apps/python/ysql-psycopg2.md

Resolves #10101
@netlify /latest/quick-start/build-apps/python/ysql-psycopg2/

[docs] add SSL to python quickstart

---

docs/content/latest/deploy/checklist.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/prerequisites.md

remove ambiguity from OS version numbers

[docs] [platform] clarify OS prerequisites

---

docs/content/latest/releases/earlier-releases/v2.6.md

Bumping the release date to today...

[docs] correct the 2.6.7.0 release date

---

docs/content/latest/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/latest/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/latest/quick-start/install/kubernetes.md
docs/content/latest/quick-start/install/linux.md
docs/content/latest/quick-start/install/macos.md
docs/content/latest/releases/earlier-releases/v2.6.md
docs/content/latest/releases/whats-new/latest-release.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md

[docs] release 2.11.0.1

---

docs/content/latest/explore/ysql-language-features/gin.md

- change hstore to supported
- add intarray to the list as unsupported

[docs] Update extensions in GIN explore doc

---

docs/content/latest/quick-start/install/linux.md
docs/content/latest/quick-start/install/macos.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md

Missed a couple version numbers in the 2.11.0.1 release. Thanks for catching this, @ddhodge!

[docs] quick version fix

---

docs/content/latest/yugabyte-cloud/cloud-basics/add-connections.md
docs/content/latest/yugabyte-cloud/cloud-connect/connect-client-shell.md
docs/content/latest/yugabyte-cloud/cloud-connect/connect-cloud-shell.md
docs/content/latest/yugabyte-cloud/cloud-faq.md

Add connection string for psql client
@netlify /latest/yugabyte-cloud/cloud-connect/connect-client-shell/#connect-using-psql

[docs] Cloud Add psql connection info

---

docs/content/latest/manage/backup-restore/point-in-time-recovery.md

This PR updates our documentation on the current PITR limitations. Features like Sequences needed more explicit mention while a few limitations no longer exist because of recent fixes.

[docs] Revised PITR limitations

---

docs/content/latest/yugabyte-platform/security/enable-encryption-in-transit.md

Preview: https://deploy-preview-10691--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/security/enable-encryption-in-transit/#enforcing-tls-versions

 [docs] PR for Clarify that ssl_protocols gflag for yb-tserver/master is not a "min" setting (Doc10018)

---

docs/content/latest/yugabyte-cloud/release-notes.md

Add known issue about Safari 14.0 and View Full Screen option in charts.
@netlify /latest/yugabyte-cloud/release-notes/#known-issues
https://deploy-preview-10839--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-cloud/release-notes/#known-issues

[docs] Cloud Safari known issue

---

docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md

[docs] PR for DocAirgapURLFix

---

docs/content/stable/yugabyte-platform/create-deployments/async-replication-platform.md

Backport of doc (https://yugabyte.atlassian.net/browse/PLAT-1978) from latest to stable

[docs] PR backport of asynch replication content from latest to stable

---

docs/content/latest/sample-data/_index.md
docs/content/latest/sample-data/chinook.md
docs/content/latest/sample-data/northwind.md
docs/content/latest/sample-data/pgexercises.md
docs/content/latest/sample-data/retail-analytics.md
docs/content/latest/sample-data/sportsdb.md

Update sample dataset instructions with cloud shell support
@netlify /latest/sample-data/

[docs] Cloud - update sample datasets for cloud shell

---

docs/content/latest/yugabyte-cloud/cloud-troubleshoot.md

Troubleshooting page for Cloud issues
@netlify /latest/yugabyte-cloud/cloud-troubleshoot/

[docs] Cloud Troubleshooting

---

docs/content/latest/yugabyte-cloud/cloud-faq.md

Quick fix to FAQ regarding releases for Free vs standard clusters.
@netlify /latest/yugabyte-cloud/cloud-faq

[docs] Cloud FAQ release versions

---

docs/content/latest/quick-start/build-apps/java/ycql.md
docs/content/latest/reference/drivers/ycql-client-drivers.md
docs/content/stable/quick-start/build-apps/java/ycql.md
docs/content/stable/reference/drivers/ycql-client-drivers.md

Updating the driver dependency for YCQL 3.x drivers to the latest `3.10.3-yb-2` dependency.

[docs] Updated the driver dependency to 3.10.3-yb-2.

---

docs/content/latest/admin/yb-admin.md
docs/content/latest/releases/earlier-releases/v2.6.md
docs/content/v2.6/admin/yb-admin.md
docs/content/v2.6/quick-start/install/docker.md
docs/content/v2.6/quick-start/install/linux.md
docs/content/v2.6/quick-start/install/macos.md
docs/content/v2.6/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md

This includes the usual changes for release notes, and ALSO a small docs change to yb-admin as a result of #10900. (@amitanandaiyer please take a look at `docs/content/v2.6/admin/yb-admin.md` to make sure that's good to go!)

[docs] release 2.6.10.0

---

docs/content/latest/faq/general.md
docs/content/latest/yugabyte-cloud/cloud-faq.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/_index.md
docs/content/latest/yugabyte-platform/overview/_index.md

Add alias for cloud root for external links

[docs][cloud] Alias cloud root

---

docs/content/latest/deploy/kubernetes/multi-zone/gke/helm-chart.md

[docs] Deploy GKE typo

---

docs/content/latest/integrations/kairosdb.md

Resolves #11057 
Updated the version and fixed few broken links.
@netlify /latest/integrations/kairosdb/

[Docs] update kairosDB integration page.

---

docs/content/latest/quick-start/build-apps/csharp/ycql.md
docs/content/latest/releases/earlier-releases/v2.6.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md
docs/content/stable/quick-start/build-apps/csharp/ycql.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md
docs/content/v2.2/quick-start/build-apps/csharp/ycql.md
docs/content/v2.2/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md
docs/content/v2.4/quick-start/build-apps/csharp/ycql.md
docs/content/v2.4/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md
docs/content/v2.6/quick-start/build-apps/csharp/ycql.md
docs/content/v2.6/quick-start/install/docker.md
docs/content/v2.6/quick-start/install/linux.md
docs/content/v2.6/quick-start/install/macos.md
docs/content/v2.6/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/content/v2.6/yugabyte-platform/install-yugabyte-platform/install-software/default.md
docs/content/v2.6/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/v2.6/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
docs/content/v2.6/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md

[docs] release 2.6.11.0

---

docs/content/latest/yugabyte-platform/administer-yugabyte-platform/ldap-authentication.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-2730
Relates to https://github.com/yugabyte/yugabyte-db/pull/11023
Preview: https://deploy-preview-11111--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/administer-yugabyte-platform/ldap-authentication/

[Doc] PR for Document LDAP support for Platform ( CLI / API ) - Part 2

---

docs/content/latest/yugabyte-cloud/cloud-faq.md

How free clusters are paused and resumed
@netlify /latest/yugabyte-cloud/cloud-faq/#clusters

[Docs] [Cloud] Pausing clusters

---

docs/content/latest/integrations/jdbc-driver.md

resolves #11231 
@netlify /latest/integrations/jdbc-driver/

[docs] [integrations] fix semicolon syntax typo on JDBC integrations page

---

docs/content/latest/yugabyte-cloud/cloud-quickstart/_index.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/_index.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-apps-java/cloud-ysql-yb-jdbc.md

Build and run a sample Java app connected to Cloud

[docs][cloud] Java app cloud example

---

docs/content/latest/yugabyte-cloud/release-notes.md

[docs][cloud] Whats new Jan

---

.github/vale-styles/Yugabyte/spelling-exceptions.txt
docs/content/latest/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/latest/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/latest/quick-start/install/kubernetes.md
docs/content/latest/quick-start/install/linux.md
docs/content/latest/quick-start/install/macos.md
docs/content/latest/releases/earlier-releases/v2.6.md
docs/content/latest/releases/whats-new/latest-release.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md

[docs] release 2.11.2.0

---

docs/content/latest/yugabyte-cloud/cloud-quickstart/qs-add.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/qs-data.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/qs-explore.md

Update quickstart to link to the new demo Java app page
@netlify /latest/yugabyte-cloud/cloud-quickstart/qs-explore/

[docs][cloud] Link to Build Apps page

---

docs/content/latest/yugabyte-cloud/cloud-clusters/add-extensions.md
docs/content/latest/yugabyte-cloud/cloud-security/_index.md
docs/content/latest/yugabyte-cloud/release-notes.md

Fix broken link
@netlify /latest/yugabyte-cloud/cloud-clusters/add-extensions/

[docs][cloud] fix link

---

docs/content/stable/yugabyte-platform/overview/_index.md

Fixed in stable.
2.4 and 2.2 are EOL.

[Docs] PR for Broken links on some of the platform tiles

---

docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/_index.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-go.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-yb-jdbc.md

Add simple Go application example

[docs][cloud] Add go application

---

docs/content/latest/reference/configuration/yugabyted.md

Typos, format
@netlify /latest/reference/configuration/yugabyted/

[docs] Yugabyted typos

---

docs/content/latest/architecture/docdb-sharding/tablet-splitting.md

Thanks for developing useful geo-distributed database!
I make a PR because I was a little troubled.
Please let me know if I misunderstood something.
Regards,

[docs] Fix an incorrect "SPLIT AT VALUES" example

---

docs/content/latest/releases/whats-new/stable-release.md
docs/content/stable/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/stable/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/stable/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/stable/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/stable/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/stable/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/stable/quick-start/install/kubernetes.md
docs/content/stable/quick-start/install/linux.md
docs/content/stable/quick-start/install/macos.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md

@netlify /latest/releases/whats-new/stable-release/#v2.8.1.1

[docs] release 2.8.1.1

---

docs/content/latest/api/ysql/extensions.md

Only one "brew install" required

[docs] Minor postgis instruction fixes

---

docs/content/latest/yugabyte-cloud/release-notes.md

[docs][cloud] Release notes Feb 3

---

docs/content/latest/api/ysql/datatypes/type_json/primitive-and-compound-data-types.md
docs/content/latest/develop/learn/data-modeling-ycql.md
docs/content/latest/quick-start/build-apps/go/ysql-gorm.md
docs/content/latest/quick-start/build-apps/java/ysql-spring-data.md
docs/content/latest/quick-start/build-apps/nodejs/ysql-sequelize.md
docs/content/latest/quick-start/build-apps/python/ysql-sqlalchemy.md
docs/content/latest/quick-start/build-apps/ruby/ysql-rails-activerecord.md
docs/content/stable/api/ysql/datatypes/type_json/primitive-and-compound-data-types.md
docs/content/stable/develop/learn/data-modeling-ycql.md
docs/content/stable/quick-start/build-apps/go/ysql-gorm.md
docs/content/stable/quick-start/build-apps/java/ysql-spring-data.md
docs/content/stable/quick-start/build-apps/nodejs/ysql-sequelize.md
docs/content/stable/quick-start/build-apps/python/ysql-sqlalchemy.md
docs/content/stable/quick-start/build-apps/ruby/ysql-rails-activerecord.md

resolves #11134 
Fixed the domain names in latest and stable in 7 files each
@netlify /latest/quick-start/build-apps/

[docs] fix domain name in quick-start pages.

---

docs/content/latest/reference/drivers/ysql-client-drivers.md
docs/content/latest/yugabyte-cloud/cloud-develop/_index.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/_index.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-python.md

Add example Python app
@netlify /latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-python/

[docs][cloud] Python app

---

docs/content/latest/yugabyte-platform/administer-yugabyte-platform/ldap-authentication.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-2984

[Doc] PR for Service Account Documentation 

---

docs/content/latest/quick-start/build-apps/nodejs/ycql.md
docs/content/latest/quick-start/build-apps/nodejs/ysql-pg.md
docs/content/latest/quick-start/build-apps/nodejs/ysql-sequelize.md
docs/content/latest/reference/drivers/ysql-client-drivers.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/_index.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-go.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-node.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-python.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-yb-jdbc.md

node.js quickstart application for Coud

[docs][cloud] nodejs application for cloud

---

docs/content/latest/quick-start/build-apps/c/ysql.md
docs/content/latest/reference/drivers/ysql-client-drivers.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/_index.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-c.md

C application for build apps section

[docs][cloud] C example app

---

docs/content/latest/releases/whats-new/stable-release.md

This item was included in error. Removing it to avoid further confusion.

[docs] remove plat-1777 from stable release notes

---

docs/content/latest/reference/drivers/ysql-client-drivers.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/_index.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-c.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-cpp.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-go.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-node.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-python.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-yb-jdbc.md

Sample C++ app for cloud quick start

[docs][cloud] C++ sample app

---

managed/devops/roles/install_backup_util/defaults/main.yml

Updated the azcopy (10.4.0 to 10.13.0) to newer versions.
The updated versions don't have any breaking changes.
Issue - yugabyte#11004

[Backport 2.4][Platform] Update azcopy version

---

docs/content/latest/manage/backup-restore/back-up-data-ycql.md
docs/content/latest/yugabyte-cloud/cloud-overview.md

Add alias to Cloud Overview for EA Cloud docs
@netlify /latest/yugabyte-cloud/cloud-overview/

[docs][cloud] EA Cloud docs alias

---

docs/content/latest/reference/drivers/ysql-client-drivers.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/_index.md
docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-csharp.md

[docs][cloud] c sharp app

---

docs/content/latest/releases/earlier-releases/v2.6.md
docs/content/v2.6/quick-start/install/docker.md
docs/content/v2.6/quick-start/install/linux.md
docs/content/v2.6/quick-start/install/macos.md
docs/content/v2.6/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md

[docs] release 2.6.14.0

---

docs/content/v2.6/yugabyte-platform/manage-deployments/upgrade-software.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-2710
Preview: https://deploy-preview-11351--infallible-bardeen-164bc9.netlify.app/v2.6/yugabyte-platform/manage-deployments/upgrade-software/

[Doc] PR for Add a section for system catalog upgrade feature upgrade in DB upgrade documentation

---

docs/content/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-yb-jdbc.md

Update to code snippet
@netlify /latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-yb-jdbc/

[docs][cloud] Java app update

---

.github/vale-styles/Yugabyte/Product-names.yml
.github/vale-styles/Yugabyte/Spelling.yml
.github/vale-styles/Yugabyte/SubstitutionWarnings.yml
.github/vale-styles/Yugabyte/spelling-exceptions.txt
docs/CONTRIBUTING.md
docs/README.md
docs/content/latest/develop/best-practices-ycql.md
docs/content/latest/develop/explore-sample-apps.md
docs/content/latest/secure/column-level-encryption.md

This is a number of little fixes:
- Vale rule updates
- Meta docs (linting, mostly)
- Fixes to a couple docs for proper rendering
Netlify preview starts on the one that most needed an update, to get rid of a huge TOC right at the top...
@netlify /latest/develop/explore-sample-apps/

[docs] misc updates

---

docs/content/latest/quick-start/build-apps/nodejs/ycql.md
docs/content/stable/quick-start/build-apps/nodejs/ycql.md
docs/content/v2.0/quick-start/build-apps/nodejs/ycql.md
docs/content/v2.1/quick-start/build-apps/nodejs/ycql.md
docs/content/v2.2/quick-start/build-apps/nodejs/ycql.md
docs/content/v2.4/quick-start/build-apps/nodejs/ycql.md
docs/content/v2.6/quick-start/build-apps/nodejs/ycql.md

this pr fixes issue #11439 and replaces pr #11451

[docs] fix YCQL example code

---

docs/content/latest/deploy/multi-dc/async-replication.md

Added info about how to do schema migrations
- Stop writes
- Use backup/restore
Also added an empty header for the bootstrap flow, to be able to reference it.

[#4571] xcluster: Add info about schema change and skeleton for bootstrap

---

docs/content/latest/explore/linear-scalability/scaling-transactions.md
docs/content/latest/explore/linear-scalability/sharding-data.md
docs/content/stable/explore/linear-scalability/scaling-transactions.md
docs/content/stable/explore/linear-scalability/sharding-data.md
docs/content/v2.6/explore/linear-scalability/scaling-transactions.md
docs/content/v2.6/explore/linear-scalability/sharding-data.md
docs/content/v2.8/explore/linear-scalability/scaling-transactions.md
docs/content/v2.8/explore/linear-scalability/sharding-data.md

Thank you @SteveXiSong for reporting the issue.
Changed the order for latest, stable , 2.8 and 2.6 versions.
@netlify /latest/explore/linear-scalability/

[docs] [explore] changed order for left nav under Horizontal scalability.

---

docs/content/latest/faq/general.md
docs/content/latest/releases/_index.md
docs/content/latest/releases/release-notes/v2.11.md
docs/content/latest/releases/release-notes/v2.12.md
docs/content/latest/releases/release-notes/v2.8.md
docs/content/v2.8/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/v2.8/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/v2.8/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/v2.8/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/v2.8/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/v2.8/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/v2.8/quick-start/install/kubernetes.md
docs/content/v2.8/quick-start/install/linux.md
docs/content/v2.8/quick-start/install/macos.md

(plus a couple of release-related aliases)
@netlify /latest/releases/release-notes/v2.8/

[docs] release 2.8.3.0

---

docs/content/latest/yugabyte-cloud/cloud-admin/manage-access.md
docs/content/latest/yugabyte-cloud/cloud-examples/hasura-cloud.md
docs/content/latest/yugabyte-cloud/cloud-examples/hasura-sample-app.md
docs/content/latest/yugabyte-cloud/cloud-faq.md
docs/content/latest/yugabyte-cloud/cloud-troubleshoot.md

Remove references to console in YB Cloud
@netlify /latest/yugabyte-cloud/cloud-faq/

[docs][cloud] Remove references to console

---

docs/content/latest/yugabyte-platform/security/create-kms-config/aws-kms.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-3288
Preview: https://deploy-preview-11664--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/security/create-kms-config/aws-kms/

[Doc] PR for Request to add kms:TagResource permission needed for AWS KMS creation in the AWS KMS doc 

---

docs/content/latest/yugabyte-cloud/cloud-examples/connect-ycql-application.md

Add an alias to page that was moved for links from Cloud UI
@netlify /latest/yugabyte-cloud/cloud-develop/connect-ycql-application/

[docs][cloud] Fix alias

---

docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md

Addresses all points of https://yugabyte.atlassian.net/browse/PLAT-3287 except the last one.
Preview: https://deploy-preview-11676--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes/

[Docs] PR for Improvements for k8s install

---

docs/content/latest/deploy/multi-dc/async-replication.md

Adding section to the xCluster setup docs for how to setup xCluster in K8s when you have pod to pod connectivity.

[11559-xCluster][Doc] Documentation on how to setup xCluster in K8s when you have pod to pod connectivity

---

docs/content/latest/deploy/multi-dc/async-replication.md

Adding section to the xCluster setup docs for how to setup xCluster replication with backup restore - using bootstrap_cdc_producer option.

[6870][Docs]Setting up xCluster Replication With Backup Restore 

---

docs/content/latest/deploy/multi-dc/async-replication.md

Fixed couple of broken links in recent code changes.

Broken link fix

---

docs/content/latest/_index.html
docs/content/latest/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/latest/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/latest/quick-start/install/kubernetes.md
docs/content/latest/quick-start/install/linux.md
docs/content/latest/quick-start/install/macos.md
docs/content/latest/releases/_index.md
docs/content/latest/releases/release-notes/v2.11.md
docs/content/latest/releases/release-notes/v2.13.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/layouts/_default/list.html
docs/layouts/_default/single.html
docs/layouts/partials/detect_version.html
docs/layouts/partials/version_switcher.html

@netlify /latest/releases/release-notes/latest-release/

[docs] release 2.13.0.0

---

docs/content/latest/integrations/django-rest-framework.md

Added parameter to turn on persistent connections with Django for now. Let me know if I need to add a more detailed description on the performance of persistent connections. Although I am planning to add that in the blog.

Add about persistent connection setting in django doc

---

docs/content/latest/yugabyte-cloud/release-notes.md

[docs][cloud]Release notes

---

docs/content/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/aws.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-3352
Preview: 
https://deploy-preview-11747--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/aws/
https://deploy-preview-11747--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp

[doc] PR for Include YSQL Port 13000 for Firewall in Platform Installation

---

docs/layouts/partials/head.html

Part 1 - Update the version to latest in the 5 series and then look at [Upgrade to version 6](https://fontawesome.com/docs/web/setup/upgrade/)
@netlify /latest/quick-start/build-apps/

[docs] [infra] update font awesome to version 5.14.4

---

docs/content/latest/yugabyte-platform/install-yugabyte-platform/uninstall-software.md

Partially addresses https://yugabyte.atlassian.net/browse/PLAT-2740
Note that the Replicated rm command (step 3) doesn't work, according to dev. Platform PM is trying to decide what to do about this part of the document. Update: decided to remove the Docker section for now. The doc ticket in Jira will remain open as "in progress".

[Doc] PR for Improve Platform uninstall instructions

---

docs/content/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/aws.md

Addresses https://github.com/yugabyte/yugabyte-db/issues/11750  and  https://yugabyte.atlassian.net/browse/PLAT-2739

[docs] PR for IAM role for AWS Platform is missing some permissions

---

docs/content/latest/develop/best-practices-ycql.md
docs/content/latest/develop/learn/ttl-data-expiration-ycql.md
docs/content/latest/reference/configuration/yb-tserver.md

Documentation for the feature that expires files based on their TTL metadata.

[#10875][Docs][DocDB] Documentation for file expiration based on TTL

---

docs/content/latest/yugabyte-cloud/release-notes.md

Note known issue in Pause/Resume UI
@netlify /latest/yugabyte-cloud/release-notes/#known-issues

[docs][cloud] Pause cluster known issue

---

docs/content/latest/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/latest/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/latest/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/latest/quick-start/install/kubernetes.md
docs/content/latest/quick-start/install/linux.md
docs/content/latest/quick-start/install/macos.md
docs/content/latest/releases/release-notes/v2.13.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md

@netlify /latest/releases/release-notes/v2.13/

[docs] release 2.13.0.1

---

docs/content/latest/architecture/concepts/yb-master.md
docs/content/latest/architecture/concepts/yb-tserver.md
docs/content/latest/architecture/docdb-replication/async-replication.md
docs/content/latest/architecture/transactions/distributed-txns.md
docs/content/latest/architecture/transactions/explicit-locking.md
docs/content/latest/architecture/transactions/single-row-transactions.md
docs/content/latest/explore/cluster-management/point-in-time-recovery-ycql.md
docs/content/latest/explore/cluster-management/point-in-time-recovery-ysql.md
docs/content/stable/architecture/concepts/yb-master.md
docs/content/stable/architecture/concepts/yb-tserver.md
docs/content/stable/architecture/docdb-replication/async-replication.md
docs/content/stable/architecture/transactions/distributed-txns.md
docs/content/stable/architecture/transactions/single-row-transactions.md
docs/content/stable/explore/cluster-management/point-in-time-recovery-ycql.md
docs/content/stable/explore/cluster-management/point-in-time-recovery-ysql.md
docs/content/v2.1/architecture/transactions/explicit-locking.md

Fixed a few typos in documentation

[docs] Fix a few typos

---

docs/content/latest/deploy/multi-dc/async-replication.md

Added a note in xCluster setup with GP section

xCluster with GeoPartitioning doc

---

docs/content/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-3354

[docs] PR for Add TServer gflag for hostname in on-prem provider setup

---

docs/content/latest/yugabyte-cloud/cloud-clusters/cloud-maintenance.md

Add info on effect of rolling maintenance/upgrade on cluster
@netlify /latest/yugabyte-cloud/cloud-clusters/cloud-maintenance/#what-to-expect-during-maintenance

[docs][cloud] Notes on maintenance

---

docs/content/latest/releases/release-notes/v2.6.md
docs/content/v2.6/quick-start/install/docker.md
docs/content/v2.6/quick-start/install/linux.md
docs/content/v2.6/quick-start/install/macos.md
docs/content/v2.6/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md

@netlify /latest/releases/release-notes/v2.6/#v2.6.16.0

[docs] release 2.6.16.0

---

docs/content/latest/deploy/checklist.md

[docs] Update checklist.md

---

docs/content/latest/manage/data-migration/ycql/bulk-export.md

NOTE: This PR is dependent on this PR: https://github.com/yugabyte/cassandra-loader/pull/4

[docs] Update cassandra-(un)loader download urls

---

docs/content/latest/yugabyte-cloud/cloud-basics/create-clusters-overview.md

Add more detail for planning clusters before deployment
@netlify /latest/yugabyte-cloud/cloud-basics/create-clusters-overview/

[docs][cloud] Updated planning page

---

docs/content/latest/manage/data-migration/ycql/bulk-export.md

Reverts yugabyte/yugabyte-db#11811

Revert "[docs] Update cassandra-(un)loader download urls"

---

docs/content/latest/yugabyte-cloud/cloud-admin/_index.md
docs/content/latest/yugabyte-cloud/cloud-basics/_index.md
docs/content/latest/yugabyte-cloud/cloud-clusters/_index.md
docs/content/latest/yugabyte-cloud/cloud-clusters/add-extensions.md
docs/content/latest/yugabyte-cloud/cloud-clusters/cloud-maintenance.md
docs/content/latest/yugabyte-cloud/cloud-connect/_index.md
docs/content/latest/yugabyte-cloud/cloud-faq.md
docs/content/latest/yugabyte-cloud/cloud-monitor/_index.md
docs/content/latest/yugabyte-cloud/cloud-overview.md
docs/content/latest/yugabyte-cloud/cloud-secure-clusters/_index.md

Formatting due to text in glossary format not being indexed
@netlify /latest/yugabyte-cloud/cloud-overview/

[docs][cloud] Formatting for search indexing

---

docs/content/latest/quick-start/build-apps/_index.html
docs/content/latest/quick-start/build-apps/go/ycql.md
docs/content/latest/quick-start/build-apps/go/ysql-gorm.md
docs/content/latest/quick-start/build-apps/go/ysql-pg.md
docs/content/latest/quick-start/build-apps/go/ysql-pgx.md
docs/content/latest/quick-start/build-apps/go/ysql-pq.md
docs/content/latest/quick-start/build-apps/go/ysql-yb-pgx.md

Quickstart doc for YugabyteDB PGX Go smart driver.

Quickstart doc for YugabyteDB PGX Go driver

---

docs/content/latest/explore/indexes-constraints/expression-index-ysql.md

added a missed comment from previous PR #11764

[docs] [explore] minor update to expression indexes page.

---

docs/content/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-3143
Preview: https://deploy-preview-11921--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises/#remove-yugabytedb-components-from-the-server

[Docs] Document how to clean up an onprem node for reuse

---

docs/content/latest/releases/release-notes/v2.12.md

@netlify /latest/releases/release-notes/v2.12/#known-issues

[docs] add known issue to 2.12.2.0

---

docs/content/latest/releases/release-notes/v2.8.md
docs/content/v2.8/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/v2.8/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/v2.8/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/v2.8/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/v2.8/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/v2.8/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/v2.8/quick-start/install/kubernetes.md
docs/content/v2.8/quick-start/install/linux.md
docs/content/v2.8/quick-start/install/macos.md
docs/data/currentVersions.json

@netlify /latest/releases/release-notes/v2.8/#v2.8.4.0

[docs] release 2.8.4.0

---

docs/content/latest/admin/ysqlsh.md

ysqlsh tablegroup metacommands dgr and dgrt
@netlify /latest/admin/ysqlsh/#dgr-pattern-patterns

[docs] Add dgr/dgrt meta commands

---

docs/config.yaml
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
docs/layouts/partials/footer_js.html
docs/static/googlebc78dc81cc5de354.html

Update to the new Algolia crawler app, change robots.txt as required, and add another google verification.

[docs] update search config

---

docs/content/preview/reference/configuration/yb-tserver.md

resolves #9174 
@netlify /preview/reference/configuration/yb-tserver/#network-compression

[docs] [reference] compression types for yb-tserver

---

docs/content/stable/explore/cluster-management/point-in-time-recovery-ysql.md

Added -master_addresses <master_addresses> in the admin commands.

[docs] add -master_addresses to yb-admin commands

---

docs/content/preview/quick-start/install/docker.md
docs/content/preview/quick-start/install/linux.md
docs/content/preview/quick-start/install/macos.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md

Fix the download links/versions in all four install pages.
@netlify /preview/quick-start/install/linux/

[docs] update download links

---

docs/content/preview/releases/release-notes/v2.12.md
docs/content/stable/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/stable/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/stable/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/stable/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/stable/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/stable/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/stable/quick-start/build-apps/java/ysql-jdbc-ssl.md
docs/content/stable/quick-start/create-local-cluster/kubernetes.md
docs/content/stable/quick-start/install/kubernetes.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.12/#v2.12.3.0

[docs] release 2.12.3.0

---

managed/src/main/java/com/yugabyte/yw/common/NativeKubernetesManager.java

Fixes some issues from PLAT-2746.
The pullSecret is actually present on the disk, we were trying to load
it using getResourceAsStream, which was returning null. This resulted
in pull secret not getting created in the destination namespace. With
this change the pull secret is loaded from the disk and passed to the
Kubernetes client library.
It also modifies the logic to create Kubernetes client to account for
blank KUBECONFIG value. This variable is set to a blank string when
user doesn't provide a kubeconfig during provider creation. In such
cases we fall back to in-cluster credentials.
- Created a couple of universes with yb.use_kubectl set to false. The
pull secret was created successfully in the destination namespace.
- Tried to create universes using a provider …

[Platform][Kubernetes client] Use pull secret from disk

---

docs/content/preview/yugabyte-cloud/cloud-quickstart/_index.md
docs/content/preview/yugabyte-cloud/cloud-quickstart/qs-add.md

Fix a link
@netlify /preview/yugabyte-cloud/cloud-quickstart/

[docs][cloud] Link fix

---

docs/content/preview/drivers-orms/_index.md
docs/content/preview/drivers-orms/csharp/_index.md
docs/content/preview/drivers-orms/csharp/compatibility.md
docs/content/preview/drivers-orms/csharp/entityframework.md
docs/content/preview/drivers-orms/csharp/postgres-npgsql.md
docs/content/preview/drivers-orms/go/_index.md
docs/content/preview/drivers-orms/go/compatibility.md
docs/content/preview/drivers-orms/go/gorm.md
docs/content/preview/drivers-orms/go/pg.md
docs/content/preview/drivers-orms/go/pgx.md
docs/content/preview/drivers-orms/go/pq.md
docs/content/preview/drivers-orms/java/_index.md
docs/content/preview/drivers-orms/java/compatibility.md
docs/content/preview/drivers-orms/java/hibernate.md
docs/content/preview/drivers-orms/java/postgres-jdbc.md
docs/content/preview/drivers-orms/java/yugabyte-jdbc.md
docs/content/preview/drivers-orms/nodejs/_index.md
docs/content/preview/drivers-orms/nodejs/compatibility.md
docs/content/preview/drivers-orms/nodejs/postgres-node-driver.md
docs/content/preview/drivers-orms/nodejs/sequelize-yugabytedb.md
docs/content/preview/drivers-orms/nodejs/sequelize.md
docs/content/preview/drivers-orms/python/_index.md
docs/content/preview/drivers-orms/python/compatibility.md
docs/content/preview/drivers-orms/python/django.md
docs/content/preview/drivers-orms/python/postgres-psycopg2.md
docs/content/preview/drivers-orms/python/sqlalchemy.md
docs/content/preview/drivers-orms/python/yugabyte-psycopg2.md
docs/content/preview/reference/drivers/go/pgx-reference.md
docs/content/preview/reference/drivers/go/pq-reference.md

Edits and style
@netlify /preview/drivers-orms/

[docs][core-drivers] Edits and fixes

---

docs/content/preview/quick-start/build-apps/rust/ysql-diesel.md

Quick start for building a Rust app using Diesel and YSQL
#11827
@netlify /preview/quick-start/build-apps/rust/ysql-diesel/

[docs][orm] Quick start Rust Diesel

---

docs/content/preview/drivers-orms/python/yugabyte-psycopg2.md
docs/content/preview/reference/drivers/python/yugabyte-psycopg2-reference.md

Added install instructions for psycopg2-yugabytedb.

Add install instructions for psycopg2 smart driver

---

docs/content/preview/releases/release-notes/v2.6.md
docs/content/v2.6/quick-start/install/docker.md
docs/content/v2.6/quick-start/install/linux.md
docs/content/v2.6/quick-start/install/macos.md
docs/content/v2.6/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/data/currentVersions.json

@jharveysmith please merge once the downloads are live...
@netlify /preview/releases/release-notes/v2.6/#v2.6.17.0

[docs] release 2.6.17.0

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
docs/content/v2.8/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-3590

[doc] PR for Link to AZCopy broken on OnPrem config docs

---

docs/content/preview/develop/learn/date-and-time-ysql.md
docs/content/preview/develop/learn/strings-and-text-ysql.md
docs/content/preview/explore/query-1-performance/pg-stat-activity.md

Update references to example data - xref Retail Analytics page due to change in quick start dataset. Misc edits and tidyups.
@netlify /preview/develop/learn/date-and-time-ysql/

[docs] Update example datasets

---

docs/content/preview/releases/release-notes/v2.6.md
docs/content/v2.6/quick-start/install/docker.md
docs/content/v2.6/quick-start/install/linux.md
docs/content/v2.6/quick-start/install/macos.md
docs/content/v2.6/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/data/currentVersions.json

(Draft mode until release time)
@netlify /preview/releases/release-notes/v2.6/#v2.6.18.0

[docs] release 2.6.18.0

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-3757

[Docs] PR for Document how to run yugabyte pods as non-root

---

docs/content/preview/releases/release-notes/v2.8.md
docs/content/v2.8/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/v2.8/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/v2.8/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/v2.8/deploy/kubernetes/single-zone/aks/helm-chart.md
docs/content/v2.8/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/v2.8/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/v2.8/quick-start/install/kubernetes.md
docs/content/v2.8/quick-start/install/linux.md
docs/content/v2.8/quick-start/install/macos.md
docs/content/v2.8/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
docs/content/v2.8/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/v2.8/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
docs/data/currentVersions.json

(Draft mode until release is ready)
@netlify /preview/releases/release-notes/v2.8/#v2.8.5.0

[docs] release 2.8.5.0

---

docs/content/preview/yugabyte-cloud/cloud-admin/_index.md
docs/content/preview/yugabyte-cloud/cloud-admin/cloud-billing-profile.md
docs/content/preview/yugabyte-cloud/cloud-faq.md
docs/content/preview/yugabyte-cloud/cloud-secure-clusters/add-connections.md

Document limit of 30 ip allow list rules for AWS clusters
@netlify /preview/yugabyte-cloud/cloud-secure-clusters/add-connections/

[docs][cloud] Add AWS allowlist rule limit

---

docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters.md
docs/content/preview/yugabyte-cloud/cloud-clusters/configure-clusters.md
docs/content/preview/yugabyte-cloud/cloud-overview.md
docs/content/preview/yugabyte-cloud/cloud-quickstart/_index.md
docs/content/preview/yugabyte-cloud/cloud-quickstart/cloud-build-apps/_index.md
docs/content/preview/yugabyte-cloud/cloud-quickstart/qs-add.md
docs/content/preview/yugabyte-cloud/cloud-quickstart/qs-explore.md

Add links to yuotube channel videos and playlist
@netlify /preview/yugabyte-cloud/cloud-quickstart/

[docs][cloud] Add video links

---

docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/_index.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-peering.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-vpc.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-configure-provider.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-vpc-intro.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-vpc-setup.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/peer/peer-aws.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/peer/peer-gcp.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/provider/provider-aws.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/provider/provider-gcp.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-applications.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-client-shell.md

To accommodate links from the UI, move the configure provider topic. Plus other edits.
@netlify /preview/yugabyte-cloud/cloud-basics/cloud-vpcs/

[docs][cloud] Reorganize peering topics

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
docs/content/v2.8/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-3837
Preview: https://deploy-preview-12377--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises/#install-systemd-related-database-service-unit-files

[Docs] PR for Add steps to install systemd related DB service unit files in the YB anywhere document

---

docs/content/preview/yugabyte-platform/security/enable-encryption-at-rest.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-3918

[docs] PR for Update "Enable encryption at rest on an existing universe" steps

---

docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-free.md

Clarify free tier limit on objects
@netlify /preview/yugabyte-cloud/cloud-basics/create-clusters-free/#limitations

[docs][cloud] Clarification of free tier limits

---

docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md

Related to https://github.com/yugabyte/yugabyte-db/pull/12306

[doc] PR that adds a command to the platform k8s upgrade doc

---

docs/content/preview/yugabyte-cloud/release-notes.md

[docs][cloud] fix dates

---

docs/content/preview/releases/release-notes/v2.12.md

@netlify /preview/releases/release-notes/v2.12/#v2.12.5.0

[docs] add 3rd-party licenses to v2.12 rel notes

---

architecture/design/docdb-change-data-capture.md

Rewording some parts, fixing the consistency and updating links.

[docs] Rewording CDC documentation

---

docs/content/preview/troubleshoot/cluster/failed_tablets.md

Fixes https://github.com/yugabyte/yugabyte-db/issues/4662

[docs] Add failed tserver because of failed tablets

---

docs/content/preview/admin/yb-admin.md

Clarify source and target for replication commands; source and target being what is used elsewhere in docs (eg https://docs.yugabyte.com/preview/deploy/multi-dc/async-replication)
#10115
@netlify /preview/admin/yb-admin/#master-follower-deployment-commands

[docs] PR for Universe Replication commands are not clear in yb-admin

---

docs/content/preview/explore/change-data-capture/_index.md

Formatting
@netlify /preview/explore/change-data-capture

[docs][CDC] Minor tidyups

---

docs/content/preview/explore/query-1-performance/pg-hint-plan.md

Address some issues with the page
@netlify /preview/explore/query-1-performance/pg-hint-plan/

[docs] pg_hint_plan format and light edit

---

docs/content/preview/manage/backup-restore/export-import-data-ycql.md
docs/content/preview/manage/backup-restore/export-import-data.md
docs/content/preview/manage/backup-restore/point-in-time-recovery.md
docs/content/preview/manage/backup-restore/snapshot-ysql.md
docs/content/preview/manage/backup-restore/snapshots-ycql.md

@netlify /preview/manage/backup-restore/

[Docs] Backup and restore documentation cleanup

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/aws.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-2655
Preview: https://deploy-preview-12761--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/aws/#yugabytedb-anywhere-managed-configuration

[Doc] PR for Document Platform support for deploying YugabyteDB on ARM

---

docs/content/preview/yugabyte-cloud/cloud-overview.md

Minor edit cloud landing page
@netlify /preview/yugabyte-cloud/cloud-overview/

[docs][cloud] Minor edit cloud landing page

---

docs/content/preview/troubleshoot/nodes/check-logs.md

Adapted from https://github.com/google/glog/blob/d8cb47f77d1c31779f3ff890e1a5748483778d6a/src/glog/logging.h.in#L265-L292 which is the glog version (0.3.4) we use for logging in master & tserver.

[Docs] Add log format section

---

docs/content/preview/manage/backup-restore/export-import-data-ycql.md
docs/content/preview/manage/backup-restore/export-import-data.md
docs/content/preview/manage/backup-restore/point-in-time-recovery.md
docs/content/preview/manage/backup-restore/snapshot-ysql.md

Note to reviewers: please check commands in the following files:
1. [/manage/backup-restore/snapshot-ysql/](https://deploy-preview-12864--infallible-bardeen-164bc9.netlify.app/preview/manage/backup-restore/snapshot-ysql/)
2. [/manage/backup-restore/snapshot-ycql/](https://deploy-preview-12864--infallible-bardeen-164bc9.netlify.app/preview/manage/backup-restore/snapshots-ycql/)

[doc] PR for Review and Fix Errors introduced by PR #12756 "Backup and restore documentation cleanup"

---

docs/content/preview/releases/release-notes/v2.12.md

@netlify /preview/releases/release-notes/v2.12/#v2.12.4.2

[docs] release 2.12.4.2

---

docs/content/preview/manage/backup-restore/snapshot-ysql.md

@netlify /preview/manage/backup-restore/snapshot-ysql/

[Docs] Added note for DDL support in snapshots

---

docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-topology.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-multisync.md
docs/content/preview/yugabyte-cloud/cloud-faq.md
docs/content/preview/yugabyte-cloud/release-notes.md

Release notes, shortcode and other fixes, maximum connections

[docs][cloud] Whats New Jun 22

---

docs/content/preview/explore/ysql-language-features/pg-extensions.md
docs/content/preview/yugabyte-cloud/cloud-admin/cloud-billing-profile.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-vpc-intro.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-topology.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-free.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-multisync.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-single-region.md
docs/content/preview/yugabyte-cloud/cloud-clusters/configure-clusters.md
docs/content/preview/yugabyte-cloud/cloud-faq.md
docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-alerts.md
docs/content/preview/yugabyte-cloud/cloud-overview.md
docs/content/preview/yugabyte-cloud/cloud-troubleshoot.md
docs/content/preview/yugabyte-cloud/release-notes.md

Fix shortcodes for Yugabyte Support to render correctly
@netlify /preview/yugabyte-cloud/cloud-admin/cloud-billing-profile/#profile-and-payment-methods

[docs][cloud] fix shortcodes

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-alerts-health-check.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-3572

[docs] PR for Document description and prometheus expression used for available predefined templates

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/openshift.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-3323

[doc] PR for Update Openshift doc with RBAC

---

docs/content/preview/yugabyte-cloud/cloud-admin/_index.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-multisync.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-single-region.md
docs/content/preview/yugabyte-cloud/cloud-faq.md
docs/content/preview/yugabyte-cloud/cloud-monitor/_index.md
docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-queries-slow.md

Minor edits to update providers, other minor changes
@netlify /preview/yugabyte-cloud/cloud-faq/

[docs][cloud] update cloud provider info

---

docs/content/preview/integrations/prisma.md
docs/content/preview/releases/release-notes/v2.12.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.12/#v2.12.7.0

[docs] release 2.12.7.0

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/aws.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-4470

[doc] PR for Change Oracle 8 to Oracle Linux 8 in all platform docs

---

docs/content/preview/manage/backup-restore/snapshot-ysql.md
docs/content/preview/manage/backup-restore/snapshots-ycql.md

In addition to the linked ticket, this PR will also close [PLAT-3871](https://yugabyte.atlassian.net/browse/PLAT-3871)

[Docs] PR for Backup and restore commands need another cleanup

---

docs/content/preview/releases/release-notes/v2.8.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.8/#v2.8.7.0

[docs] release 2.8.7.0

---

docs/content/preview/quick-start/build-apps/go/ysql-yb-pgx.md

Resolves #12149 
@netlify /preview/quick-start/build-apps/go/ysql-yb-pgx/

[docs ]updated with an appropriate go link

---

docs/content/preview/yugabyte-cloud/release-notes.md

[docs][cloud] Latest features Jun 27

---

docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
docs/content/preview/yugabyte-cloud/cloud-secure-clusters/add-users.md

Performance Advisor limitations
@netlify /preview/yugabyte-cloud/cloud-monitor/cloud-advisor/

[docs][cloud] Performance Advisor limitations

---

docs/content/preview/secure/enable-authentication/ycql.md

Fix YSQL -> YCQL typo in enable authentication YCQL docs.

---

docs/content/preview/faq/yugabyte-managed-faq.md
docs/content/preview/faq/yugabytedb-managed-faq.md
docs/content/preview/quick-start-yugabytedb-managed/_index.md
docs/content/preview/quick-start/explore/ysql.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-free.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-multisync.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-single-region.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-client-shell.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect/ycql.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect/ysql.md
docs/content/preview/yugabyte-cloud/cloud-overview.md
docs/content/preview/yugabyte-cloud/cloud-quickstart/qs-explore.md
docs/content/preview/yugabyte-cloud/release-notes.md

Move YB Managed FAQ to FAQ section, links
@netlify /preview/faq/yugabyte-managed-faq/

[docs][cloud] Move YB Managed FAQ to FAQ section

---

docs/assets/scss/_admonition.scss
docs/assets/scss/_code_block.scss
docs/assets/scss/_right_nav.scss
docs/assets/scss/_styles_project.scss
docs/layouts/_default/_markup/render-image.html
docs/layouts/_default/baseof.html
docs/layouts/_default/single.html
docs/src/index.js

[Docs] Post deploy fixes

---

docs/content/preview/releases/release-notes/v2.12.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.12/#v2.12.8.0

[docs] release 2.12.8.0

---

docs/content/preview/yugabyte-platform/security/enable-encryption-in-transit.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-4480

[Docs] PR for Add a note to make a bundle when there is an intermidiate cert for CA-signed certs

---

docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-region.md

Explain more flags when creating multi region universe.

---

docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-region.md

[Docs] PR for Fix formatting in create-universe-multi-region.md

---

docs/content/preview/yugabyte-cloud/cloud-troubleshoot.md

Add note on Remaining connections slots are reserved error
@netlify /preview/yugabyte-cloud/cloud-troubleshoot/#remaining-connections-slots-are-reserved

[docs][cloud] Troubleshooting connections

---

docs/content/preview/explore/indexes-constraints/_index.md
docs/content/preview/explore/indexes-constraints/covering-index-ysql.md
docs/content/preview/explore/indexes-constraints/expression-index-ysql.md
docs/content/preview/explore/indexes-constraints/foreign-key-ysql.md
docs/content/preview/explore/indexes-constraints/other-constraints.md
docs/content/preview/explore/indexes-constraints/partial-index-ycql.md
docs/content/preview/explore/indexes-constraints/partial-index-ysql.md
docs/content/preview/explore/indexes-constraints/primary-key-ycql.md
docs/content/preview/explore/indexes-constraints/primary-key-ysql.md
docs/content/preview/explore/indexes-constraints/secondary-indexes.md
docs/content/preview/explore/indexes-constraints/unique-index-ycql.md
docs/content/preview/explore/indexes-constraints/unique-index-ysql.md

Fixing formatting in Indexes section
@netlify /preview/explore/indexes-constraints/

[docs][explore] Formatting fixes

---

docs/content/preview/api/ysql/exprs/aggregate_functions/invocation-syntax-semantics.md
docs/content/preview/api/ysql/exprs/window_functions/invocation-syntax-semantics.md
docs/content/preview/api/ysql/user-defined-subprograms-and-anon-blocks/subprogram-attributes/_index.md
docs/content/preview/api/ysql/user-defined-subprograms-and-anon-blocks/subprogram-overloading.md

@netlify /preview/api/ysql/exprs/window_functions/invocation-syntax-semantics/

[docs] fix misbehaving syntax tabs

---

docs/content/preview/contribute/docs/docs-build.md
docs/content/preview/contribute/docs/docs-checklist.md
docs/content/preview/contribute/docs/docs-edit.md
docs/content/preview/contribute/docs/docs-page-structure.md
docs/content/preview/contribute/docs/docs-style.md

@netlify /preview/contribute/docs/

[docs] minor cleanup in the contributor's guide

---

docs/content/preview/releases/release-notes/v2.12.md

@netlify /preview/releases/release-notes/v2.12/#v2.12.6.1

[docs] release 2.12.6.1

---

docs/content/preview/releases/release-notes/v2.15.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.15/

[docs] release 2.15.0.1

---

architecture/design/docdb-encryption-at-rest.md

[DOCS] Minor grammatical fixes

---

docs/content/preview/migrate/yb-voyager/migrate-steps.md

resolves #13154
@netlify /preview/migrate/yb-voyager/migrate-steps/#create-a-user

[docs] [migrate] added local cluster step for creating a target user.

---

docs/content/preview/releases/release-notes/v2.8.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.8/#v2.8.8.0

[docs] release 2.8.8.0

---

docs/content/preview/releases/release-notes/v2.12.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.12/

[docs] release 2.12.9.0

---

docs/content/preview/drivers-orms/_index.md
docs/content/preview/yugabyte-cloud/cloud-quickstart/cloud-build-apps/_index.md

Note on smart drivers when used with YugabyteDB Managed
@netlify /preview/drivers-orms/

[docs][cloud] Note on smart drivers and YBM

---

docs/content/preview/explore/cluster-management/_index.md
docs/content/preview/explore/cluster-management/point-in-time-recovery-ysql.md
docs/content/stable/explore/cluster-management/_index.md
docs/content/stable/explore/cluster-management/point-in-time-recovery-ysql.md

@netlify /preview/explore/cluster-management/

[Docs] Removed beta tag from the PITR doc page

---

docs/content/preview/contribute/docs/docs-build.md
docs/netlify.toml

[docs] update build page in contrib guide

---

docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-vpc-aws.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-vpc-gcp.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-vpc-intro.md

Add some details on private IPs
@netlify /preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-vpc-intro/#set-the-cidr-and-size-your-vpc

[docs][cloud] Details on private IP addresses

---

docs/content/preview/contribute/docs/docs-edit.md
docs/content/preview/releases/release-notes/v2.15.md
docs/data/currentVersions.json
docs/package.json

@netlify /preview/releases/release-notes/v2.15/

[docs] release 2.15.1.0

---

docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md
docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-replicated.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-4826
@netlify /preview/yugabyte-platform/upgrade/upgrade-yp-replicated/

[docs] PR for Sync xcluster config

---

docs/content/preview/releases/release-notes/v2.14.md

[docs] quick fixes to 2.14 release notes

---

docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md
docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-replicated.md
docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-xcluster-ybadmin.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-4826

[docs] Run Sync xcluster config API after Platform upgrade

---

docs/content/preview/migrate/yb-voyager/_index.md

@netlify  /preview/migrate/yb-voyager/

[docs] [migrate] updated oracle version support for YugabyteDB Voyager

---

docs/content/preview/explore/ysql-language-features/data-manipulation.md
docs/content/preview/explore/ysql-language-features/data-types.md
docs/content/preview/explore/ysql-language-features/databases-schemas-tables.md
docs/content/preview/explore/ysql-language-features/expressions-operators.md
docs/content/preview/explore/ysql-language-features/foreign-data-wrappers.md
docs/content/preview/explore/ysql-language-features/pg-extensions.md
docs/content/preview/explore/ysql-language-features/postgresql-compatibility.md
docs/content/preview/explore/ysql-language-features/queries.md
docs/content/preview/explore/ysql-language-features/sql-feature-support.md
docs/content/preview/explore/ysql-language-features/stored-procedures.md
docs/content/preview/explore/ysql-language-features/triggers.md
docs/content/stable/explore/ysql-language-features/pg-extensions.md
docs/content/stable/explore/ysql-language-features/sql-feature-support.md
docs/content/v2.12/api/ysql/extensions.md
docs/content/v2.12/explore/ysql-language-features/advanced-features/extensions.md

Update uuid-ossp extension info; various formatting and links in Explore/SQL features sections.
Backport to
v2.12/api/ysql/extensions/#uuid-ossp
stable/explore/ysql-language-features/pg-extensions/
@netlify /preview/explore/ysql-language-features/pg-extensions

[docs] Update uuid-ossp extension

---

docs/content/preview/yugabyte-cloud/cloud-admin/_index.md
docs/content/preview/yugabyte-cloud/cloud-admin/cloud-admin-apikeys.md
docs/content/preview/yugabyte-cloud/cloud-admin/cloud-billing-costs.md
docs/content/preview/yugabyte-cloud/cloud-admin/cloud-billing-profile.md
docs/content/preview/yugabyte-cloud/cloud-admin/manage-access.md
docs/content/preview/yugabyte-cloud/cloud-basics/_index.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/_index.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-peering.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-vpc-aws.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-vpc-gcp.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-vpc.md
docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-vpc-intro.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/_index.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-applications.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-client-shell.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-cloud-shell.md
docs/content/preview/yugabyte-cloud/cloud-overview.md
docs/content/preview/yugabyte-cloud/cloud-secure-clusters/_index.md

Mockup YB managed landing page
@netlify /preview/yugabyte-cloud/cloud-overview/

[docs][cloud] YB Managed landing page

---

docs/content/preview/admin/_index.md
docs/content/preview/deploy/_index.md
docs/content/preview/develop/_index.md
docs/content/preview/develop/learn/acid-transactions-ycql.md
docs/content/preview/develop/learn/batch-operations-ycql.md
docs/content/preview/develop/quality-of-service/_index.md
docs/content/preview/develop/realworld-apps/_index.md
docs/content/preview/develop/realworld-apps/ecommerce-app.md
docs/content/preview/develop/realworld-apps/explore-sample-apps.md
docs/content/preview/develop/realworld-apps/iot-spark-kafka-ksql.md
docs/content/preview/manage/_index.md
docs/content/stable/manage/_index.md

Reorganization of real world sample apps topics and menu fixes
@netlify /preview/develop/realworld-apps/

[docs] Minor reorg of sample apps

---

docs/content/preview/releases/release-notes/v1.2.md
docs/content/preview/releases/release-notes/v1.3.md
docs/content/preview/releases/release-notes/v2.0.md
docs/content/preview/releases/release-notes/v2.1.md
docs/content/preview/releases/release-notes/v2.11.md
docs/content/preview/releases/release-notes/v2.12.md
docs/content/preview/releases/release-notes/v2.13.md
docs/content/preview/releases/release-notes/v2.14.md
docs/content/preview/releases/release-notes/v2.15.md
docs/content/preview/releases/release-notes/v2.2.md
docs/content/preview/releases/release-notes/v2.3.md
docs/content/preview/releases/release-notes/v2.4.md
docs/content/preview/releases/release-notes/v2.5.md
docs/content/preview/releases/release-notes/v2.6.md
docs/content/preview/releases/release-notes/v2.7.md
docs/content/preview/releases/release-notes/v2.8.md
docs/content/preview/releases/release-notes/v2.9.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.14/#v2.14.1.0

[docs] release 2.14.1.0

---

docs/content/preview/manage/upgrade-deployment.md

Fix indentation
@netlify /preview/manage/upgrade-deployment/

[docs] Upgrade deployment minor formatting fixes

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-4626

[docs] PR for Document recommended storage class for k8s

---

docs/content/preview/quick-start/linux.md
docs/content/preview/releases/release-notes/v2.14.md
docs/content/preview/releases/release-notes/v2.15.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/_index.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/aws.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/supported-os-and-arch.md
docs/content/stable/quick-start/linux.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/_index.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/aws.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/supported-os-and-arch.md

Fixes for PLAT-5017
@netlify /preview/yugabyte-platform/configure-yugabyte-platform/

[docs] updates for YBA arm/graviton support

---

docs/content/preview/integrations/ysql-loader.md
docs/content/v2.6/integrations/ysql-loader.md

Use consistent v1.1 pgloader container version

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-4868

[doc] PR for Update documentation to specify `xxhash` as a dependency for manually provisioned node

---

docs/assets/scss/_right_nav.scss

Preview Link: https://deploy-preview-13643--infallible-bardeen-164bc9.netlify.app/preview/contribute/docs/syntax-diagrams/

[Docs] Fix right nav scrolling

---

docs/content/preview/manage/upgrade-deployment.md

[docs] Explain downgrades aren't supported.

---

docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yb-tserver.md

Use PostgreSQL parameter `log_connections=on` when showing example of `ysql_pg_conf_csv`

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-3618

[doc] PR for Add S3 IAM permissions in platform docs

---

docs/content/preview/yugabyte-platform/manage-deployments/high-availability.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-5079
Preview: https://deploy-preview-13697--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/manage-deployments/high-availability/#limitations

[Doc] PR for Add doc for limitation of using same custom Prometheus port under Platform HA

---

docs/content/preview/releases/release-notes/v2.6.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.6/#v2.6.19.0

[docs] release 2.6.19.0

---

docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yb-tserver.md

[docs] Add `temp_file_limit` to yb-tserver.md config

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
docs/content/v2.12/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
docs/content/v2.8/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

Addresses https://github.com/yugabyte/yugabyte-db/issues/13727

[Docs] PR for Prometheus node_exporter instructions for the on-prem provider include version-specific steps 

---

docs/content/preview/deploy/checklist.md

Also edited the doc for clarity

[docs] PR for Update hardware requirement with SSE 4.2

---

docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-replicated.md

Addesses https://yugabyte.atlassian.net/browse/PLAT-5203

[docs] PR for Update Upgrade Time Information for replicated instance in the documentation

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/aws.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-4901

[Docs] PR for Issues with AWS IAM setup instructions

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-5064

[doc] PR for Documentation Update for Tectia/SSH2 keys support in the platform

---

docs/content/preview/yugabyte-platform/manage-deployments/high-availability.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-5166

[Doc] PR for Document upgrade order of HA primary and standby nodes

---

docs/content/preview/quick-start-yugabytedb-managed/_index.md
docs/content/preview/releases/release-notes/v2.12.md
docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/aws.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.12/#v2.12.9.2

[docs] release 2.12.9.2

---

docs/content/preview/contribute/docs/docs-build.md

[Docs] Fix export shell syntax

---

docs/content/preview/reference/connectors/kafka-connect-yugabytedb.md
docs/content/stable/reference/connectors/kafka-connect-yugabytedb.md
docs/content/v2.12/reference/connectors/kafka-connect-yugabytedb.md
docs/content/v2.6/reference/connectors/kafka-connect-yugabytedb.md
docs/content/v2.8/reference/connectors/kafka-connect-yugabytedb.md

Docs: Fix link to download kafka 2.5.0

---

docs/content/preview/admin/yb-admin.md
docs/content/stable/admin/yb-admin.md
docs/content/v2.12/admin/yb-admin.md
docs/content/v2.6/admin/yb-admin.md
docs/content/v2.8/admin/yb-admin.md

Improvements in change_leader_blacklist command description

Fixed change_leader_blacklist documentation

---

docs/netlify.toml

Made the same change as its in this PR : https://github.com/yugabyte/yugabyte-db/pull/13917

[docs] changes to the Voyager redirect

---

docs/config/_default/menus.toml

Deploy preview: https://deploy-preview-13914--infallible-bardeen-164bc9.netlify.app/preview/

[docs] Added integrations in the header

---

docs/content/preview/faq/yugabytedb-managed-faq.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-multisync.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-applications.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-client-shell.md

Document the requirement of peering for connecting applications to multi region clusters
@netlify /preview/yugabyte-cloud/cloud-connect/connect-client-shell/

[docs][cloud] Clarify connection requirements for multi-region

---

docs/content/preview/yugabyte-cloud/cloud-secure-clusters/add-connections.md

Allow lists and clusters can't have more thatn 100 rules
@netlify /preview/yugabyte-cloud/cloud-secure-clusters/add-connections/

[docs][cloud] Allow list limits

---

docs/content/preview/admin/ycqlsh.md
docs/content/preview/admin/ysqlsh.md
docs/content/stable/admin/ycqlsh.md
docs/content/stable/admin/ysqlsh.md
docs/content/v2.12/admin/ycqlsh.md
docs/content/v2.12/admin/ysqlsh.md
docs/content/v2.8/admin/ycqlsh.md

Add curl to instructions for using get_clients.sh script
#10472
@netlify /preview/admin/ysqlsh/

[docs] Add curl to instructions

---

.github/vale-styles/Yugabyte/spelling-exceptions.txt
docs/content/preview/releases/release-notes/v2.15.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.15/

[docs] release 2.15.2.0

---

docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-5478

[Doc] PR for Add documentation for downgrades

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/aws.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-5487

[doc] PR for Update AWS permissions needed

---

docs/content/preview/migrate/_index.md
docs/content/stable/migrate/_index.md

Includes changes to title and description.

[docs] [migrate] frontmatter changes for YugabyteDB Voyager 

---

docs/config/_default/menus.toml
docs/content/preview/faq/yugabytedb-managed-faq.md
docs/content/preview/yugabyte-cloud/release-notes.md

[docs][cloud] Update Whats New

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-5556

[docs] PR for Remove AlmaLinux 8 from list of supported YBA install prereqs

---

docs/content/preview/faq/yugabytedb-managed-faq.md
docs/content/preview/yugabyte-cloud/_index.md

Add quick links to YB Managed landing page
@netlify /preview/yugabyte-cloud/

[docs][cloud] Add quick links

---

docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md

Add note on using staging clusters on Planning page
@netlify /preview/yugabyte-cloud/cloud-basics/create-clusters-overview/#yugabytedb-version

[docs][cloud] Add note on staging clusters

---

docs/content/preview/explore/json-support/jsonb-ysql.md
docs/content/stable/explore/json-support/jsonb-ysql.md
docs/content/v2.12/explore/json-support/jsonb-ysql.md
docs/content/v2.6/explore/json-support/jsonb-ysql.md
docs/content/v2.8/explore/json-support/jsonb-ysql.md

replace typo "jbonb" to "jsonb"

Document type fix with "JSON Support"

---

docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-kubernetes.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-5586

[doc] PR for Changes required to Upgrade YBA installation on Kubernetes

---

docs/content/preview/faq/yugabytedb-managed-faq.md
docs/content/preview/quick-start-yugabytedb-managed/_index.md
docs/content/preview/quick-start/_index.md

Draft of possible links back to YBM docs from Quick Start
@netlify /preview/quick-start-yugabytedb-managed/

[docs][cloud] Add links back to YBM Docs page

---

docs/content/preview/explore/ysql-language-features/going-beyond-sql/tablespaces.md
docs/content/stable/explore/ysql-language-features/going-beyond-sql/tablespaces.md

[docs] typo fix for tablespaces

---

docs/content/preview/drivers-orms/smart-drivers-faq.md
docs/content/preview/drivers-orms/smart-drivers.md
docs/content/preview/faq/compatibility.md
docs/content/preview/faq/operations-faq.md

Pull the FAQ onto a separate page
@netlify /preview/drivers-orms/smart-drivers/

[docs] Minor changes to Smart driver page

---

docs/content/preview/drivers-orms/_index.md
docs/content/preview/explore/change-data-capture/cdc-java-console-client.md
docs/content/preview/yugabyte-cloud/release-notes.md

[docs][cloud] Preview db version update

---

docs/content/preview/quick-start/docker.md
docs/content/stable/quick-start/docker.md
docs/content/v2.12/quick-start/docker.md
docs/content/v2.6/quick-start/docker.md
docs/content/v2.8/quick-start/docker.md

resolves #14051 
Used the releases pages to fetch the right versions : https://docs.yugabyte.com/preview/releases/release-notes/v2.15/

[docs] [Quick start] mention versions in docker run command

---

docs/content/preview/drivers-orms/_index.md
docs/content/preview/drivers-orms/go/yb-pgx.md
docs/content/preview/drivers-orms/java/yugabyte-jdbc.md
docs/content/preview/drivers-orms/nodejs/yugabyte-node-driver.md
docs/content/preview/drivers-orms/python/yugabyte-psycopg2.md
docs/content/preview/drivers-orms/smart-drivers.md
docs/content/preview/faq/yugabytedb-managed-faq.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md

Enhancements to smart driver pages
@netlify /preview/drivers-orms/smart-drivers/

[docs] Smart driver clarification

---

docs/content/preview/yugabyte-platform/manage-deployments/high-availability.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-5610

[doc] PR for Add more info on high availability

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-5699

[doc] PR for Revert changes made for PLAT-4868 (per dev request)

---

docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md

Add instance types and fallback
@netlify /preview/yugabyte-cloud/cloud-basics/create-clusters-overview/#provider-and-region

[docs][cloud] Instance types and fall back

---

docs/content/preview/releases/release-notes/v2.15.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.15/#v2.15.2.1

[docs] release 2.15.2.1

---

README.md

[docs] minor update to README.md

---

docs/content/preview/releases/release-notes/v2.14.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.14/#v2.14.3.1

[docs] release 2.14.3.1

---

docs/content/preview/explore/indexes-constraints/secondary-indexes.md
docs/content/preview/yugabyte-cloud/_index.md
docs/content/stable/explore/indexes-constraints/secondary-indexes.md
docs/content/v2.12/explore/indexes-constraints/secondary-indexes.md

@netlify /preview/yugabyte-cloud/

[docs] add missing UTM tags for cloud signup

---

docs/content/preview/api/ysql/_index.md
docs/content/preview/yugabyte-cloud/cloud-clusters/_index.md
docs/content/preview/yugabyte-cloud/cloud-security/_index.md
docs/content/preview/yugabyte-cloud/cloud-security/cloud-security-features.md
docs/content/preview/yugabyte-cloud/cloud-security/shared-responsibility.md

Assorted frontmatter/metadata updates for SEO purposes.

[docs] update some frontmatter/metadata

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-5716

[doc] PR for Document need for kube-state-metrics

---

docs/content/preview/releases/release-notes/v2.8.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.8/#v2.8.9.1

[docs] release 2.8.9.1

---

docs/content/preview/releases/release-notes/v2.14.md

@netlify /preview/releases/release-notes/v2.14/#v2.14.2.1

[docs] release 2.14.2.1

---

docs/content/preview/yugabyte-cloud/cloud-admin/cloud-admin-apikeys.md
docs/content/preview/yugabyte-cloud/release-notes.md

Add setting roles for API keys
@netlify /preview/yugabyte-cloud/cloud-admin/cloud-admin-apikeys/

[docs][cloud] API key roles

---

docs/content/preview/yugabyte-cloud/release-notes.md

Add role-base API keys to What's new

[docs][cloud] What's new api key enhancement

---

.github/vale-styles/Yugabyte/spelling-exceptions.txt
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-free.md

Fix 404 from external link
@netlify /latest/yugabyte-cloud/free-tier/

[docs][cloud] fix 404 with alias

---

docs/content/preview/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/preview/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/preview/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/preview/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/preview/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/stable/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/stable/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/stable/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/stable/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/stable/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/v2.12/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/v2.12/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/v2.12/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/v2.12/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/v2.12/deploy/kubernetes/single-zone/oss/helm-chart.md
docs/content/v2.8/deploy/kubernetes/multi-cluster/gke/helm-chart.md
docs/content/v2.8/deploy/kubernetes/multi-zone/eks/helm-chart.md
docs/content/v2.8/deploy/kubernetes/multi-zone/gke/helm-chart.md
docs/content/v2.8/deploy/kubernetes/single-zone/gke/helm-chart.md
docs/content/v2.8/deploy/kubernetes/single-zone/oss/helm-chart.md

Build-preview : https://deploy-preview-14599--infallible-bardeen-164bc9.netlify.app/preview/deploy/kubernetes/single-zone/gke/helm-chart/#connect-using-external-clients

[docs] modified the external clients connectivity section 

---

docs/content/preview/secure/audit-logging/_index.md
docs/content/preview/secure/audit-logging/audit-logging-ycql.md
docs/content/preview/secure/audit-logging/audit-logging-ysql.md
docs/content/preview/secure/audit-logging/object-audit-logging-ysql.md
docs/content/preview/secure/audit-logging/session-audit-logging-ysql.md
docs/content/preview/secure/audit-logging/trace-statements-ysql.md
docs/content/stable/secure/audit-logging/_index.md
docs/content/stable/secure/audit-logging/audit-logging-ycql.md
docs/content/stable/secure/audit-logging/audit-logging-ysql.md
docs/content/stable/secure/audit-logging/object-audit-logging-ysql.md
docs/content/stable/secure/audit-logging/session-audit-logging-ysql.md
docs/content/stable/secure/audit-logging/trace-statements-ysql.md
docs/content/v2.12/secure/audit-logging/_index.md
docs/content/v2.12/secure/audit-logging/audit-logging-ycql.md
docs/content/v2.12/secure/audit-logging/audit-logging-ysql.md
docs/content/v2.12/secure/audit-logging/object-audit-logging-ysql.md
docs/content/v2.12/secure/audit-logging/session-audit-logging-ysql.md
docs/content/v2.12/secure/audit-logging/trace-statements-ysql.md

How to trace YSQL statement execution using session identifiers using logs
@netlify /preview/secure/audit-logging/

[docs] Manually trace statement execution in YSQL

---

docs/content/preview/releases/release-notes/v2.8.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.8/#v2.8.10.0

[docs] release 2.8.10.0

---

docs/content/preview/releases/release-notes/v2.14.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.14/#v2.14.4.0

[docs] release 2.14.4.0

---

docs/content/preview/explore/indexes-constraints/other-constraints.md
docs/content/preview/faq/yugabytedb-managed-faq.md

Edit pause details; format
@netlify /preview/faq/yugabytedb-managed-faq/#how-do-i-connect-to-my-cluster

[docs][cloud] Edit pause details

---

docs/content/preview/releases/release-notes/v2.15.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.15/#v2.15.3.0

[docs] release 2.15.3.0

---

docs/content/preview/reference/configuration/default-ports.md
docs/content/preview/yugabyte-platform/troubleshoot/universe-issues.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-6083

[DOC]PR for Missing information for xcluster ports 

---

docs/content/preview/explore/linear-scalability/sharding-data.md
docs/content/stable/explore/linear-scalability/sharding-data.md
docs/content/v2.12/explore/linear-scalability/sharding-data.md
docs/content/v2.6/explore/linear-scalability/sharding-data.md
docs/content/v2.8/explore/linear-scalability/sharding-data.md

Replace `total number of nodes` with `total number of tablets` typo

---

docs/content/preview/yugabyte-cloud/release-notes.md

Known issue WRT metrics and slow queries not returning result for distant regions

[docs][cloud] Known issue - metrics and slow queries

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites.md

Fixes #14783 
Fixes #14784
Fixes #14776

Docs: specify exact postgresql version on docker pull

---

docs/assets/scss/_tabs.scss

It will fix the issue as shown here:
https://deploy-preview-14810--infallible-bardeen-164bc9.netlify.app/preview/explore/#set-up-your-environment

[Docs] Remove border from the tabpane

---

docs/content/preview/releases/release-notes/v2.15.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.15/#v2.15.3.2

[docs] release 2.15.3.2

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-6267

[doc] PR for Fix formatting error in one of the install YBA files

---

docs/content/preview/explore/indexes-constraints/gin.md

Update setup of GIN example
@netlify /preview/explore/indexes-constraints/gin/

[docs][explore] GIN example setup

---

docs/content/preview/yugabyte-cloud/release-notes.md

Slow query reset known issue - query used for reset not cleared

[docs][cloud] Note on slow query reset

---

docs/content/preview/drivers-orms/_index.md
docs/content/preview/drivers-orms/c/_index.md
docs/content/preview/drivers-orms/cpp/_index.md
docs/content/preview/drivers-orms/csharp/_index.md
docs/content/preview/drivers-orms/go/_index.md
docs/content/preview/drivers-orms/java/_index.md
docs/content/preview/drivers-orms/nodejs/_index.md
docs/content/preview/drivers-orms/php/_index.md
docs/content/preview/drivers-orms/python/_index.md
docs/content/preview/drivers-orms/ruby/_index.md
docs/content/preview/drivers-orms/rust/_index.md
docs/content/preview/drivers-orms/scala/_index.md
docs/content/preview/explore/indexes-constraints/gin.md
docs/content/preview/reference/drivers/_index.md

Update landing page for Drivers and ORMs and Reference
@netlify /preview/drivers-orms/

[docs] Driver ORMs landing page

---

docs/content/preview/api/ycql/_index.md
docs/content/preview/api/ycql/batch.md
docs/content/preview/api/ycql/ddl_alter_keyspace.md
docs/content/preview/api/ycql/ddl_alter_role.md
docs/content/preview/api/ycql/ddl_alter_table.md
docs/content/preview/api/ycql/ddl_create_keyspace.md
docs/content/preview/api/ycql/ddl_create_role.md
docs/content/preview/api/ycql/ddl_create_table.md
docs/content/preview/api/ycql/ddl_create_type.md
docs/content/preview/api/ycql/ddl_drop_index.md
docs/content/preview/api/ycql/ddl_drop_keyspace.md
docs/content/preview/api/ycql/ddl_drop_role.md
docs/content/preview/api/ycql/ddl_drop_table.md
docs/content/preview/api/ycql/ddl_drop_type.md
docs/content/preview/api/ycql/ddl_grant_permission.md
docs/content/preview/api/ycql/ddl_grant_role.md
docs/content/preview/api/ycql/ddl_revoke_permission.md
docs/content/preview/api/ycql/ddl_revoke_role.md
docs/content/preview/api/ycql/ddl_use.md
docs/content/preview/api/ycql/dml_delete.md
docs/content/preview/api/ycql/dml_insert.md
docs/content/preview/api/ycql/dml_select.md
docs/content/preview/api/ycql/dml_transaction.md
docs/content/preview/api/ycql/dml_truncate.md
docs/content/preview/api/ycql/dml_update.md
docs/content/preview/api/ysql/the-sql-language/statements/txn_end.md

Notes on YCQL transaction statement
@netlify /preview/api/ycql/dml_transaction/

[docs][api] Notes on ycql transaction api

---

docs/content/preview/yugabyte-platform/security/create-kms-config/aws-kms.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-6374

[doc] PR for Azure KMS is shown twice in the public docs

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-6410

[doc] PR for Update the docker supported version in the docs 

---

docs/content/preview/drivers-orms/python/postgres-psycopg2.md
docs/content/preview/drivers-orms/python/yugabyte-psycopg2.md
docs/content/preview/reference/drivers/python/postgres-psycopg2-reference.md
docs/content/preview/reference/drivers/python/yugabyte-psycopg2-reference.md

[docs] change version and add limitation

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-6380

[doc]  PR for Add disk space requirements to K8S install section

---

docs/content/preview/develop/learn/data-types-ycql.md

Fix some typos and formatting
@netlify /preview/develop/learn/data-types-ycql/

[docs] JSONB fixes

---

docs/content/preview/quick-start/_index.md

Add 2 aliases to quick start
@netlify /latest/quick-start/create-local-cluster/

[docs] Add aliases for old pages

---

docs/content/preview/yugabyte-cloud/release-notes.md

Releases - Partition by region and Read replicas

[docs][cloud] New features

---

docs/content/preview/yugabyte-platform/administer-yugabyte-platform/ldap-authentication.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-6485

[doc] PR for Minor edit of change to LDAP authentication

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-6350

[docs] PR for Airgap platform install should link to the replicated docs for getting docker images

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites-include.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites.md
docs/content/preview/yugabyte-platform/troubleshoot/universe-issues.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-6041

[doc] PR for Document prerequisites for k8s YBA to understand where core dumps go to

---

docs/assets/scss/_code_block.scss

1. **Live:** https://docs.yugabyte.com/preview/reference/configuration/yugabyted/#flags
2. **Preview:** https://deploy-preview-15200--infallible-bardeen-164bc9.netlify.app/preview/reference/configuration/yugabyted/#flags

[Docs] Fix code elements within a dd

---

docs/content/preview/explore/query-1-performance/_index.md
docs/content/preview/explore/query-1-performance/pg-stat-activity.md
docs/content/preview/explore/query-1-performance/yb-pg-stat-get-queries.md
docs/content/stable/explore/query-1-performance/_index.md
docs/content/stable/explore/query-1-performance/yb-pg-stat-get-queries.md

Add yb_pg_stat_get_queries function topic
@netlify /preview/explore/query-1-performance/yb-pg-stat-get-queries/

[docs] PR for Create documentation for yb_pg_stat_get_queries

---

docs/src/index.js

Need a fix for pills - for example on this page https://docs.yugabyte.com/preview/develop/build-apps/java/ysql-spring-data/
click any other pill and the leftnav is no longer selected; but if you look at Go say, the tabs work correctly

[Docs] Select left nav for pills

---

docs/content/preview/reference/configuration/yb-tserver.md
docs/content/stable/reference/configuration/yb-tserver.md

Add YB-Tserver flag xcluster_svc_queue_size
@netlify /preview/reference/configuration/yb-tserver/#xcluster-flags

[docs] xcluster_svc_queue_size flag

---

docs/content/preview/explore/transactions/_index.md
docs/content/preview/explore/transactions/distributed-transactions-ycql.md
docs/content/preview/explore/transactions/distributed-transactions-ysql.md
docs/content/preview/explore/transactions/explicit-locking.md
docs/content/preview/explore/transactions/isolation-levels.md

Remove some custom formatting from table. Minor edits.
@netlify /preview/explore/transactions/distributed-transactions-ysql/

[docs] Remove formatting from table

---

docs/content/preview/architecture/docdb-sharding/colocated-tables.md

Edit for clarity of tradeoffs of using colocated tables
@netlify /preview/architecture/docdb-sharding/colocated-tables

[docs] Clarify benefits of colocated tables

---

docs/content/preview/drivers-orms/smart-drivers.md
docs/content/preview/faq/operations-faq.md
docs/content/preview/faq/smart-drivers-faq.md

Move Smart driver FAQ to FAQ section
@netlify /preview/faq/smart-drivers-faq/

[docs] Move Smart driver FAQ to FAQ section

---

docs/content/preview/develop/build-apps/cloud-add-ip.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-applications.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect-client-shell.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect/ycql.md
docs/content/preview/yugabyte-cloud/cloud-connect/connect/ysql.md

Add details on connecting applications where the cluster is deployed in a VPC
@netlify /preview/develop/build-apps/cloud-add-ip/

[docs][cloud] Public access and connecting apps

---

docs/content/preview/explore/ysql-language-features/going-beyond-sql/tablespaces-platform.md
docs/content/preview/explore/ysql-language-features/going-beyond-sql/tablespaces-yugabyted.md
docs/content/preview/explore/ysql-language-features/going-beyond-sql/tablespaces.md

Define tablespaces in intro; minor format and fix tabs
@netlify /preview/explore/ysql-language-features/going-beyond-sql/tablespaces/

[docs][explore] Tablespaces intro

---

docs/content/preview/releases/release-notes/v2.16.md

(and a bit of general cleanup)
@netlify /preview/releases/release-notes/v2.16/

[docs] add missed issue to 2.16.0.0 release notes

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md

- Documented the following helm option in the document
- affinity
- podAnnotations
- tolerations
- podLabels

[docs][plat-6512] Document helm options for yugabyte helm chart in provider config section for overrides

---

docs/content/preview/reference/configuration/default-ports.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/aws.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/azure.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/on-premises.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md
docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software.md
docs/content/stable/reference/configuration/default-ports.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-environment/aws.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-environment/azure.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-environment/on-premises.md
docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md
docs/content/stable/yugabyte-platform/manage-deployments/upgrade-software.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-6740
Note to reviewers: I didn't mention the specific releases in the doc changes because only the affected doc versions were modified and will be published.

[doc] PR for Mention port 18018 requirement for 2.16 and so on in YB docs

---

docs/content/preview/reference/drivers/ysql-client-drivers.md
docs/content/stable/reference/drivers/ysql-client-drivers.md
docs/content/v2.14/reference/drivers/ysql-client-drivers.md

Build preview : https://deploy-preview-15369--infallible-bardeen-164bc9.netlify.app/preview/reference/drivers/ysql-client-drivers/

[docs] fix links and minor changes for YSQL client drivers reference page.

---

docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-vpc-intro.md
docs/content/preview/yugabyte-cloud/release-notes.md

Update sizing recommendations for AWS clusters and their VPCs
@netlify /preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-vpc-intro/#set-the-cidr-and-size-your-vpc

[docs][cloud] VPC sizing recommendations

---

docs/content/preview/deploy/multi-dc/async-replication.md
docs/content/preview/integrations/hasura/hasura-1.md
docs/content/preview/troubleshoot/nodes/check-stats.md
src/yb/consensus/CMakeLists.txt
src/yb/consensus/log-dump.cc
src/yb/docdb/kv_debug.cc
src/yb/docdb/kv_debug.h

Fix a typo, lint
@netlify /preview/deploy/multi-dc/async-replication/

[docs] xCluster typo and format

---

docs/content/preview/admin/yb-ctl.md

Add note about loopback addresses for multi-node clusters on MacOS and Linux for yb-ctl tool
@netlify /preview/admin/yb-ctl/#create-a-local-cluster

[docs] Add loopback note for yb-ctl

---

docs/content/preview/integrations/spring-framework/sdyb.md

Add note on Spring Boot compatibility
@netlify /preview/integrations/spring-framework/sdyb/

Note on Spring Boot version

---

docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
docs/content/preview/yugabyte-cloud/release-notes.md

[docs][cloud] What's new december

---

docs/content/preview/integrations/wso2.md
docs/content/preview/tools/pgadmin.md
docs/content/preview/tools/sql-workbench.md
docs/content/stable/tools/pgadmin.md
docs/content/stable/tools/sql-workbench.md
docs/content/v2.12/reference/drivers/ysql-client-drivers.md
docs/content/v2.12/tools/pgadmin.md
docs/content/v2.12/tools/sql-workbench.md
docs/content/v2.14/tools/pgadmin.md
docs/content/v2.14/tools/sql-workbench.md
docs/content/v2.6/integrations/wso2.md
docs/content/v2.6/reference/drivers/ysql-client-drivers.md
docs/content/v2.6/tools/pgadmin.md
docs/content/v2.6/tools/sql-workbench.md
docs/content/v2.8/reference/drivers/ysql-client-drivers.md
docs/content/v2.8/tools/pgadmin.md
docs/content/v2.8/tools/sql-workbench.md

Fix links to the PG driver.
@netlify /preview/tools/pgadmin/

[docs] Fix PG driver links

---

docs/content/preview/architecture/docdb-sharding/tablet-splitting.md
docs/content/stable/architecture/docdb-sharding/tablet-splitting.md
docs/content/v2.14/architecture/docdb-sharding/tablet-splitting.md

[docs] Fix incorrect yb-ctl command on tablet-splitting.md

---

docs/content/preview/manage/backup-restore/point-in-time-recovery.md
docs/content/stable/manage/backup-restore/point-in-time-recovery.md
docs/content/v2.12/manage/backup-restore/point-in-time-recovery.md
docs/content/v2.14/manage/backup-restore/point-in-time-recovery.md
docs/content/v2.6/manage/backup-restore/point-in-time-recovery.md
docs/content/v2.8/manage/backup-restore/point-in-time-recovery.md

[docs] Include `-master_addresses` flag on yb-admin commands in PITR docs

---

docs/content/preview/sample-data/retail-analytics.md
docs/content/stable/sample-data/retail-analytics.md
docs/content/v2.12/quick-start/explore/ysql.md
docs/content/v2.14/sample-data/retail-analytics.md
docs/content/v2.6/quick-start/explore/ysql.md
docs/content/v2.8/quick-start/explore/ysql.md

[docs] Fix test to list all columns in the following query on retail-analytics sample

---

docs/content/preview/admin/yb-ctl.md

fixes #15501 
cc @ayushsengupta1991

[docs] Add ifconfig for nodes 4 & 5 on yb-ctl.md to account for new nodes that will be added

---

docs/content/preview/explore/_index.md
docs/content/preview/explore/multi-region-deployments/synchronous-replication-ycql.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-topology.md

Clarify Resilience of Replicate across regions topology
@netlify /preview/yugabyte-cloud/cloud-basics/create-clusters-topology/#replicate-across-regions

[docs][cloud] Clarify Resilience of Replicate across regions topology

---

docs/content/preview/yugabyte-platform/security/enable-encryption-at-rest.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-6889

[doc] PR Mention Azure KMS in Encryption at rest page

---

docs/content/preview/releases/release-notes/v2.14.md
docs/content/preview/releases/release-notes/v2.17.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.14/#v2.14.6.0

[docs] release 2.14.6.0

---

docs/content/preview/releases/release-notes/v2.12.md
docs/data/currentVersions.json

@netlify /preview/releases/release-notes/v2.12/#v2.12.11.0

[docs] release 2.12.11.0

---

docs/content/preview/migrate/yb-voyager-cli.md

[DOCS] fixes #15607

---

docs/content/preview/develop/build-apps/python/cloud-ysql-python.md

Build preview: https://deploy-preview-15617--infallible-bardeen-164bc9.netlify.app/preview/develop/build-apps/python/cloud-ysql-python/

[docs][develop] added deleted python page

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/azure.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-5861
Based on the comments in the Jira ticket, only the wording around the disk size needed to be changed.

[doc] PR for Add resource group role necessary for Azure provider

---

docs/content/preview/drivers-orms/orms/rust/ysql-diesel.md
docs/content/preview/explore/change-data-capture/debezium-connector-yugabytedb.md
docs/content/preview/faq/comparisons/_index.md
docs/content/preview/faq/compatibility.md
docs/content/preview/faq/general.md
docs/content/preview/faq/operations-faq.md
docs/content/preview/faq/smart-drivers-faq.md
docs/content/preview/faq/yugabyte-platform.md
docs/content/preview/faq/yugabytedb-managed-faq.md

Adjust contents format of FAQ pages to reduce Rightnav multiline clutter; fix links
@netlify /preview/faq/general/

[docs] Format FAQs

---

docs/content/preview/explore/ysql-language-features/advanced-features/views.md
docs/content/stable/explore/ysql-language-features/advanced-features/views.md
docs/content/v2.12/explore/ysql-language-features/advanced-features/views.md
docs/content/v2.14/explore/ysql-language-features/advanced-features/views.md

fix output after refresh materialized view

[docs] fix output after refresh materialized view

---

docs/content/preview/yugabyte-cloud/cloud-clusters/managed-read-replica.md
docs/content/preview/yugabyte-cloud/release-notes.md

Known issues for read replicas fixed

[docs][cloud] Read replica limitations fixed

---

docs/content/preview/explore/ysql-language-features/postgresql-compatibility.md

More detailed list of unsupported PG features along with GH issues. This is for preview release 2.17, please update this for stable 2.16 release as well.

[docs] detailed list of unsupported PG features and GH issues

---

docs/content/preview/explore/ysql-language-features/postgresql-compatibility.md
docs/content/stable/explore/ysql-language-features/postgresql-compatibility.md

Backport SQL compatibility to stable
@netlify /stable/explore/ysql-language-features/postgresql-compatibility/

[docs] Backport SQL compatibility to stable

---

docs/content/preview/faq/yugabytedb-managed-faq.md
docs/content/preview/yugabyte-cloud/release-notes.md

What's new - stable updated to 2.14.6

[docs][cloud] Stable updated to 2.14.6

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-7001

[doc] PR for Fix formatting error k8s overrides

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-6907

[doc] PR for Add yb-bind check service in the on-prem Systemd public doc

---

docs/content/preview/yugabyte-cloud/release-notes.md

What's New - Stable database track updated to 2.16.0.1

[docs][cloud] Stable track updated to 2.16

---

docs/content/preview/explore/ysql-language-features/pg-extensions.md
docs/content/preview/secure/authentication/password-authentication.md

Add parameters for customizing passwordcheck PostgreSQL extension
#15681

[docs] Passwordcheck extension parameters

---

docs/content/preview/explore/multi-region-deployments/asynchronous-replication-ycql.md
docs/content/preview/explore/multi-region-deployments/asynchronous-replication-ysql.md
docs/content/preview/explore/multi-region-deployments/row-level-geo-partitioning.md

Update Explore xCluster with latest yugabyted commands + tidyup and remove YCQL
@netlify /preview/explore/multi-region-deployments/asynchronous-replication-ysql/

[docs][explore] Update Explore xCluster page

---

docs/content/preview/explore/_index.md
docs/content/preview/explore/fault-tolerance/macos.md
docs/content/preview/yugabyte-cloud/release-notes.md

Update release notes with YBM Rest API GA release

[docs][cloud] YBM API general availability

---

docs/content/preview/deploy/multi-dc/3dc-deployment.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-geopartition.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-multisync.md

Add caveats related to data in tablespaces and replication when a preferred region is specified.
@netlify /preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-multisync/

[docs][cloud] PR for We should call out leader and follower placement for multi-region clusters

---

docs/content/preview/explore/_index.md

[Docs] updated workload simulation version

---

docs/content/preview/explore/_index.md

Fixed at two places - Click on  "Set up YugabyteDB universe" and "Universe setup" to verify from the explore landing page.
Build preview: https://deploy-preview-15812--infallible-bardeen-164bc9.netlify.app/preview/explore/

[docs] [explore] link fix for set up YugabyteDB Universe

---

docs/content/preview/admin/yb-admin.md
docs/content/preview/deploy/multi-dc/3dc-deployment.md
docs/content/preview/drivers-orms/smart-drivers.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-multisync.md

Add caveats about setting topology keys to preferred regions (if set)
@netlify /preview/drivers-orms/smart-drivers/#topology-aware-connection-load-balancing

[docs] Smart drivers and preferred regions

---

docs/content/preview/releases/release-notes/v2.8.md
docs/data/currentVersions.json
docs/go.sum

@netlify /preview/releases/release-notes/v2.8/#v2.8.12.0

[docs] release 2.8.12.0

---

docs/content/preview/explore/cluster-management/point-in-time-recovery-ycql.md
docs/content/preview/explore/cluster-management/point-in-time-recovery-ysql.md
docs/content/preview/explore/indexes-constraints/gin.md
docs/content/preview/explore/observability/prometheus-integration/macos.md
docs/content/preview/explore/query-1-performance/pg-stat-progress-copy.md
docs/content/preview/yugabyte-cloud/cloud-clusters/managed-read-replica.md
docs/layouts/shortcodes/explore-setup-multi-cloud.html
docs/layouts/shortcodes/explore-setup-multi.html
docs/layouts/shortcodes/explore-setup-single.html

Fix deeplinks in setup shortcodes
@netlify /preview/explore/transactions/distributed-transactions-ysql/

[docs][explore] Fix deeplinks

---

docs/content/preview/legal/_index.md
docs/content/preview/manage/backup-restore/point-in-time-recovery.md
docs/content/preview/yedis/_index.md
docs/content/stable/manage/backup-restore/point-in-time-recovery.md
docs/content/v2.12/manage/backup-restore/point-in-time-recovery.md
docs/content/v2.14/manage/backup-restore/point-in-time-recovery.md
docs/content/v2.6/manage/backup-restore/point-in-time-recovery.md
docs/content/v2.8/manage/backup-restore/point-in-time-recovery.md

@netlify /preview/manage/backup-restore/point-in-time-recovery/

[docs] quick fixes to PITR, legal, YEDIS

---

docs/content/preview/yugabyte-cloud/release-notes.md

What's new - Terraform provider

[docs][cloud] What's new - Terraform provider

---

docs/content/preview/yugabyte-platform/troubleshoot/_index.md
docs/content/preview/yugabyte-platform/troubleshoot/install-upgrade-issues/kubernetes.md
docs/content/preview/yugabyte-platform/troubleshoot/install-upgrade-issues/vm.md

Fix https://yugabyte.atlassian.net/browse/PLAT-6523

[docs][PLAT-6523] Added troubleshooting guide for YBA k8s installation

---

docs/content/preview/integrations/janusgraph.md

resolves #15778 
@Sfurti-yb - I have updated the version from 0.2 to 0.6.2.
Build preview : https://deploy-preview-15854--infallible-bardeen-164bc9.netlify.app/preview/integrations/janusgraph/

[docs] [integrations] changed the janusgraph version to 0.6.2

---

docs/content/preview/reference/configuration/yugabyted.md
docs/content/stable/reference/configuration/yugabyted.md
docs/content/v2.14/reference/configuration/yugabyted.md

Update yugabyted reference:
- revert some commands/features in stable that are preview only
@netlify /preview/reference/configuration/yugabyted/

[docs] Update yugabyted reference

---

docs/content/preview/yugabyte-platform/manage-deployments/delete-universe.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-7187

[doc] PR for Fix an error in delete universe page

---

docs/content/preview/integrations/akka-ycql.md
docs/content/preview/integrations/akka-ysql.md

The R2DBC integration is supported by Lightbend.
The Cassandra integration is not officially supported by Lightbend yet, but we are looking into it. I have updated the Akka Persistence Cassandra sample and docs and verified that it works (I think it was rather broken).
Refs #15634

[docs] Add Akka R2DBC integration and update Cassandra integration, #15634

---

docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-overview.md
docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters/create-clusters-free.md
docs/content/preview/yugabyte-cloud/cloud-clusters/cloud-maintenance.md

Recommendations for operating a staging cluster and performing DB upgrades
@netlify /preview/yugabyte-cloud/cloud-basics/create-clusters-overview/

[docs][cloud] Staging best practices

---

docs/content/preview/develop/best-practices-ycql.md
docs/content/preview/drivers-orms/java/_index.md
docs/content/preview/drivers-orms/smart-drivers.md

Note on setting connection pool timeout
@netlify /preview/drivers-orms/smart-drivers/

[docs] Connection pool timeout

---

docs/content/preview/api/ycql/dml_transaction.md
docs/content/stable/api/ycql/dml_transaction.md
docs/content/v2.12/api/ycql/dml_transaction.md
docs/content/v2.14/api/ycql/dml_transaction.md

resolves #16008
@netlify /preview/api/ycql/dml_transaction/
note to self : back-port till 2.12

[docs] follow-up changes to the YCQL transactions page

---

docs/content/preview/contribute/docs/docs-build.md

@netlify /preview/contribute/docs/docs-build/#prerequisites

[docs] [DOC-3] add python prereq to the docs build

---

docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-7350

[doc] PR for Add YB controller port to on-premises confuration page  PLAT-7350

---

docs/content/preview/explore/_index.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-7185

[doc] PR for Adjust instructions on how to use the simulator app (in Explore index.md) PLAT-7185

---

docs/content/preview/yugabyte-cloud/cloud-clusters/managed-read-replica.md

resolves #16036 
@netlify /preview/yugabyte-cloud/cloud-clusters/managed-read-replica/

[DOC-10] added a limitation for read replicas 

---

docs/content/preview/explore/transactions/distributed-transactions-ycql.md
docs/content/preview/explore/transactions/distributed-transactions-ysql.md
docs/content/preview/explore/transactions/explicit-locking.md
docs/layouts/shortcodes/explore-setup-multi-cloud.html
docs/layouts/shortcodes/explore-setup-multi.html
docs/layouts/shortcodes/explore-setup-single.html

Modified the text to reflect that a single-node universe needs to be created.
Didn't bring back the setup box because it's really kludgy. In addition, it repeats what's already stated in the links.

[Docs] PR for Improve Transactions section in Explore - part 2

---

docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md
docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-zone.md
docs/content/preview/yugabyte-platform/manage-deployments/delete-universe.md
docs/content/preview/yugabyte-platform/manage-deployments/edit-helm-overrides.md
docs/content/preview/yugabyte-platform/manage-deployments/edit-universe.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-6856

[doc] PR for Add separate page for edit kubernetes overrides under manage deployments

---

docs/content/preview/yugabyte-cloud/cloud-quickstart/_index.md
docs/content/preview/yugabyte-cloud/release-notes.md

fix a broken link, remove a couple of cloud shell known issues, add new preview to release notes, downgrade stable to 2.14
@netlify /preview/yugabyte-cloud/cloud-quickstart/#create-your-sandbox-cluster

[docs] misc YBM updates

---

docs/content/preview/explore/multi-region-deployments/synchronous-replication-cloud.md
docs/content/preview/explore/multi-region-deployments/synchronous-replication-yba.md
docs/content/preview/explore/multi-region-deployments/synchronous-replication-ysql.md

Addresses https://yugabyte.atlassian.net/browse/PLAT-7324

[doc] PR for Add YBA tab and info under YugabyteDB > Explorer > Multi-region Deployments > Synchronous replication PLAT-7324

---

.github/ISSUE_TEMPLATE/cdc.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/ui.yml

This PR adds a template to file CDC related issues.

Add issue template for CDC issues

---

docs/content/preview/yugabyte-platform/back-up-restore-universes/back-up-universe-data/ysql.md
docs/content/preview/yugabyte-platform/create-deployments/async-replication-platform.md
docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes.md

1. bakups -> backups 
https://deploy-preview-16161--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/back-up-restore-universes/back-up-universe-data/ysql/
2. illustaration -> illustration
https://deploy-preview-16161--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/create-deployments/async-replication-platform/
3.  aslo -> also
https://deploy-preview-16161--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/create-deployments/create-universe-multi-zone-kubernetes/

[Docs] Fix spelling typos

---

docs/data/currentVersions.json

[docs] Fix versionShort of the current release 2.17.0 -> 2.17.1

---

docs/content/preview/architecture/design-goals.md

[docs] Fix link to "YSQL vs. PostgreSQL isolation levels" in design-goals.md

---

docs/content/preview/architecture/concepts/universe.md

[docs] Fix typo "namespaces" -> "namespace"

---

docs/content/preview/explore/_index.md
docs/content/preview/faq/operations-faq.md
docs/content/preview/reference/configuration/yugabyted.md

Add setup instructions on destroying local clusters for cleanup
@netlify /preview/explore/

[docs][explore] Destroy local cluster instructions

---

docs/content/preview/releases/release-notes/v2.15.md
docs/content/preview/releases/release-notes/v2.17.md
docs/content/preview/releases/yba-releases/v2.16.md
docs/content/preview/releases/yba-releases/v2.17.md
docs/content/preview/yugabyte-platform/security/create-kms-config/aws-kms.md
docs/content/preview/yugabyte-platform/security/create-kms-config/azure-kms.md
docs/content/preview/yugabyte-platform/security/create-kms-config/google-kms.md
docs/content/preview/yugabyte-platform/security/create-kms-config/hashicorp-kms.md
docs/content/stable/yugabyte-platform/security/create-kms-config/aws-kms.md
docs/content/stable/yugabyte-platform/security/create-kms-config/azure-kms.md
docs/content/stable/yugabyte-platform/security/create-kms-config/google-kms.md
docs/content/stable/yugabyte-platform/security/create-kms-config/hashicorp-kms.md

Resolves https://yugabyte.atlassian.net/browse/PLAT-7589
Use the correct product name for Azure KMS
@netlify /preview/yugabyte-platform/security/create-kms-config/azure-kms/

[docs] [PLAT-7589] Azure KMS to Key Vault

---

docs/content/preview/reference/configuration/yb-tserver.md
docs/content/preview/secure/enable-authentication/_index.md
docs/content/stable/reference/configuration/yb-tserver.md
docs/content/stable/secure/enable-authentication/_index.md
docs/content/stable/secure/enable-authentication/ysql-login-profiles.md

Port login profiles to stable and preview
@netlify /preview/secure/enable-authentication/ysql-login-profiles/

[Docs] Port login profiles to stable and preview

---

docs/content/preview/admin/yb-admin.md
docs/content/preview/secure/security-checklist.md
docs/content/preview/yugabyte-platform/_index.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/_index.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/back-up-universe-data/ycql.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/back-up-universe-data/ysql.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/pitr.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/schedule-data-backups/ycql.md
docs/content/preview/yugabyte-platform/back-up-restore-universes/schedule-data-backups/ysql.md
docs/content/preview/yugabyte-platform/create-deployments/_index.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/back-up-restore-k8s.md
docs/content/stable/yugabyte-platform/administer-yugabyte-platform/back-up-restore-yp.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/_index.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/back-up-universe-data/ycql.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/back-up-universe-data/ysql.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/schedule-data-backups/ycql.md
docs/content/stable/yugabyte-platform/back-up-restore-universes/schedule-data-backups/ysql.md
docs/content/stable/yugabyte-platform/create-deployments/_index.md
docs/content/v2.14/yugabyte-platform/administer-yugabyte-platform/back-up-restore-k8s.md
docs/content/v2.14/yugabyte-platform/administer-yugabyte-platform/back-up-restore-yp.md

Document that YBC is only compatible with DB clusters that are 2.16 and later
@netlify /preview/yugabyte-platform/back-up-restore-universes/

[docs][yba] yb controller and versions supported

---

docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md

- Refactored the [Pull and push YugabyteDB Docker images to private container registry](https://docs.yugabyte.com/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes/#pull-and-push-yugabytedb-docker-images-to-private-container-registry)
fix: https://yugabyte.atlassian.net/browse/PLAT-6797

[plat-6797][docs] Refactored the push and pull docker images

---

docs/content/preview/migrate/known-issues/_index.md
docs/content/preview/migrate/oracle.md
docs/content/preview/migrate/reference/yb-voyager-cli.md
docs/content/preview/migrate/ubuntu.md

Minor updates for voyager 1.1 release
@netlify /preview/migrate/install-yb-voyager/#install-yb-voyager

[docs] [migrate] docs for voyager 1.1

---

docs/content/preview/explore/ysql-language-features/pg-extensions.md

Add clarification for passwordcheck extension setup on startup

[docs] Add clarification for passwordcheck setup

---

docs/content/preview/api/ysql/exprs/_index.md
docs/content/stable/api/ysql/exprs/_index.md

[docs] Fix link to Geo-partitioning helper functions page

---

docs/content/preview/api/ysql/the-sql-language/statements/ddl_alter_sequence.md
docs/content/preview/api/ysql/the-sql-language/statements/ddl_create_sequence.md
docs/content/stable/api/ysql/the-sql-language/statements/ddl_alter_sequence.md
docs/content/stable/api/ysql/the-sql-language/statements/ddl_create_sequence.md

[docs] Fix sequence max value to render correctly `2⁶³ - 1`

---

docs/config/_default/menus.toml
docs/content/preview/migrate/_index.md
docs/content/preview/migrate/release-notes.md

Build preview: https://deploy-preview-16342--infallible-bardeen-164bc9.netlify.app/preview/migrate/release-notes/

[docs]release notes for YB Voyager 1.1
