- cloud/kubernetes/yugabyte-statefulset.yaml
Fixes https://github.com/YugaByte/yugabyte-db/issues/51
> #51: Kubernetes cname only tries the first ip address on GKE

- cloud/kubernetes/helm/generate_kubeconfig.py
You would run this script with the service account and it would generate the kubeconfig with token instead of the default credentials
`./generate_kubeconfig.py -s yugabyte-helm`
@rkarthik007
> Add generate kubeconfig script

- cloud/kubernetes/helm/README.md
- cloud/kubernetes/helm/yugabyte/Chart.yaml
- cloud/kubernetes/helm/yugabyte/templates/NOTES.txt
- cloud/kubernetes/helm/yugabyte/templates/service.yaml
- cloud/kubernetes/helm/yugabyte/values.yaml
Update helm chart to support multiple namespaces 
@rkarthik007 
In order to run helm charts to create multiple instances of YugaByte DB you would run the following command.
`helm install yugabyte --name dev`
That would bring up yugabyte in `dev` namespace
`helm install yugabyte --name staging`
That would bring up yugabyte in `staging` namespace
And you can independently cleanup
`helm delete dev`
> Make helm chart support multiple namespaces

- cloud/kubernetes/helm/yugabyte/templates/NOTES.txt
- cloud/kubernetes/helm/yugabyte/templates/service.yaml
Switch to using the v1 api instead of beta fixes this issue. Now that statefulset is actually GA.
tested by running
`helm install yugabyte --name yb-demo --wait`
and then
`helm delete yb-demo --purge`
Offcourse PVC's are something we need to cleanup manually after the fact.
> Fix StatefulSet delete issue

- cloud/kubernetes/helm/yugabyte/Chart.yaml
- cloud/kubernetes/helm/yugabyte/templates/service.yaml
- cloud/kubernetes/helm/yugabyte/values.yaml
- cloud/kubernetes/yugabyte-statefulset-local-ssd-gke.yaml
- cloud/kubernetes/yugabyte-statefulset.yaml
Added detection of master POD IP and passing it to `yb-master` as `--rpc_bind_addresses`, so `yb-master` is listening on POD IP instead of `0.0.0.0`.
> ENG-3574: Kubernetes functionality broken by master addresses check

- cloud/kubernetes/helm/yugabyte/Chart.yaml
- cloud/kubernetes/helm/yugabyte/templates/service.yaml
- cloud/kubernetes/helm/yugabyte/values.yaml
Tested by running helm install 
`helm install yugabyte --set instanceType.cpu=2 --set instanceType.memory=7.5Gi --set replica.tservers=5 --name demo`
> Update Helm Chart to take replica, cpu and memory as parameters

- cloud/kubernetes/helm/yugabyte/templates/service.yaml
- cloud/kubernetes/helm/yugabyte/values.yaml
Tested by running helm install and validated 
`helm install yugabyte --name demo`
> Add memory limit to ram ratio

- cloud/kubernetes/helm/README.md
- cloud/kubernetes/helm/expose-all.yaml
- cloud/kubernetes/helm/yugabyte/templates/service.yaml
- cloud/kubernetes/helm/yugabyte/values.yaml
Tried to create a YB universe via helm with expose all override yaml. And validated the cassandra authentication was enabled.
`helm install yugabyte -f expose-all.yaml --namespace yb-demo --name yb-demo --wait`
> Add gflags override option for helm

- cloud/kubernetes/helm/yugabyte/templates/service.yaml
Add metric node name parameter for both master and tserver, this is needed if we want the correct exported_instance name to be populated for prometheus metrics
Tested by bring up a YB cluster
`helm install yugabyte -f expose-all-shared.yaml --namespace yb-demo --name yb-demo --wait`
And in the tserver service expose port 9000 as well. then hit the LB endpoint 
`curl http://<LB IP>:9000/prometheus-metrics`
This PR fixes #586
> Add Metric Node Name to helm chart

- cloud/kubernetes/helm/yugabyte/templates/service.yaml
Added universename to yb-master and yb-tserver master addresses and server_broadcast_addresses. Necessary for multi-universe environments in k8s. Also added --logtostderr flag to enable logging.
> Github issue#599 - add universename to host spec and add --logtostderr

- cloud/kubernetes/helm/yugabyte/templates/service.yaml
- cloud/kubernetes/helm/yugabyte/values.yaml
- cloud/kubernetes/yugabyte-statefulset.yaml
Adding support for enabling postgres in both the stateful set and helm.
For statefulset yml:
- install: `kubectl apply -f yugabyte-statefulset.yaml`
- run initdb: `kubectl exec -it yb-tserver-0 bash --  -c "YB_ENABLED_IN_POSTGRES=1 FLAGS_pggate_master_addresses=yb-master-0.yb-masters.default.svc.cluster.local:7100,yb-master-1.yb-masters.default.svc.cluster.local:7100,yb-master-2.yb-masters.default.svc.cluster.local:7100 /home/yugabyte/postgres/bin/initdb -D /tmp/yb_pg_initdb_tmp_data_dir -U postgres"`
- connect: `kubectl exec -it yb-tserver-0 /home/yugabyte/postgres/bin/psql -- -U postgres -d postgres -h yb-tserver-0 -p 5433`
For helm:
- install: `helm install yugabyte --wait --namespace yb-demo --name yb-demo --set "enablePostgres=true"`
- run initdb: `kubectl exec -it -n yb-demo …
> Adding postgres support to statefulset and helm

- cloud/kubernetes/helm/yugabyte/templates/service.yaml
Removing gflags setting the number of masters so that ybase explicitly uses the broadcast addresses to resolve IPs.
Tested by creating a universe and deleting the masters and seeing the new master pod is registered with the other masters. Also tested killing tservers and checking if they respawned correctly and got the balanced tablets.
> #648 Removed gflags for replication factor

- cloud/kubernetes/helm/yugabyte/templates/service.yaml
Changed the gflad logtostderr to stderrthreshold=0 so that k8s logs to disk as well as std err.
Tested by creating a universe and checking the logs are available through kubectl logs as well as through the pod disk
> Fixed gflag to log to stderr as well as disk 

- cloud/kubernetes/helm/README.md
- cloud/kubernetes/helm/yugabyte/templates/service.yaml
- cloud/kubernetes/helm/yugabyte/values.yaml
Make the volume claim to be overridable at master and tserver separately
Tested by overriding the default storage size for tserver and the storage count for master.
```
helm install yugabyte --set "storage.tserver.size=30Gi,storage.master.count=1" --namespace yb-demo --name yb-demo --wait
```
Tested by launch cluster with defaults.
```
helm install yugabyte --namespace yb-demo --name yb-demo --wait
```
fixes #678
> Split the volume claim override for master and tserver

- cloud/kubernetes/helm/yugabyte/templates/service.yaml
- cloud/kubernetes/helm/yugabyte/values.yaml
- cloud/kubernetes/yugabyte-statefulset.yaml
Added enableYsql alias
For helm:
- install: `helm install yugabyte --wait --namespace yb-demo --name yb-demo --set "enableYsql=true"`
- run initdb: `kubectl exec -it -n yb-demo yb-tserver-0 bash --  -c "YB_ENABLED_IN_POSTGRES=1 FLAGS_pggate_master_addresses=yb-master-0.yb-masters.yb-demo.svc.cluster.local:7100,yb-master-1.yb-masters.yb-demo.svc.cluster.local:7100,yb-master-2.yb-masters.yb-demo.svc.cluster.local:7100 /home/yugabyte/postgres/bin/initdb -D /tmp/yb_pg_initdb_tmp_data_dir -U postgres"`
- connect: `kubectl exec -n yb-demo -it yb-tserver-0 /home/yugabyte/postgres/bin/psql -- -U postgres -d postgres -h yb-tserver-0.yb-tservers.yb-demo -p 5433`
- Also, tested the above with --set "enablePostgres=true"
For statefulset yaml:
- install: `kubectl apply -f yugabyte-statefulset.yaml`
- …
> Added enableYsql alias for enablePostgres

- cloud/kubernetes/helm/yugabyte/templates/service.yaml
Fix RF=1 case to not hit table creation errors complaining about RF being 3 (as that is the default) by always passing in the `replication_factor` parameter to master startup.
Tested via:
```
$ helm install --name yb-iot-test --set replicas.master=1,replicas.tserver=1 . --wait
$ kubectl exec -it yb-tserver-0 /home/yugabyte/bin/cqlsh
cqlsh> CREATE KEYSPACE IF NOT EXISTS TrafficKeySpace;
cqlsh> CREATE TABLE IF NOT EXISTS TrafficKeySpace.Poi_Traffic(vehicleid text, vehicletype text, distance bigint, timeStamp timestamp, PRIMARY KEY (vehicleid));
```
> #840 Create table fails on an helm created cluster with 1 master replica.

- cloud/kubernetes/helm/yugabyte/templates/NOTES.txt
- cloud/kubernetes/helm/yugabyte/templates/_helpers.tpl
- cloud/kubernetes/helm/yugabyte/templates/service.yaml
- cloud/kubernetes/helm/yugabyte/values.yaml
- Added an override param `domainName` at each of the service level. 
- Moved some common code into the _helpers.tpl file and use template calls
Tested by bring up a TLS enabled cluster.
`helm install yugabyte --namespace yb-demo --name yb-demo --set=tls.enabled=true --set=Image.repository=quay.io/yugabyte/yugabyte --set=Image.pullSecretName=yugabyte-k8s-pull-secret --wait`
Also tested by bring up non TLS enabled cluster.
`helm install yugabyte --namespace yb-demo --name yb-demo --set=Image.repository=quay.io/yugabyte/yugabyte --set=Image.pullSecretName=yugabyte-k8s-pull-secret --wait`
fixes #883
> Helm add domain

- cloud/kubernetes/helm/README.md
- cloud/kubernetes/helm/yugabyte/templates/service.yaml
tested by passing the gflags
TLS with enable node_to_node and client_to_node enable
`
helm install yugabyte --namespace yb-demo --name yb-demo --set=tls.enabled=true,Image.repository=quay.io/yugabyte/yugabyte,gflags.master.use_node_to_node_encryption=true,gflags.tserver.use_node_to_node_encryption=true,gflags.master.allow_insecure_connections=false,gflags.tserver.allow_insecure_connections=false,Image.pullSecretName=yugabyte-k8s-pull-secret,gflags.tserver.use_client_to_server_encryption=true --wait
`
TLS with enable node_to_node 
`
helm install yugabyte --namespace yb-demo --name yb-demo --set=tls.enabled=true,Image.repository=quay.io/yugabyte/yugabyte,gflags.master.use_node_to_node_encryption=true,gflags.tserver.use_node_to_node_encryption=true,gflags.master.allow_insecure_connections=fal …
> Move TLS specific flags to be gflags override

- cloud/kubernetes/helm/expose-all-shared.yaml
- cloud/kubernetes/helm/expose-all.yaml
- cloud/kubernetes/helm/yugabyte/templates/service.yaml
- cloud/kubernetes/helm/yugabyte/values.yaml
- cloud/kubernetes/yugabyte-statefulset-rf-1.yaml
Changes include:
1. Enable YSQL by default.
2. Added yaml for replication factor 1.
Testing:
For helm:
install: `helm install yugabyte --wait --namespace yb-demo --name yb-demo`
run initdb: `kubectl exec -it -n yb-demo yb-tserver-0 bash -- -c "YB_ENABLED_IN_POSTGRES=1 FLAGS_pggate_master_addresses=yb-master-0.yb-masters.yb-demo.svc.cluster.local:7100 /home/yugabyte/postgres/bin/initdb -D /tmp/yb_pg_initdb_tmp_data_dir -U postgres"`
connect: `kubectl exec -n yb-demo -it yb-tserver-0 /home/yugabyte/postgres/bin/psql -- -U postgres -d postgres -h yb-tserver-0.yb-tservers.yb-demo -p 5433`
Also, tested the above with --set "disableYsql=true"
For statefulset yaml:
install: `kubectl apply -f yugabyte-statefulset-rf-1.yaml`
run initdb: `kubectl exec -it yb-tserver-0 bash -- -c …
> Enable YSQL by default and add yaml for replication factor 1

- cloud/kubernetes/helm/yugabyte/templates/service.yaml
- cloud/kubernetes/helm/yugabyte/values.yaml
Added nodeAffinity spec to orchestrate pod deployments on the nodes in the required zones. Also updated the master addresses to be customizable for multi-az where the addresses can't be computed by the template.
Adds support for issue #1063
> [#1063] Updated helm chart to support multi-az

- cloud/kubernetes/helm/yugabyte/templates/service.yaml
Also modified the annotations for the services to now be populated with the service endpoints.
Tested the helm chart by creating a statefulset deployment with the network annotation and also checked the service annotations after editing the serviceEndpoint values in Values.yaml.
Fixes for: #1179 and #797
> Added support for Network annotations for the Statefulset deployements.

- cloud/kubernetes/helm/yugabyte/templates/_helpers.tpl
- cloud/kubernetes/helm/yugabyte/templates/service.yaml
- cloud/kubernetes/helm/yugabyte/values.yaml
Change to support custom domains for k8s deployments.
Tested using `helm install yugabyte --name yb-demo --namespace yb-demo --dry-run --debug` to verify that all the addresses are as expected and then used `helm install yugabyte --name yb-demo --namespace yb-demo --wait` to check that the deployment went through correctly and created a YB universe.
> Added support for custom domain names

- docs/styles/_toc.scss
- docs/styles/_yuga_content.scss
> Fix FontAwesome checkmark icon for the copy button for code snippets

- docs/layouts/partials/search.html
Should be 'Yuga**Byte** DB Docs'
> [Docs] Fix formatting of name in search bar to uppercase 'Byte'

- README.md
Issue was on mobile where the logo would look stretched.
> Remove height attribute to allow for auto-scaling of YB logo on README

- bin/yb-docker-ctl
Fix for issue: #1772 
The yb-docker-ctl now uses a snapshot to initialize the sys catalog table which reduces the start-up time of the containers drastically.
Tested by creating a YB cluster using yb-docker-ctl create and checking the ysqlsh could establish a connection to the psql database.
> Modified flag to initialize sys-catalogs for YSQL in yb-docker-ctl

- docs/content/_index.html
- docs/layouts/partials/footer_links.html
- docs/layouts/partials/header.html
- docs/styles/_navbar.scss
Add mobile specific view for navbar that appears in hamburger menu. Add bootstrap breakpoint sizes for Release and Architecture tiles.
Output:
> [Docs] Add mobile view for navbar menu and fix sizing of home page tiles

- src/yb/server/webserver.cc
After adding the `/api/v1/tablet-servers` endpoint to master, we need to allow YW access to view it.
> Add access to UI from any site

- cloud/kubernetes/yugabyte-statefulset-local-ssd-gke.yaml
- fixed issue in local SSD deployment where namespaces other than default did not work
- added explicit replication_factor=3 to allow the user to customize number of replicas easily in the yb-master StatefulSet
- fixed inconsistencies in opening docs to refer to the correct yaml file name (yugabyte-statefulset-local-ssd-gke.yaml)
- added some instructions on setting up Redis (user must manually run a setup_redis script)
> Fixed issues in local SSD deployment YAML for GKE (Kubernetes)

- managed/ui/src/components/dashboard/Dashboard.js
- managed/ui/src/components/panels/UniverseDisplayPanel/UniverseDisplayPanel.js
- managed/ui/src/components/panels/UniverseDisplayPanel/UniverseDisplayPanel.scss
- managed/ui/src/components/universes/ListUniverse/ListUniverse.js
- managed/ui/src/components/universes/ListUniverse/ListUniverse.scss
Fixes #1583
We want to replace with similar layout as List Universes page, where the header is on the navbar and the two action buttons are on the top right.
> Remove dual action Add Universe button and replace

- docs/layouts/partials/header.html
- docs/styles/_navbar.scss
Point Get Started button to download.yugabyte.com and add styling for social media links in header when it is less than ultra wide.
> Change Get Started button link and add responsive styling

- docs/README.md
Heavily edit the [Advanced Usage section](../tree/master/docs/README.md#advanced-usage) of the docs README.  Split it up into four subsections: file generation, adding a page, editing rules in a page, and notes.  Introduce instructions to edit index files.  Overall, make the instructions more uniform.
> [docs] README reformat Advanced Usage section

- src/yb/master/catalog_manager.cc
- src/yb/master/catalog_manager.h
The yb-master leader tracks yb-tserver heartbeats and knows which
TServers haven't been able to heartbeat/have been unresponsive
The yb-master process exposes (via http://<master-ip>:7000/prometheus-metrics)
a num_tablet_servers_live metric, but a num_tablet_servers_dead
might be more useful/easier for setting up alerts. This number being greater
than 0 could be set to result in an alert.
To do this, expose another metric num_tablet_servers_dead from the catalog
manager similar to the num_tablet_servers_live. This metric tracks the
number of total tablet servers - live tablet servers.
Test plan:
1) Set up local yugabyte cluster with 3 nodes with prometheus monitoring
2) Verify that num_tablet_servers_live = 3 and num_tablet_servers_dead=0
on the :7000 prometheus metrics page
3) Use yb-ctl …
> Issue #1367 expose number of dead/unresponsive tservers as yb-master metric

- docs/content/latest/deploy/cdc/cdc-to-kafka.md
- docs/content/latest/deploy/cdc/cdc-to-stdout.md
- docs/content/latest/deploy/cdc/use-cdc.md
- docs/content/latest/quick-start/binary/linux-install.md
- docs/content/latest/quick-start/binary/macos-install.md
- docs/content/latest/quick-start/explore-ysql.md
- docs/content/latest/secure/tls-encryption/_index.md
Quick start
- Added prerequisite note about using `wget` or `curl`, and how to install `wget`.
- Replaced some "bullet" steps with numbered steps and improved layout.
CDC
- Fixed some syntax issues.
TLS
- Changed note to say "Client-server — using CLIs and APIs for YCQL (YSQL support in progress)" instead of "Client-server — using CLIs and APIs for YSQL and YCQL"
> Quick start and CDC cleanup

- docs/content/latest/deploy/docker/docker-compose.md
- docs/content/latest/deploy/docker/docker-swarm.md
Fix docker deploy docs to remove initdb step and use enable_ysql flag while starting yb-master.
Also updated wrong quick start links.
> Fix docker deploy docs to include enable_ysql flag

- docs/content/latest/admin/yb-docker-ctl.md
Adds optional `--tag` parameter to the `yb-docker-ctl` parameter list and a section on "Specify a docker image tag".
> Add content for new `--tag` paramter.

- docs/content/latest/quick-start/explore-ysql.md
The O/p of describe products tables in following section is distorted. 
``` 
https://docs.yugabyte.com/latest/quick-start/explore-ysql/#docker
```
Changes are done to fix the same.
> Fixed distorted O/p of describe products table command

- docs/content/latest/admin/yb-ctl.md
- docs/content/latest/explore/binary/auto-sharding.md
- docs/content/latest/troubleshoot/nodes/check-logs.md
Found many references to an older `/tmp/yugabyte-local-cluster/` directory — fixed with corrected location of `yugabyte-data` directory.
> Correct location of yugabyte-data directory

- cloud/kubernetes/design/operator_design.md
- cloud/kubernetes/design/ybcluster_crd.yaml
This is the initial draft of YugabyteDB operator design. `operator_design.md` contains overall design details along with sample CR spec. `ybcluster_crd.yaml` contains CR validation rules.
Though I am raising this PR against `yugabyte-db` repo, should there be a separate repo for operator alone? I can close this & recreate the design PR, if we do create a separate repo for operator.
> Design for YugabyteDB operator

- docs/config.yaml
- docs/content/latest/admin/_index.html
- docs/content/latest/admin/cqlsh.md
- docs/content/latest/admin/yb-ctl.md
- docs/content/latest/admin/yb-docker-ctl.md
- docs/content/latest/admin/yb-master.md
- docs/content/latest/admin/yb-tserver.md
- docs/content/latest/admin/ysqlsh.md
Add new YSQL flags. Also, reformatted CLI pages for consistency, findability, and linkability of settings. Added missing flags to `yb-ctl` page and links to relevant examples.
Fixes first item of https://github.com/yugabyte/yugabyte-db/issues/2413 and required for completing the other two items.
> Add new YSQL flags and update configuration options/flags for CLI section.

- docs/content/latest/admin/ysqlsh.md
- docs/content/latest/deploy/public-clouds/gcp/gke.md
- docs/content/latest/develop/graphql/hasura.md
Adds note to `ysqlsh` page that "Starting with YugabyteDB 2.0.1, the default `yugabyte` user for `ysqlsh` has a default password of `yugabyte`. Before this release, no password was required."
> Add default password to yugabyte user for ysqlsh.

- docs/README.md
In the docs README, there is a link to the build section of the README
of the RRDiagram repo.  However, that link is incorrectly formatted, so
it takes users to an unhelpful "Not Found" page.  Fix the link.
> [docs] Fix link to build section of RRDiagram

- docs/content/latest/admin/yb-admin.md
- docs/content/latest/admin/yb-master.md
- docs/content/latest/admin/yb-tserver.md
- docs/content/latest/reference/default-ports.md
- Fixes a syntax error in yb-admin
- Replaces "Placement options" with "Geo-distribution options"
- Add hearbeat-related settings to yb-master and yb-tserver
> [docs] Correct yb-admin syntax and add new "Geo-distributed options"

- docs/content/latest/admin/yb-ctl.md
- docs/content/latest/admin/yb-master.md
- docs/content/latest/admin/yb-tserver.md
- docs/content/latest/deploy/docker/docker-compose.md
- docs/content/latest/deploy/docker/docker-swarm.md
- docs/content/latest/deploy/manual-deployment/start-masters.md
- docs/content/latest/deploy/public-clouds/aws/manual-deployment.md
- docs/content/latest/develop/kubernetes/run-sample-apps.md
- docs/content/latest/quick-start/kubernetes/create-local-cluster.md
- docs/content/latest/releases/v2.0.3.md
- Add #2455 (Set default for enable_ysql` to `true`) to 2.0.3 release notes
- Remove all `enable_ysql` settings where not needed.
- Changed `eanable_ysql` default values in yb-master and yb-tserver to `true`.
- Remove "Initialize the YSQL API" from Kubernetes quick start.
> [docs] Update use of "enable_ysql` in settings and examples

- src/yb/rpc/outbound_call.cc
- src/yb/rpc/rpc_introspection.proto
- src/yb/rpc/rpc_stub-test.cc
- src/yb/rpc/yb_rpc.cc
- src/yb/yql/cql/cqlserver/cql_rpc.cc
- src/yb/yql/redis/redisserver/redis_rpc.cc
The elasped time is in micros-seconds and
timeout is in milliseconds for endpoint /rpcz
Set elasped time to milliseconds.
Possible Fix to #2801
> Set Timeout and elapsed time in same units

- docs/content/latest/quick-start/binary/linux-install.md
- docs/content/latest/quick-start/binary/macos-install.md
- docs/content/latest/quick-start/docker/install.md
Add note to macOS, Linux, and Docker installation requirements in Quick Start.
> Add GitHub issue and link for users to track Python 3 support.

- docs/content/latest/deploy/public-clouds/azure/azure-arm.md
- docs/content/latest/deploy/public-clouds/gcp/gcp-deployment-manager.md
- docs/content/latest/explore/binary/two-data-centers.md
- docs/content/latest/manage/backup-restore/snapshots.md
There is a place in our docs which has a `http` endpoint and it keeps giving me warning messages on netlify deployments. fix that.
> Fix the mixed content warning in docs

- docs/content/latest/api/ysql/commands/cmd_do.md
- docs/content/latest/api/ysql/commands/dcl_alter_default_privileges.md
- docs/content/latest/api/ysql/commands/dcl_alter_group.md
- docs/content/latest/api/ysql/commands/dcl_alter_policy.md
- docs/content/latest/api/ysql/commands/dcl_alter_role.md
- docs/content/latest/api/ysql/commands/dcl_alter_user.md
- docs/content/latest/api/ysql/commands/dcl_create_group.md
- docs/content/latest/api/ysql/commands/dcl_create_policy.md
- docs/content/latest/api/ysql/commands/dcl_create_role.md
- docs/content/latest/api/ysql/commands/dcl_drop_group.md
- docs/content/latest/api/ysql/commands/dcl_drop_owned.md
- docs/content/latest/api/ysql/commands/dcl_drop_policy.md
- docs/content/latest/api/ysql/commands/dcl_drop_role.md
- docs/content/latest/api/ysql/commands/dcl_drop_user.md
- docs/content/latest/api/ysql/commands/dcl_grant.md
- docs/content/latest/api/ysql/commands/dcl_reassign_owned.md
- docs/content/latest/api/ysql/commands/dcl_revoke.md
- docs/content/latest/api/ysql/commands/dcl_set_role.md
- docs/content/latest/api/ysql/commands/dcl_set_session_authorization.md
- docs/content/latest/api/ysql/commands/ddl_create_schema.md
- docs/content/latest/api/ysql/commands/ddl_create_table.md
- docs/content/latest/api/ysql/commands/perf_prepare.md
- Add mising `linkTitle`to statements
- Replace "Users and groups" in about five statements to show statement names.
> [docs] Fix YSQL statement front matter and titles

- docs/config.yaml
- docs/layouts/partials/head.html
- docs/styles/_buttons.scss
- docs/styles/_feedback.scss
- docs/styles/_footer.scss
- docs/styles/_indexpage.scss
- docs/styles/_navbar.scss
- docs/styles/_search.scss
- docs/styles/_toc.scss
- docs/styles/_yuga_content.scss
- docs/styles/_yuga_overrides.scss
- Fix h3 font-size being larger than h2 in mobile view.
- Fix definition list tags not having inline indents.
- Change fonts from Montserrat to Rubik and Open Sans to Inter.
> [Docs] Fix mobile responsive styling not sizing correctly and change fonts

- docs/layouts/partials/footer_js.html
As Steve mentioned, a search on the docs sometimes returns results from previous version BEFORE results from the latest version. This will cause confusion and led to outdated information.
The search takes place on a separate page so first check the window.referrer to find out the page from which the search from initialized and get the proper version if it exists. Now if the version is not present in the url we can assume 'latest' version, or if the user somehow lands on the url of the search page itself, then we can also assume 'latest'. Luckily we already track the version of the page through our fork of docsearch-scrapper so we only need to add that filter to the search parameter object in the JS.
Note that this change will remove all results that don't match the version of the page the …
> [#2160][Docs] Fix Algolia search to filter by version of page

- docs/content/latest/contribute/core-database/build-from-src/macos.md
Summary:
The latest version of bison on Homebrew is 3.5 and it prevents the code
from compiling as described in issue: https://github.com/yugabyte/yugabyte-db/issues/3218
This issue is resolved using the older version of bison.
Hencei, we need to update the docs describing how to do the same.
Reviewers: Karthik, MBautin
> Update docs on installing the compatible version of bison (3.4.1).

- docs/layouts/_default/single.html
- docs/styles/_toc.scss
- docs/styles/_yuga_overrides.scss
Improving Dorian's PR: https://github.com/yugabyte/yugabyte-db/pull/3301
Also, added styling fixes for h4, h5 as per @stevebang suggestion.
> [Docs] Change padding below the article h1 to be 0 and fix formatting for h4,h5

- docs/styles/_yuga_overrides.scss
Drift widget is injected via iframe by bigpicture, we don't want to show the widget on our docs page.
`npm start` 
and validated the widget was not displayed.
> Hide drift widget on docs

- docs/styles/_indexpage.scss
See page: https://docs.yugabyte.com/latest/comparisons/
Notice that the head content is spaced too close to the title.
Fix:
> [Docs] Fix head content spacing between description title

- docs/content/latest/deploy/public-clouds/aws/manual-deployment.md
- docs/content/latest/faq/general.md
- docs/content/latest/faq/operations-faq.md
- docs/content/latest/reference/configuration/yb-master.md
- docs/content/latest/reference/configuration/yb-tserver.md
- Change Karthik's code examples to use `yb-tserver` configuration options.
- Add the following three logging-related options (gflags) mentioned in the FAQ to the `yb-tserver` configuration page:
- `--log_min_segments_to_retain`
- `--log_min_seconds_to_retain`
- `--log_segment_size_mb`
> [docs] Change WAL-related FAQ and add related gflags

- docs/content/latest/architecture/concepts/universe.md
- docs/content/latest/architecture/docdb/replication.md
- docs/content/latest/comparisons/amazon-aurora.md
- docs/content/latest/faq/general.md
- docs/content/latest/introduction.md
- docs/content/latest/reference/configuration/yb-master.md
- docs/content/latest/reference/configuration/yb-tserver.md
- docs/content/latest/troubleshoot/nodes/check-logs.md
- docs/content/v1.0/architecture/concepts/replication.md
- docs/content/v1.0/introduction/overview.md
- docs/content/v1.1/architecture/concepts/docdb/replication.md
- docs/content/v1.1/introduction.md
- docs/content/v1.2/architecture/docdb/replication.md
- docs/content/v1.2/introduction.md
- docs/content/v1.3/architecture/docdb/replication.md
- docs/content/v1.3/introduction.md
- Move all Raft flags into "Raft options" sections of `yb-tserver` and `yb-master` configurations.
- Replace "read-only replica" with "read replica" for consistency and searching.
> [docs] Reorganize Raft settings and search/replace terms

- docs/content/latest/admin/ysql-dumpall.md
- docs/content/latest/api/ysql/commands/dcl_create_user.md
- docs/content/latest/api/ysql/commands/ddl_create_trigger.md
- docs/content/latest/develop/ecosystem-integrations/metabase.md
- docs/content/latest/develop/graphql/prisma.md
- docs/content/latest/develop/learn/strings-and-text.md
- docs/content/latest/develop/realworld-apps/retail-analytics.md
- docs/content/latest/quick-start/build-apps/nodejs/ysql-pg.md
- docs/content/latest/quick-start/build-apps/python/ysql-psycopg2.md
- docs/content/latest/quick-start/build-apps/ruby/ysql-pg.md
- docs/content/latest/quick-start/build-apps/ysql/c.md
- docs/content/latest/quick-start/build-apps/ysql/cpp.md
- docs/content/latest/quick-start/build-apps/ysql/csharp.md
- docs/content/latest/quick-start/build-apps/ysql/go.md
- docs/content/latest/quick-start/build-apps/ysql/php.md
- docs/content/latest/quick-start/build-apps/ysql/python.md
- docs/content/latest/quick-start/build-apps/ysql/ruby.md
- docs/content/latest/sample-data/chinook.md
- docs/content/latest/sample-data/northwind.md
- docs/content/latest/sample-data/pgexercises.md
During the initial change, we missed changing a bunch of "postgres" to "yugabyte". This PR replaces the default db, user, and password, in some YSQL statement examples and code examples.
> [docs Replace postgres user with yugabyte user

- docs/content/latest/explore/observability.md
- docs/content/latest/reference/configuration/default-ports.md
- Add link from "Observability with Prometheus" tutorial to "Monitoring with Prometheus" in default nodes page.
- Add link from "Monitoring with Prometheus" in default nodes page to tutorial on "Observability with Prometheus"
- Add Prometheus targets for `yb-master` and `yb-tserver` on default nodes page.
- Cleaned up and edited monitoring section.
> [docs] Update Prometheus monitoring content

- src/postgres/src/bin/pgbench/pgbench.c
Summary:
Currently with large scale factors we are facing troubles inserting data
into the table. This is because all of the inserts happen in one large
transaction.
This change involves persisting the rows in much smaller transactions
with the size of the batch being configured using 'batch-size' argument.
The issue is described in: https://github.com/yugabyte/yugabyte-db/issues/3229
Reviewers: Kannan, Mihnea, Neha
Performance Comparisons with and without the batching:
We see that the performance difference is 1.4X between the two approaches.
Performance with a batch size of 1024:
```
ysql_bench_batch_sizing:postgres $ time bin/ysql_bench -h 127.0.0.1 -p 5433 -i -s 20 --batch-size 1024 yugabyte
dropping old tables...
NOTICE: table "ysql_bench_accounts" does not exist, skipping
NOTICE: …
```
> #3229: Adding batching support for insertions into the table in ysql_bench.

- docs/content/latest/reference/configuration/default-ports.md
- Point to correct link of `-rpc_bind_addresseswhich` for `yb-tserver`
- Correct default value of `-tserver_master_addrs` which is `0.0.0.0:7100`
> [docs] Fix a typo in default-ports.md

- docs/content/latest/troubleshoot/nodes/_index.md
- docs/content/latest/troubleshoot/nodes/recover-disk.md
Add an FAQ to the Operations FAQ on how to deal with a single disk failure.
See: https://stackoverflow.com/questions/59922082/how-does-yugabyte-handle-single-disk-failure/59936552#59936552
> recover-disk draft

- docs/content/latest/deploy/docker/docker-compose.md
In the docker-compose example, this PR adds a client container (yb-sample-apps) that connects to the SQL service of the tserver. The client is on a separate network that is shared only with the tserver (not the master).
> Add a client to the docker-compose example

- docs/content/latest/deploy/kubernetes/oss/helm-chart.md
- docs/content/latest/develop/learn/date-and-time-ysql.md
- docs/content/latest/develop/learn/strings-and-text-ysql.md
- docs/content/latest/develop/realworld-apps/retail-analytics.md
- docs/content/latest/quick-start/build-apps/ysql/csharp.md
- docs/content/latest/quick-start/explore-ysql/_index.md
- docs/content/latest/quick-start/explore-ysql/kubernetes/explore-ysql.md
Use of hyphen causes issues with `ysqlsh`. Also, apparently, Oracle and PostgreSQL don't allow hyphens in identifiers. Need to review why Kubernetes examples all use `yb-demo` in namespaces, etc.
> [docs] Revert yb-demo to yb_demo for non-Kubernetes content

- CONTRIBUTORS.md
Extending functionality for YugabyteDB in order to orchestrate it on aws via ansible.
[issue description] (https://github.com/yugabyte/yugabyte-db/issues/3677)
> Adding to contributor list

- docs/config.yaml
- docs/layouts/_default/sitemap.xml
This PR adds an auto-generated, custom `sitemap.xml` file that only includes the `/latest/` URLs. 
- As the existing Google Search cached files expire, users will see only the latest docs in their search results.
- Users can continue to find docs for older versions using the DocSearch search on our site.
During testing, Hugo generated 3559 pages. The auto-generated sitemap includes only 1443 files.
> [docs] Add auto-generated, custom sitemap.xml to docs.yugabyte.com

- docs/content/latest/api/ysql/syntax_resources/commands/foo
- docs/static/robots.txt
Update `robots.txt` to:
- include link to `sitemap.xml`/latest/api/ysql/syntax_resources/commands/*.diagram
- disallow the following files:/latest/api/ysql/syntax_resources/commands/*.grammar
Based on discussion with @m-iancu
> [docs] Update robots.txt to exclude .diagram and .grammar files from Google Search indexing

- docs/content/latest/secure/tls-encryption/_index.html
- docs/content/latest/secure/tls-encryption/client-certificates.md
Based on comments from @bmatican, two links are fixed. And a copy command prefix was fixed.
> [docs] Fix links and copy command 

- docs/content/latest/api/ysql/datatypes/type_json/functions-operators/_index.md
Displaying a pipe (`|`) or double pipes (`||`) within code blocks within Markdown tables is a challenge. Pipes are used in the Markdown syntax for building tables. I triaged this for now using the ASCII code `&#124`. Two alternatives to consider are using HTML tables or definition lists.
> [docs] Fix pipe and double pipe display issues

- docs/styles/_indexpage.scss
The headers below the card contain padding-top that is partially covering the card above it. Easiest fix is to increase the z-index
> [Docs][#3961] Flicker is to due to excess padding on the headers below

- docs/content/latest/secure/tls-encryption/server-certificates.md
Fixes triple-hash-tick (?) indentation to properly render the document.
Keep in mind I have NOT ran the code to render this locally on my machine, only used the markdown editor on github, so it may be beneficial to double-check the rendering is 100% fixed first. I can definitely do that a bit later if desired. Sorry, don't mean to be lazy, but... I'm being a little lazy 🤷‍♂ 
Current rendering looks a little off:
> [docs] fixup server-certificates.md code formatting

- docs/layouts/partials/pagination_url_search.html
Add check that new page weight is greater than current page weight when going to next page, and less than current page weight when going to previous page.
> [Docs][#3895] Change pagination links to be set when page weight changes

- docs/config.yaml
As described in release notes due to change in the Markdown renderer Hugo uses: https://gohugo.io/news/0.60.0-relnotes/
> [Docs] Fix missing HTML snippets in index.html in latest Hugo

- docs/content/latest/manage/backup-restore/back-up-data.md
- docs/content/latest/manage/backup-restore/restore-data.md
fixes #4015 
was:
changed:
was:
changed:
> [docs] move menu on the side in backup/restore ysql

- docs/content/latest/benchmark/ycsb-ycql.md
- docs/content/latest/benchmark/ycsb-ysql.md
Summary:
Improves the documentation by showing how to pass multiple IPs to the
benchmark.
Also gives a reference for the script that runs all the workloads and a
recommended value for the threadcount.
Reviewers:
Neha
> Improve YCSB documentation.

- docs/config.yaml
- docs/layouts/partials/footer_js.html
- docs/styles/_toc.scss
Turns out we were previously removing dom elements inside the Table of Contents. Reverting this JQuery command will fix the strange formatting on various pages.
I also added a margin-top to fix the header being too close to the ToC
Current
> [Docs] Fix strange formatting of ToC under latest version of Hugo

- docs/content/latest/deploy/public-clouds/aws/manual-deployment.md
- docs/layouts/_default/single.html
Also escape backticks used in code fence.
> [Docs] Fix empty table of contents from being shown underneath header

- docs/styles/_navbar.scss
Example of current docs homepage on phone
> [Docs] Fix top navbar from overflowing when viewing on Pixel 3a

- docs/config.yaml
Disables the conversion of double hyphens (`--`) used for flags into en dashes.
Affects all documentation use of flags (`--`). 
Disabling the "typographer" extension is similar to the previous "smartyPants = false" blackFriday setting.
> [docs] Disable typographer extension

- docs/layouts/_default/_markup/render-link.html
Adds new `render-link.html` to layouts > _markup > render-link.html that includes Render Hooks Templates (https://gohugo.io/getting-started/configuration-markup/#render-hook-templates) to open Markdown links that start with `http` to:
- open external link in a new tab
- display an "external link" icon
> [docs] Open external links in new tab and show external link icon

- docs/config.yaml
Previous blackFriday Markdown render engine handled header link IDs differently. The newer goldmark, by default, uses GFM (github) to auto-create IDs. That's likely better, but too many links would need to be updated to use the `github` behavior. This change preserves the old ID behavior for now, until we can update the links and teach everyone the differences.
For details, see https://gohugo.io/getting-started/configuration-markup#goldmark
> [docs] Change goldmark autoHeadingIDType to blackfriday

- docs/content/latest/contribute/core-database/build-from-src-centos.md
Needed for Python.h
Repros on vanilla CentOS 7 machine from GCP.
> Add python-devel to list of packages

- docs/content/latest/architecture/_index.md
Indented divs caused _index.md to show HTML code instead of generate subsections.
> [docs] Move indented div elements in

- docs/content/latest/contribute/_index.md
- docs/content/v2.0/contribute/_index.md
Change the links from archived repo to current location in the contribute.
> [Documentation] Fix links to docs and contributing 

- docs/layouts/partials/footer_js.html
This code does not generate a permalink icon but does make the headers clickable as long as `isTocNested` is true but not a number.
> [Docs][#4365] Make the default option for clickable queryHeaders to be h2 thru h6

- docs/content/latest/admin/yb-admin.md
- docs/content/latest/admin/yb-ts-cli.md
- docs/content/latest/admin/ysql-dump.md
- docs/content/latest/admin/ysql-dumpall.md
- docs/content/latest/admin/ysqlsh.md
- docs/content/latest/reference/configuration/default-ports.md
- docs/content/latest/reference/configuration/yb-master.md
- docs/content/latest/reference/configuration/yb-tserver.md
- docs/content/latest/reference/connectors/kafka-connect-yugabytedb.md
- docs/content/latest/reference/drivers/postgresql-jdbc-driver.md
- docs/content/latest/reference/drivers/spring-data-yugabytedb.md
- docs/content/latest/reference/drivers/yugabytedb-jdbc-driver.md
- docs/layouts/partials/footer_js.html
- Changes all `isTocNested` to use true instead of level numbers.
- Changes `footer_js.html` to show header-link icon. Adds to change in #4366.
> [docs] Update isTocNested and add h4 to h6 to queryHeaders

- docs/content/latest/api/ysql/datatypes/type_array/_index.md
- docs/content/latest/api/ysql/datatypes/type_array/array-constructor.md
- docs/content/latest/api/ysql/datatypes/type_array/array-of-domains.md
- docs/content/latest/api/ysql/datatypes/type_array/functions-operators/_index.md
- docs/content/latest/api/ysql/datatypes/type_array/functions-operators/array-agg-unnest.md
- docs/content/latest/api/ysql/datatypes/type_array/functions-operators/array-fill.md
- docs/content/latest/api/ysql/datatypes/type_array/functions-operators/array-position.md
- docs/content/latest/api/ysql/datatypes/type_array/functions-operators/array-remove.md
- docs/content/latest/api/ysql/datatypes/type_array/functions-operators/array-to-string.md
- docs/content/latest/api/ysql/datatypes/type_array/functions-operators/comparison.md
- docs/content/latest/api/ysql/datatypes/type_array/functions-operators/concatenation.md
- docs/content/latest/api/ysql/datatypes/type_array/functions-operators/properties.md
- docs/content/latest/api/ysql/datatypes/type_array/functions-operators/replace-a-value.md
- docs/content/latest/api/ysql/datatypes/type_array/functions-operators/slice-operator.md
- docs/content/latest/api/ysql/datatypes/type_array/functions-operators/string-to-array.md
- docs/content/latest/api/ysql/datatypes/type_array/literals/_index.md
- docs/content/latest/api/ysql/datatypes/type_array/literals/array-of-primitive-values.md
- docs/content/latest/api/ysql/datatypes/type_array/literals/array-of-rows.md
- docs/content/latest/api/ysql/datatypes/type_array/literals/row.md
- docs/content/latest/api/ysql/datatypes/type_array/literals/text-typecasting-and-literals.md
This PR is for @bllewell's brand new `type_array` tree under:
> `.../docs/content/latest/api/ysql/datatypes`
There are no changes to existing files. All changes are additions within the brand-new directory tree. In all, it's twenty `.md` files.
All the content has been carefully reviewed by @m-iancu and @stevebang. All their feedback has been acted upon.
**Note:** One small piece remains to be done. But it's entirely self-contained and its absence doesn't detract in any way from the value of the content that this PR covers. You'll see this as _"Coming soon"_ in the file `array-of-domains.md`. There's a reference to this in `.../type_array/_index.md`. Look for _"Sometimes, a ragged structure is useful"_. I didn't want to delay publishing my work to date. I'll create a new PR very soon for …
> Brand new "Array" doc under "APIs > YSQL > Data types"

- docs/content/latest/deploy/public-clouds/aws/cloudformation.md
These policies are required to create all the resources in the AWS account.
- Created a new user and gave it following policies
- `AWSCloudFormationFullAccess`
- `AmazonEC2FullAccess`
- `ssm:GetParameters`
- `s3:CreateBucket`
- `s3:PutObject`
- `s3:GetObject`
- Switched to that user using switch role / or one can login directly using credentials
- Tried creating a new stack from the UI as mentioned in the document.
- Using credentials of same user, tried stack creation from CLI.
Fixes #4336
> [docs] add missing policies to AWS CloudFormation

- docs/content/latest/contribute/core-database/build-from-src-macos.md
These docs may need to be modified slightly since 'brew install python@2' has reached EOL and been removed (https://github.com/Homebrew/homebrew-core/pull/49796). 
Maybe better solution to replace pip2 here: https://github.com/yugabyte/yugabyte-db/blob/master/build-support/common-build-env.sh ?
> replace 'brew install python@2' in Mac OS build

- docs/content/latest/deploy/docker/docker-swarm.md
- Added 'tasks' before the YB master service name in '--master_addresses' option to resolve communication issues between YB master containers.
- Removed extra hyphens from the initialize [YEDIS API](https://docs.yugabyte.com/latest/deploy/docker/docker-swarm/#yedis-api) command.
Tested Scenarios with this change -
- [APIs](https://docs.yugabyte.com/latest/deploy/docker/docker-swarm/#5-test-the-apis)
- [Test fault-tolerance with node failure](https://docs.yugabyte.com/latest/deploy/docker/docker-swarm/#6-test-fault-tolerance-with-node-failure)
- [Test auto-scaling with node addition](https://docs.yugabyte.com/latest/deploy/docker/docker-swarm/#7-test-auto-scaling-with-node-addition)
> Update docker-swarm docs to fix communication between masters

- docs/content/latest/reference/configuration/yb-master.md
- docs/content/latest/reference/configuration/yb-tserver.md
Discussed with @iSignal -- users need to make sure to use the same values on all `yb-master` and `yb-tserver` configurations.
> [docs] Add note about matching rpc_bind_addresses_ values on yb-master and yb-tserver

- docs/content/latest/deploy/multi-dc/2dc-deployment.md
- docs/static/files/determine_replication_lag.sh
> [DOCS] Add replication lag script

- ent/src/yb/tools/yb-admin_cli_ent.cc
- ent/src/yb/tools/yb-admin_client.h
- ent/src/yb/tools/yb-admin_client_ent.cc
Solved issue #4351 
The test output is attached at bottom.
> [docdb] Add flag for yb-admin list_snapshots to not show fully RESTORED entries #4351

- src/postgres/CMakeLists.txt
Summary:
postgres build fails on Ubuntu 20.04 (gcc version 9.3.0), due to
"-Werror=format-truncation" & "-Werror=stringop-truncation" warnings
being generated.
When $COMPILER_FAMILY is 'gcc8', these warnings are ignored. 'gcc8'
compiler family is only for gcc with version 8.*
Since Ubuntu 20.04, has gcc version 9.3.0, the $COMPILER_FAMILY is
'gcc' and these warnings are not ignored and hence they are treated
as errors and the build fails.
Fix is to add the check to postgres/CMakeLists.txt for gcc versions
9 & above.
Test Plan: `./yb_build.sh release` on Ubuntu 20.04
Reviewers:
Reviewed By:
Subcribers:
Differential Revision:
> [#4775] Fix build on Ubuntu 20.04 (gcc 9.3.0)

- cloud/grafana/README.md
- cloud/grafana/YugabyteDB.json
Original Issue: [Create a grafana dashboard for YugabyteDB](https://github.com/yugabyte/yugabyte-db/issues/4725)
Added grafana dashboard for YugabyteDB.
Tested with Grafana v6.0.0 and v7.0.3.
Fixes #4725
> Added grafana dashboard for YugabyteDB

- docs/content/latest/api/ycql/quick-start/kubernetes/explore-ycql.md
- docs/content/latest/deploy/kubernetes/multi-cluster/gke/helm-chart.md
- docs/content/latest/deploy/kubernetes/multi-zone/eks/helm-chart.md
- docs/content/latest/deploy/kubernetes/multi-zone/gke/helm-chart.md
- docs/content/latest/deploy/kubernetes/single-zone/aks/statefulset-yaml.md
- docs/content/latest/deploy/kubernetes/single-zone/gke/helm-chart.md
- docs/content/latest/deploy/kubernetes/single-zone/gke/statefulset-yaml-local-ssd.md
- docs/content/latest/deploy/kubernetes/single-zone/gke/statefulset-yaml.md
- docs/content/latest/deploy/kubernetes/single-zone/oss/helm-chart.md
- docs/content/latest/deploy/kubernetes/single-zone/oss/operator-hub.md
- docs/content/latest/deploy/kubernetes/single-zone/oss/rook-operator.md
- docs/content/latest/deploy/kubernetes/single-zone/oss/yugabyte-operator.md
- docs/content/latest/develop/kubernetes/run-sample-apps.md
- docs/content/latest/manage/enterprise-edition/migrate-to-helm3.md
- docs/content/latest/yedis/quick-start/kubernetes/test-yedis.md
- Changes `/home/yugabyte/bin/ycqlsh` to `ycqlsh` and `/home/yugabyte/bin/ysqlsh` to `ysqlsh` as both are in `PATH`
- Similar to https://github.com/yugabyte/yugabyte-db/pull/4267 updates all the commands to use `--` at correct place
- Updates all the commands to use absolute paths, ref: https://github.com/yugabyte/charts/pull/9
- Executed each type of command at least once
> [docs] update kubectl exec commands to use binary names directly

- docs/styles/_yuga_overrides.scss
Also increase the sidebar width slightly.
Wide screen example of fix:
Wide screen another example of fix:
Mobile view example of fix:
Mobile view another example of fix:
> [Docs][#4927] Fix sidebar toggle element from wrapping on longer article titles

- src/postgres/src/interfaces/libpq/fe-connect.c
Fixes #2484
- Before changes: 
```
./bin/ysqlsh -U xxx
ysqlsh: FATAL:  database "xxx" does not exis
```
- After changes:
```
./bin/ysqlsh -U xxx
ysqlsh (11.2-YB-2.1.8.0-b0)
Type "help" for help.
yugabyte=>
```
> [YSQL] Use default db as yugabyte irrespective of user name 

- docs/layouts/_default/_markup/render-link.html
Example of link with additional space on `/latest/api/ycql/dml_select`
Example of link with fixed formatting
> [Docs][#5074] Fix link rendering element to remove extra space when no external icon

- docs/content/latest/quick-start/create-local-cluster/docker.md
- docs/content/latest/reference/configuration/yb-master.md
- docs/content/latest/reference/configuration/yb-tserver.md
1. The default value for --server_broadcast_addresses in the code is an empty string.
@daniel-yb noticed the docs were incorrect.
2. The docker cmd line was changed to (a) remove --ui=false which is not necessary and (b) specify the volume by an explicit path "~/yb_data" instead of a volume name. (b) will help us locate the yugabyte log files for debugging in a more easy way. With the older volume specification, it is much harder to find the actual files on MacOS - see https://www.freshblurbs.com/blog/2017/04/16/inspect-docker-volumes-on-mac.html
> Modify docker quick start cmd line and clarify default value for server_broadcast_addresses in docs

- docs/content/latest/quick-start/install/macos.md
Fix missing space in command line that causes `$` to be copied.
> [docs] Fix missing space

- CONTRIBUTORS.md
- src/yb/consensus/raft_consensus.cc
- src/yb/consensus/raft_consensus.h
- src/yb/integration-tests/create-table-itest.cc
#3688 
Created Metric `is_leader` which tracks whether a tablet is leader/follower.
Plugged in the Metric into `raft_consensus.cc` to determine when the leader becomes leader and steps down from leader. 
The metric does so in the following way 
- Set the metric to 1 at the end of  func `RaftConsensus::BecomeLeaderUnlocked()` (Becomes a leader)
- Set the metric to 0 at the end of func `RaftConsensus::BecomeReplicaUnlocked()`(Steps down)
> Created Metric to track whether tablet is leader

- docs/content/latest/quick-start/explore/ysql.md
Hi YugaBytes team,
The sample query for a group by aggregation on `source` and summarizing `totoal_sales` is too slow for this size of rows.
I change the query and use Joins to speed up the query response time.
Best Regards
> [Docs] Fix slow query on quick-start page aggregations/view sections

- CONTRIBUTORS.md
- src/yb/master/master_main.cc
- src/yb/tserver/tablet_server_main.cc
prometheus-metrics: change default metric_node_name to hostname:port
Default value for GFLAG metric_node_name was "DEFAULT_NODE_NAME". Changed this to hostname:web_server_port.
<target>/prometheus-metrics now show new default value.
Summary:
Test (on localhost):
Command: `./bin/yb-ctl start --rf 1 `
On opening http://127.0.0.1:7000/prometheus-metrics, the `exported_instance` field shows hostname:webserverPort
Command with custom `metric_node_name`: `./bin/yb-ctl start --rf 1 --master_flags "metric_node_name=alpha:1"`
On opening http://127.0.0.1:7000/prometheus-metrics, the `exported_instance` field shows `alpha:1`
> [#4859] Change default value of flag metric_node_name to hostname:port

- docs/content/latest/api/ycql/type_datetime.md
Separated the syntax for the three types (date, time and timestamp) to make it clearer.
Closes: #5259
> Update docs for CQL time format

- docs/content/latest/contribute/core-database/checklist.md
Just adding a link to make it easier for new folks to navigate documentation.
> Add link for start local cluster page in contribution checklist

- docs/content/latest/api/ycql/_index.md
- docs/content/latest/api/ycql/type_number.md
- docs/content/latest/api/ysql/datatypes/type_numeric.md
From: https://www.postgresql.org/docs/11/datatype-numeric.html
fixes #5258
> [docs] fixed numeric precision

- .github/workflows/create-repository-dispatch.yml
Added repository dispatch event for the `yugbyte-db-action` repo on release event.
Whenever the `yugabyte-db` repo gets the new release, it triggers the test job on the `yugbyte-db-action` repo to test the new YugabyteDB docker image.
Related PR: https://github.com/yugabyte/yugabyte-db-action/pull/1/files
Fixes: https://github.com/yugabyte/yugabyte-db/issues/5098
> issue-5098: Added repository dispatch event for yugabyte-db-action

- docs/content/latest/deploy/kubernetes/clients.md
Added document to use TLS Secured YugabyteDB Cluster by Helm Charts
**Added two approaches to connect the TLS Secured YugabyteDB cluster -** 
1. Within Kubernetes Cluster.
2. Remotely.
Fixes: https://github.com/yugabyte/yugabyte-db/issues/4726
> Added document to use TLS Secured YugabyteDB Cluster by Helm Charts

- docs/content/latest/secure/tls-encryption/client-certificates.md
- Fix title — change "Client client certificates" to "Create client certificates".
- Expand explanation at the end of "Create client certificates" to give better clarification of what the client certificates are used for.
> [docs] Fix client certificates title and expand explanation at end of topic

- docs/layouts/partials/detect_version.html
- docs/layouts/partials/version_switcher.html
When on 'latest' or 'stable' version the textbox does not display what version number when the dropdown in minimized. Show the version number along with the version text.
> [Docs][#5637] Sidebar version indicator list displays the version number

- bin/yugabyted
- docs/content/latest/reference/configuration/yugabyted.md
Added env variables functionality in `yugabyted`
- Added env variables for YSQL: `YSQL_USER, YSQL_PASSWORD, YSQL_DB`
- Added env variables for YCQL: `YCQL_USER, YCQL_PASSWORD, YCQL_KEYSPACE`
-  Added docs to use environment variables
**Edited:**
-----
- Environment variables should exist with every execution to maintain idempotency. Authentication flags will be added to the tserver on the existence of environment variables.
- `yugabyted` won't execute environment variables based configuration snippet on `follower nodes`.
**Note:** 
- `bin/yugabyted status` command output will change with the existence of environment variables.
- For now, the default credentials haven't been removed.
**Test Plan:**
1. A single node cluster with and without environment variables.
2. Multinode cluster with …
> Added env variables functionality in yugabyted

- docs/content/latest/_index.html
- docs/content/latest/releases/earlier-releases/_index.md
- docs/content/latest/releases/releases-overview.md
- docs/content/latest/releases/versioning.md
- docs/content/latest/releases/whats-new/_index.md
- docs/content/latest/releases/whats-new/latest-releases.md
- docs/content/latest/releases/whats-new/stable-releases.md
- docs/content/stable/_index.html
Adds changes to the Releases section:
- Updates content of the pages: "Release versioning" and Supported and planned releases"
- Reorganizes the What's new to be a section with two pages:
- "What's new in the 2.3 latest release series"
- includes sections for "Notable features and changes" and "Release notes"
- "What's new in the 2.2 stable release series"
- includes sections for "Notable features and changes" and "Release notes"
- Notes added to top of default documentation pages for v2.2 and v2.3.
> [docs] Add releases updates

- docs/layouts/_default/list.html
- docs/layouts/_default/single.html
The version listed should be "Go to the latest version (2.3)" instead of 2.2
> [Docs][#5736] Fix version listed when on page that is not the latest

- docs/content/latest/manage/backup-restore/snapshots-ycql.md
@ddorian Please review these changes and see how to properly separate commands from outputs and use "postgresql" instead of "sql" for YSQL code blocks.
> [docs] Fix code blocks - separate command from output and change syntax highlighting from "sql" to "postgresql"

- bin/yugabyted
- Added relative path support for `--base_dir` flag in `yugabyted`.
1. With `--base_dir`
```sh
ubuntu@ip-172-31-12-205:~/yugabyte-2.3.1.0$ bin/yugabyted start --daemon=true --ui=false --base_dir=../base_db/ 
Starting yugabyted...
✅ System checks           
+--------------------------------------------------------------------------------------------------+
|                                            yugabyted                                             |
+--------------------------------------------------------------------------------------------------+
| Status              : Running                                                                    |
| Web console         : http://127.0.0.1:7000                                                      |
| JDBC                : …
```
> Added relative path support for base_dir in yugabyted

- architecture/design/online-index-backfill.md
The index backfill design doc is incorrect in saying that the backfill
write time can be a specific time in the past.  An exploit is described
in issue #5811.  Remove the option.  Fix some style issues as well.
> [arch] Fix write time in backfill design

- bin/yugabyted
- docs/content/latest/reference/configuration/yugabyted.md
- Added `--initial_scripts_dir` flag for initialization scripts functionality in `yugabyted`.
- Using the `--initial_scripts_dir` flag user can provide a directory from where yugabyted can read the scripts at the time of the first installation of the YB cluster.
- Format: 
- For YSQL - `.sql`
- For YCQL - `.cql`
- Scripts will be executed in the sorted name order.
**1. With initialization scripts**
- Create a directory and copy-paste the Northwind demo database files and named `1_northwind_ddl.sql` and `2_northwind_data.sql`.
- Use [this](https://docs.yugabyte.com/latest/quick-start/explore/ycql/#1-connect-with-ycqlsh) link to create demo CQL scripts.
- The directory will look like this:
```
ubuntu@ip-172-31-12-205:~/test-yugabyted/yugabyte-2.3.0.0$ ll ../initial-scripts/
total 352 …
```
> Added flag for initialization scripts in yugabyted

- docs/content/latest/benchmark/sysbench-ysql.md
Summary:
Right now the docs erroneously indicate that controlling the number of
tables is done using `num_tables` instead of `tables`. Correct it.
Reviewers:
Kannan
> [Docs] Sysbench: correct the argument for the number of tables.

- docs/content/latest/benchmark/tpcc-ysql/10000-wh/tpcc-ysql.md
Summary:
The total warehouses and the start warehouse id for the client uses the
wrong argument names.
Reviewers:
Rob
> [Docs] Remove errors from the TPCC documentation.

- .github/workflows/create-repository-dispatch.yml
We want to capture the case when a pre-release is changed to release.
https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#release
> Change github workflow to handle promoted pre-releases.

- cloud/grafana/YugabyteDB.json
With this change the dashboard can be loaded without any intervention. Earlier user had to select the datasource while importing the dashboard. Which made it impossible to automatically import the dashboard with an entry in grafana.ini or using a ConfigMap in Kubernetes.
-   Tired loading the dashboard and selected the correct datasource from the dropdown menu. It works with default as well, if there is a default Prometheus datasource present.
Ref: #5606
> Add datasource variable to the Grafana dashboard

- docs/content/latest/architecture/design-goals.md
- docs/content/stable/architecture/design-goals.md
- docs/content/v1.3/architecture/design-goals.md
- docs/content/v2.0/architecture/design-goals.md
- docs/content/v2.1/architecture/design-goals.md
- docs/layouts/_default/single.html
- docs/layouts/indexpage/single.html
This PR comments out the following code in `layouts/_default/single.html` and `layouts/indexpage/singlthml`  turns off the "previous" and "next" buttons because none of the pages have `hidePagination: true` (removed that from the only page in all branches that had that setting). 
```
```
Original commit that added this conditional logic is: https://github.com/yugabyte/yugabyte-db/commit/f379afc167d5ba5d6546d0ee333db7b3d155760f
Closes #5676.
Closes #4333.
> [docs] Disable previous and next buttons

- CONTRIBUTORS.md
- src/yb/tserver/tablet_server-test.cc
- src/yb/tserver/tserver-path-handlers.cc
Summary:
Added tablet ID in the tablet-consensus-status UI page
Added test in tserver_tablet_server-test to verify the same
Reviewers:
Rob
Screenshot:
> [docdb] Added tablet ID in the /tablet-consensus-status UI page

- docs/content/latest/deploy/kubernetes/single-zone/oss/operator-hub.md
- docs/content/latest/deploy/kubernetes/single-zone/oss/yugabyte-operator.md
- The following file names are changed as part of the SDK update (https://github.com/yugabyte/yugabyte-operator/pull/17), this
commit updates the related documentation pages.
- yugabyte_v1alpha1_ybcluster_crd.yaml =>
yugabyte.com_ybclusters_crd.yaml
- yugabyte_v1alpha1_ybcluster_cr.yaml =>
yugabyte.com_v1alpha1_ybcluster_cr.yaml
- yugabyte_v1alpha1_ybcluster_full_cr.yaml =>
yugabyte.com_v1alpha1_ybcluster_full_cr.yaml
Ref: #5987
> docs: update operator related pages according to file name changes

- bin/yb-docker-ctl
In b689b91587176212f0496832570a99eadaab2e19 the value of -minloglevel flag was set to 2 for yb-admin. The function wait_for_cluster runs `yb-admin … setup_redis_table` command and expects the output to have string 'created.'. This change modifies the minloglevel for that particular invocation of yb-admin so that the INFO level log statement expected by wait_for_cluster is printed.
The check is executed when creating a cluster. Tried creating a new cluster, works as expected.
> [yb-docker-ctl] wait_for_cluster: set minloglevel to 0 for yb-admin

- .github/workflows/create-repository-dispatch.yml
Add yb_release_train info to release dispatch github action. This
indicates which release branch should be updated in the downstream
repos affected by this release event.
> [CI] Add info to release dispatch for dependent repos.

- bin/yugabyted
The verification check is to resolve the below-mentioned issues:
- Update the password for the default user only if the password is different from the default.
- Without this check, the workflow will break for YCQL when someone sets only `YCQL_KEYSPACE` in env vars because yugabyted tries to update the password even if `YCQL_PASSWORD` doesn't exist.
Set `YCQL_KEYSPACE` in environment and executed the below command. It's working as expected.
```sh
export YCQL_KEYSPACE=testks
bin/yugabyted start --daemon=true --ui=false
```
> [yugabyted] don't update the password if it's same as default password

- docs/content/latest/explore/fault-tolerance/kubernetes.md
- docs/content/latest/quick-start/explore/kubernetes/explore-ysql.md
-   Changes the directory to `/home/yugabyte` before starting ysqlsh in the Kubernetes pod, this makes sure the instructions like `\i share/*.sql` work as expected.
-   Ref: <https://github.com/yugabyte/charts/pull/9> (current directory is different if Helm chart is being used.)
-   Update remaining kubectl exec commands according to <https://github.com/yugabyte/yugabyte-db/pull/4818>
-   Tried executing the modified commands to make sure they work as expected.
> [docs] explore-ysql: start ysqlsh from correct directory

- .github/workflows/yugabyted-test.yml
- scripts/yugabyted/test/yugabyted-test-runner.sh
- scripts/yugabyted/test/yugabyted-test.sh
- Added test script for `yugabyted`.
- Added Github action to run the test script on any push or pull request event if any update in any of the following scripts. (`yugabyted, yugabyted-test.sh, yugabyted-test-runner.sh`)
- Tested Github action: https://github.com/baba230896/yugabyte-db/actions/runs/316853512
- `yugabyted-test-runner.sh` calls `yugabyted-test.sh` internally and it's working as expected.
- `yugabyted-test-runner.sh --help`
```sh
ubuntu@ip-172-31-12-205:~$ ./yugabyted-test-runner.sh --help
Usage: yugabyted-test-runner.sh [<options>]
Options:
-h, --help
Print usage information.
-p, --package
YugabyteDB package.
-i, --image
YugabyteDB Docker image with tag.
-y, --yugabyted
Custom Yugabyted.
-P, --python
Provide Python interpreter.
-T, --testsuite
Provide Test Suite. Default: …
```
> [yugabyted] Test script and github action

- docs/content/latest/api/ysql/the-sql-language/statements/ddl_alter_sequence.md
- docs/content/latest/api/ysql/the-sql-language/statements/ddl_create_sequence.md
- docs/content/latest/reference/configuration/yb-tserver.md
The documentation is related to this Github issue: #6041.
The new tserver flag sets the cache size of sequence objects in YSQL.
This change is not included in v2.2.
3 pages have been updated:
1. Path: /latest/reference/configuration/yb-tserver/#ysql-sequence-cache-minval
New section is added for --ysql_sequence_cache_minval under YSQL yb-tserver flag page.
2. Path: /latest/api/ysql/the-sql-language/statements/ddl_create_sequence/#cache-cache
Added more description under create sequence cache clause section.
3. Path: /latest/api/ysql/the-sql-language/statements/ddl_alter_sequence/#cache-cache
Added more description under alter sequence cache clause section.
> [Doc][YSQL][#6041] Adding documentation related to TServer flag "ysql_sequence_cache_minval"

- .circleci/config.yml
Defines a minimal build, and then ignores it for all branches.
> Disable CircleCI builds on master branch.

- src/yb/common/partition.cc
- src/yb/gutil/strings/numbers.cc
- src/yb/gutil/strings/numbers.h
Summary:
Master UI make hash_split more readable
Fix: #4811
Screenshot:
> [docdb] master UI make hash_split more readable

- docs/content/latest/faq/yugabyte-platform.md
- docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
- docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/default.md
- docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
- docs/content/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md
- docs/content/latest/yugabyte-platform/install-yugabyte-platform/prerequisites.md
- docs/content/stable/faq/yugabyte-platform.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/default.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites.md
- docs/content/v1.3/deploy/enterprise-edition/install-admin-console/airgapped.md
- docs/content/v1.3/deploy/enterprise-edition/install-admin-console/default.md
- docs/content/v1.3/faq/enterprise-edition.md
- docs/content/v2.0/deploy/enterprise-edition/install-admin-console/airgapped.md
- docs/content/v2.0/deploy/enterprise-edition/install-admin-console/default.md
- docs/content/v2.0/faq/yugabyte-platform.md
- docs/content/v2.1/deploy/enterprise-edition/install-admin-console/airgapped.md
- docs/content/v2.1/deploy/enterprise-edition/install-admin-console/default.md
- docs/content/v2.1/deploy/enterprise-edition/install-admin-console/kubernetes.md
- docs/content/v2.1/faq/yugabyte-platform.md
Yugabyte support does not currently control the license issuing process,
so direct folks following along in the documentation to the form that
leads them down the right path.
> Direct Platform license requests to website form.

- docs/content/latest/reference/configuration/yb-tserver.md
- docs/content/latest/secure/_index.md
- docs/content/latest/secure/audit-logging/ycql.md
- docs/content/stable/reference/configuration/yb-tserver.md
- docs/content/stable/secure/_index.md
- docs/content/stable/secure/audit-logging/ycql.md
This PR adds:
- Audit logging page to Secure section (YugabyteDB Core)
- `--ycql_enable_audit_log` configuration flag to YB-TServer Core
- copies to both stable and latest
> [docs] Add YCQL audit logging to Secure section (YugabyteDB Core)

- src/yb/master/master-path-handlers.cc
Summary:
Removed the user and index tables section from the home-page
Modified this only for the master server
Reviewers:
Rob
Screenshot
> [#6116] Removed user and index tables from the master home page

- bin/yugabyted
- Added support for `- (hypen)` in YSQL and YCQL env vars.
1. Docker: Spinup YB in container using yugabyted with env vars
```bash
ubuntu@ip-172-31-12-205:~/test-yugabyted$ docker run -d -e YSQL_USER=some-user baba230896/yugabyte-db:6410 yugabyted start --daemon=false --ysql_enable_auth=true
Unable to find image 'baba230896/yugabyte-db:6410' locally
6410: Pulling from baba230896/yugabyte-db
524b0c1e57f8: Already exists 
b5318e0f4ff7: Already exists 
eb4537f79042: Already exists 
4ea65c2f4c06: Already exists 
3d1a7749a5b7: Already exists 
405aed9026de: Already exists 
9a6231b35012: Already exists 
Digest: sha256:3044d95ce15d12ad527ac67b30d87e2b9a944487f9f07a51c0832243a8f0992c
Status: Downloaded newer image for baba230896/yugabyte-db:6410 …
```
> [yugabyted] Added support of - in YSQL and YCQL env vars

- docs/content/latest/deploy/manual-deployment/system-config.md
Remove note about epel-release
If a node doesn't have internet access, then installing epel-release
won't be helpful, as it only provides access to epel and no packages
from it.
---
Add clarity to the ulimits section
Note that ulimits should be applied permanently
---
Update docs to indicate THP must be enabled
TCMalloc heavily relies on transparent hugepages, so we should document
that they must be enabled.
[TCMalloc tuning reference](https://github.com/google/tcmalloc/blob/master/docs/tuning.md)
> [Docs] Update system config documentation

- docs/content/latest/contribute/core-database/build-from-src-macos.md
Bison and flex do not need to be installed, since they are in thirdparty
dependencies.
> [docs] Update macos build requirements.

- docs/content/latest/secure/authentication/ldap-authentication.md
Previously:
```
./bin/yb-tserver --fs_data_dirs=/home/guru/Desktop/yugabyte/manual-data-dirs --ysql_hba_conf_csv='host all yugabyte 127.0.0.1/0 password,"host   all         all      0.0.0.0/0  ldap ldapserver=ldap.yugabyte.com ldapbasedn="dc=yugabyte, dc=com" ldapsearchattribute=uid"'
F1209 13:07:46.882664 15065 pg_wrapper.cc:346] Check failed: _s.ok() Bad status: Invalid argument (yb/yql/pgwrapper/pg_wrapper.cc:149): Failed to write ysql hba configuration: : Malformed CSV 'host all yugabyte 127.0.0.1/0 password,"host   all         all      0.0.0.0/0  ldap ldapserver=ldap.yugabyte.com ldapbasedn="dc=yugabyte, dc=com" ldapsearchattribute=uid"': 0 vs. 1
Fatal failure details written to /home/guru/Desktop/yugabyte/manual-data-dirs/yb-data/tserver/logs/yb-tserver.FATAL.details.2020-12-09T13_07 …
```
> [docs] fix ldap-config example

- docs/README.md
Removes reference to the config.yaml.sample. This was orginally removed
in commit ff5c536410f2e (#2169), but came back in 1ac5dba048d654.
> [docs] Update docs contribution quickstart

- docs/content/latest/secure/tls-encryption/client-to-server.md
- fix: rm trailing backtick in fenced codeblocks
- style: rm useless whitespace
> docs: fix client-to-server.md style

- bin/yugabyted
- Added `--stdout` functionality to `collect_logs` command of `yugabyted`
- Mentioning `--stdout` like this `bin/yugabyted collect_logs --stdout` will publish the `logs.tar.gz` on stdout. We can use the redirection operator to capture the output. So the final command will be like this to capture the logs from yugabyted in docker. `docker exec <container-id> bin/yugabyted collect_logs --stdout > yugabyted-logs.tar.gz`.
- Tested with Python v2 and v3.
- Working as expected in the local environment.
- Created the docker image and execute the above-mentioned command to get logs outside from the docker container.
```bash
ubuntu@ip-172-31-12-205:~/test-yugabyted/test$ docker run -d baba230896/yugabyte-db:6145 bin/yugabyted start --daemon=false …
```
> [yugabyted] Added --stdout to collect_logs for docker

- docs/content/latest/explore/transactions/_index.md
- docs/content/latest/yugabyte-platform/_index.md
Transactions section image
Page link of duplicated card: https://docs.yugabyte.com/latest/yugabyte-platform/
Fixed link
> [Docs] Fix section image in exploring Transactions page. Add correct page link

- managed/src/main/java/com/yugabyte/yw/controllers/SessionController.java
This change makes it possible to configure the value of log.override.path via application conf file.
The application.conf should have following entries to configure this.
```
play.logger.includeConfigProperties=true
log.override.path=/opt/platform-logs
```
The existing way to change the value continues to work i.e specifying flag `-Dlog.override.path=/opt/platform-logs`.
- Started platform with following snippet in the application.conf file.
```
play.logger.includeConfigProperties=true
log.override.path=/opt/yugaware_data/logs
```
The logs were created in that directory and the `/logs` endpoint was showing the logs.
- Started platform with `-Dlog.override.path=/opt/yugaware_data/logs`
The logs were created in the given directory and the `/logs` endpoint was showing the logs.
> [Platform] Use appConfig to get value of log.override.path

- bin/log_cleanup.sh
- This change expects that the core dump files are present in /var/yugabyte/cores. Does nothing if the directory doesn't exist.
~~- Deletes the files if they are taking up more than 100MB (default value).~~
- Deletes the files if they are taking up more than 10% of the disk (default value).
-   Installed YugabyteDB using Helm chart from https://github.com/yugabyte/charts/pull/41.
-   Created few large files in `/home/yugabyte/cores`.                                                                                                
-   Copied over the modified log_cleanup.sh to yb-cleanup container and executed it.                                                        
-   It was able to cleanup the core dump files mounted at `/var/yugabyte/cores` …
> Cleanup the core dump files as part of log_cleanup script

- architecture/design/docdb-automatic-tablet-splitting.md
Improve style of `docdb-automatic-tablet-splitting.md`.
> arch: improve tablet split doc style

- src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c
This patch separates out the metrics for transaction begin/commit/rollback statements. 
[**Note:** It doesn't break out PREPARE statements yet. The handling for that might require different logic, which I haven't been able to figure out yet. Might be best to separate the PREPARE handling into its own issue.]
**Testing:**
* I created a local YugabyteDB cluster using yb-ctl
* Used ysqlsh to create a sample table and perform of combination of begin, insert, commit, and rollback statements
* Visited the metrics page [http://127.0.0.1:13000/metrics] to ensure that these new metrics showed up and that their counters were incremented
**Sample output from page shown below:**
```
[
{
"type": "server",
"id": "yb.ysqlserver",
"metrics": [
{
"name": …
```
> Create separate metrics for BEGIN, COMMIT, and ROLLBACK statements in YSQL (#6486)

- src/yb/yql/cql/cqlserver/cql_processor.cc
for backwards compatibility with DataStax PHP driver (and possibly their cpp driver, which PHP driver relies on).
> allow OPTIONS in CQL protocol prior to AUTHENTICATE

- .github/workflows/create-repository-dispatch.yml
version.txt is a symlink to managed/version.txt is a symlink to managed/src/main/resources/version.txt.  Since git show doesn't resolve symlinks, we need to do it manually.
> Manually resolve version.txt symlink

- docs/content/latest/quick-start/install/linux.md
fixed type in Linux Qucikstart
$ tar xvfz yugabyte-2.5.0.0-linux.tar.gz && cd yugabyte-2.5.1.0/
to 
$ tar xvfz yugabyte-2.5.1.0-linux.tar.gz && cd yugabyte-2.5.1.0/
> fixed typo in version in Linux Qucikstart

- managed/ui/src/components/universes/UniverseDetail/UniverseDetail.js
- managed/ui/src/components/universes/UniverseDetail/UniverseDetailContainer.js
- managed/ui/src/components/universes/UniverseDetail/compounds/UniverseTaskList.jsx
Universe task was not showing if the user clicks on the task tab after creating a manual backup.
The issue happens because we are not fetching latest task. Added API call when the user clicks on universe task tab.
> [#6164] Manual backup of ysql task is not showing up in the universe tasks page

- src/yb/client/snapshot-txn-test.cc
- src/yb/integration-tests/master_path_handlers-itest.cc
- src/yb/integration-tests/mini_cluster.cc
- src/yb/master/master-path-handlers.cc
- src/yb/master/master-path-handlers.h
- src/yb/master/master.cc
- src/yb/master/master.proto
- src/yb/master/master_service.cc
- src/yb/master/ts_descriptor.h
- src/yb/server/hybrid_clock.h
- src/yb/tserver/heartbeater.cc
- src/yb/util/date_time.cc
- src/yb/util/date_time.h
- src/yb/util/timestamp.cc
- src/yb/util/timestamp.h
This patch adds a `/tablet-server-clocks` page to the yb-master UI.
The physical and hybrid times of the tablet server are sent as a part of the heartbeat mechanism.
**Testing**
- Created a local YugabyteDB cluster with using `yb-ctl --rf 3 start`
- Then verified that the patch worked by going to `http://127.0.0.1:7000/tablet-server-clocks`
Screenshots of the changes included below.
**Utilities View** - This view has a new panel for TServer Clocks.
**Tablet Server Clocks View** - This is the newly added view which displays the physical and hybrid times.
**Default Tablet Servers View** - This is the default tablet servers view, which should remain the same as before even after the re-factoring of code for the new view.
> #6772 display tserver clock information in yb-master UI

- docs/content/latest/benchmark/tpcc-ysql/_index.md
- Change the version to be downloaded for TPCC.
- Rectify an error in the configuration.
> [docs] Improve docs for TPCC.

- src/yb/util/net/net_util.cc
> [#6990] fixed:StripWhiteSpace() be doubly called

- docs/content/latest/reference/configuration/default-ports.md
- docs/content/stable/reference/configuration/default-ports.md
- docs/content/v2.0/reference/configuration/default-ports.md
- docs/content/v2.1/reference/configuration/default-ports.md
Adds additional default ports needed for firewall rules when setting up a cluster managed by YB Platform.
> Additional default firewall ports

- docs/content/latest/releases/whats-new/stable-releases.md
- docs/content/stable/releases/whats-new/stable-releases.md
Removing this entry from the stable (2.4) release notes at @ameyb's request.
> stable release notes: remove tablet splitting

- docs/.markdownlint.json
- docs/content/latest/quick-start/build-apps/_index.html
- docs/content/stable/quick-start/build-apps/_index.html
- docs/content/v2.2/quick-start/build-apps/_index.html
- docs/netlify.toml
Adding a redirect so all /version/releases/* point to /latest/releases/*
More of these to come, as we identify more redundant content that should be version-independent...
(Also a couple of small random fixes)
> netlify update: redirect release notes to latest

- docs/content/latest/releases/releases-overview.md
- docs/netlify.toml
Missed one occurrence of 2.2 as stable. At the same time, I realized the release-notes redirect wasn't working. This fixes both of those issues.
> docs: fix another version number and redirect

- managed/devops/bin/cluster_health.py
- managed/devops/bin/yb_backup.py
- managed/src/main/java/com/yugabyte/yw/commissioner/tasks/DestroyKubernetesUniverse.java
- managed/src/main/java/com/yugabyte/yw/commissioner/tasks/KubernetesTaskBase.java
- managed/src/main/java/com/yugabyte/yw/commissioner/tasks/subtasks/KubernetesCheckNumPod.java
- managed/src/main/java/com/yugabyte/yw/commissioner/tasks/subtasks/KubernetesCommandExecutor.java
- managed/src/main/java/com/yugabyte/yw/commissioner/tasks/subtasks/KubernetesWaitForPod.java
- managed/src/main/java/com/yugabyte/yw/common/KubernetesManager.java
- managed/src/main/java/com/yugabyte/yw/common/PlacementInfoUtil.java
- managed/src/main/java/com/yugabyte/yw/controllers/MetaMasterController.java
- managed/src/test/java/com/yugabyte/yw/commissioner/tasks/CreateKubernetesUniverseTest.java
- managed/src/test/java/com/yugabyte/yw/commissioner/tasks/DestroyKubernetesUniverseTest.java
- managed/src/test/java/com/yugabyte/yw/commissioner/tasks/EditKubernetesUniverseTest.java
- managed/src/test/java/com/yugabyte/yw/commissioner/tasks/UpgradeKubernetesUniverseTest.java
- managed/src/test/java/com/yugabyte/yw/commissioner/tasks/subtasks/KubernetesCommandExecutorTest.java
- managed/src/test/java/com/yugabyte/yw/common/KubernetesManagerTest.java
- managed/src/test/java/com/yugabyte/yw/common/PlacementInfoUtilTest.java
- managed/ui/src/components/config/PublicCloud/Kubernetes/AddRegionList.js
- managed/ui/src/components/config/PublicCloud/Kubernetes/CreateKubernetesConfiguration.js
These set of changes introduces a new key KUBENAMESPACE in the AZ config. Useful for the situations where the platform software does not have access to create, list or delete namespaces in the cluster.
When KUBENAMESPACE is present in the AZ config, the deployment in that AZ in done in that namespace only. Platform does not try to create namespace when creating the universe. It does not delete the namespace when destroying the universe.
Makes changes to the kubectl, helm commands from KubernetesManager.java to use namespace as well as nodePrefix. The value of nodePrefix and namespace can be same if the AZ does not have KUBENAMESPACE.
DestroyKubernetesUniverse now always deletes the volumes before deleting the namespace and uses release label selector to make sure the volumes being deleted …
> [Platform] [Kubernetes] Allow specifying namespace in the AZ config

- managed/src/main/java/com/yugabyte/yw/common/CertificateHelper.java
- managed/src/main/java/com/yugabyte/yw/controllers/CertificateController.java
- managed/src/test/java/com/yugabyte/yw/common/CertificateHelperTest.java
- managed/src/test/java/com/yugabyte/yw/controllers/CertificateControllerTest.java
**Summary:**
Currently, the backend performs no verification of the certs that the user uploads. This diff changes this behavior and adds a check on the backend to verify that the certificates/keys being uploaded to the platform are correctly formed.
**Testing:**
1. Try to upload self signed certificate with either invalid certificate file or key file.
2. Try to upload invalid CA certs.
In both the cases we should get an appropriate error message from the API response in browser console
Added the unit Tests as well.
**O/p of SBT tests**
**One test got failed, this is not related to my changes**
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1101) has been closed.
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
at …
> [#5594][Platform]:Handle invalid certs/keys correctly.

- managed/ui/src/components/universes/UniverseForm/AZSelectorTable.js
- managed/ui/src/components/universes/UniverseForm/ClusterFields.js
Description: The user was not able to edit the numbers of nodes from the AZ section while editing the universe.
> [#7024] Platform: Fixed edit number of nodes in AZ section

- docs/content/latest/manage/backup-restore/snapshot-ysql.md
- docs/content/stable/manage/backup-restore/snapshot-ysql.md
- docs/content/v2.2/manage/backup-restore/snapshot-ysql.md
use `ysql.schema.sql` to explain that this is a sql file with only the schema and reuse that filename in other commands
> [docs] fix commands in ysql-snapshots to make them consistent

- managed/src/main/java/com/yugabyte/yw/commissioner/tasks/subtasks/KubernetesCommandExecutor.java
- managed/src/test/java/com/yugabyte/yw/commissioner/tasks/subtasks/KubernetesCommandExecutorTest.java
The generated Helm overrides are recursively merged with the Helm overrides provided at the zone/region/provider level. Consider following blocks,
generated YAML:
```
resource:
master:
requests:
cpu: 2
memory: 2Gi
limits:
cpu: 2
memory: 2Gi
```
Zone level override:
```
resource:
master:
requests:
cpu: 650m
```
final merged YAML:
```
resource:
master:
requests:
cpu: 650m
memory: 2Gi
limits:
cpu: 2
memory: 2Gi
```
Arrays/lists are not merged, and are replaced directly. For Helm, if one has to change something from a list, they have to provide the whole list in their overrides YAML. We are following the same mechanism.
Fixes https://github.com/yugabyte/yugabyte-db/issues/5930
Set the 'Zone level override' block in the provider and tried creating a universe with instance …
> [Platform][Kubernetes] Merge the Helm overrides YAML recursively

- managed/devops/bin/cluster_health.py
When the argument cluster_payload is missing, the health check script
exits with 0 exit code (i.e. it silently fails). This happened with an
older version of this script where there was a mismatch with the
platform code and devops tar). As the platform code was new and it was
passing only one argument but the script was expecting two, it was
failing silently.
This change makes sure that this condition result in a non-zero return
code.
- Created a universe and checked if the health checks work as expected.
- When the health checks fail with non-zero code, the errors are shown
in the Alerts tab. (tried by commenting the Java code which adds
--cluster_payload argument to the script).
> [Platform] Exit health check with non zero code on invalid arguments

- managed/ui/src/components/config/ConfigProvider/DataCenterConfiguration.js
- managed/ui/src/components/config/ConfigProvider/providerConfig.scss
- managed/ui/src/components/config/PublicCloud/Kubernetes/CreateKubernetesConfiguration.js
- managed/ui/src/components/config/PublicCloud/Kubernetes/KubernetesProviderConfiguration.js
- managed/ui/src/config.js
This enables the Red Hat OpenShift tab in the Configs section. The
image registry for this provider is set to
registry.connect.redhat.com/yugabytedb/yugabyte.
**_Marking the provider as alpha._**
This is how it looks without any provider:
With one provider:
Fixes #7228, fixes #7225
- Created OpenShift, Tanzu, Kubernetes providers as follows
- Without specifying any registry.
- With a custom container registry.
- All these providers had correct default registries.
- These 6 providers were listed correctly under their own tabs.
> [#7228, #7225][Platform UI] Enable the OpenShift tab

- managed/devops/bin/cluster_health.py
- Previously the health-check verify the status using starting characters of output, but now it checks for the successful status string in the output of the command.
**Explaination**
In OpenShift, `ycqlsh` gives a warning `Cannot create directory at `/.cassandra`. Command history will not be saved` (https://github.com/yugabyte/yugabyte-db/issues/6522). The health check verifies the output using Python's `startswith` & expects the string `Connected to local cluster at …`, but in reality, we get a warning & then successful status message like shown below. As a result, it fails the health check.
```
Warning: Cannot create directory at `/.cassandra`. Command history will not be saved.
Connected to local cluster at yb-tserver-0.yb-tservers.yb-us-east4-a.svc:9042.
```
- Able to get health …
> [#7392][Platform] Fix the cqlsh healthcheck failures happening because of warnings in the output

- docs/content/latest/architecture/docdb-sharding/tablet-splitting.md
Enhancing limitations page for tablet splitting. Also adding GH links to all of them.
> [docs] Tablet splitting limitations

- docs/content/latest/admin/yb-admin.md
To get the deployment commands to show up in the right nav, bumped the deployment commands up one level from h4 to h3.
Also adjusted the mini-TOC for the commands section to reflect document order.
> [docs] adjust heading levels for deployment commands

- managed/ui/src/components/config/ConfigProvider/providerConfig.scss
- The UI shows the tab as beta instead of alpha.
> [Platform] Mark the OpenShift provider tab as beta

- docs/netlify.toml
Yes, it's technically a no-op, butit works to catch the images the `/:version` redirects are breaking!
(Netlify redirects are first-match-wins, so this stops the problem of the broken images on /latest/releases/releases-overview/ as well as others.)
> [docs] stop redirecting /images

- managed/ui/src/components/universes/NodeDetails/NodeConnectModal.js
Modified the UI to show the `kubectl` command for Kubernetes pods in Connect modal.
Able to use the `Connect` button to check the way to connect pod on K8s based YB universe.
fixes: https://github.com/yugabyte/yugabyte-db/issues/6681
> [#6681][Platform UI] Show kubectl command for Kubernetes pods in Connect modal

- managed/ui/src/components/universes/UniverseOverview/UniverseOverviewNew.js
When the new upgrade is available then for Pause universe the upgrade button is available which is not supposed to be the case.
If Universe is in a Pause state then no action supposed to be available apart from the Resume and Delete universe.
> [#7472] Platform: Hide upgrade action on Pause Universe

- docs/content/latest/reference/configuration/yb-tserver.md
- docs/content/stable/reference/configuration/yb-tserver.md
The default value for `ysql_disable_index_backfill` changed in YB 2.4 from `true` to `false`. Updating the docs to match.
> [Docs] change default: ysql_disable_index_backfill

- docs/content/latest/reference/configuration/default-ports.md
- docs/content/stable/reference/configuration/default-ports.md
- docs/content/v2.0/reference/configuration/default-ports.md
- docs/content/v2.1/reference/configuration/default-ports.md
- docs/content/v2.2/reference/configuration/default-ports.md
Commit 2cc084f introduced some extra ports, and the 93000 had a extra zero on it. This corrects that.
> [docs] Correct prometheus port from 93000 to 9300

- src/yb/rocksdb/util/histogram.cc
Summary:
rocksdb::HistogramImpl::Clear() does a memset() on
HistogramImpl::buckets_, which is std::atomic<uint64_t>, generates the
following warning,
‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct std::atomic<long unsigned int>’,
with no trivial copy-assignment; use value-initialization instead [-Werror=class-memaccess]
Make use of the set_bucket() to set all values to zero.
Test Plan:
`ybd --cxx-test rocksdb_histogram_test`
Reviewers:
Reviewed By:
> [#7603] rocksdb: Calling memset on atomic variable generates warning

- managed/src/main/java/com/yugabyte/yw/controllers/CloudProviderController.java
- managed/src/test/java/com/yugabyte/yw/controllers/CloudProviderControllerTest.java
Heading:
[#6460]Platform: Follow up change to fix blocker issue which was caused by https://github.com/yugabyte/yugabyte-db/pull/6948)
Description:
**mock** import was missing in the test file and same variable was declared twice in the file which lead to compile error during sbt  run.
RCA: This might be introduced when tried to resolve merge conflict on the github.
**Testing:**
**All the  sbt tests are getting passed except these two:**
Test com.yugabyte.yw.controllers.ApiDiscoveryControllerTest.testApiIndexWithAuthBadRoute failed: java.lang.AssertionError: expected:<404> but was:<200>,
error] Test com.yugabyte.yw.ConfigTest.singleKey(application.test.conf, test.expected.conf, envTest) [4] failed: junit.framework.AssertionFailedError: 
**sbt test o/p:**
[info] Test …
> [#6460]Platform: Follow up change to fix blocker issue which was caused by https://github.com/yugabyte/yugabyte-db/pull/6948)

- src/yb/master/master-path-handlers.cc
- src/yb/master/master.proto
- src/yb/master/master_service.cc
- src/yb/master/ts_descriptor.h
- src/yb/tserver/heartbeater.cc
- src/yb/tserver/heartbeater.h
In the tablet server, this change tracks the roundtrip time of a heartbeat to the yb-master leader. This information is sent on the subsequent heartbeat and displayed in the http://yb-master:7000/tablet-server-clocks view.
> #7199 track and display heartbeat roundtrip time from each yb-tserver in yb-master UI

- docs/content/latest/reference/configuration/yb-master.md
- docs/content/latest/reference/configuration/yb-tserver.md
References GH Issue#[7666](https://github.com/yugabyte/yugabyte-db/issues/7666). There was a code change recently to change the default value of `ysql_num_shards_per_tserver`. Documentation should be updated to reflect this.
> [DOC] Change documentation of the default value of ysql_num_shards_per_tserver

- docs/content/latest/explore/multi-region-deployments/asynchronous-replication-ycql.md
- docs/content/latest/explore/multi-region-deployments/asynchronous-replication-ysql.md
Resolves #7486 
This PR includes the correct commands required for Asynchronous replication in YSQL and YCQL. 
In specific, it addresses the interchanged commands for the same.
PREVIEW BUILD IS [HERE (YCQL)](https://deploy-preview-7692--infallible-bardeen-164bc9.netlify.app/latest/explore/multi-region-deployments/asynchronous-replication-ycql) and [HERE (YSQL)](https://deploy-preview-7692--infallible-bardeen-164bc9.netlify.app/latest/explore/multi-region-deployments/asynchronous-replication-ysql)
> [#7486][docs]  Commands to fix the YSQL and YCQL pages for Asynchronous replication.

- docs/README.md
resolves #7448 
This PR includes a command to ensure "xcode-select" is pointing to the right directory for Catalina.
> [#7448 ][docs] Additional step for macOS Catalina to ensure "npm ci" does not fail

- docs/content/latest/api/ysql/the-sql-language/statements/ddl_create_index.md
Add lots of useful information about YSQL online index backfill on the
YSQL CREATE INDEX page.  Include
- comparison between online and not online CREATE INDEX
- suggestions on common errors
and more.
[PREVIEW BUILD IS HERE](https://deploy-preview-7689--infallible-bardeen-164bc9.netlify.app/latest/api/ysql/the-sql-language/statements/ddl_create_index/#semantics)
> docs: add useful info on YSQL online CREATE INDEX

- docs/content/latest/deploy/kubernetes/multi-cluster/gke/helm-chart.md
The extra spaces break the helm chart.
> [Docs] Fix `masterAddress` lists in example Helm overrides

- docs/content/latest/api/ysql/datatypes/type_json/functions-operators/concatenation-operator.md
- docs/content/latest/api/ysql/datatypes/type_range.md
- docs/content/latest/api/ysql/the-sql-language/statements/dml_values.md
```
.../ysql/the-sql-language/statements/dml_values.md
.../ysql/datatypes/type_range.md
.../ysql/datatypes/type_json/functions-operators/concatenation-operator.md
```
`VALUES` statement: Fixed typo in "counter-example".
`range` data type: fixed typo in table formatting.
The array concatenation operator: fixed typo in code sample that shows priority rule when LHS and RHS _objects_ have colliding key-value pairs (i.e. same key for pairs).
> Three small bug fixes

- docs/content/latest/deploy/kubernetes/single-zone/oss/helm-chart.md
The default values for CPU / memory have changed. The text on this page
needs to be updated to reflect the new values.
> Update OSS helm chart docs to reflect new CPU / memory default values

- docs/content/latest/secure/_index.md
We had duplicate Audit Logging entries on [/latest/secure/](https://docs.yugabyte.com/latest/secure/). This fixes that.
> [docs] fix duplicate Audit Logging links on secure

- docs/content/latest/api/ysql/the-sql-language/statements/ddl_create_index.md
Replace mentions of flag `ysql_index_state_flags_update_delay_ms`
(actually supposed to be `TEST_ysql_index_state_flags_update_delay_ms`)
with GUC variable `yb_index_state_flags_update_delay`.
> [#7724] docs: switch to GUC var yb_index_state_flags_update_delay

- docs/content/latest/api/ysql/the-sql-language/statements/ddl_create_index.md
Alan pointed out that increasing the timeout flags was not working.  It
turns out that one of the flags was wrong.  Fix that.
> docs: fix YSQL backfill client timeout flag

- docs/content/latest/develop/ecosystem-integrations/_index.html
- docs/content/latest/develop/ecosystem-integrations/apache-kafka.md
- docs/content/latest/develop/ecosystem-integrations/apache-spark/scala.md
- docs/content/latest/develop/ecosystem-integrations/janusgraph.md
- docs/content/latest/develop/ecosystem-integrations/kairosdb.md
- docs/content/latest/develop/ecosystem-integrations/metabase.md
- docs/content/latest/develop/ecosystem-integrations/presto.md
- docs/content/latest/develop/ecosystem-integrations/spring.md
Having inputs and outputs in the same code block renders the copy button useless.
It'll take a fair while to address this across the docs, but this is a start for the ecosystem integrations section.
Using Janusgraph as a first target...
**Deploy preview**: https://deploy-preview-7981--infallible-bardeen-164bc9.netlify.app/latest/develop/ecosystem-integrations/janusgraph/
> [docs] break ecosystem snippets into in+out

- managed/src/main/java/com/yugabyte/yw/commissioner/tasks/subtasks/cloud/CloudAccessKeySetup.java
- managed/src/test/java/com/yugabyte/yw/commissioner/tasks/CloudBootstrapTest.java
**Heading:[**
#6447]Platform: Remove cloud accessKey after cloud provider is deleted
After deleting the cloud provider we don't clean up the platform generated ssh
accessKey which can lead to universe creation failures for the new cloud provider.
**Runtime error: KeyPair already exists yb-dev-aws-cloud-key**
Now, we are making sure unique ssh key gets generated while creating the
provider
**Testing:**
1. Try to create AWS cloud provider by giving any name
2. SSH key should include providerUUID
eg:  i.e yb-admin-aws87db5f86-b61a-42a7-9eee-9d600c18bb04-key
> [#6447]Platform: Remove cloud accessKey after cloud provider is deleted

- managed/ui/src/components/universes/UniverseForm/ClusterFields.js
Description: Disabling node-to-node TLS sets the client-to-node TLS to be disabled, but this field was not updating payload form value, it was just done for UI.
Scenario: After this fix, I tried creating Universe for the following scenario.
1. Keeping node-to-node and client-to-node set to true (**Default**)
2. Keeping node-to-node enabled and client-to-node to be disabled.
3. Keeping node-to-node and client-to-node set to false.
> [#7959] Platform: Fixed Universe Failure when node-to-node TLS is disabled. 

- docs/content/latest/reference/configuration/yugabyted.md
- docs/content/latest/yugabyte-platform/configure-yugabyte-platform/_index.md
- docs/content/stable/reference/configuration/yugabyted.md
- docs/content/stable/yugabyte-platform/configure-yugabyte-platform/_index.md
- docs/content/v2.2/reference/configuration/yugabyted.md
One broken link in stable, and one link that _will_ break in latest when we make a new stable... This fixes both.
Click the "Configure the Cloud Provider" boxes for each of these in the preview build, and make sure they go to the right place (AWS config).
[/**stable**/yugabyte-platform/configure-yugabyte-platform/](http://deploy-preview-8008--infallible-bardeen-164bc9.netlify.app/stable/yugabyte-platform/configure-yugabyte-platform/)
[/**latest**/yugabyte-platform/configure-yugabyte-platform/](http://deploy-preview-8008--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/configure-yugabyte-platform/)
> [docs] fix broken links to "configure the cloud provider"

- docs/content/latest/explore/ysql-language-features/_index.md
- docs/content/latest/explore/ysql-language-features/cursor.md
This doc needs a technical review to make sure we don't mention something that's not yet supported in YSQL.
@nocaway  
Would the users need to use syntax different from what's in Postgresql to use our workaround for FETCH NEXT/FORWARD: [5f96f45](https://github.com/yugabyte/yugabyte-db/commit/5f96f45dc21280bb2ab4c4551a899c77e11fc405) ?
**Build preview** is here: https://deploy-preview-7999--infallible-bardeen-164bc9.netlify.app/latest/explore/ysql-language-features/cursor/
> [doc] PR for Add content for CURSOR in YSQL (Doc7753)

- docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
- Remove note about logging out of admin account
- The note was there because the whole section of finding Availability Zones was at some other place.
- Use different word than IP address
- There are setups where you don't have an IP address for a LoadBalancer service, instead you get a hostname. Changing the word IP address with location for now, I wasn't able to find anything better than that. URI can be used but it will add some confusion.
-  Add a note about admin and normal user accounts
> [docs][OpenShift] Use different word than IP address and add clarification about admin user

- managed/src/main/java/com/yugabyte/yw/commissioner/tasks/UniverseTaskBase.java
- managed/src/test/java/com/yugabyte/yw/commissioner/tasks/UniverseTaskBaseTest.java
**Description:** Once we delete the onpremis universe, we have to clear the node instance so that we can use the node to create another universe.
**Testing: :**
1. Add instance under onpremis
2. Created the universe with the instance (should get failed)
3. Delete the universe.
4. Used the same instance to create another universe.
5. The change should not affect anything else.
**Note**: Have not tested in local for 2.4 as the changes are working in master.
**sbt test**
```[info] Passed: Total 1127, Failed 0, Errors 0, Passed 1123, Skipped 4```
**sbt compile**
```[info] Passed: Total 1127, Failed 0, Errors 0, Passed 1123, Skipped 4
mahendra@mahendra-HP-ZBook-14u-G5:~/yugabyte-main/yugabyte-db/managed$ sbt compile
[info] Loading project definition from …
```
> [#6758][Platform] Unable to reuse On-premise instance incase previouse universe failed / deleted

- managed/devops/roles/install_backup_util/defaults/main.yml
- managed/devops/roles/install_backup_util/tasks/install-gsutil.yml
- Refactored the `gsutil` installation approach, previously it was installed using `google-cloud-sdk` & now it's installed using standalone binary.
- Spin up the YB universe using YW on AWS.
fixes: https://github.com/yugabyte/yugabyte-db/issues/7280
> [YW] Replaced google-cloud-sdk installation with gsutil installation

- managed/src/main/java/com/yugabyte/yw/cloud/CloudAPI.java
- managed/src/main/java/com/yugabyte/yw/cloud/aws/AWSCloudImpl.java
- managed/src/main/java/com/yugabyte/yw/controllers/CloudProviderController.java
- managed/src/main/java/com/yugabyte/yw/forms/CloudProviderFormData.java
- managed/src/test/java/com/yugabyte/yw/controllers/CloudProviderControllerTest.java
- managed/ui/src/actions/cloud.js
- managed/ui/src/components/config/PublicCloud/ProviderConfigurationContainer.js
**Heading:**
[#6460]Platform: Preflight checks for cloud provider configuration
We need to validate the AWS credentials at the time of cloud provider configuration
**Summary**
This change had already been merged into the master but due to itest change failure, we had to revert it back
Already merged PR: https://github.com/yugabyte/yugabyte-db/pull/6948/
Reverted PR: https://github.com/yugabyte/yugabyte-db/pull/7712/
Now we have incorporated the changes required in itest script so we should be good now.
i-test changes PR:  https://phabricator.dev.yugabyte.com/D11540
**Test Plan:**
We can test this by passing invalid aws access key or secret key while configuring AWS cloud provider.
**SBT Test results:**
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource …
> [#6460] Platform: Preflight checks for AWS cloud provider configuration

- docs/content/latest/explore/query-1-performance/_index.md
- docs/content/latest/explore/query-1-performance/pg-stat-activity.md
Resolves #6519 
The document contains information about using "pg_stat_activity" to run different live query patterns and analyze them for different purposes.
Build preview is here: https://deploy-preview-8358--infallible-bardeen-164bc9.netlify.app/latest/explore/query-1-performance/pg-stat-activity/
> [#6519][docs] Add document to analyze queries with pg_stat_activity.

- docs/content/latest/releases/releases-overview.md
Changing the v2.3 link in the support timeline to point at the right place
> [docs] 404 fix

- managed/ui/src/components/queries/SlowQueries.js
**Description:** 
When the Universe is in a `paused state` the users will not perform any actions for that respective universe. But for now, when the users go under the `Queries tab` they can perform the actions like `query monitoring and reset stats`. This is not supposed to happen.
**Test Plan:**
1. Go to the universe page.
2. Hit the Action button next to connect and hit Pause universe.
3. Once the universe is paused then hit the Queries tab for that universe.
4. Click on Show queries. 
5. Check whether Reset stats and Query Monitoring is present or not.
If the above-mentioned buttons are not present then it's working fine. Check for both the Universes:
1. For Pasued Universe - Buttons are not supposed to be there on the UI.
2. For Normal Universe(Ready State) - Buttons are supposed to …
> [#8324] [Platform] Disabled the query monitoring under Queries tab.

- .github/workflows/build.yml
- .github/workflows/managed-java-checks.yaml
Run an `sbt javafmtCheck` on PRs and pushes.
Also disable the C++ build for managed sub directory.
Test Plan: https://github.com/iSignal/yugabyte-db/actions/runs/875999659
> Add format check for Java code under managed

- managed/ui/src/components/config/Storage/AwsStorageConfiguration.js
- managed/ui/src/components/config/Storage/StorageConfiguration.js
Backup -> Edit configuration. I edited something in the AWS key but I clicked cancel, though the value is not saved, the values I edited are still showing up. Once I reload the page, the edited values are gone and original (saved) values are shown, which is correct. It's good to reload the original values if cancel clicked rather than showing the edited values.
**Test Plan:**
1. Click on config from the side nav.
2. Go to Backup-> AWS.
3. Create a new Backup config.
4. Hit the Edit configuration button.
5. Change some values and hit the Cancel button.
Check if it's restoring the original values or not.
> [#8620] [Platform] [Backport-2.4] Reset the values on cancel.

- managed/ui/src/components/config/Storage/AwsStorageConfiguration.js
- managed/ui/src/components/config/Storage/StorageConfiguration.js
Backup -> Edit configuration. I edited something in the AWS key but I clicked cancel, though the value is not saved, the values I edited are still showing up. Once I reload the page, the edited values are gone and original (saved) values are shown, which is correct. It's good to reload the original values if cancel clicked rather than showing the edited values.
**Test Plan:**
1. Click on `config` from the side nav.
2. Go to Backup-> AWS.
3. Create a new Backup config.
4. Hit the Edit configuration button.
5. Change some values and hit the Cancel button.
Check if it's restoring the original values or not.
> [#8620] [Platform] [Backport-2.6] Reset the values on cancel.

- managed/src/main/java/com/yugabyte/yw/common/kms/util/AwsEARServiceUtil.java
- managed/src/main/java/com/yugabyte/yw/controllers/CustomerTaskController.java
- managed/src/main/resources/reference.conf
- managed/src/test/java/com/yugabyte/yw/controllers/CustomerTaskControllerTest.java
Description:
We could make the tasks UI more functional by adding a LIMIT 2000 to our tasks DB query, so we don't end up with a spinning task UI for Platform instances that accumulate many tasks over time.
Currently it is set to 2000 in reference.conf.
Original Commit: [https://github.com/yugabyte/yugabyte-db/pull/7477] (57d835e9c13c92cf2feaaa716d5f08e6cdef9442)
Test Plan:
Updated reference.conf to 20.
Verified whether the API returning only 20 entries or not.
Also verified the working endpoint of a particular task.
Verified by creating 10 + tasks and verified pagination in UI too.
sbt test
```	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser$WrappingDatasource.getConnection(DefaultEbeanConfig.java:153)
at …
```
> [#6945] [Platform] [Backport-2.6] Add limit to customer task API.

- managed/src/main/java/com/yugabyte/yw/controllers/CustomerTaskController.java
- managed/src/main/resources/application.test.conf
- managed/src/main/resources/reference.conf
- managed/src/test/java/com/yugabyte/yw/controllers/CustomerTaskControllerTest.java
Description:
We could make the tasks UI more functional by adding a LIMIT 2000 to our tasks DB query, so we don't end up with a spinning task UI for Platform instances that accumulate many tasks over time.
Currently it is set to 2000 in reference.conf.
Original Commit: [https://github.com/yugabyte/yugabyte-db/pull/7477] (57d835e9c13c92cf2feaaa716d5f08e6cdef9442)
Test Plan:
Updated reference.conf to 20.
Verified whether the API returning only 20 entries or not.
Also verified the working endpoint of a particular task.
Verified by creating 10 + tasks and verified pagination in UI too.
sbt test:
```info] Test com.yugabyte.yw.cloud.UniverseResourceDetailsTest.testAddPriceWithRemovingOneNode started
[info] Test run finished: 0 failed, 0 ignored, 7 total, 1.009s
[info] Passed: Total 1131, Failed …
```
> [#6945] [Platform] [Backport-2.4] Add limit to customer task API.

- managed/ui/src/components/config/Storage/AwsStorageConfiguration.js
- managed/ui/src/components/config/Storage/StorageConfiguration.js
When the users will hit the `Edit configuration` button from a particular backup config then the other tabs also enables the editing even though you clicked it or not. So it shouldn't happen. Edit config will only allow editing the backup config of the respective tab. 
**Test Plan:**
1. Click config from the side nav.
2. Hit the backup tab and create backup configs for the respective tabs.
3. Then go to one of the tabs and hit the edit-config button.
4. Without saving it or cancelling it go to another tab and see if edit-config is available or not. If yes then it's a bug otherwise we're good to go.
> [#8611] [Platform] [Backport-2.6] Enable edit backup configuration for the active tab only.

- managed/ui/src/components/config/Storage/AwsStorageConfiguration.js
- managed/ui/src/components/config/Storage/StorageConfiguration.js
When the users will hit the Edit configuration button from a particular backup config then the other tabs also enables the editing even though you clicked it or not. So it shouldn't happen. Edit config will only allow editing the backup config of the respective tab.
**Test Plan:**
1. Click config from the side nav.
2. Hit the backup tab and create backup configs for the respective tabs.
3. Then go to one of the tabs and hit the edit-config button.
4. Without saving it or cancelling it go to another tab and see if edit-config is available or not. If yes then it's a bug otherwise we're good to go.
> [#8611] [Platform] [Backport-2.4] Enable edit backup configuration for the active tab only. 

- src/yb/master/backfill_index.cc
- src/yb/master/backfill_index.h
I went over the changes, and I observed that their might've been some inconsistencies with my approach. I added a helper method instead which would retrieve the index table names instead (as the field ```requested_index_names_``` might not necessarily contain only the indexes we are currently backfilling).
> [#8619] Log index table name instead of index id

- .github/workflows/yugabyted-test.yml
Prior change (b10270234f10e55a8fa012ea924e9db5beb1101d) added file
exemptions to the workflow that are not allowed to be mixed with paths
statements.
> github workflow: Revert github workflow error.

- managed/src/main/java/com/yugabyte/yw/models/Backup.java
Whenever we create any scheduled backup, config API starts getting failed.
Scenario:- 
1. Configure Storage
2. Add sample data
3. Create a scheduled backup
4. Try to access the universe backup page/ Config page.
Both pages started getting failed. 
Debug and got to know very minor issue. One place we had used toString() for jsonNode.
tested and working fine.
Testcase report:- 
[info] Test run finished: 0 failed, 0 ignored, 7 total, 0.134s
[info] Passed: Total 1359, Failed 0, Errors 0, Passed 1355, Skipped 4
[success] Total time: 2087 s (34:47), completed 7 Jun, 2021 3:22:24 PM
> [#7349]Change ToString to TextVlue for json node

- managed/build.sbt
- managed/src/main/java/com/yugabyte/yw/commissioner/tasks/subtasks/KubernetesCommandExecutor.java
- managed/src/main/java/com/yugabyte/yw/common/KubernetesManager.java
- managed/src/main/java/com/yugabyte/yw/controllers/CloudProviderController.java
- managed/src/main/resources/application.test.conf
- managed/src/main/resources/swagger.json
- managed/src/main/resources/v1.routes
- managed/src/test/java/com/yugabyte/yw/common/KubernetesManagerTest.java
- managed/src/test/java/com/yugabyte/yw/controllers/CloudProviderControllerTest.java
-   This API tries to fetch the details which can be used to pre-fill the data during Kubernetes provider creation (should work on OpenShift or Tanzu as well). The returned JSON is similar to what we use for the create call. Please refer this issue for more details: https://github.com/yugabyte/yugabyte-db/issues/7394
-   Use blank string for KUBECONFIG if kubeconfig file is not provided. This allows us to in-cluster credentials (ServiceAccount) when running in the same cluster as of the target cluster. Can be used to simplify the current flow later, we won't need a separate kubeconfig in that case.
-   Finds out the region and AZ based on node annotations.
-   Takes the pull secret name and the storage class name from app config.
-   Ran platform inside Kubernetes, curl …
> [Platform] Add API for Kubernetes provider configuration discovery

- managed/build.sbt
- managed/src/main/java/com/yugabyte/yw/controllers/CloudProviderController.java
This is a follow up change from https://github.com/yugabyte/yugabyte-db/pull/8371
- Ran platform inside Kubernetes, curl the API, it returns the expected JSON.
> [Platform] Remove commons-collections4 and use guava instead

- managed/ui/src/components/config/Storage/StorageConfiguration.js
On the 2.6 portal, the edit configuration button under cloud provider config makes editing available alternatively.
**Test Plan:**
1. log in 2.6 portal
2. Go to Configs -> Backup -> Amazon S3
3. Click on edit Configuration
4. Click on Cancel without making any changes
5. Click on Edit configuration again
6. The fields are editable. If yes then we're good to go.
> [#8809] [Platfrom] [Backport-2.6] Editing fields is only available alternatively when we click 'Edit Configuration'.

- docs/content/latest/architecture/docdb-replication/async-replication.md
- docs/content/latest/architecture/docdb-replication/change-data-capture.md
- docs/content/latest/deploy/multi-dc/async-replication.md
Add a missing alias since we changed the name of the file. Also catch any remaining links to the old name.
http://deploy-preview-8966--infallible-bardeen-164bc9.netlify.app/latest/deploy/multi-dc/async-replication
http://deploy-preview-8966--infallible-bardeen-164bc9.netlify.app/latest/deploy/multi-dc/2dc-deployment (make sure this redirects to async-replication)
> [docs] add missing alias to async-replication

- managed/ui/src/components/config/Storage/StorageConfiguration.js
On the 2.4 portal, the edit configuration button under cloud provider config makes editing available alternatively.
Test Plan:
1. login 2.4 portal
2. Go to Configs -> Backup -> Amazon S3
3. Click on edit Configuration
4. Click on Cancel without making any changes
5. Click on Edit configuration again
6. The fields are editable. If yes then we're good to go.
> [#8809] [Platfrom] [Backport-2.4] Editing fields is only available alternatively when we click 'Edit Configuration'.

- docs/content/latest/secure/audit-logging/audit-logging-ysql.md
Some typos and formatting issues (per Kannan, via slack). 
Also the whole file is kind of messed up.
Doc build preview: https://deploy-preview-8946--infallible-bardeen-164bc9.netlify.app/latest/secure/audit-logging/audit-logging-ysql/
> [doc] Fixed typos and formatting issues in Configure Audit Logging in YSQL 

- docs/content/latest/develop/best-practices-ycql.md
The "example usage" text in the "use partition_hash for large table scans" section of the YCQL best practices page did not contain the correct link. This PR fixes that.
> fixed partly broken link to partition_hash page in the YCQL best practices page "use partition_hash for large table scans" section

- docs/content/latest/manage/backup-restore/point-in-time-recovery.md
Google is still indexing the old addresses of the PITR pages under /latest/manage. This will avoid 404s. Try the deploy preview link (`point-in-time-restore-ysql`) to verify that you get redirected to `point-in-time-recovery`.
@netlify /latest/manage/backup-restore/point-in-time-restore-ysql/
> [docs] add aliases to old PITR pages

- docs/content/latest/api/ysql/_index.md
- docs/content/latest/api/ysql/datatypes/type_datetime/_index.md
- docs/content/latest/api/ysql/datatypes/type_datetime/conceptual-background.md
- docs/content/latest/api/ysql/datatypes/type_datetime/date-time-data-types-semantics/type-interval/_index.md
- docs/content/latest/api/ysql/datatypes/type_datetime/date-time-data-types-semantics/type-interval/custom-interval-domains.md
- docs/content/latest/api/ysql/datatypes/type_datetime/date-time-data-types-semantics/type-interval/interval-utilities.md
- docs/content/latest/api/ysql/datatypes/type_datetime/intro.md
- docs/content/latest/api/ysql/datatypes/type_datetime/timezones/extended-timezone-names/_index.md
- docs/content/latest/api/ysql/datatypes/type_datetime/timezones/extended-timezone-names/canonical-no-country-no-dst.md
- docs/content/latest/api/ysql/datatypes/type_datetime/timezones/extended-timezone-names/unrestricted-full-projection.md
- docs/content/latest/api/ysql/datatypes/type_datetime/timezones/recommendation.md
- docs/content/latest/api/ysql/datatypes/type_datetime/timezones/ways-to-spec-offset/name-res-rules/helper-functions.md
- docs/content/latest/api/ysql/datatypes/type_datetime/timezones/ways-to-spec-offset/name-res-rules/rule-1.md
- docs/content/latest/api/ysql/datatypes/type_datetime/timezones/ways-to-spec-offset/name-res-rules/rule-2.md
- docs/content/latest/api/ysql/datatypes/type_datetime/timezones/ways-to-spec-offset/name-res-rules/rule-3.md
- docs/content/latest/api/ysql/datatypes/type_datetime/timezones/ways-to-spec-offset/name-res-rules/rule-4.md
_index is now just the table of contents. Fixed some broken links.
> Split off .../type_datetime/intro.md from ~/_index.md.

- managed/ui/src/components/universes/NodeDetails/NodeConnectModal.js
**Issues:** 
- The Connect button wasn't working for the Kubernetes-based universe due to the unavailability of access keys. It works fine if the YW has one k8s based universe & a VM-based cloud-config provider (GCP, AWS). The condition checks for the following parameters - access keys & node IPs.
- YW appends the zone name with pod name in multi-zone deployment so the kubectl command created that has appended name. If the user copies it & runs then it won't work.
**Fix:** 
- Conditional check has been updated & now it has one more condition to check the universe type.
- Extract pod name from the appended nodeName.
- Spin up the YW UI locally & connected the local UI to the YW container deployed on the GKE cluster.
fixes: https://github.com/yugabyte/yugabyte-db/issues/6681
> [Platform UI] Fixed connect button for K8s-based universes.

- managed/devops/opscli/ybops/data/preflight_checks.sh
- The existing check for internet connectivity runs a "ping" check to "yugabyte.com".
- This can be problematic since enterprise customers often block icmp, even when there is internet access.
- The new check uses "/dev/tcp" to try to reach "yugabyte.com" on port 443. This was chosen in favor of netcat since there's no assurance that netcat will be present on the system.
> [Platform][Issue #9103] Update "preflight_checks.sh" from ping to tcp check.

- docs/content/latest/releases/whats-new/stable-release.md
Adding the release notes for 2.6.0.0.
NOTE! Another PR (#9155) does the actual moving-around of the docs, and updating version numbers everywhere.
@netlify /latest/releases/whats-new/stable-release/
> [docs] 2.6.0.0 release notes

- .github/workflows/yugabyted-test.yml
Add a path exclusion to yugabyted-test.yaml so changes in the docs tree don't trigger this long job.
> exclude docs/** from yugabyted-test github action

- docs/content/latest/yugabyte-platform/security/security-checklist-yp.md
> [docs] Update security-checklist-yp.md

- docs/content/latest/troubleshoot/nodes/check-logs.md
> [docs] explain logs location when using `docker` & `yugabyted` cli

- managed/src/main/resources/cloudFeatureConfig.json
- managed/src/main/resources/ossFeatureConfig.json
- managed/src/main/resources/readOnlyFeatureConfig.json
- managed/ui/src/components/universes/UniverseDetail/UniverseDetail.js
Description
--
Disable "Pause Universe" operation for Read-Only users in YB-PLATFORM
Changes
--
On a high level
1. Since the READONLY user should have the `Pause Universe` disabled, ensure to have the `Available` property for the element
2. Ensure in the `readOnlyConfig.json`, set "pausedUniverse" to disabled and in other configs set it to "enabled", this is to ensure only readOnly users should have it disabled and not other users
> (YUGA-9261) - Disable "Pause Universe" operation for Read-Only users in YB-PLATFORM

- .github/workflows/yb-ctl-test.yml
yb-ctl workflow was being run for updates to the docs pages for it.
> Ignore docs changes for yb-ctl  GH action

- docs/content/latest/benchmark/tpcc-ysql/10000-wh/tpcc-ysql.md
- docs/content/latest/integrations/liquibase.md
Sonal Agarwal  3:12 AM via slack:
@doc-team There is a typo in tpcc benchmark docs :  For 10000 warehouses, in the “TPC-C Benchmark Results” section,  in the command to merge results, the command line option should be “merge-results”,  but it is “merge_results”
https://docs.yugabyte.com/latest/benchmark/tpcc-ysql/#10000-wh
> [docs] PR to Fix an error in one of benchmarking files

- CONTRIBUTORS.md
- src/yb/tools/ts-cli.cc
There was no notification for completion of all tablets compaction previously. 
This PR adds 2 print statements following the completion of compaction for single tablet and all tablets.
> [#9430] Added success message for all tablets and single tablet compaction

- .gitignore
- docs/content/latest/releases/earlier-releases/v2.1.8.md
- docs/content/v1.3/introduction.md
- docs/content/v2.0/deploy/multi-dc/3dc-deployment.md
(I've also started testing a link checker, hence the new gitignore entry)
> [docs] fix a few 404s

- docs/content/latest/explore/query-1-performance/pg-hint-plan.md
There were a couple unescaped asterisks on the pg_hint_plan page that needed escaping.
> [Docs] fixed unescaped asterisks in pg_hint_plan page

- docs/src/index.js
A couple of code-block handling changes.
1. Strip prompts from `cassandra` and `cql` blocks. (Yes, these are valid source-highlighter languages, and distinct from the sql ones...)
2. Adjust how the `output` language works, and add a `nocopy` one. Specify either one alone and they both work as output did before. Or, append a language name to have the code block highlighted but _without_ a copy button.
\
All of these are valid: `output`, `nocopy`, `nocopy.java`, and `output.json`. (The language name needs to come last!)
**Discussion**
First thing, you can keep on going with blocks tagged as `output` just like you could before. This change adds options, but doesn't change that base behaviour.
We could drop the "output" and just go with "nocopy", but:
- there's a lot of output already tagged …
> [docs] adjust copy button behaviour on code blocks

- docs/content/latest/admin/yb-ctl.md
- scripts/installation/bin/yb-ctl
yb-ctl --master_flags and --tserver_flags each take a comma-separated
list of key-value pairs.  It gets tricky when the value has commas or
equals.  Explain how to deal with that in the docs and script docstring.
> [docs] yb-ctl explain how to quote flags

- docs/content/latest/integrations/spring-framework/_index.md
**NOTE** click the PR preview link once the Netlify bot has added it, and make sure you get redirected to `/latest/integrations/spring-framework/`
@netlify /latest/reference/drivers/spring-data-yugabytedb
> [docs] redirect deleted spring page to integrations

- docs/content/latest/explore/cluster-management/point-in-time-recovery-ysql.md
- docs/content/latest/manage/backup-restore/point-in-time-recovery.md
Added steps for performing metadata restores for YSQL DDL types such as Create Table/index, Drop Table/index, and Alter table add column/drop column/rename column.
Tracking issue#[7120](https://github.com/yugabyte/yugabyte-db/issues/7120)
@netlify /latest/explore/cluster-management/point-in-time-recovery-ysql/
> [Docs] PITR: Changes documenting PITR support for YSQL DDL

- docs/config.yaml
- docs/layouts/_default/list.html
- docs/layouts/_default/single.html
- docs/layouts/_default/term.html
- docs/layouts/home.html
- docs/layouts/index.html
- docs/layouts/indexpage/list.html
- docs/layouts/indexpage/single.html
- docs/layouts/partials/drawer.html
- docs/layouts/partials/feedback.html
- docs/layouts/partials/footer.html
- docs/layouts/partials/footer_content.html
- docs/layouts/partials/header.html
- docs/layouts/search/single.html
- docs/layouts/versionlist/list.html
- docs/layouts/versionlist/single.html
- docs/netlify.toml
- docs/package.json
In addition to a Netlify change (turning off form detection), I'm trying a few more optimizations to bring down our docs build and deploy times:
* set a sidebar cache limit (may not have an impact)
* call a number of partials as `partialCached`
* bump hugo to current version
* add `debug-build` and `hugo-build-with-metrics` scripts to package.json to get hugo to output some useful metrics
* redirect / to /latest so we bypass the landing page with no left nav
**To verify things are working as they should:**
@netlify /latest/quick-start/install/macos/
> [docs] improve docs build and hugo caching

- docs/netlify.toml
Bumping Hugo to the latest version. Works locally. This is OK to merge after the preview build runs, provided it looks right!
> [docs] bump hugo to latest

- docs/content/latest/explore/ysql-language-features/data-types.md
Fix a typo in "To insert a row, use the RUN keyword" (should be ROW, and now is). While I was at it, I fixed all the markdownlint warnings and cleaned up the code snippet tagging.
@netlify /latest/explore/ysql-language-features/data-types
> [docs] update explore data-types: typo+linting

- docs/content/latest/architecture/design-goals.md
Fixing an incorrect link in the design goals section of architecture.
Thanks to Kripa Sreenivasan for catching this!
@netlify /latest/architecture/design-goals/
> [docs] fix incorrect link in design-goals

- docs/content/latest/secure/authentication/ldap-authentication-ycql.md
- docs/content/latest/secure/authentication/ldap-authentication-ysql.md
- docs/content/stable/secure/authentication/_index.md
- docs/content/stable/secure/authentication/ldap-authentication-ycql.md
- docs/content/stable/secure/authentication/ldap-authentication-ysql.md
[Alex note: this is new for 2.6, and already in 2.9, but the files are the same. Edited in /stable, then copied the content into /latest]
> [Docs] LDAP authentication for YCQL

- managed/ui/src/components/config/Security/certificates/AddCertificateForm.js
Current Behavior:
When creating a new CA signed certificate, the suggested paths for Node Cert and Node Key are reversed. Currently, for Database Node Certificate Path, the suggested path is /opt/yugabyte/keys/cert1/node.key but it should be /opt/yugabyte/keys/cert1/node.crt. And, for Database Node Certificate Private Key, the suggested path is /opt/yugabyte/keys/cert1/node.crt but it should be /opt/yugabyte/keys/cert1/node.key.
Please refer to https://github.com/yugabyte/yugabyte-db/issues/9850
> [#9850][Platform] - Fix suggested Paths for Node Cert Path and Key

- docs/content/latest/deploy/docker/docker-compose.md
- docs/content/latest/deploy/public-clouds/aws/cloudformation.md
- Cloud Formation page need a fix in this line : "Because the stack creates a security group that restricts access to the database, you might need to update the security group inbound rules if you have trouble connecting to it. if you have trouble connecting to the DB."
Build preview: https://deploy-preview-9830--infallible-bardeen-164bc9.netlify.app/latest/deploy/public-clouds/aws/cloudformation/
- Added the link to the Deployment checklist before creating clusters on the Docker compose page. This could help with understanding replication and other necessary configs.
Build preview: https://deploy-preview-9830--infallible-bardeen-164bc9.netlify.app/latest/deploy/docker/docker-compose/
> [docs] CloudFormation and docker compose fixes

- docs/content/latest/reference/connectors/kafka-connect-yugabytedb.md
- docs/content/stable/integrations/_index.html
- docs/content/stable/integrations/change-data-capture/cdc-generic.md
- docs/content/stable/integrations/change-data-capture/cdc-kafka.md
- docs/content/stable/reference/connectors/kafka-connect-yugabytedb.md
Removing references to the (alpha) CDC content.
@netlify /latest/reference/connectors/kafka-connect-yugabytedb/
> [docs] remove remaining CDC content

- docs/layouts/partials/drawer.html
Issue: https://github.com/yugabyte/yugabyte-db/issues/10480
Description
--
The issue currently today is that when a user goes to Yugabyte document page when they change the version of docs on the left side menu, the dropdown value always sticks to the first index instead of reacting to the dropDownValue change
Fix
--
This happens because the `version_switcher.html` component is cached and is not allowed to re-render in `drawer.html`.
> [UI] [docs] Fix re-rendering of docs page version dropdown

- docs/content/v2.1/api/ysql/datatypes/type_json/functions-operators/jsonb-set-jsonb-insert.md
(also lint the markdown)
(also lint the markdown)
@netlify /v2.1/api/ysql/datatypes/type_json/functions-operators/jsonb-set-jsonb-insert/#semantics-when-jsonb-in-is-a-json-object
> [docs] remove old merge-conflict markers

- docs/.gitignore
- docs/netlify.toml
Redirects:
* all older versions of /_version_/yugabyte-cloud point to /latest/yugabyte-cloud
* all older versions of /_version_/integrations and /_version_/develop/ecosystem-integrations point to /latest/integrations
Also bumping Hugo to [current 89.1](https://github.com/gohugoio/hugo/releases) from 88.1. (This required adding the build lock to .gitignore.)
> [docs] redirect updates

- docs/netlify.toml
Hugo 89.2 addresses a rendering bug for indented code blocks. If the code snippets in the numbered steps render correctly, we're good to go.
@netlify /latest/explore/cluster-management/point-in-time-recovery-ycql/
> [docs] bump hugo version

- docs/content/latest/reference/configuration/yb-tserver.md
Adding docs for RPC compression. Latest only right now, but once we're happy, I'll also add to 2.6 and 2.8.
Fixes #10003
@netlify /latest/reference/configuration/yb-tserver/#network-compression
> [docs] network compression docs

- docs/content/latest/quick-start/build-apps/java/ysql-jdbc-ssl.md
Change the command to run the application with `mvn` command, otherwise, the original `java` cmd will return error as `no main manifest attribute`. 
If still using `java`, 
- it can be resolved with adding the main class `com.yugabyte.HelloSqlSslApp` as follows the sample code.
- Also, the postgres driver will not found with the classpath, the external library will be found in `$HOME/.m2/ directory` if no additional configurations are there in maven. so may need to add the classpath to that, or configure maven to copy the dependencies to `target/lib`
> [Docs] need to modify the command to run the Java application

- docs/content/latest/api/ysql/datatypes/type_datetime/date-time-data-types-semantics/type-timestamp.md
In particular, "A minimal simulation of a calendar application" to give link target for blog post.
> [docs] Added two ### headings in .../type-timestamp.md

- docs/content/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
Resolves #9648 
The commands are added for the following account types:
- Global Restricted
- Namespace Admin
- Namespace Restricted
@netlify /latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes/#service-account
> [docs] commands to validate service account types

- docs/content/latest/integrations/jdbc-driver.md
Added an alias to redirect the smart driver to the new JDBC page.
@netlify /latest/integrations/jdbc-driver/
> [docs] alias to redirect to the new jdbc page

- docs/config.yaml
This change tells Hugo to pull each file's last-committed date from Git to populate the `<pubDate>` elements in the RSS.
The feed we most care about currently is `/latest/releases/whats-new/index.xml` — verify that the two pages in that file actually have non-zero pub dates!
Compare the new output to the old output...
```sh
$ curl https://deploy-preview-10568--infallible-bardeen-164bc9.netlify.app/latest/releases/whats-new/index.xml
$ curl https://docs.yugabyte.com/latest/releases/whats-new/index.xml
$ curl https://deploy-preview-10568--infallible-bardeen-164bc9.netlify.app/latest/releases/whats-new/index.xml | grep pubDate
$ curl https://docs.yugabyte.com/latest/releases/whats-new/index.xml | grep pubDate
```
> [docs] update hugo config to provide dates in RSS

- docs/content/latest/releases/earlier-releases/_index.md
- docs/content/latest/releases/earlier-releases/v2.4.md
- docs/content/latest/releases/earlier-releases/v2.5.md
- docs/content/latest/releases/earlier-releases/v2.6.md
- docs/content/latest/releases/earlier-releases/v2.7.md
- docs/content/latest/releases/whats-new/latest-release.md
- docs/content/latest/releases/whats-new/stable-release.md
- docs/content/v2.6/quick-start/install/docker.md
- docs/content/v2.6/quick-start/install/linux.md
- docs/content/v2.6/quick-start/install/macos.md
- docs/layouts/partials/head.html
And some other minor changes:
- add 2.6 to table of earlier releases
- left-nav ordering of earlier releases
- fix the RSS template to correct a hugo warning
- remove "headcontent" from non-index files
> [docs] 2.6.6.0 release notes

- docs/content/latest/api/ysql/datatypes/_index.md
- docs/content/stable/api/ysql/datatypes/_index.md
Only two occurrences found:
```
docs/content/latest/api/ysql/datatypes/_index.md
docs/content/stable/api/ysql/datatypes/_index.md
```
> [docs] Fixed 'timestampz' typo to 'timestamptz' in 'latest' and 'stable'

- docs/content/latest/yugabyte-platform/alerts-monitoring/alert.md
- docs/content/latest/yugabyte-platform/configure-yugabyte-platform/set-up-alerts-health-check.md
Docs on alerts should benefit from a link to a new blog post on the topic.
Added the link to two files.
> [docs] PR Add links to the blog post about alerts (Doc-BlogLinkInAlertsDocs)

- docs/.markdownlint.json
- docs/package-lock.json
Removing a couple of redundant entries, and adding some more specificity to a couple of rules.
(Also a tiny update to docs package-lock)
> [docs] update markdownlint configuration

- docs/content/latest/explore/multi-region-deployments/row-level-geo-partitioning.md
- docs/content/stable/explore/multi-region-deployments/row-level-geo-partitioning.md
- docs/content/v2.6/explore/multi-region-deployments/row-level-geo-partitioning.md
Remove an extra semicolon for one of the commands for latest, stable, and v2.6.
@netlify /latest/explore/multi-region-deployments/row-level-geo-partitioning/
> [docs] Fix for row-level-geo-partitioning page.

- docs/content/latest/explore/ysql-language-features/gin.md
- Switch example from yb-ctl to yugabyted
- Get rid of extraneous cache bias queries/comments
- Convert tab characters to spaces for table alignment
> [docs] Update GIN explore doc

- docs/content/latest/reference/configuration/yb-tserver.md
- docs/content/stable/reference/configuration/yb-tserver.md
Updated(latest and stable) the default value for  `timestamp_history_retention_interval_sec` based on this [code reference](https://github.com/yugabyte/yugabyte-db/blob/cee2332682dadaf498f3850edf93e72c67965dbf/src/yb/tablet/tablet_retention_policy.cc#L50).
@netlify /latest/reference/configuration/yb-tserver/#timestamp-history-retention-interval-sec
> [docs] update default for timestamp_history_retention_interval_sec

- docs/content/latest/integrations/jdbc-driver.md
Addressed the two changes:
1. Renamed  “Creating the Driver”  to “Getting the Driver”. 
2. "Use the Driver" section starts with this statement about the driver class `The YugabyteDB JDBC driver’s driver class is com.yugabyte.Driver.`
Build preview: https://deploy-preview-10722--infallible-bardeen-164bc9.netlify.app/latest/integrations/jdbc-driver/#getting-the-driver
> [docs] Minor edits to the JDBC integrations page.

- docs/content/latest/api/ysql/datatypes/type_datetime/date-time-data-types-semantics/type-interval/custom-interval-domains.md
- docs/content/latest/api/ysql/datatypes/type_datetime/functions/current-date-time-moment.md
- docs/content/v2.4/api/ysql/datatypes/_index.md
- docs/content/v2.6/api/ysql/datatypes/_index.md
Also fixed `timestampz` -> `timestampz` in overall table of data types. (Loose end left over from PR #10641).
> [docs] Misc minor fixes in date-time trees

- docs/content/latest/develop/_index.md
- docs/content/latest/yedis/develop/_index.md
Removing a pair of conflicting (and very old) aliases. The deploy preview should be a 404.
@netlify /develop
> [docs] remove conflicting redirects from /develop

- docs/content/latest/yugabyte-platform/troubleshoot/install-upgrade-yp-issues.md
Our docs reference firewalld commands as SElinux, but the two are
different concepts. The docs we have in this troubleshooting section are
specifically for firewall, so this commit just corrects the titles of
the sections.
I also added a proper link to our support portal
Signed-off-by: Tyler Ramer <tramer@yugabyte.com>
> [docs] Make sure references to firewall are accurately titled

- docs/content/latest/troubleshoot/overview.md
Support KB's often have the most recent information for Bugs affecting customers, they also have a wealth of information not available in the current troubleshooting section of the docs. This will allow customers reading the docs to have a link to explore support articles.
> [docs] add reference and link to support site

- docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
- Ran the command and created one universe. Was able to see the
metrics on the overview page.
Fixes https://github.com/yugabyte/yugabyte-db/issues/8976
> [docs] Fix the indentation of ClusterRoleBinding from OpenShift Helm

- docs/content/latest/yugabyte-platform/manage-deployments/high-availability.md
- docs/content/stable/yugabyte-platform/manage-deployments/high-availability.md
- docs/content/v2.6/yugabyte-platform/manage-deployments/high-availability.md
Platform HA was Beta in v2.5.3.1, and went GA in v2.6:
https://docs.yugabyte.com/latest/releases/earlier-releases/v2.6/
Announcing YugabyteDB 2.6 > Yugabyte Platform High Availability (HA)
> HA mode of Yugabyte Platform, first announced in YugabyteDB 2.7, is now
generally available.
> [docs] [#10890] Platform: Remove HA Beta tag

- docs/content/latest/develop/learn/batch-operations-ycql.md
Link at the bottom of YCQL Batch operations page for “Browse the Java source code for the batch application to see how everything fits together.” is broken.
https://deploy-preview-10930--infallible-bardeen-164bc9.netlify.app/latest/develop/learn/batch-operations-ycql/
> [docs] Fix link to source code

- docs/content/latest/quick-start/build-apps/python/ycql.md
- docs/content/stable/quick-start/build-apps/python/ycql.md
- docs/content/v2.2/quick-start/build-apps/python/ycql.md
- docs/content/v2.4/quick-start/build-apps/python/ycql.md
- docs/content/v2.6/quick-start/build-apps/python/ycql.md
Resolves #5684 
- Updated the commands as per the ticket instructions.
- Also updated the command to run the application from python2 to python3. 
- Changes in latest,stable ,2.6, 2.4,and 2.2.
@netlify /latest/quick-start/build-apps/python/ycql/
> [docs] [Quick start] Updated python driver install commands for ycql

- docs/layouts/partials/feedback.html
- docs/layouts/partials/feedback_widget.html
- docs/layouts/partials/nav_version_menu.html
- docs/layouts/partials/pagination_url_search.html
- docs/layouts/shortcodes/includeMarkdown.html
Hugo 0.92 _completely removes_ two functions we depend on ([release notes](https://github.com/gohugoio/hugo/releases/tag/v0.92.0)). This PR replaces them with supported functions.
1. Verify that `includeMarkdown` is working properly: make sure the PR preview landing page (dcl_alter_role) has its grammar and syntax diagram tabs populated.
2. Verify that the left nav still works (top-level items, and lower-level items).
3. Verify that the version menu still works (remember: it's _supposed_ to dump you at the top level right now; that fix hasn't landed yet!).
4. (Feedback and pagination, we're not using, but theoretically they do work...)
**Note...** We're not actually using the current version of Hugo right now, but I worry that these will trip up people running the build locally. And I'll …
> [docs] [infra] remove deprecated hugo functions

- docs/content/latest/yugabyte-cloud/cloud-overview.md
- docs/content/latest/yugabyte-cloud/cloud-quickstart/_index.md
Reorganization of Docs left nav meant some links to separate topics from the cloud UI were pointing at the same topic (quick start)
@netlify /latest/yugabyte-cloud/cloud-overview/
> [docs][cloud]Add overview page for links from cloud UI

- docs/layouts/partials/footer_js.html
- docs/styles/_yuga_overrides.scss
Resolves #11041
Verified locally that documentation looks fine with `npm start` and
behavior is as expected.
> [Docs] Make headers actual links, but no visual change

- .github/vale-styles/Yugabyte/spelling-exceptions.txt
spelling-exceptions.txt additions ysqlsh ycqlsh psql
> [docs] [infra] Add spelling exceptions for shell names

- docs/content/latest/integrations/janusgraph.md
resolves #11108 
The graph traversal step now points to the right link. 
@netlify /latest/integrations/janusgraph/
> [docs] [integrations] fixed link on Janusgraph integrations page

- docs/content/latest/deploy/multi-dc/async-replication.md
Adding section to the xcluster setup docs for how to create xCluster replications setups with TLS (where both universes have either the same certs or different certs)
[Alex edit to add: you can set the entry point for the PR preview by tagging the Netlify bot. It only reads these tags at initial PR creation time and again after any subsequent commits.]
@netlify /latest/deploy/multi-dc/async-replication/
> [docs] [#9160] Describe the process for using xCluster replication with TLS

- managed/src/main/java/com/yugabyte/yw/controllers/handlers/CloudProviderHandler.java
c0b9786ec2eec41d5773eef07f88d87ed77d189e changed the behavior of az.setConfig and added az.updateConfig. This change uses the correct method to add `{"KUBECONFIG": ""}` to the existing configuration instead of overwriting the whole AZ configuration.
This was missed when I rebased https://github.com/yugabyte/yugabyte-db/pull/8371 against latest changes.
Fixes https://github.com/yugabyte/yugabyte-db/issues/10860
> [Platform][Kubernetes] Use az.updateConfig for incluster credentials

- docs/content/latest/api/ysql/exprs/func_yb_hash_code.md
- docs/content/stable/api/ysql/exprs/func_yb_hash_code.md
The link for partition_hash should now point to the right page in latest and stable. 
Thanks @sushantrmishra  fro reporting the issue.
@netlify /latest/api/ysql/exprs/func_yb_hash_code/#see-also
> [docs] [api] fix link for partition hash on yb_hash_code() page

- docs/content/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
- managed/devops/roles/install_backup_util/defaults/main.yml
- managed/devops/roles/swamper/meta/main.yml
- Updated the azcopy (10.4.0 to 10.13.0), and node-exporter (1.2.2 to 1.3.1) to newer versions. 
**Note -**
- Changes completed the itest successfully, and there are no breaking changes in these updated versions.
Fixes https://github.com/yugabyte/yugabyte-db/issues/11004
> [Platform] Updated the azcopy and node-exporter version

- managed/devops/roles/install_backup_util/defaults/main.yml
- managed/devops/roles/swamper/meta/main.yml
Updated the azcopy (10.4.0 to 10.13.0), and node-exporter (1.2.2 to 1.3.1) to newer versions.
The updated versions don't have any breaking changes.
Issue - yugabyte#11004
> [Backport 2.12][Platform] Updated the azcopy and node-exporter version

- managed/devops/roles/install_backup_util/defaults/main.yml
- managed/devops/roles/swamper/meta/main.yml
Updated the azcopy (10.4.0 to 10.13.0), and node-exporter (1.2.2 to 1.3.1) to newer versions.
The updated versions don't have any breaking changes.
Issue - https://github.com/yugabyte/yugabyte-db/issues/11004
> [Backport 2.8][Platform] Updated the azcopy and node-exporter version

- managed/devops/roles/install_backup_util/defaults/main.yml
Updated the azcopy (10.4.0 to 10.13.0) to newer versions.
The updated versions don't have any breaking changes.
Issue - https://github.com/yugabyte/yugabyte-db/issues/11004
> [Backport 2.6][Platform] Update azcopy version

- docs/content/latest/architecture/docdb-replication/async-replication.md
Updating the feature and limitations section of the xcluster docs:
- Remove references to master / slave
- Beef up topology section
- Changed main `Features` section to talk about the architectural pieces (eg: at-least-once semantics, multi-shard txns, conflict resolution)
- Polished `Limitations` section
- Added GH issues to some known items
- Beef up DDL section with mentions to DROP & TRUNCATE
- Added Scalability section
- Added Kubernetes section
- Added cross-feature integration section with `Supported` and `Not yet supported` sub-sections
Still has a couple of TBD items, mostly for GH issues, pending eng and product review.
> [#7846, #11532] Update xcluster docs

- managed/devops/bin/node_client_utils.py
- managed/devops/bin/run_node_action.py
- managed/src/main/java/com/yugabyte/yw/common/NodeUniverseManager.java
Currently we don't use kubeconfig given by user at the time of provider creation, this in-turn means that any kubectl commands run by NodeUniverseManager uses in-cluster ServiceAccount credentials. In case of OpenShift the platform pod's ServiceAccount doesn't have permissions to run `kubectl exec` and hence operations like software upgrade fail.
- Changes the run_node_action.py to accept a new kubeconfig flag.
- Addresses the scenario where node_name is pod-hostname_azname (multiaz universes): this fixes issues with operations like software upgrade, download logs etc.
- Created one multi AZ Kubernetes universe, then ran universe upgrade. It worked as expected.
- Download logs works as expected as well.
- Ran same steps on OpenShift where platform's ServiceAccount …
> [PLAT-3171, PLAT-3169] Use provider KUBECONFIG in NodeUniverseManager

- managed/devops/bin/node_client_utils.py
- managed/devops/bin/run_node_action.py
- managed/src/main/java/com/yugabyte/yw/common/NodeUniverseManager.java
Original commit: 0a3c893cf25ef19544d84b2c21d5b156554d342e
Currently we don't use kubeconfig given by user at the time of
provider creation, this in-turn means that any kubectl commands run by
NodeUniverseManager uses in-cluster ServiceAccount credentials. In
case of OpenShift the platform pod's ServiceAccount doesn't have
permissions to run `kubectl exec` and hence operations like software
upgrade fail.
- Changes the run_node_action.py to accept a new kubeconfig flag.
- Addresses the scenario where node_name is
pod-hostname_azname (multiaz universes): this fixes issues with
operations like software upgrade, download logs etc.
- Created OpenShift universe where platform's ServiceAccount doesn't
have permission to run `kubectl exec`
- Then ran universe upgrade. It worked …
> [Backport 2.12][PLAT-3171, PLAT-3169] Use provider KUBECONFIG in NodeUniverseManager

- docs/content/latest/admin/yb-admin.md
- docs/content/latest/architecture/docdb-replication/async-replication.md
Adding yb-admin references for
- delete_cdc_stream
- bootstrap_cdc_producer
> [#11541] Add missing xcluster commands to yb-admin reference

- docs/content/latest/yugabyte-cloud/release-notes.md
spikes in the YSQL Operations/sec chart due to cluster health checks
@netlify /latest/yugabyte-cloud/release-notes/#known-issues
> [docs][cloud] YSQL Ops known issue

- managed/devops/bin/node_client_utils.py
- managed/devops/bin/run_node_action.py
- managed/src/main/java/com/yugabyte/yw/common/NodeUniverseManager.java
Currently we don't use kubeconfig given by user at the time of
provider creation, this in-turn means that any kubectl commands run by
NodeUniverseManager uses in-cluster ServiceAccount credentials. In
case of OpenShift the platform pod's ServiceAccount doesn't have
permissions to run `kubectl exec` and hence operations like software
upgrade fail.
- Changes the run_node_action.py to accept a new kubeconfig flag.
- Addresses the scenario where node_name is
pod-hostname_azname (multiaz universes): this fixes issues with
operations like software upgrade, download logs etc.
> [Backport 2.8][PLAT-3171, PLAT-3169] Use provider KUBECONFIG in NodeUniverseManager

- docs/content/latest/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
- docs/content/v2.6/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
- docs/content/v2.8/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
All the platform images which are UBI based have been in a separate
container registry since 2.6+, with same tags as of the main yugaware
registry.
- Have been using this command to install platform on OpenShift
> [docs][OpenShift] Use correct container registry with Helm

- docs/content/v2.8/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
- We have updated the azcopy and node-exporter versions in the docker image, so it'll have new versions whenever we have a new 2.8 release.
- We can merge this PR once the new 2.8 release is available. 
https://github.com/yugabyte/yugabyte-db/issues/11004
> [Platform][Docs] Bump the azcopy and node-exporter version

- docs/content/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
make service account access levels easier to read
> [docs] Update kubernetes.md

- docs/content/latest/reference/configuration/default-ports.md
- docs/content/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/aws.md
- docs/content/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp.md
- docs/content/latest/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md
@nzaporozhets 
- Could you, please, let me know under which category I should add 54422 in https://docs.yugabyte.com/latest/reference/configuration/default-ports/ and https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes/#ports ?
- Should the firewall rules section for GCP also have port 54422 added? https://docs.yugabyte.com/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp/#create-a-firewall-rule
> [Docs] PR for AWS Security group is missing ports

- README.md
- src/README.md
Adding a Codemap section to describe the top-level source code directories better for onboarding new engineers.
> Adding a Codemap to our README

- docs/content/latest/admin/yb-admin.md
Add docs for missing yb-admin command.
Also polished some of the wording of the other snapshot schedule commands.
> [#10779] Docs for PITR delete_snapshot_schedule

- docs/content/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
Addresses https://yugabyte.atlassian.net/browse/PLAT-3531
> [doc] PR for Changes to account setup for kubernetes config

- docs/content/latest/deploy/kubernetes/single-zone/gke/helm-chart.md
Changes made -->
1. Added explanation of why we need 8 core machines in k8s install on GKE using helm.
2. Edited the install of kubectl section - installing under gcloud puts it into a different directory that comes typically after the homebrew path. Thus installing under gcloud root directory may not do anything. Plus kubectl can be installed on Windows and Mac separately, separate from gcloud anyway.
> [docs] Changed explanation of cpu cores needed for helm

- src/yb/rpc/inbound_call.cc
- src/yb/rpc/inbound_call.h
- src/yb/rpc/service_pool.cc
- src/yb/yql/cql/cqlserver/cql_processor.cc
- src/yb/yql/cql/cqlserver/cql_rpc.cc
- src/yb/yql/cql/cqlserver/cql_rpc.h
- src/yb/yql/cql/ql/util/cql_message.cc
- src/yb/yql/cql/ql/util/cql_message.h
In this phab, we modify the CQL protocol with the metadata flag. If the flag
is set, then the first 8 bytes of the request body are reserved for RPC-related
metadata. Currently, the request will have 2 bytes set to the RPC queue limit,
which is used for load-shedding on the server. Also, the response will have 2
bytes set to the RPC queue position of the request, which is used for adaptive
throttling on the client.
> ycql: add RPC metadata to cql protocol

- docs/content/latest/benchmark/tpcc-ysql/_index.md
- docs/content/stable/benchmark/tpcc-ysql/_index.md
removing strict requirement on $HOME makes copy button more useful
> [docs] minor change to tpcc download command

- docs/netlify.toml
Adjusting some redirects...
The PR preview link should land you on the same page under /preview by way of two redirects. Verify with `curl -I` to see what the chain is...
@netlify /latest/yugabyte-cloud/cloud-secure-clusters/add-connections/
> [docs] update some server-side redirects

- docs/content/preview/admin/yb-ts-cli.md
Added documentation for the yb-ts-cli reload_certificates command added in https://github.com/yugabyte/yugabyte-db/commit/73a3ca42ed0dfe7fa71de6f86777e18f5b4d7ab7 (https://github.com/yugabyte/yugabyte-db/issues/11531).
Resolves #12334.
> [docs] Add documentation for yb-ts-cli reload_certificates

- architecture/design/ysql-colocated-tables.md
This content along with the doc was migrated from internal resources. The original
doc that it should be linked to is too casual to be public.
Removing this line of sentence will reduce confusion to the public
readers.
**Test**
Reviewed the rendered content in MD viewer.
> [Docs] Remove confusing doc content in Colocation doc

- README.md
Link to logo in top README.md has been broken since at least May 17.
Point to a new, working link mentioned by Alex Ball.  This new image is
an SVG, so it has better quality compared to the previous raster image.
> [docs] Fix logo link in README.md

- docs/content/preview/api/ycql/expr_fcall.md
- docs/content/preview/api/ycql/function_datetime.md
> [docs] document minTimeUUID & maxTimeUUID in YCQL

- docs/content/preview/secure/authorization/create-roles-ycql.md
- docs/content/preview/secure/authorization/create-roles.md
- docs/content/preview/yugabyte-cloud/cloud-secure-clusters/add-users.md
Internal testers have noted that SQL's standard practice of converting to lower case was surprising and might trip up users. This change adds a note in the quickstart page about this potential pitfall.
What are your thoughts on moving this `Note` into the YSQL reference page? https://docs.yugabyte.com/preview/api/ysql/the-sql-language/statements/dcl_create_role/
> Add note to cloud shell quickstart page about case sensitivity

- docs/content/preview/secure/authorization/rbac-model.md
- docs/content/preview/yugabyte-cloud/cloud-secure-clusters/cloud-users.md
Details on the yb_db_admin role used to grant yb_superusers aome superuser abilities
@netlify /preview/yugabyte-cloud/cloud-secure-clusters/cloud-users/#yb-db-admin
> [docs][cloud] yb_db_admin role

- docs/content/preview/reference/configuration/yb-tserver.md
- docs/content/stable/reference/configuration/yb-tserver.md
- docs/content/v2.8/reference/configuration/yb-tserver.md
- Move "compression_type" documentation to a location under
"performance" because it's not networking related
- Small text / readability enhancements
> [Docs] Update compression flags

- docs/content/preview/explore/multi-region-deployments/row-level-geo-partitioning.md
- docs/content/preview/reference/configuration/yb-tserver.md
With 5f339ee6 (2.13.3/2.14 onwards), users no longer run into the `Nonlocal tablet accessed in local transaction` error by default, and thus the `Running distributed transactions` section of the Row-Level Geo-Partitioning explore page is no longer relevant. This PR removes that section and adds documentation for gflags related to geo-partitioned transactions.
> [Docs] Update row-level geo-partitioning docs for transaction promotion

- docs/content/preview/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md
Restart is no longer required, so this step is removed.
> [doc] PR for Remove a step that's no longer required

- docs/content/preview/reference/configuration/yb-master.md
- docs/content/preview/reference/configuration/yb-tserver.md
- docs/content/stable/reference/configuration/yb-master.md
- docs/content/stable/reference/configuration/yb-tserver.md
- docs/content/v2.4/reference/configuration/yb-master.md
- docs/content/v2.4/reference/configuration/yb-tserver.md
- docs/content/v2.6/reference/configuration/yb-master.md
- docs/content/v2.6/reference/configuration/yb-tserver.md
- docs/content/v2.8/reference/configuration/yb-master.md
- docs/content/v2.8/reference/configuration/yb-tserver.md
Added documentation for the `webserver_certificate_file`, `webserver_authentication_domain`, and `webserver_password_file` gflags that were present in all past releases but not documented.
Context: #12861
> [Docs] Add docs on gflags for webserver SSL/authentication

- architecture/design/docdb-encryption-at-rest.md
The number in CTR-128 refers to the key size in bits, hence 16 byte key.
> Update "bytes" to "bits" in EAR docs

- docs/content/preview/reference/drivers/ycql-client-drivers.md
@netlify /preview/reference/drivers/ycql-client-drivers/
Verify the maven repository link : https://deploy-preview-13088--infallible-bardeen-164bc9.netlify.app/preview/reference/drivers/ycql-client-drivers/#yugabyte-java-driver-for-ycql-4-6
> [docs] [reference] fixed maven repo link for yugabyte java driver for ycql. 

- docs/content/preview/architecture/core-functions/write-path.md
> Correct that direct-to-server write query is only available in YCQL smart client.

- docs/content/preview/yugabyte-cloud/release-notes.md
Some queries missing from Slow Queries page
> [docs][cloud] Slow queries known issue

- architecture/design/ysql-row-level-partitioning.md
Executing Range and Hash partitioning DDL statement with primary key constraints won't allow creating a table. We should remove the primary key constraints from the Range and Hash partitioning 'CREATE TABLE' statements as the primary key has to be a part of partition keys.
> Correcting DDL statements for YSQL Table Partitioning document.

- docs/content/preview/api/ysql/the-sql-language/statements/txn_show.md
Since just `SHOW TRANSACTION;` does nothing.
> Minor fixes to SHOW TRANSACTION documentation

- docs/content/preview/drivers-orms/python/sqlalchemy.md
- This is a 🐁 small change.
- This PR  fixes the code formatting issue on the [Python SQLAlchemy ORM example](https://docs.yugabyte.com/preview/drivers-orms/python/sqlalchemy/) page.
**- Before the fix:**
**- After the fix:**
@netlify /preview/drivers-orms/python/sqlalchemy
> [Doc]: Fix the code formatting of Python SQLAlchemy ORM example page

- docs/content/preview/deploy/docker/docker-compose.md
- docs/content/preview/deploy/manual-deployment/start-tservers.md
- docs/content/preview/deploy/multi-dc/3dc-deployment.md
- docs/content/preview/reference/configuration/yb-master.md
- docs/content/preview/reference/configuration/yb-tserver.md
- docs/content/stable/deploy/docker/docker-compose.md
- docs/content/stable/deploy/manual-deployment/start-tservers.md
- docs/content/stable/deploy/multi-dc/3dc-deployment.md
- docs/content/stable/reference/configuration/yb-master.md
- docs/content/stable/reference/configuration/yb-tserver.md
- docs/content/v2.12/deploy/docker/docker-compose.md
- docs/content/v2.12/deploy/manual-deployment/start-tservers.md
- docs/content/v2.12/deploy/multi-dc/3dc-deployment.md
- docs/content/v2.12/reference/configuration/yb-master.md
- docs/content/v2.12/reference/configuration/yb-tserver.md
- docs/content/v2.4/deploy/docker/docker-compose.md
- docs/content/v2.4/deploy/manual-deployment/start-tservers.md
- docs/content/v2.4/deploy/multi-dc/3dc-deployment.md
- docs/content/v2.4/reference/configuration/yb-master.md
- docs/content/v2.4/reference/configuration/yb-tserver.md
- docs/content/v2.6/deploy/docker/docker-compose.md
- docs/content/v2.6/deploy/manual-deployment/start-tservers.md
- docs/content/v2.6/deploy/multi-dc/3dc-deployment.md
- docs/content/v2.6/reference/configuration/yb-master.md
- docs/content/v2.6/reference/configuration/yb-tserver.md
- docs/content/v2.8/deploy/docker/docker-compose.md
- docs/content/v2.8/deploy/manual-deployment/start-tservers.md
- docs/content/v2.8/deploy/multi-dc/3dc-deployment.md
- docs/content/v2.8/reference/configuration/yb-master.md
- docs/content/v2.8/reference/configuration/yb-tserver.md
We deprecated the `--start_pgsql_proxy` flag in v2.2, but never replaced it everywhere in the docs with `--enable_ysql`. This fixes that in all YugabyteDB versions (well, all the versions on the main docs site: 2.4 and up).
@netlify /preview/reference/configuration/yb-tserver/#example
> [docs] remove very deprecated "start_pgsql_proxy"

- docs/content/preview/api/ycql/dml_select.md
With https://github.com/yugabyte/yugabyte-db/commit/c1a46aa8034486371ca929b9b9ac25bb4b655c41, we introduced support for multi clustering column for `IN` operator. This PR updates the docs for the same.
> [Docs] Adds multi-clustering-column for IN operator

- managed/devops/replicated.yml
Summary:
Raise default nginx timeout (read, connect, send) for Platform API requests
Applied changes to replicated.yml
Test Plan: Doesn't include tests
Reviewers: sanketh, arnav, sneelakantan
Reviewed By: sneelakantan
Subscribers: jenkins-bot, yugaware
Differential Revision: https://phabricator.dev.yugabyte.com/D18549
> [PLAT-4688] Raise default nginx timeout for Platform API requests

- docs/content/preview/yugabyte-platform/security/enable-encryption-in-transit.md
- docs/content/stable/yugabyte-platform/security/enable-encryption-in-transit.md
Notes from slack thread -
so ssl keys can be downloaded from portal directly, but the only documentation we have is this page
https://docs.yugabyte.com/preview/develop/build-apps/java/ysql-jdbc-ssl/#set-up-ssl-certificates-for-java-applications
but it’s not about yugaware case.
basically we need only these lines to convert keys:
```
openssl x509 -outform der -in /home/centos/nm/puppy-food-arm-1.crt -out /home/centos/nm/puppy-food-arm-1.crt.der
openssl pkcs8 -topk8 -inform PEM -in /home/centos/nm/puppy-food-arm-1.key -outform DER -nocrypt -out /home/centos/nm/puppy-food-arm-1.key.pk8
```
@qvad , here's the deploy preview. Please take a look if this note is sufficient. https://deploy-preview-13607--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/security/enable-encryption-in- …
> [docs] [Anywhere] Added information about converting certs when using JDBC driver with YugabyteDB Anywhere

- docs/content/preview/api/ysql/the-sql-language/statements/cmd_copy.md
- docs/content/preview/migrate/manual-import/import-data.md
- docs/content/stable/api/ysql/the-sql-language/statements/cmd_copy.md
- docs/content/stable/migrate/manual-import/import-data.md
The default value for the ROWS_PER_TRANSACTION parameter is currently set to 10000, which is sufficient for most cases. Therefore, there is no reason to mention it in examples for COPY FROM command.
@netlify /preview/migrate/manual-import/import-data/
> [Docs] Removed references to ROWS_PER_TRANSACTION

- docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
- docs/content/v2.12/quick-start/_index.md
- docs/content/v2.12/quick-start/docker.md
- docs/content/v2.12/quick-start/linux.md
- docs/content/v2.12/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
- docs/content/v2.6/yugabyte-platform/install-yugabyte-platform/install-software/airgapped.md
- docs/layouts/shortcodes/yb-version.html
The shortcode logic wasn't quite correct for numbered versions. This fixes that, and updates a few incorrect invocations while we're at it.
@netlify /v2.8/yugabyte-platform/install-yugabyte-platform/install-software/airgapped/#install-replicated
> [docs] fix the yb-version shortcode

- docs/content/preview/develop/build-apps/java/ycql-4.6.md
- docs/content/preview/develop/build-apps/java/ycql.md
- docs/content/preview/develop/build-apps/java/ysql-ebean.md
- docs/content/preview/develop/build-apps/java/ysql-hibernate.md
- docs/content/preview/develop/build-apps/java/ysql-jdbc-ssl.md
- docs/content/preview/develop/build-apps/java/ysql-jdbc.md
- docs/content/preview/develop/build-apps/java/ysql-sdyb.md
- docs/content/preview/develop/build-apps/java/ysql-spring-data.md
- docs/content/preview/develop/build-apps/java/ysql-vertx-pg-client.md
- docs/content/preview/develop/build-apps/java/ysql-yb-jdbc.md
- docs/content/preview/reference/drivers/ysql-client-drivers.md
This PR adds the docs for Vertx PG Client in [build-app](https://docs.yugabyte.com/preview/develop/build-apps/java/ysql-yb-jdbc/) for Java and mentions as supported client drivers in [reference](https://docs.yugabyte.com/preview/reference/drivers/ysql-client-drivers/).
> [docs] Added docs for vertx pg client for Java

- docs/content/preview/explore/ysql-language-features/data-manipulation.md
- docs/content/preview/explore/ysql-language-features/data-types.md
- docs/content/stable/explore/ysql-language-features/data-manipulation.md
- docs/content/stable/explore/ysql-language-features/data-types.md
- docs/content/v2.12/explore/ysql-language-features/data-manipulation.md
- docs/content/v2.12/explore/ysql-language-features/data-types.md
- docs/content/v2.6/explore/ysql-language-features/data-manipulation.md
- docs/content/v2.6/explore/ysql-language-features/data-types.md
- docs/content/v2.8/explore/ysql-language-features/data-manipulation.md
- docs/content/v2.8/explore/ysql-language-features/data-types.md
> Fix formatting in a `CREATE TABLE` example, fix formatting in `ENUM` data type examples

- docs/content/preview/releases/_index.md
Should be May, not June
@netlify /preview/releases/#release-support-timelines
> [docs] adjust EOL date for v2.8

- docs/content/preview/explore/ysql-language-features/postgresql-compatibility.md
- docs/content/stable/explore/ysql-language-features/postgresql-compatibility.md
@dmagda , here's the Deploy preview for adding the exception note on Pessimistic locking:
https://deploy-preview-13752--infallible-bardeen-164bc9.netlify.app/preview/explore/ysql-language-features/postgresql-compatibility/#unsupported-postgresql-features
@netlify /preview/explore/ysql-language-features/postgresql-compatibility/
> [docs] [explore] added an exception note about pessimistic locking

- docs/content/preview/integrations/apache-spark/java-ycql.md
- docs/content/preview/integrations/apache-spark/java-ysql.md
- docs/content/preview/integrations/apache-spark/python-ycql.md
- docs/content/preview/integrations/apache-spark/python-ysql.md
- docs/content/preview/integrations/apache-spark/scala-ycql.md
- docs/content/preview/integrations/apache-spark/scala-ysql.md
- docs/content/preview/integrations/apache-spark/spark-sql.md
@netlify /preview/integrations/apache-spark/
Currently, there are two extra entries under integrations left nav titled YSQL and YCQL which are pages from Apache Spark. 
This PR removes the duplicates.
> [docs] [integrations] Removed duplicate left navigation entry for Apache Spark 

- docs/content/preview/contribute/core-database/build-from-src-macos.md
Edit Contribute page to clarify Java requirement for building on macOS.
#11639
@netlify /preview/contribute/core-database/build-from-src-macos/
> [docs] PR for Update contributor instructions to include JDK 1.8 pre-requisite

- docs/content/preview/migrate/yb-voyager/migrate-steps.md
- docs/content/stable/migrate/yb-voyager/migrate-steps.md
> Fix missing `\` in docs of `yb-boyager import schema`

- docs/content/preview/reference/configuration/yb-master.md
- docs/content/preview/reference/configuration/yb-tserver.md
Made changes in /reference/configuration/yb-tserver/ and /reference/configuration/yb-master/ files.
https://docs.yugabyte.com/preview/deploy/manual-deployment/start-tservers/#run-yb-tserver-with-command-line-flags and https://docs.yugabyte.com/preview/deploy/manual-deployment/start-masters/#run-yb-master-servers-with-command-line-flags reference the --rpc_bind_addresses flag with updated description.
> [doc] PR for rpc_bind_addresses param for yb-master and yb-tserver is not set to 0.0.0.0 

- docs/content/preview/reference/drivers/ycql-client-drivers.md
Was recently noticed two times in QA, and there are existing bugs about this: https://github.com/yugabyte/yugabyte-db/issues/520
So there seems to be some confusion on this topic, best to clear that up in documentation.
> [docs] Add note about YCQL requiring Yugabyte-specific client drivers

- docs/content/preview/quick-start/_index.md
- docs/content/preview/quick-start/docker.md
- docs/content/preview/quick-start/linux.md
- docs/content/preview/yugabyte-cloud/cloud-basics/cloud-vpcs/cloud-add-vpc-aws.md
Add port forward instruction for running Docker on macOS Monterey
@netlify /preview/quick-start/docker/#create-a-local-cluster
> [docs] Add Monterey note for Docker Quick Start

- docs/content/preview/manage/data-migration/bulk-import-ysql.md
- docs/content/stable/manage/data-migration/bulk-import-ysql.md
The changes from this [PR](https://github.com/yugabyte/yugabyte-db/pull/13631/files#diff-2c2c4f64aa513966f5352d12261e6c5e11787b794fea0f882c38297b19bb927e) got accidentally added while moving the pages from migrate to manage section. This PR resolves the issue.
> [docs] removed changes that got accidentally added to import ysql steps

- docs/content/preview/admin/yb-admin.md
This PR adds documentation for the `yb-admin add_transaction_tablet` command added in d32b78841427161bef5e761df809e7a8aa28eb2a.
> Add documentation for yb-admin add_transaction_tablet

- docs/content/preview/admin/yb-ts-cli.md
- docs/content/preview/troubleshoot/cluster/replace_failed_peers.md
- docs/content/stable/admin/yb-ts-cli.md
- docs/content/v2.12/admin/yb-ts-cli.md
- docs/content/v2.8/admin/yb-ts-cli.md
This PR adds documentation for the `yb-ts-cli remote_bootstrap` command added in dec0805927f6b77f0e6b8918ef69b6efa5a9ba30 and backported to 2.8, 2.12, and 2.14.
Resolves #14053
> Add documentation for yb-ts-cli remote_bootstrap

- docs/content/preview/deploy/kubernetes/multi-zone/eks/helm-chart.md
- docs/content/preview/deploy/kubernetes/multi-zone/gke/helm-chart.md
- docs/content/stable/deploy/kubernetes/multi-zone/eks/helm-chart.md
- docs/content/stable/deploy/kubernetes/multi-zone/gke/helm-chart.md
By using WaitForFirstConsumer, we can simplify these docs and avoid the need for a storage class per zone.
> [docs] Remove need for storage class per zone

- docs/content/preview/admin/ycqlsh.md
- docs/content/stable/admin/ycqlsh.md
- docs/content/v2.12/admin/ycqlsh.md
Added the flag _refresh_on_describe_ to [ycqlsh](https://docs.yugabyte.com/preview/admin/ycqlsh/#flags) page .
Changes are in preview, stable and 2.12
Deploy preview : https://deploy-preview-14252--infallible-bardeen-164bc9.netlify.app/preview/admin/ycqlsh/#flags
> [docs] added missing ycqlsh flag

- docs/content/preview/explore/linear-scalability/sharding-data.md
The host value in the command should be `127.0.0.6` to match what is shown in the screenshot that follows it.
> [docs] [sharding] Fix typo in command

- docs/content/preview/reference/configuration/yb-master.md
- docs/content/stable/reference/configuration/yb-master.md
Removing comment about updating the flag on tservers as this is a master only flag.
> [doc] Fix cdc_wal_retention_time_secs gflag description

- docs/content/preview/contribute/core-database/build-from-src-centos.md
- docs/content/preview/contribute/core-database/build-from-src-ubuntu.md
Remove some unneeded packages and do not mention an outdated version of OpenSSL. Add --no-linuxbrew until we make sure we automatically disable the use of Linuxbrew on Ubuntu.
> [docs] [#14484] Fix Ubuntu build instructions

- docs/content/preview/contribute/core-database/build-from-src-centos.md
- docs/content/preview/contribute/core-database/build-from-src-macos.md
- docs/content/preview/contribute/core-database/checklist.md
- docs/content/preview/contribute/core-database/run-unit-tests.md
Fix some outdated portions of core-db contribute docs.  There are other
outdated portions remaining, like the recommended OS changing from
centos to alma and the default compiler changing from gcc to clang, but
leave that change to the build team.
Also fix some typos/grammar.
> [docs] Update core-db contribute docs

- docs/data/currentVersions.json
- docs/layouts/shortcodes/yb-version.html
Changing the name of the version array from `docVersions` to `dbVersions`, to make this a bit more future-proof.
@netlify /preview/quick-start/
> [docs] update yb-version shortcode and data file

- docs/content/preview/reference/drivers/nodejs/postgres-pg-reference.md
- docs/content/preview/yugabyte-platform/security/enable-encryption-in-transit.md
- Set up SSL for java applications : https://deploy-preview-14807--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/security/enable-encryption-in-transit/#connect-to-a-ysql-endpoint-with-tls
- cluster certificate link for Managed : https://deploy-preview-14807--infallible-bardeen-164bc9.netlify.app/preview/reference/drivers/nodejs/postgres-pg-reference/#configure-ssl-tls
> [docs] fix broken links

- .arclint
Lint rule gflag_register_flag_validator has been renamed to flags
>  [ONLY 2.16] Fix flags lint rule name

- .arclint
Lint rule gflag_register_flag_validator has been renamed to flags
>  [ONLY 2.17.0] Fix flags lint rule name

- docs/content/preview/secure/tls-encryption/server-certificates.md
Addresses https://github.com/yugabyte/yugabyte-db/issues/10686
Preview: https://deploy-preview-14577--infallible-bardeen-164bc9.netlify.app/preview/secure/tls-encryption/server-certificates/#specify-subject-alternative-name
> [Docs] PR for Specify Subject Alternative Name(SAN) when creating server certificates in docs

- docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
- docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
Summary:
The <namespace> placeholder and the <SA_NAMESPACE> from the RBAC YAML were creating confusion on which one to replace while running the commands.
With this change we set an environment variable and use it across all the commands, so that users can just set one variable and easily execute all the commands.
Fixes https://github.com/yugabyte/yugabyte-db/issues/11475
Test Plan:
- Tried all the commands from this page with the variable value set and without it.
> [docs][PLAT-5834] Use env vars in K8s service account creation steps

- docs/content/preview/reference/configuration/yb-master.md
Update default for follower_unavailable_considered_failed_sec and log_min_seconds_to_retain flags
@netlify /preview/reference/configuration/yb-master/#follower-unavailable-considered-failed-sec
> [docs][ybmaster] Fix default for 2 flags

- CMakeLists.txt
- build-support/run-test.sh
- yb_build.sh
- Fix shellcheck warnings in run-test.sh and yb_build.sh.
- Change required CMake version to 3.17.3.
> Fix shellcheck warnings and lower the required CMake version

- docs/content/preview/reference/configuration/insecure-yugabyted-examples.md
- docs/content/preview/reference/configuration/yugabyted.md
Summary: Updated the yugabyted CLI reference page:
* Added description, sub-command and flags for command 'cert'.
* Added description and flags for sub-commands 'data_placement' and 'encrypt_at_rest' under 'configure' command.
* Added examples for secure deployment and toggling encryption-at-rest.
Reviewers: nchandrappa
Subscribers: gargsans-yb
> [Docs][#15105] Updating the documentation for referance page of yugabyted CLI

- docs/netlify.toml
Update the Netlify redirects to address some ancient links from blog posts and whatnot
@netlify /preview/releases/release-notes/v2.16/
> [docs] update redirects

- docs/content/preview/drivers-orms/go/pgx.md
The two lines below were in conflict.
Create a file called QuickStart.go ...
Run the project QuickStartApp.go ...
Changed the filename to `QuickStartApp.go` so it would run.
> [docs] Correct the file name for the example

- docs/content/preview/integrations/akka-ycql.md
- docs/content/preview/integrations/akka-ysql.md
Included YSQL and YCQL tabs for Akka persistence integration with YugabyteDB. 
Content for YSQL remaining.
> [docs] added ysql and ycql tabs for Akka

- docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/openshift.md
- docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/openshift.md
Summary:
The placeholder and the <SA_NAMESPACE> from the RBAC YAML were creating confusion on which one to replace while running the commands.
With this change we set an environment variable and use it across all the commands, so that users can just set one variable and easily execute all the commands.
This is same change as
https://github.com/yugabyte/yugabyte-db/pull/14951 for OpenShift.
Test Plan:
- Tried all the commands from this page with the variable value set and without it.
> [docs][PLAT-5834] Use env vars in OCP service account creation steps

- docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
- docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
- docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md
- docs/content/preview/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md
- docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites.md
- docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/prepare-on-prem-nodes.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites.md
- Adds section for each override, that way we can link to them.
- Switch to using a values YAML file instead of just --set flag. The flag is hard to use in most of the cases, and some users tend to forget what all they had applied. On the other hand using YAML is easier, and it can be version controlled.
- Consolidate all the storage class related section to one section in Prepare the environment.
Preview: 
- https://deploy-preview-15495--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/install-yugabyte-platform/install-software/kubernetes
- https://deploy-preview-15495--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/install-yugabyte-platform/prepare-environment/kubernetes/#storage-class-considerations
> [docs][PLAT-6511] Document Helm overrides for YBA chart

- docs/content/preview/drivers-orms/java/postgres-jdbc.md
- docs/content/preview/faq/smart-drivers-faq.md
- docs/content/stable/drivers-orms/java/postgres-jdbc.md
- docs/content/v2.14/drivers-orms/java/postgres-jdbc.md
- docs/content/v2.14/drivers-orms/java/yugabyte-jdbc.md
Some changes were needed 
- Replaced occurrences of "string" with "String"
- Changed code snippets with incorrect syntax like the following :
```
String yburl = "jdbc:postgresql://localhost:5433/yugabyte", "yugabyte", "yugabyte";
Connection conn = DriverManager.getConnection(yburl);
```
to :
```
String yburl = "jdbc:postgresql://localhost:5433/yugabyte";
Connection conn = DriverManager.getConnection(yburl,"yugabyte", "yugabyte");
```
Slack conversation link reporting the issue - https://yugabyte.slack.com/archives/CDQB8MEAU/p1675110021134259
> [docs] modified incorrect code syntax for postgres jdbc page

- docs/content/preview/drivers-orms/python/ycql.md
resolves #15836 
@netlify /preview/drivers-orms/python/ycql/
Note to self - back-port to older versions.
> [docs] [develop] SSL steps for python YCQL driver 

- docs/content/preview/yugabyte-platform/troubleshoot/universe-issues.md
Adds documentation about debug hooks which were added as part of https://github.com/yugabyte/charts/commit/2596d9f04a4340cf02b420d5f5df3d8abb8750cd
Create a new section of debugging crashing pods and move the core dump related section under it (link remains the same).
Preview: https://deploy-preview-16575--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/troubleshoot/universe-issues/#debug-crashing-yugabytedb-pods-in-kubernetes
> [docs][PLAT-7630] Troubleshooting section on Kubernetes debug hooks

- docs/content/preview/explore/query-1-performance/pg-stat-activity.md
https://github.com/yugabyte/yugabyte-db/commit/f8b522feb30038fc074772cf6b5bf0a46eff245d add two new columns `allocated_mem_bytes` and `rss_mem_bytes` in pg_stat_activity. 
This commit adds documentation for these columns.
Fixes #16569
> [docs] Describe allocated_mem_bytes and rss_mem_bytes in pg_stat_activity

- java/yb-cql/src/test/java/org/yb/cql/BaseCQLTest.java
attemptsMade is not change in loop.
So add attemptsMade++;
```
while (attemptsMade < 30) {
int numPeers = execute("SELECT peer FROM system.peers").all().size();
if (numPeers >= expectedNumPeers) {
waitSuccessful = true;
break;
}
LOG.info("system.peers still contains only " + numPeers + " entries, waiting");
Thread.sleep(1000);
}
```
> [#16883][YCQL]Fix java unit test setUpCqlClient maybe endless loop

- docs/layouts/shortcodes/tabs.html
- The `.Page.Rending` was creating additional space between the header and the tabs
> removing explicit rendering

- docs/content/preview/develop/learn/transactions/transactions-performance-ysql.md
- In the On Conflict page, we missed using the clause in the examples.
> use `on conflict` in the examples

- docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/openshift.md
- Added `securityContext.enabled=false` for YBA installation in OCP docs.
- Recently, we have enabled the security context for all the installations.
Fix: https://yugabyte.atlassian.net/browse/PLAT-8332
> [PLAT-8332][docs] Added securityContext.enabled=false for YBA installation in OCP docs

- yb_build.sh
Issue https://github.com/yugabyte/yugabyte-db/issues/16139, added check to only execute `which cmake` if cmake exists. Otherwise, print error and exit with Code 1.
> Issue #16139 - Fix: Add check to detect whether cmake exists

- docs/content/preview/api/ysql/the-sql-language/statements/ddl_truncate.md
> [docs] Add note that explains that TRUNCATE is not transactional in YugabyteDB and not MVCC-safe in PostgreSQL

- docs/content/preview/api/ysql/the-sql-language/statements/ddl_create_table.md
> [docs] Explain that `ybrowid` is used for PRIMARY KEY when one is not defined in YSQL `CREATE TABLE` query

- docs/content/preview/api/ycql/syntax_resources/ycql_grammar.ebnf
Found when making other changes. Fixes the following errors:
```
WARNING: Undefined rules referenced in rule 'table_properties': [=]
WARNING: Undefined rules referenced in rule 'alter_keyspace': [keyspae_name]
```
> [docs] Fix typo/warnings in ycql_grammar.ebnf for `table_properties` & `alter_keyspace`

- docs/content/preview/reference/configuration/yb-tserver.md
- docs/content/preview/secure/audit-logging/trace-statements-ysql.md
- docs/content/stable/reference/configuration/yb-tserver.md
- docs/content/stable/secure/audit-logging/trace-statements-ysql.md
Backport of https://github.com/yugabyte/yugabyte-db/pull/17346 & other changes to stable branch.
> [docs] Backport "PostgreSQL Options" on yb-tserver.md to stable branch

- docs/content/preview/explore/change-data-capture/_index.md
- docs/content/preview/explore/change-data-capture/cdc-get-started.md
- docs/content/preview/explore/change-data-capture/cdc-monitor.md
- docs/content/preview/explore/change-data-capture/cdc-overview.md
- docs/content/preview/explore/change-data-capture/cdc-tutorials/_index.md
- docs/content/preview/explore/change-data-capture/cdc-tutorials/cdc-aws-msk.md
- docs/content/preview/explore/change-data-capture/cdc-tutorials/cdc-azure-event-hub.md
- docs/content/preview/explore/change-data-capture/cdc-tutorials/cdc-confluent-cloud.md
- docs/content/preview/explore/change-data-capture/cdc-tutorials/cdc-redpanda.md
- docs/content/preview/explore/change-data-capture/debezium-connector-yugabytedb.md
- docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes.md
Summary
- Added Early access tags for YBA support for [MCS](https://deploy-preview-17320--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/kubernetes/#configure-kubernetes-multi-cluster-environment) and [CDC](https://deploy-preview-17320--infallible-bardeen-164bc9.netlify.app/preview/explore/change-data-capture/). 
- addressed https://yugabyte.atlassian.net/browse/IDEA-46?atlOrigin=eyJpIjoiNjM4NTY0NjE5ZWQ2NDFhZmI5Mjg4MTcxMmNkMGQ5ZGYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
- Note to self - Todo- update EA link for Performance advisor along with CD and MCS once Dwight's release page is merged.
> [docs] update MCS note and EA tags

- docs/content/preview/admin/yb-admin.md
- docs/content/stable/admin/yb-admin.md
- docs/content/v2.12/admin/yb-admin.md
- docs/content/v2.14/admin/yb-admin.md
- docs/content/v2.16/admin/yb-admin.md
Internal thread https://yugabyte.slack.com/archives/C4K1838GL/p1685431092510919
The commit in question: https://github.com/yugabyte/yugabyte-db/commit/f9c8d2ff443c06d41074c7115b85d128779c4597#diff-0ba0805e8f4b95723324d7862ebd1144f917008cee55f0806c43e43fc646d762R2447
Left it in place in 2.8 since the commit above is not in 2.8.
> [docs] Remove note that says range sharded tablets can't be manually split

- docs/content/preview/contribute/docs/docs-style.md
- docs/content/preview/contribute/docs/widgets-and-shortcodes.md
- docs/layouts/shortcodes/table.html
- Use `{{<table>}} ...{{</table>}}`
- Supports multi-line rows
- supports bullets, code blocks
- Needs full table structure specified in markdown
> Adding table shortcode for multi-line tables

- docs/content/preview/architecture/core-functions/high-availability.md
- docs/content/stable/architecture/core-functions/high-availability.md
- docs/content/v2.12/architecture/core-functions/high-availability.md
- docs/content/v2.14/architecture/core-functions/high-availability.md
- docs/content/v2.16/architecture/core-functions/high-availability.md
- docs/content/v2.8/architecture/core-functions/high-availability.md
Documentation currently says two seconds, which is wrong.  It should say three seconds.
Fixing both preview and stable.
> [Doc][DocDB] Fix unavailability window in documentation

- docs/content/preview/architecture/docdb/persistence.md
- docs/content/stable/architecture/docdb/persistence.md
Changes:
* clarify that there can be zero hash columns
* clarify that the 16-bit hash is only present if there are one or more hash columns
* mention the colocation ID
* fix the discussion of the liveliness column to indicate that it has a row-level TTL not a per-column level TTL.
> [Doc][DocDB] Improve documentation for architecture storage model

- docs/content/preview/architecture/docdb-replication/replication.md
- docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/vmware-tanzu.md
- docs/content/stable/architecture/docdb-replication/replication.md
- docs/content/v2.16/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
- docs/content/v2.16/yugabyte-platform/manage-deployments/remove-nodes.md
Updates to On-Premises provider configuration instructions in 2.16:
- remove node agent
- update centos 7 VM instructions [PLAT-9190]
@netlify /preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises/#configure-hardware-for-yugabytedb-nodes
[PLAT-9190]: https://yugabyte.atlassian.net/browse/PLAT-9190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [docs][yba] Update On-prem provider in 2.16

- docs/content/preview/architecture/transactions/isolation-levels.md
- docs/content/stable/architecture/transactions/isolation-levels.md
Changes:
* internal locking in DocDB section:
* removed references to nonexistent pure-write transactions
* summarized the conflict table in English
* explained why write locks don't block other writers and what that means for concurrent blind writes
* explained that snapshot lock is really a combination of the other two locks
* added section explicitly explaining locking granularities, including which levels we can take lock set
* added an explanation of what strong and weak locks are accomplishing and how they work
* English explanation of the giant conflict table
* removed text talking about how snapshot isolation transactions modifying different columns in the same row can run concurrently
* Piyush says we are removing this functionality
Same changes to both preview and stable …
> [Doc][DocDB] improve architecture isolation levels page

- docs/content/preview/architecture/concepts/yb-tserver.md
- docs/content/preview/reference/configuration/yb-tserver.md
Adds statistics-based full compaction documentation to the `preview` section. This includes:
- Addition of a new section (Statistics-based full compactions to improve read performance) to the `yb-tserver` page, near the other compaction documentation.
- Documentation of the following gflags:
-- auto_compact_check_interval_sec
-- auto_compact_stat_window_seconds
-- auto_compact_percent_obsolete
-- auto_compact_min_obsolete_keys_found
-- auto_compact_min_wait_between_seconds
Also adds the Scheduled Full Compactions documentation to the `preview` documentation (it already exists in the `stable` documentation).
Addresses https://github.com/yugabyte/yugabyte-db/issues/15188
> [Docs][DocDB] Statistics-based full compactions documentation

- docs/content/preview/releases/release-notes/v2.19.md
Fix links on 2.19 RN page
@netlify /preview/releases/release-notes/v2.19/
> [docs] Fix 2.19 links

- docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
If the node is running SELinux and the home directory is customized, set the correct SELinux ssh context
PLAT-9283
@netlify /preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises/#set-up-database-nodes-manually
> [doc][yba][PLAT-9283] Add SELinux step for on-prem

- docs/content/preview/yugabyte-cloud/cloud-basics/create-clusters-topology.md
Currently there is a commented out section on this page that talks about xCluster replication using outdated terminology and gives incorrect information about consistency.
This diff changes just the commented out section (so no visible changes) with more recent terminology and somewhat better information about consistency.  Probably still needs additional editing if we were to make it visible.
Terminology changes:
* sink -> target
* cluster -> universe
* we replicate between universes, not clusters
* nonetheless, the feature is called xCluster replication :-(
I have temporarily uncommented out the section so you can see it in the preview.  I will return it to being commented out before I land it.
This page does not occur in stable so I will not be backporting it.
The edited version has a …
> Update create-clusters-topology.md on cross universe replication

- src/postgres/src/backend/parser/analyze.c
- src/postgres/src/backend/tcop/postgres.c
- src/yb/client/client.cc
- src/yb/client/client.h
- src/yb/common/common.proto
- src/yb/tserver/pg_client.proto
- src/yb/tserver/pg_client_service.cc
- src/yb/tserver/pg_client_service.h
- src/yb/yql/pggate/pg_client.cc
- src/yb/yql/pggate/pg_client.h
- src/yb/yql/pggate/pg_session.cc
- src/yb/yql/pggate/pg_session.h
- src/yb/yql/pggate/pggate.cc
- src/yb/yql/pggate/pggate.h
- src/yb/yql/pggate/ybc_pg_typedefs.h
- src/yb/yql/pggate/ybc_pggate.cc
- src/yb/yql/pggate/ybc_pggate.h
This diff fetches TServer UUID and stores it in the pg_session object so that it can be used to fill up the outgoing rpcs and also be accessible from PG.
Also, another field is added to the PgPerformOptionsPB called AUHMetadataPB, which is required for the necessary data to be sent from PG to TServer.
> Fetch TServer UUID and send AUH Metadata along with the Perform protobuf

- docs/content/preview/architecture/docdb-replication/_index.md
- docs/content/preview/architecture/docdb-replication/change-data-capture.md
- docs/content/preview/architecture/docdb-replication/read-replicas.md
- docs/content/preview/architecture/docdb-replication/replication.md
- docs/content/stable/architecture/docdb-replication/_index.md
- docs/content/stable/architecture/docdb-replication/change-data-capture.md
- docs/content/stable/architecture/docdb-replication/read-replicas.md
- docs/content/stable/architecture/docdb-replication/replication.md
Changing from using cluster to universe for replication architecture pages
This is fixing the terminology; fixes were already made to the xCluster page -- this is fixing the other pages in this section.
A few other minor fixes are made.
I will backport this to stable once accepted.
> Replication architecture pages: cluster->universe

- src/postgres/src/backend/parser/analyze.c
- src/postgres/src/backend/storage/lmgr/proc.c
- src/postgres/src/backend/tcop/postgres.c
- src/postgres/src/backend/utils/adt/pgstatfuncs.c
- src/postgres/src/backend/utils/misc/pg_yb_utils.c
- src/postgres/src/include/catalog/catalog.h
- src/postgres/src/include/catalog/pg_proc.dat
- src/postgres/src/include/catalog/pg_yb_migration.dat
- src/postgres/src/include/pg_yb_utils.h
- src/postgres/src/include/storage/proc.h
- src/yb/yql/pggate/pg_session.cc
- src/yb/yql/pggate/ybc_pg_typedefs.h
- src/yb/yql/pgwrapper/ysql_migrations/V39_22222_add_wait_event_info.sql
Also add `yb_wait_metadata` fn to list the metadata in the procarray.
```
yugabyte=# select * FROM (pg_stat_get_backend_idset() beid CROSS JOIN yb_wait_metadata(beid)) B;
beid | remote_host | remote_port |       queryid        |            node_uuid             |          top_request_id
------+-------------+-------------+----------------------+----------------------------------+----------------------------------
1 |             |             |                    0 |                                  |
2 |             |             |                    0 |                                  |
3 | 127.0.0.1   |       57985 | -7867685903730603530 | 57dd688b2ce049f2ab28e31e5d544f38 | 2f5abc82761d4c8b9ec241b75e2329d7
4 |             |             |                      | …
```
> Add AUH metadata to procarray

- src/postgres/contrib/yb_auh/Makefile
- src/postgres/contrib/yb_auh/yb_auh--1.0.sql
- src/postgres/contrib/yb_auh/yb_auh.c
- Changed the flag to be circular buffer size in kb rather than the count of items in circular buffer
- Added remaining parameters to the circular buffer and to the auh view.
> Circular buffer size flag: yb_auh.circular_buf_size_kb 

- docs/content/preview/integrations/atomicjar.md
Testcontainers can be used using Java 8. Also, fixing typos.
> [docs] Fix typos in Testcontainers docs

- src/yb/util/wait_state.h
- src/yb/yql/pggate/pg_doc_op.cc
- src/yb/yql/pggate/pg_doc_op.h
- src/yb/yql/pggate/pg_operation_buffer.cc
- src/yb/yql/pggate/pg_operation_buffer.h
- src/yb/yql/pggate/pg_perform_future.cc
- src/yb/yql/pggate/pg_perform_future.h
- src/yb/yql/pggate/pg_session.cc
- src/yb/yql/pggate/pggate.cc
The previous approach of setting the wait_event in PgDocResponse was wrong. It assumed that each Response represented a single Request. That is not true. A response or PerformFuture represents multiple ops. There is no restriction on the type of ops. So a batch may contain reads/writes. Therefore I have introduced a new type `DmlReadWrite` for batches that may have a mix of reads/writes. I am not sure if a mixed batch can occur in practice. 
The old approach has been removed.
Tested that both DmlRead and DmlWrite are set in ProcArray.
```
yugabyte=# select pid, wait_event_type, wait_event, state, query from pg_stat_activity where state='active';
pid  | wait_event_type | wait_event | state  |                                              query …
```
> Fix propagation of event type to PerformFuture

- docs/content/preview/architecture/docdb-sharding/tablet-splitting.md
- docs/content/preview/explore/linear-scalability/sharding-data.md
- docs/content/preview/reference/configuration/yb-master.md
- docs/content/preview/reference/configuration/yb-tserver.md
- docs/content/preview/reference/configuration/yugabyted.md
- docs/content/stable/architecture/docdb-sharding/tablet-splitting.md
- docs/content/stable/explore/linear-scalability/sharding-data.md
- docs/content/stable/reference/configuration/yb-master.md
- docs/content/stable/reference/configuration/yb-tserver.md
- docs/content/v2.14/architecture/docdb-sharding/tablet-splitting.md
- docs/content/v2.14/reference/configuration/yb-master.md
- docs/content/v2.14/reference/configuration/yb-tserver.md
- docs/content/v2.16/architecture/docdb-sharding/tablet-splitting.md
- docs/content/v2.16/reference/configuration/yb-master.md
- docs/content/v2.16/reference/configuration/yb-tserver.md
Update automatic tablet splitting description for 2.18
preview/reference/configuration/yb-tserver/#yb-num-shards-per-tserver
preview/architecture/docdb-sharding/tablet-splitting/#automatic-tablet-splitting
preview/explore/linear-scalability/sharding-data/
@netlify /preview/architecture/docdb-sharding/tablet-splitting/
> [docs][DOC-64] Auto tablet splitting clarification

- docs/content/preview/explore/indexes-constraints/secondary-indexes-ysql.md
- docs/content/preview/troubleshoot/cluster/recover_server.md
- docs/content/stable/explore/indexes-constraints/covering-index-ycql.md
- docs/content/stable/explore/indexes-constraints/covering-index-ysql.md
- docs/content/stable/explore/indexes-constraints/secondary-indexes-with-jsonb-ycql.md
- docs/content/stable/explore/indexes-constraints/secondary-indexes-with-jsonb-ysql.md
- docs/content/stable/explore/indexes-constraints/secondary-indexes-ycql.md
- docs/content/stable/explore/indexes-constraints/secondary-indexes-ysql.md
- fixes #18243 , #17628
@netlify /stable/explore/indexes-constraints/covering-index-ycql/
> [docs] secondary and covering indexes backport, systemd cmd for service identification.

- docs/config/_default/menus.toml
- docs/content/preview/releases/_index.md
- docs/content/preview/releases/versioning.md
- docs/content/preview/releases/yba-releases/_index.md
In Releases section, leftnav, when selecting a release under YBA releases, the core releases menu opens. And selecting item in YBA releases doesn't close Releases menu.
> [Docs] Fix Release section left navigation

- src/postgres/contrib/yb_auh/yb_auh.c
- src/yb/common/common.proto
- src/yb/rpc/yb_rpc.cc
- src/yb/tserver/tablet_service.cc
- src/yb/util/wait_state.cc
- src/yb/util/wait_state.h
- src/yb/yql/pggate/ybc_pg_typedefs.h
- src/yb/yql/pggate/ybc_pggate.cc
There are some RPCs in the TServer which are not from Perform() like CreateTablet, FinishTransaction, Heartbeat, and even ActiveUniverseHistory. Right now, these don't have metadata like top_level_request_id, top_level_node_id, query_id.
This PR adds the method name in the aux_info so we can identify these.
> Add method name in wait_event_aux for TServer RPCs

- docs/content/preview/explore/ycql-language/cassandra-feature-support.md
- `CREATE keyspace if not exists` & `SELECT ... CONTAINS [KEY] ` are now supported.
> Marking newly implemented features as supported.

- src/postgres/src/backend/tcop/postgres.c
Fix to reset QueryId at the end of a call . May have been causing a check failure
>  Fix to reset QueryId at the end of a call. 

- src/postgres/contrib/yb_auh/yb_auh.c
- src/postgres/src/include/miscadmin.h
- src/yb/common/ql_protocol.proto
- src/yb/master/master_tserver.cc
- src/yb/master/master_tserver.h
- src/yb/tserver/pg_client.proto
- src/yb/tserver/pg_client_service.cc
- src/yb/tserver/tablet_server.cc
- src/yb/tserver/tablet_server.h
- src/yb/tserver/tablet_server_interface.h
- src/yb/util/wait_state.cc
- src/yb/util/wait_state.h
- src/yb/yql/cql/cqlserver/cql_processor.cc
- src/yb/yql/cql/cqlserver/cql_rpc.cc
- src/yb/yql/cql/cqlserver/cql_server.cc
- src/yb/yql/cql/cqlserver/cql_service.cc
- src/yb/yql/cql/ql/exec/executor.cc
- src/yb/yql/cql/ql/ql_processor.cc
- src/yb/yql/cql/ql/ql_processor.h
- src/yb/yql/cql/ql/util/ql_env.h
- src/yb/yql/pggate/pg_client.cc
- src/yb/yql/pggate/util/ybc_stat.cpp
Implement a GFlag that allows us to "freeze" wait-states in time to avoid/prevent the jagged-edge effect which could happen if the API to fetch wait-states itself takes too long.
> Ability to Freeze WaitState in time while fetching waitstates.

- docs/content/preview/architecture/transactions/read-committed.md
- docs/content/stable/architecture/transactions/read-committed.md
- docs/content/v2.16/architecture/transactions/read-committed.md
- Also add back the example that uses statement timeouts to workaround deadlocks when not using wait queues.
> [Docs] Update limitations section in Read Committed isolation docs page

- docs/content/preview/yugabyte-platform/security/ldap-authentication-platform.md
This is a bit pedantic, but the terminology gets confusing when talking about options, flags, and values when things are included inside other things.  The quoted text is an example instead of a literal value to be pasted.
> [docs] Update ldap-authentication-platform.md

- docs/content/preview/admin/yb-admin.md
- docs/content/preview/explore/change-data-capture/debezium-connector-yugabytedb.md
- docs/content/stable/admin/yb-admin.md
- docs/content/stable/explore/change-data-capture/debezium-connector-yugabytedb.md
This PR adds the documentation related to using transaction ordering with CDC in YugabyteDB.
> [docs] CDCSDK: Add documentation for transaction ordering with CDC

- docs/content/preview/deploy/manual-deployment/system-config.md
- docs/content/stable/deploy/manual-deployment/system-config.md
- docs/content/v2.12/deploy/manual-deployment/system-config.md
- docs/content/v2.14/deploy/manual-deployment/system-config.md
- docs/content/v2.16/deploy/manual-deployment/system-config.md
- docs/content/v2.8/deploy/manual-deployment/system-config.md
Fixes #18840
systemd docs saying the same thing https://www.freedesktop.org/software/systemd/man/systemd.exec.html
> [docs] Use `bytes` instead of kilobytes for systemd `LimitSTACK`

- src/yb/tools/yb-admin_client.cc
Currently `yb-admin get_xcluster_info` returns invalid JSON which makes parsing long output with tools like `jq` difficult.
Steps to reproduce
Before:
```
$ yb-admin get_xcluster_info | jq
parse error: Invalid numeric literal at line 1, column 63
```
After:
```
$ yb-admin get_xcluster_info | jq
{
"version": 0,
"xcluster_producer_registry": {},
"consumer_registry": {}
}
```
> [#19018] yb-admin get_xcluster_info should return valid JSON

- docs/content/preview/contribute/docs/all-page-elements.md
Replace old grammar/diagram pair with updated codes
@netlify /preview/contribute/docs/all-page-elements/
> [docs] Fix API diagram on Contribute page

- docs/layouts/partials/hooks/body-end.html
There are couple of instances where we have links that goes outside from the docs and technically all those links needs to be open in a new tab, this PR is to fix them. Few examples are mentioned below:
Live Site examples:
1. [Google Spanner](https://docs.yugabyte.com/preview/architecture/docdb-replication/)
2. [Kubernetes multi-zone documentation](https://docs.yugabyte.com/preview/deploy/kubernetes/multi-zone/)
3. [YugabyteDB Managed API](https://docs.yugabyte.com/preview/yugabyte-cloud/managed-automation/)
Preview examples:
1. [Google Spanner](https://deploy-preview-19319--infallible-bardeen-164bc9.netlify.app/preview/architecture/docdb-replication/)
2. [Kubernetes multi-zone documentation](https://deploy-preview-19319--infallible-bardeen-164bc9.netlify.app/preview/deploy/kubernetes/mult …
> [Docs] Add target on external links

- docs/package-lock.json
- docs/package.json
- fix for invalid rules
- forcing `--oldformat` as param to use the previous scheme.
> Updating to rrdiagram@0.0.7

- docs/content/preview/explore/change-data-capture/debezium-connector-yugabytedb.md
- docs/content/preview/releases/release-notes/v2.17.md
- docs/content/stable/explore/change-data-capture/debezium-connector-yugabytedb.md
This PR contains a documentation change to the connector config `database.hostname`. Earlier, this config used to take the IP address of leader node. After a recent change to support fail-over connection in multi-node clusters, this config can now also accept a coma separated list of multiple node addresses (ex: `ip1:port1,ip2:port2,ip3:port3`).
> [docs][CDCSDK] Documentation Changes in Connector config

- docs/content/preview/admin/yb-ctl.md
- docs/content/preview/reference/configuration/yugabyted.md
- docs/content/preview/secure/authentication/host-based-authentication.md
- docs/content/stable/admin/yb-ctl.md
- docs/content/stable/reference/configuration/yugabyted.md
- docs/content/stable/secure/authentication/host-based-authentication.md
- docs/content/v2.16/secure/authentication/host-based-authentication.md
Add info on using local connections with host authentication and need to provide the path to the UNIX socket using -h flag
@netlify /preview/secure/authentication/host-based-authentication/
> [docs] Host authentication and UNIX socket address

- docs/content/preview/deploy/multi-dc/async-replication.md
- docs/content/stable/deploy/multi-dc/async-replication.md
- docs/content/v2.14/deploy/multi-dc/async-replication.md
- docs/content/v2.16/deploy/multi-dc/async-replication.md
Fix the Backup/Restore link on XCluster bootstrap instructions to direct users to YSQL distributed snapshots instead of the main-page for backup/restore
> [docs] Update async-replication.md

- docs/config/_default/config.toml
- docs/layouts/partials/hooks/head-end.html
Universal Analytics properties stopped processing new data so it is better to remove unused code from the website. GA4 was already implemented few months back through GTM.
https://support.google.com/analytics/answer/11583528?hl=en
> [Docs] Remove Universal Analytics code

- docs/src/algolia-search.js
On search result, it should show the page title rather than first heading.
> [Docs] Show the page title rather than first heading

- docs/content/preview/yugabyte-platform/create-deployments/create-universe-multi-zone.md
This gives semantic parity to the first sentence of each of the two tabs: generic and kubernetes.  The existing generic phrasing seems to imply that you cannot create a kubernetes universe in one geographic region across multiple AZs.  But you can; all it takes is using the kubernetes provider -- which is explained on the other tab.
> [docs] Update create-universe-multi-zone.md

- docs/content/preview/contribute/core-database/build-from-src-ubuntu.md
Ubuntu contributor instructions were incorrectly changed by commit
a6a0f8d52b3fbf7ecdfce49ba2140969416928a1:
- gettext package was removed from instructions.  It is needed by
Ubuntu 20.04 (and possibly others).
- Unnecessary packages were added to the instructions, some of which are
duplicates because they show up again later in the page.
Revert those changes to the file.
Also notice that ninja-build package is duplicated in the top section
and "Ninja (optional)" section, so remove it from the top section.  And
update instructions to officially support 23.04.
Validate the instructions using ubuntu:23.04 docker image:
./yb_build.sh release --clang17
sudo apt install file patchelf
./yb_release --no_yugabyted_ui --build_args=--clang17
./yb_release --no_yugabyted_ui --build_args='debug …
> [docs] Fix ubuntu contributor instructions

- src/postgres/contrib/yb_auh/auh_global_views.sql
This script establishes connection with all the servers in the YB cluster and creates a global view for pg_stat_statements and pg_active_universe_history. Since password is needed, we need to pass it as custom.password parameter as show below           
Usage:                                                                                            
$ PGOPTIONS="-c custom.password=${yb_passwd}" bin/ysqlsh -U yugabyte -f auh_global_views.sql
> auh global view

- docs/content/preview/admin/yb-admin.md
- docs/content/preview/manage/upgrade-deployment.md
- docs/content/stable/manage/upgrade-deployment.md
Update the link in upgrade-deployment to point to the promote-auto-flags command in the yb-admin page.
Remove kNewInstallOnly from the allowed values in promote_auto_flags command.
> [Doc] Fix promote-auto-flags doc

- docs/assets/scss/_code_block.scss
Glitch on code block where copy button and text are overlapping in Safari.
> [Docs] Glitch on code block in Safari

- docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
- docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
- docs/content/v2.18/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
Fix these typos
Typo 1: In the first section, Install Node Agent the third bullet talks about installation of node agent with this template ./installer.sh -c install -u https://<yba_address>:9000 -t <api_token> But then immediately below lists an instance of the above template with a different command node configure node-agent node configure -t 1ba391bc-b522-4c18-813e-71a0e76b060a -u http://10.98.0.42:9000 
Typo 2 - In the Reconfigure a node agent section its the opposite of Typo 1. That is, in point 4, we show the template for node configure node-agent node configure -t <api_token> -u https://<yba_address>:9000 But the instance we show is for the install command ./installer.sh  -c install -u http://10.98.0.42:9000 -t 301fc382-cf06-4a1b-b5ef-0c8c45273aef
> Fix two typos with YBA Node agent commands

- docs/content/preview/yugabyte-platform/troubleshoot/install-upgrade-issues/kubernetes.md
- docs/content/stable/yugabyte-platform/troubleshoot/install-upgrade-issues/kubernetes.md
- I observed the following error `0/10 nodes are available: 3 node(s) had volume node affinity conflict, 7 node(s) didn't match Pod's node affinity/selector. preemption: 0/10 nodes are available: 10 Preemption is not helpful for scheduling..` while deploying the YB DB universe through the local(auto) k8s provider. It used the `standard` storage class and had immediate as `volumebindingmode`. I used the troubleshooting guide and observed we haven't mentioned the volume node affinity error. 
- I used the resolution steps from the troubleshooting guide and it worked well.
> [docs][PLAT-11979] Added the volume node affinity error in the troubleshooting guide

- docs/content/preview/api/ysql/the-sql-language/statements/ddl_alter_table.md
- docs/content/stable/api/ysql/the-sql-language/statements/ddl_alter_table.md
> [docs] Add `ADD/DROP PRIMARY KEY` warning that explains table rewrite that happens underneath

- docs/content/preview/deploy/multi-dc/async-replication/async-deployment.md
- docs/content/stable/deploy/multi-dc/async-replication/async-deployment.md
Add a note in xCluster docs for ADD COLUMN ... DEFAULT:
The user must perform the ADD COLUMN ... DEFAULT operation on the target with the computed default value.
> [docs] Document #19259: Add a note in xCluster docs for ADD COLUMN ... DEFAULT 

- docs/content/preview/architecture/docdb-sharding/colocated-tables.md
> [docs] Use `colocation_id` when creating indexes in colocated databases that are xCluster replicated

- docs/content/preview/api/ysql/syntax_resources/ysql_grammar.ebnf
- docs/content/preview/api/ysql/the-sql-language/statements/perf_explain.md
- Added `DIST`/ `DEBUG` to the grammar info.
- Adds explanation for more options
- Adds a caveat about `EXPLAIN` statement on DDL statements.
> Add DIST & DEBUG options to the EXPLAIN page

- docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
- docs/content/v2.18/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
#19893 highlight which configuration options can't be changed after install
- installRoot
- postgres.useExisting
- service_username
- postgres.install.ldap_enabled
@netlify /preview/yugabyte-platform/install-yugabyte-platform/install-software/installer/#configuration-options
> [doc] YBA Installer - Identify settings that can't be reconfigured #19893

- docs/content/preview/deploy/multi-dc/async-replication/async-transactional-tables.md
- docs/content/stable/deploy/multi-dc/async-replication/async-transactional-tables.md
Two typos in the curl command:
- missing single quotes after data (payload missing)
- missing key targetUniverseUUID
> [docs] Correct the statement used to sync YBA with command-line changes

- docs/content/preview/yugabyte-platform/create-deployments/async-replication-platform.md
- docs/content/stable/yugabyte-platform/create-deployments/async-replication-platform.md
- docs/content/v2.18/yugabyte-platform/create-deployments/async-replication-platform.md
For ysql, clicking replication cannot be restarted for a subset of tables in the UI. There will not be an intermediary screen to choose which tables should have replication restarted. The proposed text clarifies that this is for ycql.
> [docs] Clarify difference between ysql and ycql in restarting replication

- docs/content/preview/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md
- docs/content/v2.18/yugabyte-platform/install-yugabyte-platform/prerequisites/installer.md
The docs specified that python 3.8 - 3.11 was installed, but not that the system used that version, as required by the installation scripts. 
The addition provides this clarification as well as an example of how to achieve this on some systems.
> [docs] Ensure users are pointing python & python3 to appropriate version

- docs/content/stable/yugabyte-platform/manage-deployments/edit-config-flags.md
Update edit-config-flags.md to provide guidance on complex configuration values. The common example provided is for ysql_pg_conf_csv.
> Add guidance for complex configuration values on edit-config-flags.md

- docs/assets/scss/_dropdown_list.scss
- docs/layouts/partials/navbar-version-selector.html
Remove the link for the prior versions and add a tool tip indicating that "this feature is not available in the respective version". By using this approach, we can prevent “page not found” issues for the upcoming features.
https://deploy-preview-21311--infallible-bardeen-164bc9.netlify.app/stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/
> [Docs] Disable unsupported versions links in the version dropdown

- docs/assets/scss/_dropdown_list.scss
- docs/assets/scss/_sidebar-tree.scss
Fix arrows on the left nav. They are supposed to be filled but after updating to Font Awesome Pro some are filled now and some outlined.
@netlify /preview/explore/
> [Docs] Arrows on the left nav

- docs/assets/scss/_yb_tabs.scss
- docs/layouts/shortcodes/nav/tabs.html
Allow multiple tabs to show as same size, not the different size as shown here:
https://docs.yugabyte.com/preview/explore/fault-tolerance/handling-region-failures/#third-region-failure
Add `repeatedTabs="true"` parameter on the `nav/tabs` shortcode where you like to have the tabs to be same size.
Current shortcode example:
```
{{<nav/tabs list="local,anywhere" active="local"/>}}
```
Shortcode with repeated tabs example:
```
{{<nav/tabs list="local,anywhere" active="local" repeatedTabs="true" />}}
```
> [Docs] Repeated tabs with the same look

- docs/content/preview/manage/backup-restore/point-in-time-recovery.md
- docs/content/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
- docs/content/stable/manage/backup-restore/point-in-time-recovery.md
- docs/content/stable/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
- docs/content/v2.14/manage/backup-restore/point-in-time-recovery.md
- docs/content/v2.14/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
- docs/content/v2.16/manage/backup-restore/point-in-time-recovery.md
- docs/content/v2.16/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises.md
- docs/content/v2.18/manage/backup-restore/point-in-time-recovery.md
- docs/content/v2.18/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises-manual.md
Fix unix timestamp units for PITR page
@netlify /preview/manage/backup-restore/point-in-time-recovery/#restore-to-a-point-in-time
> [doc] Fix unix timestamp units for PITR page

- docs/netlify.toml
The release notes link on GitHub releases is broken. Redirection has a typo.
> [DOC-303] Fixed release notes broken links

- docs/content/preview/admin/yb-ts-cli.md
This commit introduces a new command called clear_server_metacache which helps the user to delete all the meta-cache stored on a tablet server.
> Update doc for the clearing of meta-cache

- docs/content/preview/architecture/_index.md
- docs/content/preview/architecture/query-layer/_index.md
- docs/content/preview/explore/observability/pg-stat-activity.md
- docs/content/preview/explore/observability/pg-stat-progress-copy.md
- docs/netlify.toml
- We noticed 404s for certain architecture pages that were recently reorganized.
> Add aliases for external links

- docs/content/preview/contribute/core-database/build-from-src-macos.md
- docs/content/preview/contribute/core-database/build-from-src-ubuntu.md
- docs/content/preview/contribute/core-database/includes/build-the-code.md
- docs/content/preview/contribute/core-database/includes/yugabyted-ui.md
At some point, yugabyted-ui started requiring Go version >= 1.20.  While
this generally affects all platforms, only the Ubuntu Go installation
instruction suffered from explicitly specifying the old 1.18 version.
Fix both the Go instructions and the Ubuntu instructions.
Secondly, there are issues building with third-party archive on Ubuntu
20.04 without specifying `--clang16` because the defaults changed to
clang17 at some point.  Since this will probably be a recurring theme,
put a general catch-all note in the build instructions to guide users in
case such an issue is encountered.  (Also, since these instructions
reference `#opt-yb-build`, add that missing section to the macos
instructions.)
Lastly, no longer explicitly mention Ubuntu 23.04 as supported since it
is EOL.  This also …
> [docs] Fix ubuntu coredb contributor instructions

- docs/src/index.js
Removing `console.log`. `console.log()` outputs a message to the console which is mainly used for development purposes.
> [Docs] Remove console.log from the script

- docs/config/_default/menus.toml
In header, cloud URL is pointing to the dev environment which was changed for the Segment integration testing.
> [Docs] Correct cloud URL in header menu

- docs/content/preview/develop/common-patterns/timeseries/partitioning-by-time.md
- docs/content/preview/explore/ysql-language-features/indexes-constraints/secondary-indexes-ysql.md
- docs/content/preview/explore/ysql-language-features/join-strategies.md
- docs/content/preview/explore/ysql-language-features/pg-extensions/extension-auto-explain.md
[This commit](https://github.com/yugabyte/yugabyte-db/commit/7df8abd1a2db3e2d8c6d7b9eac49d948617065cc) updated some of the terminology for the EXPLAIN field names. This diff updates the documentation accordingly.
> [docs] renaming docs to be consistent with #14503

- docs/content/preview/contribute/core-database/build-from-src-almalinux.md
- docs/content/preview/contribute/core-database/build-from-src-centos.md
Update CoreDB contributor instructions, which went out of date some time
ago.
- Add patchelf package to installation instructions.  It was always
required, but what likely happened is that it used to be implicitly
installed as part of a dependency of a different required package, and
that is no longer the case today.
- Note that there may be compilation issues with centos + gcc.
> [docs] Fix coredb contributor instructions for alma, centos

- docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
Include a restart after replicated migration to workaround a specific issue affecting ybc release migration.
> Include a restart after replicated migration

- docs/content/preview/drivers-orms/go/yb-pgx.md
- docs/content/preview/drivers-orms/orms/go/ysql-gorm.md
- docs/content/preview/reference/drivers/go/yb-pgx-reference.md
- docs/content/stable/drivers-orms/go/yb-pgx.md
- docs/content/stable/drivers-orms/orms/go/ysql-gorm.md
- docs/content/stable/reference/drivers/go/yb-pgx-reference.md
- docs/content/v2.14/quick-start/build-apps/go/ysql-gorm.md
- docs/content/v2.16/drivers-orms/orms/go/ysql-gorm.md
- docs/content/v2.18/drivers-orms/orms/go/ysql-gorm.md
The Gorm orm-example was recently updated([PR](https://github.com/YugabyteDB-Samples/orm-examples/pull/115)) to use latest go functionality and smart driver. I have updated the docs to reflect these changes as well. Please take a look and let me know in case of any queries. Thanks!
> [Docs] Update GORM Docs to reflect the latest changes in the Gorm orm-examples application

- src/postgres/src/backend/bootstrap/bootstrap.c
- src/postgres/src/backend/catalog/indexing.c
- src/postgres/src/backend/commands/copy.c
- src/postgres/src/backend/commands/createas.c
- src/postgres/src/backend/commands/matview.c
- src/postgres/src/backend/commands/tablecmds.c
- src/postgres/src/backend/executor/nodeModifyTable.c
- src/postgres/src/backend/executor/ybcModifyTable.c
- src/postgres/src/include/executor/ybcModifyTable.h
In the sample table we have almost all char columns and few varchar columns for both of these data types attlen in pg_attribute table is -1.  Since we have varlen attributes in nocachegetattr function it is going to this part of the code [(nocachecode,](https://github.com/naanagon/yugabyte-db/blob/master/src/postgres/src/backend/access/common/heaptuple.c#L607) [ybcModifyTable](https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/src/backend/executor/ybcModifyTable.c#L326)) . In this way the time complexity is O(n*n) where n is number of attributes.
there is an another for loop in ([nocachecode](https://github.com/naanagon/yugabyte-db/blob/master/src/postgres/src/backend/access/common/heaptuple.c#L607)) as it is doing the same work every time, whey can't we build a prefix sum …
> Enhancing copy throughput by retrieving datums with checkpointing available in TupleTableSlot

- docs/content/preview/api/ycql/ddl_create_index.md
- docs/content/preview/api/ysql/the-sql-language/statements/ddl_create_index.md
- docs/content/preview/develop/learn/data-modeling-ycql.md
- docs/content/preview/develop/learn/data-modeling-ysql.md
- docs/content/preview/explore/ycql-language/indexes-constraints/_index.md
- docs/content/preview/explore/ycql-language/indexes-constraints/secondary-indexes-ycql.md
- docs/content/preview/explore/ysql-language-features/indexes-constraints/_index.md
- docs/content/preview/explore/ysql-language-features/indexes-constraints/secondary-indexes-ysql.md
- docs/content/preview/faq/comparisons/cassandra.md
There have been repeated questions on whether indexes are distributed similarly to tables and if they are colocated. Hence adding a clarification.
> Placing a note about distribution of index vs table

- docs/content/preview/launch-and-manage/monitor-and-alert/metrics/replication.md
- docs/content/stable/launch-and-manage/monitor-and-alert/metrics/replication.md
- docs/content/v2.18/launch-and-manage/monitor-and-alert/metrics/replication.md
- docs/content/v2.20/launch-and-manage/monitor-and-alert/metrics/replication.md
These consumer safe time metrics are reported from yugabyte db in milliseconds and not microseconds: https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/xcluster/xcluster_consumer_metrics.cc#L40
Have also verified by stopping the source universe in a DR setup and observing that the reported number is indeed in milliseconds.
@netlify /preview/launch-and-manage/monitor-and-alert/metrics/replication
> [docs] Update consumer safe time metric unit from microseconds to milliseconds

- docs/config/_default/params.toml
- docs/content/preview/reference/configuration/operating-systems.md
- docs/content/preview/releases/ybdb-releases/v2024.1.md
- docs/content/stable/reference/configuration/operating-systems.md
- docs/content/v2.20/reference/configuration/operating-systems.md
Slack threads:
- Formatting issue - https://yugabyte.slack.com/archives/CDQB8MEAU/p1717726111046699
- https://docs.yugabyte.com/preview/reference/configuration/operating-systems/
For "Ubuntu 18" it is mentioned as "Deprecated in v2.20.0; not supported in v2.21.0.0 release and [upcoming release series](https://docs.yugabyte.com/preview/releases/#upcoming-release-series)", but why are we still listing it with a green tick mark in 2.21 doc section when it is not supported? Same for Red Hat Enterprise Linux 7, Oracle Linux 7, CentOS7, Amazon Linux2 - https://yugabyte.slack.com/archives/CDQB8MEAU/p1717726701546229
On release notes page- https://yugabyte.slack.com/archives/C04RTHBC1M2/p1717712767125199
> [docs] OS support pages update for v2.20, v2024.1, v2.21.

- docs/content/preview/admin/yb-admin.md
- docs/content/preview/explore/change-data-capture/cdc-get-started.md
- docs/content/preview/explore/change-data-capture/debezium-connector-yugabytedb.md
- docs/content/preview/reference/configuration/yb-master.md
- docs/content/preview/reference/configuration/yb-tserver.md
- docs/content/stable/explore/change-data-capture/cdc-get-started.md
- docs/content/stable/explore/change-data-capture/debezium-connector-yugabytedb.md
- docs/content/stable/reference/configuration/yb-master.md
- docs/content/stable/reference/configuration/yb-tserver.md
- docs/content/v2.16/explore/change-data-capture/debezium-connector-yugabytedb.md
- docs/content/v2.16/reference/configuration/yb-master.md
- docs/content/v2.16/reference/configuration/yb-tserver.md
- docs/content/v2.18/explore/change-data-capture/cdc-get-started.md
- docs/content/v2.18/explore/change-data-capture/debezium-connector-yugabytedb.md
- docs/content/v2.18/reference/configuration/yb-master.md
- docs/content/v2.18/reference/configuration/yb-tserver.md
- docs/content/v2.20/explore/change-data-capture/cdc-get-started.md
- docs/content/v2.20/explore/change-data-capture/debezium-connector-yugabytedb.md
- docs/content/v2.20/reference/configuration/yb-master.md
- docs/content/v2.20/reference/configuration/yb-tserver.md
This PR adds the following sections missing from the CDC documentation:
1. Connector compatibility matrix - this lists the version of connector which will be compatible with a given YugabyteDB version.
2. Instructions on troubleshooting failures in case of a table being dropped; this is also valid if a table needs to be dropped.
3. Multiple before image modes supported by YugabyteDB.
DOC-296
> [docs] CDCSDK: Update CDC documentation with missing sections

- docs/content/preview/architecture/docdb-sharding/tablet-splitting.md
- docs/content/preview/reference/configuration/yb-master.md
- docs/content/preview/releases/ybdb-releases/v2.14.md
- docs/content/stable/architecture/docdb-sharding/tablet-splitting.md
- docs/content/stable/reference/configuration/yb-master.md
- docs/content/v2.14/architecture/docdb-sharding/tablet-splitting.md
- docs/content/v2.14/reference/configuration/yb-master.md
- docs/content/v2.18/architecture/docdb-sharding/tablet-splitting.md
- docs/content/v2.18/reference/configuration/yb-master.md
- docs/content/v2.20/architecture/docdb-sharding/tablet-splitting.md
- docs/content/v2.20/reference/configuration/yb-master.md
- Update the default value of `tablet_split_low_phase_size_threshold_bytes` to 128 MiB and `tablet_split_low_phase_shard_count_per_node` to 1.
- Remove the reference to `tablet_split_limit_per_table` since it is now inactive by default
- Add an entry in the flags list for `max_create_tablets_per_ts`, and a corresponding reference in the tablet splitting docs
> [docs] Fix tablet splitting flag default values

- docs/content/preview/reference/configuration/yb-tserver.md
- docs/content/stable/reference/configuration/yb-tserver.md
- docs/content/v2.20/reference/configuration/yb-tserver.md
@netlify preview/reference/configuration/yb-tserver/
Resolves #23232
> [docs] Add ysql_output_buffer_size to yb-tserver config reference.

- docs/content/preview/drivers-orms/java/yugabyte-jdbc.md
- docs/content/preview/drivers-orms/nodejs/yugabyte-node-driver.md
- docs/content/stable/drivers-orms/java/yugabyte-jdbc.md
- docs/content/stable/drivers-orms/nodejs/yugabyte-node-driver.md
- docs/content/v2.18/drivers-orms/java/yugabyte-jdbc.md
- docs/content/v2.18/drivers-orms/nodejs/yugabyte-node-driver.md
- docs/content/v2.20/drivers-orms/java/yugabyte-jdbc.md
- docs/content/v2.20/drivers-orms/nodejs/yugabyte-node-driver.md
From internal thread: https://yugabyte.slack.com/archives/CDQB8MEAU/p1721618032406759
> [docs] Fix load balance keyword in drivers page

- docs/netlify.toml
We are no longer using 6sense tool. Removing their domains from the CSP headers.
> [Docs] Remove 6sense domains from CSP headers

- docs/content/preview/reference/configuration/operating-systems.md
- docs/content/stable/reference/configuration/operating-systems.md
- docs/content/v2.20/reference/configuration/operating-systems.md
Summary: 
- For the 2.20 OS support page, made the changes as suggested in the ticket: https://deploy-preview-23372--infallible-bardeen-164bc9.netlify.app/v2.20/reference/configuration/operating-systems/
- For the v2.21 and v2024.1 pages, the tables are split into supported entries in one and unsupported entries in a second one. 
https://deploy-preview-23372--infallible-bardeen-164bc9.netlify.app/preview/reference/configuration/operating-systems/
https://deploy-preview-23372--infallible-bardeen-164bc9.netlify.app/stable/reference/configuration/operating-systems/
@netlify /preview/reference/configuration/operating-systems/
> [DOC-435] Split supported versus unsupported OSs into two tables.

- docs/content/preview/yugabyte-cloud/cloud-clusters/backup-clusters.md
Admin user on target
DOC-427
Location of backups
DOC-331
> [doc][ybm] Backup and restore clarifications

- docs/content/preview/yugabyte-platform/install-yugabyte-platform/migrate-replicated.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/migrate-replicated.md
> [PLAT-14912] docs warning for install root as subdirectory

- docs/assets/scss/_tables.scss
When the right side panel is hidden, HTML table should cover the entire available content space.
> [Docs] Fix table layout to utilize maximum available space

- docs/layouts/shortcodes/flags/flag-table.html
- Don't error out on Flags XML fetch failure. 
- Or else deploy previews will fail before the release is pushed out.
> Change error to warn

- docs/content/preview/yugabyte-platform/install-yugabyte-platform/migrate-replicated.md
- docs/content/stable/yugabyte-platform/install-yugabyte-platform/migrate-replicated.md
- docs/content/v2.20/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
Don't need to restart YBA after replicated migrate
> [DOC] Remove restart from replicated-migrate start

- docs/content/preview/reference/configuration/all-flags-yb-master.md
- docs/content/preview/reference/configuration/all-flags-yb-tserver.md
- docs/content/stable/reference/configuration/all-flags-yb-master.md
- docs/content/stable/reference/configuration/all-flags-yb-tserver.md
- docs/content/v2.14/reference/configuration/all-flags-yb-master.md
- docs/content/v2.14/reference/configuration/all-flags-yb-tserver.md
- docs/content/v2.18/reference/configuration/all-flags-yb-master.md
- docs/content/v2.18/reference/configuration/all-flags-yb-tserver.md
- docs/content/v2.20/reference/configuration/all-flags-yb-master.md
- docs/content/v2.20/reference/configuration/all-flags-yb-tserver.md
- docs/layouts/shortcodes/all-flags-list.html
- Because it is a plain page with one large table, the page is not indexed by Algolia.
- Separating it into sections with linkable headers
@netlify /preview/reference/configuration/all-flags-yb-master/
> Change flags list from table to sections

- docs/content/preview/deploy/multi-dc/async-replication/async-replication-transactional.md
- docs/content/preview/deploy/multi-dc/async-replication/async-transactional-failover.md
- docs/content/preview/deploy/multi-dc/async-replication/async-transactional-setup-dblevel.md
- docs/content/preview/deploy/multi-dc/async-replication/async-transactional-setup.md
- docs/content/preview/deploy/multi-dc/async-replication/async-transactional-switchover.md
- docs/content/preview/deploy/multi-dc/async-replication/async-transactional-tables.md
- docs/content/stable/deploy/multi-dc/async-replication/async-replication-transactional.md
- docs/content/stable/deploy/multi-dc/async-replication/async-transactional-failover.md
- docs/content/stable/deploy/multi-dc/async-replication/async-transactional-setup-dblevel.md
- docs/content/stable/deploy/multi-dc/async-replication/async-transactional-setup.md
- docs/content/stable/deploy/multi-dc/async-replication/async-transactional-switchover.md
- docs/content/stable/deploy/multi-dc/async-replication/async-transactional-tables.md
Database-level setup of transactional xCluster replication
@netlify /preview/deploy/multi-dc/async-replication/async-replication-transactional/
> [doc][xcluster][2024.1.2] Semi-automatic transactional xCluster

- docs/content/preview/yugabyte-voyager/airgapped.md
> [doc][vgr] Airgapped download links

- docs/content/preview/yugabyte-platform/security/authorization-platform.md
- docs/content/preview/yugabyte-platform/security/create-kms-config/hashicorp-kms.md
- docs/content/stable/yugabyte-platform/security/authorization-platform.md
- docs/content/stable/yugabyte-platform/security/create-kms-config/hashicorp-kms.md
- docs/content/v2.20/yugabyte-platform/security/authorization-platform.md
- docs/content/v2.20/yugabyte-platform/security/create-kms-config/hashicorp-kms.md
Clarify handling of expiring Hashicorp Vault tokens
DOC-451
DOC-447
DOC-438
DOC-465
@netlify /preview/yugabyte-platform/security/create-kms-config/hashicorp-kms/
> [doc][yba] KMS and expiring tokens

- docs/content/preview/manage/_index.md
- docs/content/preview/manage/backup-restore/_index.md
- docs/content/preview/yugabyte-cloud/cloud-clusters/backup-clusters.md
- docs/content/preview/yugabyte-platform/back-up-restore-universes/_index.md
- docs/content/preview/yugabyte-platform/back-up-restore-universes/back-up-universe-data.md
- docs/content/preview/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
- docs/content/preview/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md
- docs/content/preview/yugabyte-platform/back-up-restore-universes/restore-universe-data.md
- docs/content/preview/yugabyte-platform/back-up-restore-universes/schedule-data-backups.md
- docs/content/preview/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-storage.md
- docs/content/stable/manage/_index.md
- docs/content/stable/manage/backup-restore/_index.md
- docs/content/stable/yugabyte-platform/back-up-restore-universes/_index.md
- docs/content/stable/yugabyte-platform/back-up-restore-universes/back-up-universe-data.md
- docs/content/stable/yugabyte-platform/back-up-restore-universes/configure-backup-storage.md
- docs/content/stable/yugabyte-platform/back-up-restore-universes/disaster-recovery/disaster-recovery-setup.md
- docs/content/stable/yugabyte-platform/back-up-restore-universes/restore-universe-data.md
- docs/content/stable/yugabyte-platform/back-up-restore-universes/schedule-data-backups.md
- docs/content/stable/yugabyte-platform/prepare/cloud-permissions/cloud-permissions-storage.md
Backups and DDLs
CLOUDGA-22917
@netlify /preview/manage/backup-restore/
> [doc] Backups and DDLs

- docs/content/preview/reference/configuration/yugabyted.md
- docs/content/preview/releases/ybdb-releases/v2.21.md
- docs/content/preview/releases/ybdb-releases/v2024.1.md
- docs/content/stable/explore/ysql-language-features/postgresql-compatibility.md
- docs/content/stable/reference/configuration/yugabyted.md
As per https://yugabyte.slack.com/archives/CDQB8MEAU/p1726095196976899?thread_ts=1726065292.830579&cid=CDQB8MEAU, 
- enable_pg_parity_early_access is in 2.21
- enable_pg_parity_tech_preview is in 2024.1
> [docs] changed flag "enable_pg_parity_early_access" to "enable_pg_parity_tech_preview" in stable

- docs/content/preview/explore/ysql-language-features/postgresql-compatibility.md
- docs/content/preview/reference/configuration/yugabyted.md
- docs/content/preview/releases/ybdb-releases/v2.21.md
https://github.com/yugabyte/yugabyte-db/pull/23909/files
Verify that in both stable and preview releases, it needs to be `enable_pg_parity_tech_preview`
> [docs] Reverted PR 23909 changes

- docs/content/preview/drivers-orms/smart-drivers.md
- docs/content/preview/faq/smart-drivers-faq.md
- docs/content/preview/yugabyte-cloud/cloud-connect/connect-applications.md
Clarify behavior of smart driver when it doesn't have access to nodes (eg, not peered)
DOC-421
DOC-404
@netlify /preview/faq/smart-drivers-faq/
> [doc] Smart driver clarification

- docs/content/preview/drivers-orms/go/pg.md
- docs/content/preview/drivers-orms/orms/rust/ysql-diesel.md
- docs/content/preview/faq/general.md
- docs/content/preview/manage/data-migration/migrate-from-postgres.md
- docs/content/preview/quick-start-yugabytedb-managed/quick-start-buildapps-include.md
- docs/content/preview/yugabyte-platform/prepare/server-nodes-software/_index.md
- Replace target with YugabyteDB
- Update FAQ trade-offs
- Fix broken links
> Minorfixes

- docs/content/preview/architecture/transactions/concurrency-control.md
- docs/content/preview/develop/learn/transactions/transactions-errorcodes-ysql.md
- docs/content/preview/develop/learn/transactions/transactions-retries-ysql.md
- docs/content/preview/explore/transactions/distributed-transactions-ysql.md
- docs/content/stable/architecture/transactions/concurrency-control.md
- docs/content/stable/develop/learn/transactions/transactions-errorcodes-ysql.md
- docs/content/stable/develop/learn/transactions/transactions-retries-ysql.md
- docs/content/stable/explore/transactions/distributed-transactions-ysql.md
- docs/content/v2.18/develop/learn/transactions/transactions-retries-ysql.md
- docs/content/v2.20/develop/learn/transactions/transactions-retries-ysql.md
1. Remove remaining usage of the words "optimistic" and "pessimistic" for concurrency control modes in distributed-transactions-ysql.md.
2. Fix information around serialization errors and deadlock errors in transactions-errorcodes-ysql.md and transactions-retries-ysql.md.
3. Replace usage of ysql_max_write_restart_attempts with yb_max_query_layer_retries in concurrency-control.md.
> [Docs] Minor fixes to docs pages around transactions

- docs/content/preview/drivers-orms/go/yb-pgx-reference.md
- docs/content/preview/drivers-orms/java/postgres-jdbc.md
- docs/content/preview/drivers-orms/java/yugabyte-jdbc.md
- docs/content/preview/drivers-orms/nodejs/postgres-node-driver.md
- docs/content/preview/drivers-orms/nodejs/postgres-pg-reference.md
- docs/content/preview/drivers-orms/nodejs/yugabyte-node-driver.md
- docs/content/preview/drivers-orms/orms/nodejs/ysql-prisma.md
- docs/content/preview/drivers-orms/python/postgres-psycopg2.md
- docs/content/preview/drivers-orms/python/yugabyte-psycopg2.md
- docs/content/preview/drivers-orms/rust/rust-postgres-reference.md
- docs/content/preview/explore/change-data-capture/using-yugabytedb-grpc-replication/debezium-connector-yugabytedb.md
- docs/content/preview/integrations/hashicorp-vault.md
- docs/content/preview/tutorials/azure/azure-api-management.md
- docs/content/preview/tutorials/azure/azure-private-link.md
- docs/content/stable/drivers-orms/go/yb-pgx-reference.md
- docs/content/stable/drivers-orms/java/postgres-jdbc.md
- docs/content/stable/drivers-orms/java/yugabyte-jdbc.md
- docs/content/stable/drivers-orms/nodejs/postgres-node-driver.md
- docs/content/stable/drivers-orms/nodejs/postgres-pg-reference.md
- docs/content/stable/drivers-orms/nodejs/yugabyte-node-driver.md
- docs/content/stable/drivers-orms/orms/nodejs/ysql-prisma.md
- docs/content/stable/drivers-orms/python/postgres-psycopg2.md
- docs/content/stable/drivers-orms/python/yugabyte-psycopg2.md
- docs/content/stable/drivers-orms/rust/rust-postgres-reference.md
- docs/content/stable/explore/change-data-capture/using-yugabytedb-grpc-replication/debezium-connector-yugabytedb.md
> [doc][ybm] Certificate links

- docs/content/preview/explore/change-data-capture/using-logical-replication/monitor.md
- docs/content/preview/explore/change-data-capture/using-yugabytedb-grpc-replication/cdc-monitor.md
- docs/content/stable/explore/change-data-capture/using-logical-replication/monitor.md
- docs/content/stable/explore/change-data-capture/using-yugabytedb-grpc-replication/cdc-monitor.md
- docs/content/v2.18/explore/change-data-capture/cdc-monitor.md
- docs/content/v2.20/explore/change-data-capture/cdc-monitor.md
In the current CDC documentation, the name of the lag metric is incorrectly mentioned as `cdcsdk_event_lag_micros`. (For example [here](https://docs.yugabyte.com/preview/explore/change-data-capture/using-logical-replication/monitor/#cdc-service-metrics)).
This PR corrects the name to `cdcsdk_sent_lag_micros`.
> [#24166] DOCS: CDCSDK: Fix lag metric name in documentation

- docs/content/preview/faq/yugabytedb-managed-faq.md
- docs/content/preview/yugabyte-cloud/cloud-clusters/backup-clusters.md
#21105
@netlify /preview/faq/yugabytedb-managed-faq/
> [doc][ybm] Add reasoning behind no access to yugabyte user #21105

- docs/assets/scss/_code_block.scss
Code snippet style inside the call out section is broken. Missing all paddings [View the issue](https://docs.yugabyte.com/stable/explore/going-beyond-sql/#cluster-topology).
> [Docs] Fix Code snippet

- docs/content/preview/yugabyte-voyager/migrate/live-fall-forward.md
- docs/layouts/_default/single.html
- docs/src/index.js
Previously, we have build a functionality to switch all tabs on the same page by clicking on the single tab. This PR fixes that functionality.
1. JS changed to work on all the pages
2. Make `id` attribute same in Content file for `/preview/yugabyte-voyager/migrate/live-fall-forward/`.
Changes verified on the following pages:
- https://deploy-preview-24276--infallible-bardeen-164bc9.netlify.app/preview/api/ysql/user-defined-subprograms-and-anon-blocks/subprogram-attributes/
- https://deploy-preview-24276--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-voyager/migrate/live-fall-forward/
> [Docs] Switch multiple tabbed sections

- src/postgres/src/backend/optimizer/util/pathnode.c
This PR addresses a bug that can result in a division by zero when calculating selectivity in yb_create_distinct_index_path.
This addresses issue [#24568](https://github.com/yugabyte/yugabyte-db/issues/24568) by enhancing the reliability of the selectivity computation.
Please review my implementation and provide feedback.
> Fix division by zero error in selectivity calculation

- docs/assets/scss/_dropdown_list.scss
- docs/assets/scss/_styles_project.scss
- docs/assets/scss/_yb_tags.scss
- docs/content/_index.md
- docs/layouts/_default/content.html
- docs/layouts/_default/single.html
- docs/layouts/indexpage/list.html
- docs/layouts/partials/navbar-version-selector.html
- docs/layouts/partials/navbar.html
- docs/layouts/partials/sidebar-tree.html
> [Docs] Improved version selector

- docs/content/preview/architecture/docdb-replication/async-replication.md
- docs/content/preview/architecture/docdb-replication/replication.md
- docs/content/preview/deploy/checklist.md
- docs/content/stable/architecture/docdb-replication/async-replication.md
- docs/content/stable/architecture/docdb-replication/replication.md
- docs/content/stable/deploy/checklist.md
Odd RF numbers are allowed and safe. Clarifying why even RF us preferable to odd RF.
> [Doc] Clarify usage of odd RF numbers

- docs/assets/scss/_yb_headings.scss
- docs/src/index.js
When the banner is enabled, clicking on a heading link in the right navigation takes the user to a location below the actual heading section.
> [Docs] Right nav heading links are misdirected

- docs/netlify.toml
The Content Security Policy (CSP) Frame Ancestors header contains a legacy Netlify preview URL. Following internal deliberation, we may consider removing this header to enhance security posture.
> [Docs] Remove old Netlify preview URL from CSP Frame Ancestors header

- docs/content/preview/releases/yba-releases/v2.23.md
- docs/content/preview/releases/ybdb-releases/v2.23.md
- docs/data/currentVersions.json
@netlify /preview/releases/ybdb-releases/v2.23/#v2.23.1.0
> [docs] Release notes for 2.23.1.0

- managed/api-examples/python-simple/user-management.ipynb
The notebook provides examples for the following YBA platform user management tasks:
- list current users
- get details for a specific user
- create a user
- delete a user
> Add a notebook for example user management platform API endpoint calls

- docs/content/preview/yugabyte-platform/alerts-monitoring/anywhere-export-configuration.md
- docs/content/stable/yugabyte-platform/alerts-monitoring/anywhere-export-configuration.md
- docs/content/v2024.2/yugabyte-platform/alerts-monitoring/anywhere-export-configuration.md
Add requirements for logWriter role and project scoping detail to the section on configuring GCP cloud logging, to make it easier for user to understand the full requirements when setting up this integration.
> [DOC-529] Add requirements for roles and scoping to GCP cloud logging for DBAL

- docs/content/stable/reference/configuration/yugabyted.md
- docs/content/v2024.2/explore/observability/active-session-history.md
- docs/content/v2024.2/explore/ysql-language-features/pg-extensions/extension-pgcron.md
- docs/content/v2024.2/manage/backup-restore/instant-db-cloning.md
- docs/content/v2024.2/reference/configuration/yb-tserver.md
Summary:
- https://yugabyte.atlassian.net/issues/DOC-536 - xCluster support in yugabyted - This is supposed to be EA in 2024.1 (so added the ea tag in stable (2024.1) as it was missing)
- https://yugabyte.atlassian.net/issues/DOC-502 - [tp->ga] pg_cron extension - Changed this.
- https://yugabyte.atlassian.net/jira/polaris/projects/IDEA/ideas/view/5361900?selectedIssue=IDEA-990&issueViewSection=comments - [tp->ea] DB cloning done, added limitations.
- https://yugabyte.atlassian.net/jira/polaris/projects/IDEA/ideas/view/5361900?selectedIssue=IDEA-830&issueViewLayout=sidebar&issueViewSection=overview - [tp->ea] ASH done.
[IDEA-260](https://yugabyte.atlassian.net/jira/polaris/projects/IDEA/ideas/view/5162660?selectedIssue=IDEA-260&issueViewSection=comments) - removed EA tag for this flag …
> [DOC-502] [DOC-536] [DOC-551] [DOC-533] [2024.2]Changing tags for DB features 

- docs/layouts/shortcodes/table.html
- Use a non-printing character as the temporary splitter/placeholder
- remove debug statements
-
> Replace 7E with 01

- docs/content/preview/yugabyte-cloud/_index.md
- docs/content/preview/yugabyte-platform/_index.md
- docs/content/preview/yugabyte-voyager/_index.md
- docs/content/stable/yugabyte-platform/_index.md
- docs/content/v2.14/yugabyte-platform/_index.md
- docs/content/v2.18/yugabyte-platform/_index.md
- docs/content/v2.20/yugabyte-platform/_index.md
- docs/content/v2024.1/yugabyte-platform/_index.md
Problem with the breadcrumbs - they take their text from the linkTitle, which overrides title and name.
> [Docs] Fix Breadcrumb to show Product name rather than Overview

- docs/config/_default/menus.toml
- docs/content/preview/releases/_index.md
- docs/content/preview/releases/versioning.md
- docs/content/preview/releases/yba-releases/_index.md
- docs/content/preview/releases/ybdb-releases/_index.md
- docs/content/preview/releases/ybdb-releases/v2.23.md
- docs/content/preview/releases/ybdb-releases/v2024.2.md
Releases format and minor reorg
> [doc] Releases format and minor reorg

- docs/content/preview/releases/versioning.md
Clarification of release numbering
@netlify /preview/releases/versioning/
> [doc] Clarification of release numbering

- docs/content/preview/architecture/docdb-replication/async-replication.md
- docs/content/preview/deploy/multi-dc/async-replication/async-replication-transactional.md
- docs/content/stable/architecture/docdb-replication/async-replication.md
- docs/content/stable/deploy/multi-dc/async-replication/async-replication-transactional.md
- docs/content/v2.18/architecture/docdb-replication/async-replication.md
- docs/content/v2.20/architecture/docdb-replication/async-replication.md
- docs/content/v2.20/deploy/multi-dc/async-replication/async-replication-transactional.md
- docs/content/v2024.1/architecture/docdb-replication/async-replication.md
- docs/content/v2024.1/deploy/multi-dc/async-replication/async-replication-transactional.md
xCluster target backup limitation
@netlify /preview/architecture/docdb-replication/async-replication/#limitations
> [doc] xCluster target backup limitation

- docs/content/preview/develop/change-data-capture/using-logical-replication/_index.md
- docs/content/stable/develop/change-data-capture/using-logical-replication/_index.md
- docs/content/v2024.1/develop/change-data-capture/using-logical-replication/_index.md
Updated logical replication limitations to reflect the recent changes of allowing table re-write DDLs before the slot creation.
For more info:
1. [Table Re-write DDLs Before Slot Creation](https://docs.google.com/document/d/1AYq1OXyJLbH7kVdtyOC8KvG7RAgiO8tLYsHYEZK2B4M/edit?tab=t.0#heading=h.rdfsjqxh6mj8)
2. [Issues with DDLs in Logical Replication](https://docs.google.com/document/d/1KQvVOi-tB4TKw1uEOAMZ-4Ur7AP-AwKccvk-LVWln5M/edit?tab=t.0#heading=h.kr5zym3bg5pk)
DOC-611
> [doc][cdc] Update logical replication limitation on table rewrite DDLs

- docs/content/stable/develop/best-practices-ysql.md
- docs/content/stable/explore/going-beyond-sql/connection-mgr-ysql.md
- docs/content/stable/yugabyte-platform/create-deployments/create-universe-multi-zone.md
- docs/content/stable/yugabyte-platform/manage-deployments/edit-universe.md
Updating connection manager to EA from Tech Preview on 2024.2 docs
@netlify /stable/explore/going-beyond-sql/connection-mgr-ysql/
> [doc][2024.2.1] Update YSQL Connection Manager to EA tag

- docs/content/stable/explore/going-beyond-sql/connection-mgr-ysql.md
This PR adds the "Limitations" section for v2024.2 docs of YSQL Connection Manager.
@netlify /stable/explore/going-beyond-sql/connection-mgr-ysql/
> [doc][2024.2.1] Added limitations for YSQL Connection Manager

- docs/content/preview/explore/colocation.md
- docs/content/preview/explore/going-beyond-sql/tablespaces.md
- docs/content/stable/explore/going-beyond-sql/tablespaces.md
Tablespaces support for colocated tables and databases was introduced in 2024.2.0
Copy to preview and add section to Colocation page
> [doc][2.25] Update docs to remove limitation of tablespaces for colocated tables

- docs/content/preview/secure/authentication/host-based-authentication.md
- docs/content/preview/secure/tls-encryption/tls-authentication.md
- docs/content/stable/secure/tls-encryption/tls-authentication.md
- docs/content/v2.20/secure/tls-encryption/tls-authentication.md
- docs/content/v2024.1/secure/tls-encryption/tls-authentication.md
`md5 clientcert=1` in the hba conf file was documented to mean a combination of md5 and cert - however, there is a slight distinction. The cert method verifies the client cert and authenticates the user using the CN of the client cert. clientcert=1 only verifies the client cert.
> [DOC-610] Clarify the meaning of clientcert=1 in TLS docs

- docs/content/preview/reference/configuration/yugabyted.md
- docs/content/stable/reference/configuration/yugabyted.md
- docs/content/v2024.1/reference/configuration/yugabyted.md
Summary:
* Changing the example to include a backslash before a double quote `"` inside any CSV flag value as part of `tserver_flags` or `master_flags`.
* Affected versions: preview(2.25), stable(2024.2), 2024.1
> [docs]yugabyted: Updating example of `Pass additional flags to YB-Master and YB-TServer` in yugabyted

- docs/content/stable/api/ysql/the-sql-language/statements/ddl_create_index.md
@netlify /stable/api/ysql/the-sql-language/statements/ddl_create_index/#split-at-values
> [doc] Fix syntax error in DDL create index example

- docs/content/stable/explore/going-beyond-sql/connection-mgr-ysql.md
Documentation for the new gflag added for YSQL connection manager
2024.2.1 and 2.25.1
> [YSQL][docs][2024.2.1] YSQL connection manager gflags docs

- docs/assets/scss/_admonition.scss
Some of our banners seem to be not aligned right in this example.
The icon is vertically centered but the copy is more top aligned.
@netlify /preview/tutorials/build-apps/cloud-add-ip/
> [Docs] Vertically align text in note

- .github/workflows/build.yml
Ubuntu-20.04 is being deprecated by github. Run docker on 24.04 instead.
> [DEVOPS-3352] build: Update github runners' OS

- docs/content/preview/develop/change-data-capture/using-logical-replication/_index.md
- docs/content/preview/develop/change-data-capture/using-yugabytedb-grpc-replication/_index.md
- docs/content/preview/yugabyte-platform/manage-deployments/xcluster-replication/_index.md
- docs/content/stable/develop/change-data-capture/using-logical-replication/_index.md
- docs/content/stable/develop/change-data-capture/using-yugabytedb-grpc-replication/_index.md
- docs/content/stable/yugabyte-platform/manage-deployments/xcluster-replication/_index.md
- docs/content/v2.14/explore/change-data-capture/_index.md
- docs/content/v2.18/explore/change-data-capture/cdc-overview.md
- docs/content/v2.20/explore/change-data-capture/cdc-overview.md
- docs/content/v2024.1/develop/change-data-capture/using-logical-replication/_index.md
- docs/content/v2024.1/develop/change-data-capture/using-yugabytedb-grpc-replication/_index.md
- docs/content/v2024.1/yugabyte-platform/manage-deployments/xcluster-replication/_index.md
We have inconsistent documentation regarding the support of CDC on xCluster source / target universes. This doc PR fixes these inconsistencies.
CDC is not supported on both the xCluster source as well as target universes.
> [doc] Fix inconsistent documentation regarding CDC + xCluster

- docs/content/preview/tutorials/quick-start/linux.md
- docs/content/preview/tutorials/quick-start/macos.md
@netlify /preview/tutorials/quick-start/linux/#connect-to-the-database
> [doc] Update include syntax in quick-start tutorials for Linux and macOS

- docs/content/preview/integrations/_index.md
- docs/content/preview/integrations/apache-spark/java-ycql.md
- docs/content/preview/integrations/apache-spark/java-ysql.md
- docs/content/preview/integrations/apache-spark/python-ysql.md
- docs/content/preview/integrations/apache-spark/scala-ysql.md
- docs/content/preview/integrations/apache-spark/spark-sql.md
A new plugin, `spark-yugabytedb-dialect`, has been created for spark to use it with yugabytedb. Updating the doc to add that as a dependency. More details on the plugin are in the [doc](https://docs.google.com/document/d/1Bf8A3cfG8XXh2j203m2UeiHX6u0k2UE36D4-w5GUuws/edit?tab=t.0#heading=h.xjdxcpkwfbzt) and the [spark-yugabytedb-dialect](https://github.com/yugabyte/spark-yugabytedb-dialect) repository.
> [Docs] Update spark ysql doc to add spark yugabytedb dialect

- docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-api-key.md
https://github.com/netlify /preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-api-key/
> [DOC-625][docs][cli][ybm] CLI documentation for additional functionality in API keys

- docs/content/preview/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_is_local_table.md
- docs/content/preview/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_region.md
- docs/content/preview/develop/gitdev/codespaces.md
- docs/content/preview/develop/gitdev/gitpod.md
- docs/content/preview/explore/going-beyond-sql/tablespaces-yugabyted.md
- docs/content/preview/explore/going-beyond-sql/tablespaces.md
- docs/content/preview/integrations/cdc/debezium.md
- docs/content/preview/tutorials/quick-start/linux.md
- docs/content/stable/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_is_local_table.md
- docs/content/stable/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_region.md
- docs/content/stable/develop/gitdev/codespaces.md
- docs/content/stable/develop/gitdev/gitpod.md
- docs/content/stable/explore/going-beyond-sql/tablespaces-yugabyted.md
- docs/content/stable/explore/going-beyond-sql/tablespaces.md
- docs/content/v2.20/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_is_local_table.md
- docs/content/v2.20/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_region.md
- docs/content/v2.20/develop/gitdev/codespaces.md
- docs/content/v2.20/develop/gitdev/gitpod.md
- docs/content/v2.20/explore/ysql-language-features/going-beyond-sql/tablespaces-yugabyted.md
- docs/content/v2024.1/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_is_local_table.md
- docs/content/v2024.1/api/ysql/exprs/geo_partitioning_helper_functions/func_yb_server_region.md
- docs/content/v2024.1/develop/gitdev/codespaces.md
- docs/content/v2024.1/develop/gitdev/gitpod.md
- docs/content/v2024.1/explore/going-beyond-sql/tablespaces-yugabyted.md
- docs/content/v2024.1/explore/going-beyond-sql/tablespaces.md
@netlify /preview/tutorials/quick-start/linux/#create-a-local-cluster
> [DOC-428][doc] Fix Linux yugabyted examples

- docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-examples/managed-cli-example-create.md
- docs/content/preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-reference/managed-cli-cluster.md
@netlify /preview/yugabyte-cloud/managed-automation/managed-cli/managed-cli-examples/managed-cli-example-create/#create-update-and-describe-an-ear-enabled-cluster
> [DOC-428][doc][ybm] CLI example for EAR

- docs/content/stable/explore/going-beyond-sql/connection-mgr-ysql.md
> [doc][2024.2.2] Added sticky connections section to Connection Manager docs

- docs/assets/scss/_styles_project.scss
- docs/assets/scss/_yb_page_finder.scss
- docs/content/preview/manage/backup-restore/_index.md
- docs/content/preview/yugabyte-cloud/cloud-clusters/backup-clusters.md
- docs/content/preview/yugabyte-platform/back-up-restore-universes/_index.md
- docs/layouts/shortcodes/page-finder/head.html
- docs/layouts/shortcodes/page-finder/list.html
- docs/src/index.js
- docs/static/icons/bookmark.svg
Create a Hugo shortcode to convey that the workflow can be done in the other products (as applicable) and incorporating link to relevant page.
```md
{{< page-finder/head text="Back Up and Restore" subtle="across different products">}}
{{< page-finder/list icon="/icons/database-hover.svg" text="YugabyteDB" current="" >}}
{{< page-finder/list icon="/icons/server-hover.svg" text="YugabyteDB Anywhere" url="../../yugabyte-platform/back-up-restore-universes/" >}}
{{< page-finder/list icon="/icons/cloud-hover.svg" text="YugabyteDB Aeon" url="../../yugabyte-cloud/cloud-clusters/backup-clusters/" >}}
{{< /page-finder/head >}}
```
> [Docs] Create a Note block to link to other product pages

- docs/content/v2.20/reference/configuration/yugabyted.md
Looks like `backup_daemon` is only available in 2.21+ after checking source code and releases https://github.com/yugabyte/yugabyte-db/issues/18416
This was added mistakenly in this commit https://github.com/yugabyte/yugabyte-db/pull/24425/files#diff-0e3061a60df89f868758027263270653dc1ac6bb20b5f9ead17c8dfb3e752594.
> [docs] Remove `backup_daemon` from 2.20 docs because it's not available

- docs/content/preview/explore/going-beyond-sql/connection-mgr-ysql.md
- docs/content/stable/explore/going-beyond-sql/connection-mgr-ysql.md
Remove mention of requirement of preview flag for connection manager on stable docs
> [doc] Update Connection Manager stable docs

- docs/content/preview/tutorials/cdc-tutorials/cdc-confluent-cloud.md
This PR adds the changes required to fix some typos and missing redirects to Confluent's documentation.
> [docs] CDC: Fix typos in CDC with Confluent tutorial

- docs/content/preview/api/ysql/syntax_resources/ysql_grammar.ebnf
- docs/content/preview/api/ysql/the-sql-language/statements/ddl_create_database.md
- docs/content/stable/api/ysql/syntax_resources/ysql_grammar.ebnf
- docs/content/stable/api/ysql/the-sql-language/statements/ddl_create_database.md
Adds `CREATE DATABASE ... AS OF <timestamp>` syntax to the railroad diagram for `CREATE DATABASE`.
> [doc] Add db clone to CREATE DATABASE railroad diagram

- docs/content/preview/drivers-orms/include-drivers-orms-list.md
- docs/content/preview/drivers-orms/nodejs/_index.md
- docs/content/preview/drivers-orms/nodejs/prisma.md
- docs/content/preview/drivers-orms/nodejs/sequelize.md
- docs/content/preview/drivers-orms/nodejs/typeorm.md
- docs/content/preview/integrations/typeorm.md
- docs/content/stable/drivers-orms/include-drivers-orms-list.md
- docs/content/stable/drivers-orms/nodejs/_index.md
- docs/content/stable/drivers-orms/nodejs/prisma.md
- docs/content/stable/drivers-orms/nodejs/sequelize.md
- docs/content/stable/drivers-orms/nodejs/typeorm.md
- docs/content/v2.20/drivers-orms/include-drivers-orms-list.md
- docs/content/v2.20/drivers-orms/nodejs/_index.md
- docs/content/v2.20/drivers-orms/nodejs/prisma.md
- docs/content/v2.20/drivers-orms/nodejs/sequelize.md
- docs/content/v2.20/drivers-orms/nodejs/typeorm.md
- docs/content/v2024.1/drivers-orms/include-drivers-orms-list.md
- docs/content/v2024.1/drivers-orms/nodejs/_index.md
- docs/content/v2024.1/drivers-orms/nodejs/prisma.md
- docs/content/v2024.1/drivers-orms/nodejs/sequelize.md
- docs/content/v2024.1/drivers-orms/nodejs/typeorm.md
Changes to include CRUD example for typeORM
> [Docs] Add documentation for typeorm

- src/yb/consensus/raft_consensus.cc
This PR fixes https://github.com/yugabyte/yugabyte-db/issues/1348
It brings in delayed validators to make sure `raft_heartbeat_interval_ms` is less than `leader_lease_duration_ms`
> [#1348] DocDB: Add validator for leader lease to be larger than heartbeat interval

- docs/content/preview/yugabyte-voyager/known-issues/postgresql.md
https://deploy-preview-27325--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-voyager/known-issues/postgresql/#hotspots-with-range-sharded-timestamp-date-indexes
> [Docs] [Voyager] Minor changes to Hotspots with timestamp indexes issue in PostgreSQL schema review workaround

- python/yugabyte/csi_report.py
Quick fix that won't be exercised by diff build/test -- currently only enabled on official builds.
> i[DEVOPS-3400] test automation: Fix log-upload API parsing

- docs/assets/scss/_code_block.scss
- docs/assets/scss/_tables.scss
- docs/layouts/shortcodes/table.html
Currently, table short code allows adding code block in between the columns. However in short code, it doesn't respect the indentation if there are any in the code block. 
This PR fixes this issue and allows indentation inside code block under table short code.
> [Docs] Allow indentation in the code block inside table shortcode

- docs/content/preview/tutorials/quick-start/docker.md
Fixes [#27619](https://github.com/yugabyte/yugabyte-db/issues/27619)
> [docs] Use spaces on port number in `docker run -p` command

- docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
- docs/content/stable/explore/ysql-language-features/pg-extensions/extension-pgcron.md
- docs/content/v2025.1/explore/ysql-language-features/pg-extensions/extension-pgcron.md
The recommendation is to first drop the extension and then change the cron database name. Already present, tweaked text to make it more prominent
@netlify /preview/explore/ysql-language-features/pg-extensions/extension-pgcron/#set-up-pg-cron
> [DOC-760] Tweak pgcron text

- docs/content/preview/explore/observability/active-session-history.md
- docs/content/preview/releases/ybdb-releases/v2.25.md
Verify that - 2.25 docs has the EA badge. No changes needed for 2025.1.
@netlify /preview/explore/observability/active-session-history/
> [DOC-825] [2025.1] [EA->GA] Active session history changes

- docs/content/preview/reference/configuration/yugabyted.md
- docs/content/v2025.1/reference/configuration/yugabyted.md
These changes affect preview and 2025.1
DOC-770
Changes:
* xCluster automatic mode is now marked as early access instead of technical preview
* the use of the word "cluster" has been fixed
* when it means all nodes including the primary and read clusters, "universe" is correct
* when it is referring only to a subset of nodes such as just the read cluster, "cluster" is correct
* fixing this is necessary for this page because we use both meaning and it would be confusing otherwise
* warn about the state of target databases after dropping or removing replication in some cases
* the reference is correct but I haven't put in the details of the problem in the target page yet (separate pull request)
* fixed the bootstrapping stuff; the previous link did not exist
* made it clear that …
> Update yugabyted public documentation for xCluster changes in 2025.1

- managed/devops/opscli/ybops/cloud/aws/cloud.py
- managed/devops/opscli/ybops/cloud/azure/utils.py
- managed/devops/opscli/ybops/cloud/common/method.py
- managed/devops/opscli/ybops/cloud/common/utils.py
- managed/devops/opscli/ybops/cloud/gcp/cloud.py
- python/yugabyte/common_util.py
- python/yugabyte/kill_long_running_minicluster_daemons.py
- python/yugabyte/lto.py
- scripts/installation/bin/yb-ctl
This PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
It also fixes a few typos along the way.
> Resolve logger warnings

- docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
- docs/content/stable/yugabyte-platform/administer-yugabyte-platform/high-availability.md
- docs/content/v2.20/yugabyte-platform/administer-yugabyte-platform/high-availability.md
- docs/content/v2024.1/yugabyte-platform/administer-yugabyte-platform/high-availability.md
- docs/content/v2025.1/yugabyte-platform/administer-yugabyte-platform/high-availability.md
Sign in after HA failover must use Super User
@netlify /preview/yugabyte-platform/administer-yugabyte-platform/high-availability/#promote-a-standby-instance-to-active
> [DOC-359][yba] Sign in after HA failover

- docs/content/preview/api/ysql/the-sql-language/statements/ddl_create_index.md
- docs/content/preview/reference/configuration/yb-tserver.md
- docs/content/stable/api/ysql/the-sql-language/statements/ddl_create_index.md
- docs/content/stable/reference/configuration/yb-tserver.md
- docs/content/v2.20/api/ysql/the-sql-language/statements/ddl_create_index.md
- docs/content/v2.20/reference/configuration/yb-tserver.md
- docs/content/v2024.1/api/ysql/the-sql-language/statements/ddl_create_index.md
- docs/content/v2024.1/reference/configuration/yb-tserver.md
- docs/content/v2025.1/api/ysql/the-sql-language/statements/ddl_create_index.md
- docs/content/v2025.1/reference/configuration/yb-tserver.md
1. Clarify concurrently vs nonconcurrently
2. Add workaround for partitions
3. Add links to index backfill flags
> Explain concurrent index creation better 

- docs/content/preview/api/ysql/the-sql-language/statements/cmd_copy.md
- docs/content/stable/api/ysql/the-sql-language/statements/cmd_copy.md
- docs/content/v2.20/api/ysql/the-sql-language/statements/cmd_copy.md
- docs/content/v2024.1/api/ysql/the-sql-language/statements/cmd_copy.md
- docs/content/v2025.1/api/ysql/the-sql-language/statements/cmd_copy.md
@netlify /preview/api/ysql/the-sql-language/statements/cmd_copy/#replace
> [DOC-866] Added warning to avoid using REPLACE for tables with secondary indexes

- docs/content/preview/architecture/transactions/concurrency-control.md
- docs/content/stable/architecture/transactions/concurrency-control.md
- docs/content/v2.20/architecture/transactions/concurrency-control.md
- docs/content/v2024.1/architecture/transactions/concurrency-control.md
- docs/content/v2024.2/architecture/transactions/concurrency-control.md
Correct units for wait queue metric
@netlify /preview/architecture/transactions/concurrency-control/#metrics
> [doc] Correct units for wait queue metric

- docs/content/preview/yugabyte-voyager/rhel.md
The current RHEL installation documentation uses query parameter-based URLs for the YugabyteDB repository installation, which causes URL encoding issues when using `yum`/`dnf` install commands:
```bash
https://software.yugabyte.com/repos/reporpms/yb-yum-repo-1.1-0.noarch.rpm?os=rhel-8
https://software.yugabyte.com/repos/reporpms/yb-yum-repo-1.1-0.noarch.rpm?os=rhel-9
```
**Issue:** The `?` character gets URL-encoded to `%3f`, causing 404 errors:
```
Status code: 404 for https://software.yugabyte.com/repos/reporpms/yb-yum-repo-1.1-0.noarch.rpm%3fos%3drhel-9
```
Updated both RHEL 8 and RHEL 9 installation documentation to use path-based URLs that avoid query parameter encoding issues:
```bash
https://software.yugabyte.com/repos/reporpms/rhel-8/yb-yum-repo-1.1-0.noarch.rpm …
```
> fixing rhel links

- docs/content/stable/architecture/transactions/concurrency-control.md
- docs/content/stable/reference/configuration/yb-master.md
Fix default values for the `master_ysql_operation_lease_ttl_ms` flag. The value is 5 minutes in the 2025.1 branch, which uses the `stable` branch of documentation currently.
> fix default values

- src/postgres/src/test/regress/expected/yb.orig.index_recheck.out
- src/postgres/src/test/regress/sql/yb.orig.index_recheck.sql
Updated to use `HASH` in tests.
Closes #28027
> test(postgres/regress): update to use HASH

- docs/content/preview/architecture/transactions/concurrency-control.md
- docs/content/stable/architecture/transactions/concurrency-control.md
- docs/content/v2024.1/architecture/transactions/concurrency-control.md
- docs/content/v2024.2/architecture/transactions/concurrency-control.md
Clarify WoC is default in YSQL (2024.1 and later)
@netlify /preview/architecture/transactions/concurrency-control/
> [DOC-960] Clarify WoC is default in YSQL

- docs/content/preview/architecture/docdb-replication/async-replication.md
- docs/content/stable/architecture/docdb-replication/async-replication.md
xCluster pgvector index limitation
@netlify /preview/architecture/docdb-replication/async-replication/#limitations
> [DOC-966] xCluster pgvector index limitation

- src/postgres/src/backend/utils/adt/dbsize.c
https://github.com/yugabyte/yugabyte-db/issues/23181
`pg_total_relation_size` returns incorrect total sizes because the calculate_indexes_size function consider only local filesystem-based calculation and not considering the path for querying DocDB (Context: in https://github.com/yugabyte/yugabyte-db/commit/2e767c443d80ac1144bfe75739dff84801f763b0 table sizes takes into account of DocDB layer, but this did not add a same behaviour to indexes). **This results in indexes reporting 0 bytes**, making `pg_total_relation_size` **only reflect table size** without indexes.
This fix modifies calculate_indexes_size in [`src/postgres/src/backend/utils/adt/dbsize.c`](https://github.com/yugabyte/yugabyte-db/blob/adacff9f274ce1ffc270db7aa0a91d31fb2ba66c/src/postgres/src/backend/utils/adt/dbsize.c#L574-L …
> [#23181] YSQL: Fix pg_total_relation_size to include index sizes
